// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/templateJsonUtils/fieldInfo/FieldInfoBuilder",["./utils","dojo/i18n!esri/nls/jsapi"],function(d,g){function l(a){Object.keys(a).forEach(function(c){var b=a[c];void 0!==b&&null!==b||delete a[c]})}g=g.geoenrichment.dijit.ReportPlayer.ReportPlayer;var e={NUMBER:"n/",createFieldInfoFromCalculator:function(a,c,b){if(!a)return null;a=(c="function"===typeof a.getDescriptionWithType?a:null)?c.variable:a;var f=b&&b.format,e=b&&b.autoformatCurrency,
g=b&&b.additionalText,h=b&&b.calculatorName,k=b&&b.defaultDistanceUnits;b={comparisonIndex:b&&b.comparisonIndex};b.alias=c?c.getDescriptionWithType()||c.getAliasWithType():a.description||a.alias;b.hasVariable=!0;b.variableID=a.id;b.fullName=a.fullName;b.fieldCategory=a.fieldCategory;b.vintage=a.vintage;b.type=a.type;var m=c&&c.getToggleGroup&&c.getToggleGroup();b.statefulName=m?m.value:"n/"+a.fullName;c=c?c.getCalcType().charAt(0):"n";b.name=d.name.createFieldNameFromVariable(a,c);f?d.format.setFieldInfoFormat(b,
f):(b.decimals=a.precision,b.showCurrency=!(!e||"n"!==c||!a.units||"CURRENCY"!==a.units.toUpperCase()),b.showPercent=!b.showCurrency&&("p"===c||"n"===c&&a.units&&"PCT"===a.units.toUpperCase()),b.useThousandsSeparator=!0);"string"===typeof g&&(b.additionalText=g);a.isWebMap?(b.isWebMap=!0,b.webMapFieldName=a.fieldName,b.webMapField=a.field,b.webMapId=a.webMapId,!f&&a.field&&a.field.format&&(b.decimals=a.field.format.places,b.useThousandsSeparator=!1!==a.field.format.digitSeparator)):a.customDataCollection?
(b.isCustomDataCollection=!0,b.customDataCollectionId=a.customDataCollection.id,b.customDataCollectionUrl=a.customDataCollection.url,b.customDataCollectionPortalUrl=a.customDataCollection.portalUrl):a.isSiteAttribute?(b.isSiteAttribute=!0,b.attribute=a.attribute,!f&&0<a.attribute.places&&(b.decimals=a.attribute.places)):a.isDataLayerAttribute&&(b.isDataLayerAttribute=!0,b.layerID=a.layerID,b.layerUrl=a.layerUrl,b.layerName=a.layerName,b.attribute=a.attribute,b.type=a.attribute.type,!f&&0<a.attribute.decimals&&
(b.decimals=a.attribute.decimals),"DISTANCE"===a.attribute.name&&(b.units=a.attribute.units||k||"esriMiles"));b.usedFields=a.usedFields;b.expressionText=a.expressionText;d.name.provideQualifiedFieldInfoTemplateName(b,h);l(b);return b},createFieldInfoFromScript:function(a,c,b){c=b&&b.format;var f=b&&b.additionalText,e=b&&b.calculatorName;a=a||{};a.name=a.name||d.name.DEFAULT_SCRIPT_NAME;a.alias=a.alias||g.scriptNameDefault;a.decimals=Number(a.decimals)||0;b={comparisonIndex:b&&b.comparisonIndex};b.name=
d.name.createFieldNameFromScript(a);d.name.provideQualifiedFieldInfoTemplateName(b,e);b.script=a;c?d.format.setFieldInfoFormat(b,c):(b.decimals=Number(a.decimals),b.showCurrency=!1,b.showPercent=!1,b.useThousandsSeparator=!0);"string"===typeof f&&(b.additionalText=f);l(b);return b},createFieldInfoFromChart:function(a){return{isChart:!0,chartJson:a}},createFieldInfoFromImage:function(a,c){return{isImage:!0,imageJson:a,triggerJson:c}},createFieldInfoFromShape:function(a){return{isShape:!0,shapeJson:a}},
createFieldInfoFromSection:function(a){return{isReportSection:!0,sectionJson:a}},createFieldInfoFromInfographic:function(a){return{isInfographic:!0,infographicJson:a}},createFieldInfoFromMissingVariable:function(a,c){return{name:a&&a.substr(a.indexOf(".")+1),templateName:a,isMissing:!0,alias:c}}},h=/^\[\w+\]$/,k=/\[\w+\]/;e.createFieldInfoFromLabel=function(a,c){if("string"!==typeof a)return null;a=a.trim();var b=h.test(a);if(!c||b){if(!b)return null;a=a.replace(/\[|\]/g,"").toUpperCase();return e.createFieldInfoFromSpecialFieldName(d.fields.uiToTemplate(a))}return k.test(a)?
(a=d.richText.collectFieldInfosFromRenderedXMLString(a))&&d.richText.createFieldInfoFromRichText(a.xmlString,a.fieldInfos,a.specialFieldInfos):null};e.createFieldInfoFromSpecialFieldName=function(a,c){if("string"!==typeof a)return null;var b;a=a.substr(a.indexOf(".")+1);a=a.toUpperCase();"CURRDATE"===a?b={name:d.fields.DATE_FIELD_NAME,alias:d.fields.DATE_FIELD_ALIAS,format:c||d.fields.DATE_FIELD_DEFAULT_FORMAT}:"SITENOTE"===a?b={name:d.fields.SITENOTE_FIELD_NAME,alias:d.fields.SITENOTE_FIELD_ALIAS}:
"SITENOTES"===a&&(b={name:d.fields.SITENOTES_FIELD_NAME,alias:d.fields.SITENOTES_FIELD_ALIAS});if(b)return b;(c=d.fields.templateToUIHeader(a))?b={name:d.fields.qualifyTemplateHeaderName(a),alias:c}:(c=d.fields.templateToUIReportVar(a))&&(b={name:c,alias:c});return b};var n=/_P$/i;e.isFieldInfoInPercentState=function(a){return a&&a.statefulName&&("p"===a.statefulName.charAt(0)||n.test(a.statefulName))};return e});