// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
var __extends=this&&this.__extends||function(){var n=function(d,g){n=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(g,l){g.__proto__=l}||function(g,l){for(var d in l)l.hasOwnProperty(d)&&(g[d]=l[d])};return n(d,g)};return function(d,g){function m(){this.constructor=d}n(d,g);d.prototype=null===g?Object.create(g):(m.prototype=g.prototype,new m)}}();
define("esri/arcade/featureset/actions/OrderBy","require exports dojo/Deferred ../support/FeatureSet ../support/IdSet ../support/OrderbyClause ../support/shared".split(" "),function(n,d,g,m,l,q,b){var p=function(d){function k(a){var c=d.call(this,a)||this;c._orderbyclause=null;c.declaredClass="esri.arcade.featureset.actions.OrderBy";c._maxProcessing=100;c._orderbyclause=a.orderbyclause;c._parent=a.parentfeatureset;return c}__extends(k,d);k.prototype._getSet=function(a){var c=this,h=new g;null===this._wset?
this._ensureLoaded().then(b.callback(function(){c._getFilteredSet("",null,null,c._orderbyclause,a).then(b.callback(function(b){c._checkCancelled(a);c._wset=b;h.resolve(c._wset)},h),b.errback(h))},h),b.errback(h)):h.resolve(this._wset);return h.promise};k.prototype.manualOrderSet=function(a,c){var h=this,f=new g;this.getIdColumnDictionary(a,[],-1,c).then(b.callback(function(a){h._orderbyclause.order(a);for(var c=new l([],[],!0,null),b=0;b<a.length;b++)c._known.push(a[b].id);f.resolve(c)},f),b.errback(f));
return f.promise};k.prototype.getIdColumnDictionary=function(a,c,h,f){var d=this,e=new g;if(h<a._known.length-1){var k=this._maxQueryRate();"GETPAGES"===a._known[h+1]?this._parent._expandPagedSet(a,k,0,0,f).then(b.callback(function(g){d.getIdColumnDictionary(a,c,h,f).then(b.callback(function(a){e.resolve(a)},e),b.errback(e))},e),b.errback(e)):this._parent._getFeature(a,a._known[h+1],f).then(b.callback(function(g){h+=1;d._checkCancelled(f);c.push({id:a._known[h],feature:g});d.getIdColumnDictionary(a,
c,h,f).then(b.callback(function(a){e.resolve(a)},e),b.errback(e))},e),b.errback(e))}else 0<a._candidates.length?this._refineSetBlock(a,this._maxProcessingRate(),f).then(b.callback(function(){d._checkCancelled(f);d.getIdColumnDictionary(a,c,h,f).then(b.callback(function(a){e.resolve(a)},e),b.errback(e))},e),b.errback(e)):e.resolve(c);return e.promise};k.prototype._isInFeatureSet=function(a){return this._parent._isInFeatureSet(a)};k.prototype._getFeatures=function(a,c,b,d){return this._parent._getFeatures(a,
c,b,d)};k.prototype._featureFromCache=function(a){if(void 0===this._featureCache[a]){var c=this._parent._featureFromCache(a);return void 0===c?void 0:null===c?null:this._featureCache[a]=c}return this._featureCache[a]};k.prototype._fetchAndRefineFeatures=function(a,c,b){a=new g;a.reject(Error("Fetch and Refine should not be called in this featureset"));return a.promise};k.prototype._getFilteredSet=function(a,c,h,d,k){var e=this,f=new g;this._ensureLoaded().then(b.callback(function(){e._parent._getFilteredSet(a,
c,h,null===d?e._orderbyclause:d,k).then(b.callback(function(a){e._checkCancelled(k);var d;d=new l(a._candidates.slice(0),a._known.slice(0),a._ordered,e._clonePageDefinition(a.pagesDefinition));var g=!0;0<a._candidates.length&&(g=!1);!1===d._ordered?e.manualOrderSet(d,k).then(b.callback(function(a){!1!==g||null===c&&null===h||(a=new l(a._candidates.slice(0).concat(a._known.slice(0)),[],a._ordered,e._clonePageDefinition(a.pagesDefinition)));f.resolve(a)},f),b.errback(f)):f.resolve(d)},f),b.errback(f))},
f),b.errback(f));return f.promise};k.prototype.arcadeScriptStep=function(a,c,b){a=this.arcadeAssignNextScriptStepIdentifiers(b);c=this._orderbyclause.constructClause();return"var "+a.newFeatureSet+" \x3d "+this.bigDataCachePipeline("orderby( "+a.currentFeatureSet+',"'+c+'")')+";"};return k}(m);m._featuresetFunctions.orderBy=function(b){return""===b?this:new p({parentfeatureset:this,orderbyclause:new q(b)})};return p});