// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
var __extends=this&&this.__extends||function(){var q=function(p,h){q=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(h,k){h.__proto__=k}||function(h,k){for(var f in k)k.hasOwnProperty(f)&&(h[f]=k[f])};return q(p,h)};return function(p,h){function r(){this.constructor=p}q(p,h);p.prototype=null===h?Object.create(h):(r.prototype=h.prototype,new r)}}();
define("esri/arcade/featureset/actions/SpatialFilter","require exports dojo/Deferred dojo/promise/all ../sources/Empty ../support/FeatureSet ../support/IdSet ../support/shared ../../../geometry/geometryEngineAsync".split(" "),function(q,p,h,r,k,f,t,g,n){var m=function(b){function e(a){var c=b.call(this,a)||this;c._relation="";c._relationGeom=null;c._relationString="";c.declaredClass="esri.arcade.featureset.actions.SpatialFilter";c._relationString=a.relationString;c._parent=a.parentfeatureset;c._maxProcessing=
40;c._relation=a.relation;c._relationGeom=a.relationGeom;return c}__extends(e,b);e.prototype._getSet=function(a){var c=this,d=new h;null===this._wset?this._ensureLoaded().then(g.callback(function(){c._parent._getFilteredSet("esriSpatialRelRelation"!==c._relation?c._relation:c._relation+":"+c._relationString,c._relationGeom,null,null,a).then(g.callback(function(b){c._checkCancelled(a);c._wset=new t(b._candidates.slice(0),b._known.slice(0),b._ordered,c._clonePageDefinition(b.pagesDefinition));d.resolve(c._wset)},
d),g.errback(d))},d),g.errback(d)):d.resolve(this._wset);return d.promise};e.prototype._isInFeatureSet=function(a){var c=this._parent._isInFeatureSet(a);if(c===g.IdState.NotInFeatureSet)return c;c=this._idstates[a];return void 0===c?g.IdState.Unknown:c};e.prototype._getFeature=function(a,c,b){return this._parent._getFeature(a,c,b)};e.prototype._getFeatures=function(a,c,b,g){return this._parent._getFeatures(a,c,b,g)};e.prototype._featureFromCache=function(a){return this._parent._featureFromCache(a)};
e.prototype.executeSpatialRelationTest=function(a){if(null===a.geometry){var c=new h;c.resolve(!1);return c.promise}switch(this._relation){case "esriSpatialRelEnvelopeIntersects":return c=g.shapeExtent(this._relationGeom),a=g.shapeExtent(a.geometry),n.intersects(c,a);case "esriSpatialRelIntersects":return n.intersects(this._relationGeom,a.geometry);case "esriSpatialRelContains":return n.contains(this._relationGeom,a.geometry);case "esriSpatialRelOverlaps":return n.overlaps(this._relationGeom,a.geometry);
case "esriSpatialRelWithin":return n.within(this._relationGeom,a.geometry);case "esriSpatialRelTouches":return n.touches(this._relationGeom,a.geometry);case "esriSpatialRelCrosses":return n.crosses(this._relationGeom,a.geometry);case "esriSpatialRelRelation":return n.relate(this._relationGeom,a.geometry,this._relationString)}};e.prototype._fetchAndRefineFeatures=function(a,c,b){var d=this,e=new h,l=new t([],a,!1,null),k=Math.min(c,a.length);this._parent._getFeatures(l,-1,k,b).then(g.callback(function(){d._checkCancelled(b);
for(var l=[],h=0;h<k;h++){var f=d._parent._featureFromCache(a[h]);l.push(d.executeSpatialRelationTest(f))}r(l).then(g.callback(function(b){for(var l=0;l<c;l++)d._idstates[a[l]]=!0===b[l]?g.IdState.InFeatureSet:g.IdState.NotInFeatureSet;e.resolve("success")},e),g.errback(e))},e),g.errback(e));return e.promise};e.prototype._getFilteredSet=function(a,c,b,e,k){var d=this,f=new h;this._ensureLoaded().then(g.callback(function(){d._parent._getFilteredSet("esriSpatialRelRelation"!==d._relation?d._relation:
d._relation+":"+d._relationString,d._relationGeom,b,e,k).then(g.callback(function(a){d._checkCancelled(k);a=null!==c?new t(a._candidates.slice(0).concat(a._known.slice(0)),[],a._ordered,d._clonePageDefinition(a.pagesDefinition)):new t(a._candidates.slice(0),a._known.slice(0),a._ordered,d._clonePageDefinition(a.pagesDefinition));f.resolve(a)},f),g.errback(f))},f),g.errback(f));return f.promise};e.prototype._stat=function(a,c,b,e,f,k,m){var d=this,l=new h;""!==b?l.resolve({calculated:!1}):this._parent._stat(a,
c,"esriSpatialRelRelation"!==this._relation?this._relation:this._relation+":"+this._relationString,this._relationGeom,f,k,m).then(g.callback(function(h){!1===h.calculated?null===f&&""===b&&null===e?d._manualStat(a,c,k,m).then(g.callback(function(a){l.resolve(a)},l),g.errback(l)):l.resolve({calculated:!1}):l.resolve(h)},l),g.errback(l));return l.promise};e.prototype._canDoAggregates=function(a,c,b,e,f){var d=new h;return""!==b||null!==e||null===this._parent?(d.resolve(!1),d.promise):this._parent._canDoAggregates(a,
c,"esriSpatialRelRelation"!==this._relation?this._relation:this._relation+":"+this._relationString,this._relationGeom,f)};e.prototype._getAggregatePagesDataSourceDefinition=function(a,c,b,e,f,g,k){b=new h;if(null===this._parent)b.reject(Error("Should never be called"));else return this._parent._getAggregatePagesDataSourceDefinition(a,c,"esriSpatialRelRelation"!==this._relation?this._relation:this._relation+":"+this._relationString,this._relationGeom,f,g,k);return b.promise};e.prototype.arcadeScriptStep=
function(a,b,d){a=this.arcadeAssignNextScriptStepIdentifiers(d);switch(this._relation){case "esriSpatialRelEnvelopeIntersects":return"var "+a.newFeatureSet+" \x3d "+this.bigDataCachePipeline("envelopeIntersects( "+a.currentFeatureSet+","+this.constructArcadeGeom(null===this._relationGeom?null:this._relationGeom.extent,b,d)+")")+"; ";case "esriSpatialRelIntersects":return"var "+a.newFeatureSet+" \x3d "+this.bigDataCachePipeline("intersects( "+a.currentFeatureSet+","+this.constructArcadeGeom(this._relationGeom,
b,d)+")")+"; ";case "esriSpatialRelContains":return"var "+a.newFeatureSet+" \x3d "+this.bigDataCachePipeline("contains( "+a.currentFeatureSet+","+this.constructArcadeGeom(this._relationGeom,b,d)+")")+"; ";case "esriSpatialRelOverlaps":return"var "+a.newFeatureSet+" \x3d "+this.bigDataCachePipeline("overlaps( "+a.currentFeatureSet+","+this.constructArcadeGeom(this._relationGeom,b,d)+")")+"; ";case "esriSpatialRelWithin":return"var "+a.newFeatureSet+" \x3d "+this.bigDataCachePipeline("within( "+a.currentFeatureSet+
","+this.constructArcadeGeom(this._relationGeom,b,d)+")")+"; ";case "esriSpatialRelTouches":return"var "+a.newFeatureSet+" \x3d "+this.bigDataCachePipeline("touches( "+a.currentFeatureSet+","+this.constructArcadeGeom(this._relationGeom,b,d)+")")+"; ";case "esriSpatialRelCrosses":return"var "+a.newFeatureSet+" \x3d "+this.bigDataCachePipeline("crosses( "+a.currentFeatureSet+","+this.constructArcadeGeom(this._relationGeom,b,d)+")")+"; ";case "esriSpatialRelRelation":return"var "+a.newFeatureSet+" \x3d "+
this.bigDataCachePipeline("relate( "+a.currentFeatureSet+","+this.constructArcadeGeom(this._relationGeom,b,d)+', "'+this._relationString+'")')+";"}return"var "+a.newFeatureSet+" \x3d null; "};return e}(f);f._featuresetFunctions.intersects=function(b){return null===b||void 0===b?new k({parentfeatureset:this}):new m({parentfeatureset:this,relation:"esriSpatialRelIntersects",relationGeom:b})};f._featuresetFunctions.envelopeIntersects=function(b){return null===b||void 0===b?new k({parentfeatureset:this}):
new m({parentfeatureset:this,relation:"esriSpatialRelEnvelopeIntersects",relationGeom:b})};f._featuresetFunctions.contains=function(b){return null===b||void 0===b?new k({parentfeatureset:this}):new m({parentfeatureset:this,relation:"esriSpatialRelContains",relationGeom:b})};f._featuresetFunctions.overlaps=function(b){return null===b||void 0===b?new k({parentfeatureset:this}):new m({parentfeatureset:this,relation:"esriSpatialRelOverlaps",relationGeom:b})};f._featuresetFunctions.within=function(b){return null===
b||void 0===b?new k({parentfeatureset:this}):new m({parentfeatureset:this,relation:"esriSpatialRelWithin",relationGeom:b})};f._featuresetFunctions.touches=function(b){return null===b||void 0===b?new k({parentfeatureset:this}):new m({parentfeatureset:this,relation:"esriSpatialRelTouches",relationGeom:b})};f._featuresetFunctions.crosses=function(b){return null===b||void 0===b?new k({parentfeatureset:this}):new m({parentfeatureset:this,relation:"esriSpatialRelCrosses",relationGeom:b})};f._featuresetFunctions.relate=
function(b,e){return null===b||void 0===b?new k({parentfeatureset:this}):new m({parentfeatureset:this,relation:"esriSpatialRelRelation",relationGeom:b,relationString:e})};return m});