// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
var __extends=this&&this.__extends||function(){var p=function(l,k){p=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(k,n){k.__proto__=n}||function(k,n){for(var d in n)n.hasOwnProperty(d)&&(k[d]=n[d])};return p(l,k)};return function(l,k){function m(){this.constructor=l}p(l,k);l.prototype=null===k?Object.create(k):(m.prototype=k.prototype,new m)}}();
define("esri/arcade/featureset/actions/Top","require exports dojo/Deferred ../support/FeatureSet ../support/IdSet ../support/shared".split(" "),function(p,l,k,m,n,d){var r=function(l){function e(a){var b=l.call(this,a)||this;b._topnum=0;b.declaredClass="esri.arcade.featureset.actions.Top";b._countedin=0;b._maxProcessing=100;b._topnum=a.topnum;b._parent=a.parentfeatureset;return b}__extends(e,l);e.prototype._getSet=function(a){var b=this,g=new k;null===this._wset?this._ensureLoaded().then(d.callback(function(){b._parent._getSet(a).then(d.callback(function(a){b._wset=
new n(a._candidates.slice(0),a._known.slice(0),!1,b._clonePageDefinition(a.pagesDefinition));b._setKnownLength(b._wset)>b._topnum&&(b._wset._known=b._wset._known.slice(0,b._topnum));b._setKnownLength(b._wset)>=b._topnum&&(b._wset._candidates=[]);g.resolve(b._wset)},g),d.errback(g))},g),d.errback(g)):g.resolve(this._wset);return g.promise};e.prototype._setKnownLength=function(a){return 0<a._known.length&&"GETPAGES"===a._known[a._known.length-1]?a._known.length-1:a._known.length};e.prototype._isInFeatureSet=
function(a){var b=this._parent._isInFeatureSet(a);if(b===d.IdState.NotInFeatureSet)return b;var g=this._idstates[a];return g===d.IdState.InFeatureSet||g===d.IdState.NotInFeatureSet?g:b===d.IdState.InFeatureSet&&void 0===g?this._countedin<this._topnum?(this._idstates[a]=d.IdState.InFeatureSet,this._countedin++,d.IdState.InFeatureSet):this._idstates[a]=d.IdState.NotInFeatureSet:d.IdState.Unknown};e.prototype._expandPagedSet=function(a,b,g,h,q){var c=this,f=new k;if(null===this._parent)return b=new k,
b.reject(Error("Parent Paging not implemented")),b.promise;b>this._topnum&&(b=this._topnum);if(this._countedin>=this._topnum&&a.pagesDefinition.internal.set.length<=a.pagesDefinition.resultOffset)return b=a._known.length,0<b&&"GETPAGES"===a._known[b-1]&&(a._known.length=b-1),b=a._candidates.length,0<b&&"GETPAGES"===a._candidates[b-1]&&(a._candidates.length=b-1),f.resolve("success"),f.promise;this._parent._expandPagedSet(a,b,g,h,q).then(d.callback(function(b){c._setKnownLength(a)>c._topnum&&(a._known.length=
c._topnum);c._setKnownLength(a)>=c._topnum&&(a._candidates.length=0);f.resolve(b)},f),d.errback(f));return f.promise};e.prototype._getFeatures=function(a,b,g,h){var q=this,c=new k,f=[],e=this._maxQueryRate();if(!0===this._checkIfNeedToExpandKnownPage(a,e,h))return this._expandPagedSet(a,e,0,0,h).then(d.callback(function(f){q._getFeatures(a,b,g,h).then(d.callback(function(a){c.resolve(a)},c),d.errback(c))},c),d.errback(c)),c.promise;-1!==b&&void 0===this._featureCache[b]&&f.push(b);for(var l=0,m=a._lastFetchedIndex;m<
a._known.length&&!(l++,l<=g&&(a._lastFetchedIndex+=1),void 0===this._featureCache[a._known[m]]&&(a._known[m]!==b&&f.push(a._known[m]),f.length>e-1));m++);if(0===f.length)c.resolve("success");else{var e=new n([],f,!1,null),p=Math.min(f.length,g);this._parent._getFeatures(e,-1,p,h).then(d.callback(function(a){for(a=0;a<p;a++){var b=q._parent._featureFromCache(f[a]);void 0!==b&&(q._featureCache[f[a]]=b)}c.resolve("success")},c),d.errback(c))}return c.promise};e.prototype._getFilteredSet=function(a,b,
g,h,e){var c=this,f=new k;this._ensureLoaded().then(d.callback(function(){c._getSet(e).then(d.callback(function(a){a=new n(a._candidates.slice(0).concat(a._known.slice(0)),[],!1,c._clonePageDefinition(a.pagesDefinition));f.resolve(a)},f),d.errback(f))},f),d.errback(f));return f.promise};e.prototype._refineKnowns=function(a,b){for(var g=0,h=null,e=[],c=0;c<a._candidates.length;c++){var f=this._isInFeatureSet(a._candidates[c]);if(f===d.IdState.InFeatureSet){if(a._known.push(a._candidates[c]),g+=1,null===
h?h={start:c,end:c}:h.end===c-1?h.end=c:(e.push(h),h={start:c,end:c}),a._known.length>=this._topnum)break}else if(f===d.IdState.NotInFeatureSet)null===h?h={start:c,end:c}:h.end===c-1?h.end=c:(e.push(h),h={start:c,end:c}),g+=1;else if(f===d.IdState.Unknown)break;if(g>=b)break}null!==h&&e.push(h);for(b=e.length-1;0<=b;b--)a._candidates.splice(e[b].start,e[b].end-e[b].start+1);this._setKnownLength(a)>this._topnum&&(a._known=a._known.slice(0,this._topnum));this._setKnownLength(a)>=this._topnum&&(a._candidates=
[])};e.prototype._stat=function(a,b,d,e,l,c,f){a=new k;a.resolve({calculated:!1});return a.promise};e.prototype._canDoAggregates=function(a,b,d,e,l){a=new k;a.resolve(!1);return a.promise};e.prototype.arcadeScriptStep=function(a,b,d){a=this.arcadeAssignNextScriptStepIdentifiers(d);return"var "+a.newFeatureSet+" \x3d "+this.bigDataCachePipeline("top( "+a.currentFeatureSet+","+this._topnum.toString()+")")+"; "};return e}(m);m._featuresetFunctions.top=function(d){return new r({parentfeatureset:this,
topnum:d})};return r});