// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/playerSupports/_SmartLayoutSupport","dojo/_base/declare dojo/when dojo/dom-class dojo/on esri/dijit/geoenrichment/utils/DomUtil ../PlayerResizeModes".split(" "),function(f,e,c,g,h,d){return f(null,{_width:0,_height:0,_measuredWinBox:null,_initSmartLayout:function(){var a=this;this.resizeMode===d.FIT_WINDOW&&this.own(g(window,"resize, orientationchange",function(){setTimeout(function(){a._measuredWinBox=null;a.resize()})}));this._resize()},_resize:function(a){a=
a||{};c.remove(this.domNode,"esriGEReportPlayerFullScreen esriGEReportPlayerAutoResize esriGEReportPlayerManualResize");switch(this.resizeMode){case d.FIT_WINDOW:return this._resize_fitWindow(a);case d.AUTO:return this._resize_auto(a);case d.MANUAL:return this._resize_manual(a)}},_resize_fitWindow:function(a){var b=this;this._measuredWinBox=this._measuredWinBox||h.getWindowBox();this._width=this._maxWidth=this._measuredWinBox.w;this._height=this._maxHeight=this._measuredWinBox.h;c.add(this.domNode,
"esriGEReportPlayerFullScreen");this.domNode.style.width=this._width+"px";this.domNode.style.height=this._height+"px";if(this._currentReportContainer)return this._currentReportContainer.setMaxWidth&&this._currentReportContainer.setMaxWidth(this._maxWidth),this._currentReportContainer.setMaxHeight&&this._currentReportContainer.setMaxHeight(this._maxHeight-this._getToolbarHeight()),e(this._currentReportContainer.resize(this._width,this._height-this._getToolbarHeight()),function(){b._emitResizedEvent(a.isPaginating)})},
_resize_auto:function(a){var b=this;this._height=this._width=0;c.add(this.domNode,"esriGEReportPlayerAutoResize");this.domNode.style.width="auto";this.domNode.style.height="auto";if(this._currentReportContainer)return this._currentReportContainer.setMaxWidth&&this._currentReportContainer.setMaxWidth(this._maxWidth),this._currentReportContainer.setMaxHeight&&this._currentReportContainer.setMaxHeight(this._maxHeight-this._getToolbarHeight()),e(this._currentReportContainer.resize(0,0),function(){b._emitResizedEvent(a.isPaginating)})},
_resize_manual:function(a){var b=this;this._width=void 0!==a.width?a.width:this._width;this._height=void 0!==a.height?a.height:this._height;if(this._width&&this._height&&(this._maxWidth&&(this._width=Math.min(this._maxWidth,this._width)),this._maxHeight&&(this._height=Math.min(this._maxHeight,this._height)),c.add(this.domNode,"esriGEReportPlayerManualResize"),this.domNode.style.width=this._width+"px",this.domNode.style.height=this._height+"px",this._currentReportContainer))return this._currentReportContainer.setMaxWidth&&
this._currentReportContainer.setMaxWidth(this._maxWidth||this._width),this._currentReportContainer.setMaxHeight&&this._currentReportContainer.setMaxHeight((this._maxHeight||this._height)-this._getToolbarHeight()),e(this._currentReportContainer.resize(this._width,this._height-this._getToolbarHeight()),function(){b._emitResizedEvent(a.isPaginating)})},_getToolbarHeight:function(){return this.showToolbarInPopup?0:50},_maxWidth:0,_maxHeight:0,setMaxWidth:function(a){this._maxWidth=a},setMaxHeight:function(a){this._maxHeight=
a}})});