// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/geoenrichment/ReportPlayer/core/templates/sectionDynamicSettings/RefineFilters.html":'\x3cdiv class\x3d"esriGEReportPlayer_sectionDynamicRefineFilters"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"refineResultsTitle" class\x3d"esriGERow20"\x3e\x3c/div\x3e\r\n    \x3cdiv class\x3d"esriGESpaceBeforeBig"\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"textFilterBlock" class\x3d"sectionDynamicRefineFilters_row"\x3e\r\n            \x3cdiv class\x3d"esriGERowHigh"\x3e${nls.byKeywords}\x3c/div\x3e\r\n            \x3cdiv data-dojo-attach-point\x3d"textFilterDiv" class\x3d"esriGERowHigh"\x3e\x3c/div\x3e\r\n        \x3c/div\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"filtersBlock"\x3e\x3c/div\x3e\r\n        \x3cdiv class\x3d"esriGERowHigh"\x3e\r\n            \x3cdiv data-dojo-attach-point\x3d"resetButton" class\x3d"dijitInline esriGELink"\x3e${nls.resetFilters}\x3c/div\x3e\r\n        \x3c/div\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/geoenrichment/ReportPlayer/core/sections/dynamicSettings/RefineFilters","dojo/_base/declare dojo/on dojo/string dojo/dom-construct dijit/_WidgetBase dijit/_TemplatedMixin dijit/form/TextBox esri/dijit/geoenrichment/NumericalSlider esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/InvokeUtil dojo/text!../../templates/sectionDynamicSettings/RefineFilters.html dojo/i18n!esri/nls/jsapi".split(" "),function(k,g,l,h,m,n,p,q,f,r,t,e){e=e.geoenrichment.dijit.ReportPlayer.SectionDynamicSettingsBuilder;
return k([m,n],{templateString:t,nls:e,hasTitle:!1,hasTextFilter:!1,hasRangeFilters:!1,textFilterPlaceHolder:null,_originalFilterRanges:null,_filters:null,textFilter:null,_filterWidgets:null,postCreate:function(){var a=this;this.inherited(arguments);this._buildKeywordFilter();g(this.resetButton,"click",function(){a._resetFilters()});f[this.hasTitle?"show":"hide"](this.refineResultsTitle);f[this.hasTextFilter?"show":"hide"](this.textFilterBlock);f[this.hasRangeFilters?"show":"hide"](this.filtersBlock)},
_resetFilters:function(a){this.textFilter.set("value","");this._buildFiltersFromOriginals();this._buildRangeFilters();!a&&this._doEmitEvent()},setTitle:function(a,b,c){this.refineResultsTitle.innerHTML=l.substitute(a,{numTotal:b||0,numShown:c||0})},setFilterRanges:function(a){this._originalFilterRanges=a||[];this._buildFiltersFromOriginals();this._buildRangeFilters()},_buildFiltersFromOriginals:function(){this._filters=this._originalFilterRanges?this._originalFilterRanges.map(function(a){return{label:a.alias,
fieldName:a.fieldName,minValue:a.min,maxValue:a.max,lowerValue:a.min,upperValue:a.max,decimals:a.decimals,dataArray:a.dataArray}}):[]},_buildKeywordFilter:function(){this.textFilter=(new p({"class":"sectionDynamicRefineFilters_textFilter",trim:!0,placeHolder:this.textFilterPlaceHolder||e.keywordsPlaceholder})).placeAt(this.textFilterDiv);g(this.textFilter.textbox,"keyup",this._emitEvent.bind(this));this.own(this.textFilter)},_buildRangeFilters:function(){var a=this;this._destroyFilterWidgets();this._filterWidgets=
[];this._filters.forEach(function(b){var c=h.create("div",{"class":"esriGERowHigh sectionDynamicRefineFilters_row"},a.filtersBlock),d=(new q({label:b.label,minValue:b.minValue,maxValue:b.maxValue,lowerValue:b.lowerValue,upperValue:b.upperValue,decimals:b.decimals,timeIntervalLength:250,onChange:function(c){b.lowerValue=d.round(c.lowerValue);b.upperValue=d.round(c.upperValue);a._emitEvent()}})).placeAt(c);d.startup();setTimeout(function(){b.dataArray&&d.domNode&&d.setStatistics(b.dataArray)},100);
a._filterWidgets.push(d)})},_emitEvent:function(){r.invoke(this,"_doEmitEvent",100)},_doEmitEvent:function(){this.onFilterChanged({searchText:this.textFilter.get("value"),filterRanges:this._filters&&this._filters.map(function(a){return{fieldName:a.fieldName,min:a.lowerValue,max:a.upperValue}}),hasFiltersOn:this.hasFiltersOn()})},onFilterChanged:function(a){},hasFiltersOn:function(){return!!(this.textFilter.get("value")||this._filters&&this._filters.some(function(a){return a.lowerValue>a.minValue||
a.upperValue<a.maxValue}))},setVisualState:function(a){a?(a.filterRanges&&(a.filterRanges.forEach(function(a,c){c=this._filters.filter(function(b){return b.fieldName===a.fieldName})[0];c.lowerValue=a.min;c.upperValue=a.max},this),this._buildRangeFilters()),this.textFilter.set("value",a.searchText||"")):this._resetFilters(!0)},_destroyFilterWidgets:function(){this._filterWidgets&&(this._filterWidgets.forEach(function(a){a.destroy()}),this._filterWidgets.length=0);h.empty(this.filtersBlock)},destroy:function(){this._destroyFilterWidgets();
this.inherited(arguments)}})});