// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/sections/dynamicSettings/SectionDynamicSettingsBuilder","dojo/_base/declare dojo/on dojo/when dojo/promise/all dojo/dom-class dojo/dom-construct dijit/Destroyable esri/dijit/geoenrichment/ReportPlayer/PlayerSelect esri/dijit/geoenrichment/ReportPlayer/PlayerThemes esri/dijit/geoenrichment/ReportPlayer/ReportPlayerState ./chart/_ChartSettingsBuilder ./locator/_LocatorSettingsBuilder ./areaDetails/_AreaDetailsSettingsBuilder ./comparison/_ComparisonSettingsBuilder ./dynamicInfographic/_DynamicInfographicSettingsBuilder ./map/_MapSettingsBuilder ./multiFeature/_MultiFeatureSettingsBuilder ./SectionDynamicSettings esri/dijit/geoenrichment/utils/DeviceUtil esri/dijit/geoenrichment/utils/DnDUtil esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/MouseUtil esri/dijit/geoenrichment/utils/PopupUtil esri/dijit/geoenrichment/utils/TooltipUtil dojo/i18n!esri/nls/jsapi".split(" "),
function(q,g,k,r,h,d,t,u,v,w,x,y,z,A,l,B,C,D,E,F,m,e,n,G,f){f=f.geoenrichment.dijit.ReportPlayer.SectionDynamicSettingsBuilder;return q(t,{_section:null,_settingsWidget:null,_settingsToolbar:null,_settingsButton:null,_filtersOnIndicator:null,_featureSelectDiv:null,_buttonBar:null,_onButtonBarShowCallbacks:null,_needRequerySettingsSet:!1,constructor:function(a){this._section=a;this._createSettings()},_createSettings:function(){var a=this;this._getSettingsSet().then(function(b){if(b.chartSettings||
b.locatorSettings||b.areaDetailsSettings||b.comparisonSettings||b.dynamicInfographicSettings||b.mapSettings||b.multiFeatureSettings)a._tryAddFeatureSelect(b.multiFeatureSettings,b),a._tryAddLocatorExportButton(b.locatorSettings),a._tryAddSettingsButton(b),(b.locatorSettings&&!b.locatorSettings.hasTitle||b.areaDetailsSettings&&!b.areaDetailsSettings.hasTitle||b.comparisonSettings)&&h.add(a._settingsToolbar,"needsTopOffset"),a._buttonBar&&1<a._buttonBar.children.length&&h.add(a._buttonBar,"hasMultipleButtons")})},
_getSettingsSet:function(){return r({chartSettings:x.provideChartSettings(this._section),locatorSettings:y.provideLocatorSettings(this._section),areaDetailsSettings:z.provideAreaDetailsSettings(this._section),comparisonSettings:A.provideComparisonSettings(this._section),dynamicInfographicSettings:l.provideDynamicInfogarphicSettings(this._section),mapSettings:B.provideMapSettings(this._section),multiFeatureSettings:C.provideMultiFeatureSettings(this._section)})},_tryAddFeatureSelect:function(a,b){var c=
this;if(a&&a.canSelectFeatures){a=this._section.viewModel.dynamicReportInfo.analysisAreas.map(function(a,b){return{value:b,label:a.shortName||a.name}});var p=(new u({options:a,value:0,allowRepetitiveSelection:!1,onChange:function(a){c._needRequerySettingsSet=!0;c._setFiltersOnIndicatorVisible(!1);var d=c._section.toJson();d.currentFeatureIndex=a.value;c._section.fromJson(d);p.closePopup();c._settingsWidget&&(b.dynamicInfographicSettings?k(l.provideDynamicInfogarphicSettings(c._section),function(a){c._settingsWidget.updateDynamicInfographicSettings(a)}):
c._settingsWidget.setVisualState(c._section.getVisualState()))}})).placeAt(this._createSettingsToolbar().featureSelectDiv);p.setTheme(v.DARK)}},_tryAddLocatorExportButton:function(a){if(a&&a.canExportToExcel){var b=this._createButton("dijitInline sectionDynamicSettings_exportButton");g(b,"click",function(){a.exportToExcel()});G.setTooltipToNode(b,f.exportInfographicPanel)}},_tryAddSettingsButton:function(a){var b=this,c=!1;if(a.chartSettings||a.locatorSettings||a.areaDetailsSettings||a.comparisonSettings||
a.dynamicInfographicSettings||a.mapSettings)this._settingsButton=this._createButton("dijitInline "+(a.locatorSettings||a.areaDetailsSettings||a.comparisonSettings&&a.comparisonSettings.filterRanges||a.dynamicInfographicSettings?"sectionDynamicSettings_filterButton":"sectionDynamicSettings_settingsButton"),function(){c||(c=!0,n.makePopup(function(){return k(b._needRequerySettingsSet?b._getSettingsSet():a,function(a){b._needRequerySettingsSet=!1;return b._createPopup(a)})},this._section,b._settingsButton,
{orient:["before","below"]}))})},_createButton:function(a,b){return d.create("div",{"class":a},this._createSettingsToolbar(b).buttonBar)},_createSettingsToolbar:function(a){function b(a){c._section.isDataDrillingView&&(a=!0);c._buttonBar.style.display=!a||!c._section.isDataDrillingView&&w.isViewingDataDrillingZoom?"none":"";a&&c._onButtonBarShowCallbacks.forEach(function(a){return a()});a?c._syncWithPanelScale():c._closeSettingsPopup();h[a?"add":"remove"](c._section.domNode,"hasDynamicSettingsToolbar")}
var c=this;this._settingsToolbar||(this._settingsToolbar=d.create("div",{"class":"sectionDynamicSettings_toolbar"},this._section.domNode),this._adjustToolbarPosition(),this._featureSelectDiv=d.create("div",{"class":"dijitInline"},this._settingsToolbar),this._buttonBar=d.create("div",{"class":"dijitInline sectionDynamicSettings_buttonBar"},this._section.dynamicSettingsToolbarRoot||this._settingsToolbar),this._onButtonBarShowCallbacks=[],b(!1),E.isMobileDevice()?(F.addNoDragClickHandler(this._section.domNode,
function(){b(!0)}),this.own(g(document.body,"touchstart",function(a){c.isMouseOver(a)||b(!1)}))):this.own(g(document.body,"mousemove",function(){b(c.isMouseOver())})));a&&this._onButtonBarShowCallbacks.push(a);return{buttonBar:this._buttonBar,featureSelectDiv:this._featureSelectDiv}},_adjustToolbarPosition:function(){if(this._settingsToolbar){var a=this._section.getMapImages()[0];if(a){var a=m.position(a.domNode),b=m.position(this._section.domNode);this._settingsToolbar.style.top=a.y-b.y+"px";this._settingsToolbar.style.right=
b.x+b.w-a.x-a.w+"px"}}},_createPopup:function(a){function b(){return c._section.getInfographic().getInnerInfographic()}var c=this;this._settingsWidget||(this._settingsWidget=new D({chartSettings:a.chartSettings,locatorSettings:a.locatorSettings,areaDetailsSettings:a.areaDetailsSettings,comparisonSettings:a.comparisonSettings,dynamicInfographicSettings:a.dynamicInfographicSettings,mapSettings:a.mapSettings,onSortChart:function(a){c._closeSettingsPopup();c._section.getChart().sortChart(a)},onChartToTable:function(){c._closeSettingsPopup();
c._section.getChart().chartToTable()},onTableToChart:function(){c._closeSettingsPopup();c._section.getChart().tableToChart()},onCalcStateChanged:function(a){c._closeSettingsPopup();c._section.setChartCalculationState(a)},onChartFilterChanged:function(a){c._section.getChart().setFilterRanges(a.filterRanges);c._setFiltersOnIndicatorVisible(a.hasFiltersOn)},onLocatorFilterChanged:function(a){b().setSearchText(a.searchText);b().setFilterRanges(a.filterRanges);c._setFiltersOnIndicatorVisible(a.hasFiltersOn)},
onAreaDetailsFilterChanged:function(a){b().setSearchText(a.searchText);c._setFiltersOnIndicatorVisible(a.hasFiltersOn)},onShowChart:function(a){c._closeSettingsPopup();b().setChartView(a)},onComparisonFilterChanged:function(a){b().setFilterRanges(a.filterRanges);c._setFiltersOnIndicatorVisible(a.hasFiltersOn)},onDynamicInfographicFilterChanged:function(a){b().setFilterRanges(a.filterRanges);c._setFiltersOnIndicatorVisible(a.hasFiltersOn)},onLegendVisibilityChanged:function(a){c._section.getMapImages()[0].setLegendVisible(a)},
onClosePopup:function(){c._closeSettingsPopup()}}),this.own(this._settingsWidget),this._settingsWidget.setVisualState(this._section.getVisualState()));return this._settingsWidget},_closeSettingsPopup:function(){n.close(this._settingsWidget)},_setFiltersOnIndicatorVisible:function(a){this._filtersOnIndicator&&d.destroy(this._filtersOnIndicator);this._filtersOnIndicator=a&&d.create("div",{"class":"sectionDynamicSettings_filtersOnIndicator",innerHTML:f.on},this._settingsButton)},setVisualState:function(a){this._settingsWidget&&
this._settingsWidget.setVisualState(a)},notifyShown:function(){this._adjustToolbarPosition()},_panelScale:null,setPanelScale:function(a){this._panelScale=a;this._syncWithPanelScale()},_syncWithPanelScale:function(){this._panelScale&&this._settingsToolbar&&(this._settingsToolbar.style.transformOrigin=this._section.isDataDrillingView?"100% 100%":"100% 0%",this._settingsToolbar.style.transform="scale("+1/this._panelScale+")",this._settingsToolbar.style["webkit-transform"]="scale("+1/this._panelScale+
")")},isMouseOver:function(a){return e.isMouseOver(this._section.domNode,{event:a})||e.isMouseOver(this._settingsToolbar,{event:a})||this._settingsWidget&&(e.isMouseOver(this._settingsWidget.domNode,{event:a})||e.isMouseOver(this._settingsWidget.domNode.parentNode,{event:a}))},destroy:function(){d.destroy(this._settingsToolbar)}})});