// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/geoenrichment/ReportPlayer/core/templates/sectionDynamicSettings/ChartSettings.html":'\x3cdiv class\x3d"esriGEReportPlayer_sectionDynamicChartSettings"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"viewOptionsDiv" class\x3d"esriGERow15 esriGESpaceBeforeBig"\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"toggleViewButton" class\x3d"dijitInline esriGELink"\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"toggleStateOptionsDiv" class\x3d"esriGERow15 esriGESpaceBeforeBig"\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"toggleStateOptionsToggleDiv" class\x3d"dijitInline"\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"sortingListDiv" class\x3d"esriGERow15"\x3e\x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"filtersBlock" class\x3d"esriGERow15"\x3e\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/geoenrichment/ReportPlayer/core/sections/dynamicSettings/chart/ChartSettings","dojo/_base/declare dojo/on dojo/dom-construct dijit/_WidgetBase dijit/_TemplatedMixin esri/dijit/geoenrichment/FlowList esri/dijit/geoenrichment/DataBrowser/VariableToggle ../RefineFilters esri/dijit/geoenrichment/utils/DomUtil dojo/text!../../../templates/sectionDynamicSettings/ChartSettings.html dojo/i18n!esri/nls/jsapi".split(" "),function(e,f,h,k,l,g,m,n,d,p,c){c=c.geoenrichment.dijit.ReportPlayer.SectionDynamicSettingsBuilder;
var q=e(g.itemRenderers.DefaultItemRenderer,{createLabelNode:!0,createImageAfterLabel:!1,_createImageNode:function(a,b){return h.create("div",{"class":"dijitInline"},b)}});return e([k,l],{templateString:p,calcStateToggle:null,sortingList:null,_isChartShownFlag:!0,setViewOptions:function(a){var b=this;d[a?"show":"hide"](this.viewOptionsDiv);f(this.toggleViewButton,"click",function(){b._isChartShownFlag=!b._isChartShownFlag;b._updateControlsForView();b[b._isChartShownFlag?"onTableToChart":"onChartToTable"]()});
this._updateControlsForView()},_updateControlsForView:function(){this.toggleViewButton.innerHTML=this._isChartShownFlag?c.viewTable:c.viewChart;d.enableContentAbsolute(this.sortingListDiv,this._isChartShownFlag)},onChartToTable:function(){},onTableToChart:function(){},setToggleCalcStateOptions:function(a){var b=this;d[a?"show":"hide"](this.toggleStateOptionsDiv);a&&(this.calcStateToggle=new m(a,this.toggleStateOptionsToggleDiv),this.own(this.calcStateToggle),this.calcStateToggle.stopMouseEventPropagation=
!1,this.calcStateToggle.set("value",a.value),f(this.calcStateToggle,"change",function(){b.onCalcStateChanged(b.calcStateToggle.getStateName())}))},onCalcStateChanged:function(a){},setSortingOptions:function(a,b){var c=this;this.sortingList||(this.sortingList=(new g({"class":"sectionDynamicChartSettings_sortingList",itemRenderer:new q,onChange:function(){c.onSortChart(c.sortingList.get("value"))}})).placeAt(this.sortingListDiv),this.own(this.sortingList));this.sortingList.setItems(a);this.sortingList.set("value",
b)},onSortChart:function(a){},setFilterRanges:function(a){var b=this;d[a?"show":"hide"](this.filtersBlock);a&&(this.refineFilters||(this.refineFilters=(new n({hasTitle:!0,hasRangeFilters:!0,onFilterChanged:function(a){b.onFilterRangesChanged(a)}})).placeAt(this.filtersBlock),this.own(this.refineFilters)),this.refineFilters.setFilterRanges(a))},setNumAreas:function(a,b){this.refineFilters&&this.refineFilters.setTitle(c.refineYourAreas,a,b)},onFilterRangesChanged:function(a){},setVisualState:function(a){if(a=
a&&a.stackElements[0]&&a.stackElements[0].cells&&a.stackElements[0].cells[0])this._isChartShownFlag=!a.isTableView,a.sorting&&this.sortingList.set("value",a.sorting),this._updateControlsForView(),a.filterRanges&&this.refineFilters.setVisualState(a)}})});