// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/grid/coreUtils/GridQueryUtil",["./GridDataUtil","esri/dijit/geoenrichment/utils/ArrayUtil","esri/dijit/geoenrichment/utils/MouseUtil"],function(l,m,g){var f={querySingleCell:function(c,a){a.fieldCell&&(a={rowId:a.fieldCell.rowId,columnId:a.fieldCell.columnId});var d;c.getFieldCells().some(function(b){if(b.parentGrid&&b.column&&b.gridData&&!(b.columnId!==a.columnId&&b.column.index!==a.columnIndex&&b.column.field!==a.columnField||b.rowId!==a.rowId&&
b.gridData.index!==a.rowIndex))return d=b,!0});if(d)return d;if(a.considerSpans){var b=f.queryColumn(c,a),e=f.queryData(c,a);if(!b||!e)return null;var h=b.index,k=e.index;c.store.data.some(function(a){return c.columns.some(function(b){var e=b.index,n=b.index+(a.columnSpans&&a.columnSpans[b.field]||0),g=a.index;b=a.index+(a.rowSpans&&a.rowSpans[b.field]||0);if(e<=h&&n>=h&&g<=k&&b>=k)return d=f.querySingleCell(c,{columnIndex:e,rowIndex:g}),!0})})}return d},queryColumn:function(c,a){var d;c.columns.some(function(b){if(b.id===
a.columnId||b.index===a.columnIndex||b.field===a.columnField)return d=b,!0});return d},queryData:function(c,a){var d;c.store.data.some(function(b){if(b.id===a.rowId||b.index===a.rowIndex)return d=b,!0});return d},queryCells:function(c,a){if(a.fieldCell){var d=[],b=a.rowSpan||1,e=a.columnSpan||1;if(a=f.querySingleCell(c,a))for(var h=a.gridData.index;h<a.gridData.index+b;h++)for(var k=a.column.index;k<a.column.index+e;k++){var g=f.querySingleCell(c,{rowIndex:h,columnIndex:k});g&&d.push(g)}return d}return this.queryCellsInArray(c.getFieldCells(),
a)},queryCellsInArray:function(c,a){var d=[];if(!Object.keys(a).length)return d;c.forEach(function(b,c){if(void 0===a.cellIndex||c===a.cellIndex)if(void 0===a.cellIndexes||-1!==a.cellIndexes.indexOf(c))if(void 0===a.columnId||b.columnId===a.columnId)if(void 0===a.columnIds||-1!==a.columnIds.indexOf(b.columnId))if(void 0===a.columnIndex||b.column.index===a.columnIndex)if(void 0===a.columnIndexes||-1!==a.columnIndexes.indexOf(b.column.index))if(void 0===a.columnField||b.column.field===a.columnField)if(void 0===
a.columnFields||-1!==a.columnFields.indexOf(b.column.field))if(void 0===a.rowId||b.rowId===a.rowId)if(void 0===a.rowIds||-1!==a.rowIds.indexOf(b.rowId))if(void 0===a.rowIndex||b.gridData.index===a.rowIndex)void 0!==a.rowIndexes&&-1===a.rowIndexes.indexOf(b.gridData.index)||d.push(b)});return d},getTitleCell:function(c){var a=f.querySingleCell(c,{rowIndex:0,columnIndex:0});if(a&&!l.getFieldInfo(a)&&(1===c.columns.length||l.getColumnSpan(a)===c.columns.length))return a},isDynamicFieldCell:function(c,
a){return c._dynamicBindings&&c._dynamicBindings[a.column.field]},getDynamicallyBoundColumns:function(c,a){return c._dynamicBindings&&c._dynamicBindings[a.field]},getDynamicallyBoundFieldCells:function(c,a){if(a.column){var d=c._dynamicBindings&&c._dynamicBindings[a.column.field];if(!d)return null;var b=[];d.forEach(function(d){(d=d&&f.querySingleCell(c,{columnId:d.id,rowId:a.rowId}))&&b.push(d)});return b}},getAllBoundCells:function(c,a,d){var b=[],e={};a&&a.forEach(function(a){if((!d||d(a))&&!e[a.uniqueId]){e[a.uniqueId]=
!0;var h=f.getDynamicallyBoundFieldCells(c,a);h?h.forEach(function(a){b.push(a);e[a.uniqueId]=!0}):b.push(a)}});return m.removeDuplicates(b,"uniqueId")},trimDynamicBindings:function(c,a){var d=[],b={};a&&a.forEach(function(a){var e=f.getDynamicallyBoundFieldCells(c,a);e&&e.length?(b[e[0].uniqueId]||d.push(e[0]),e.forEach(function(a){b[a.uniqueId]=!0})):d.push(a)});return d},collectFieldInfos:function(c,a){var d=[];a=a||{};var b=a.fieldCells||c.getFieldCells();a.trimDynamicBinding&&b&&(b=f.trimDynamicBindings(c,
b));b&&b.forEach(function(a){var b=l.getFieldInfo(a);b&&d.push(b);(a=a.content&&a.content.collectFieldInfos&&a.content.collectFieldInfos())&&a.length&&(d=d.concat(a))});return d},cellHasFloatingTableParent:function(c){function a(c){return c.isFloatingTable?!0:c.parentWidget?a(c.parentWidget):!1}return c&&c.parentGrid?a(c.parentGrid):!1},getOverFieldCell:function(c,a){a=a||{};if(!g.isMouseOver(c.domNode))return null;var d=a.cellFilter||function(){return!0},b;c.getForegroundFloatingCells({topFirst:!0}).some(function(c){if(d(c)&&
g.isMouseOver(c.domNode,{checkAllChildren:a.checkAllChildren}))return b=c,!0});b||c.getFieldCells().some(function(c){if(d(c)&&g.isMouseOver(c.domNode,{checkAllChildren:a.checkAllChildren}))return b=c,!0});b||c.getBackgroundFloatingCells({topFirst:!0}).some(function(c){if(d(c)&&g.isMouseOver(c.domNode,{checkAllChildren:a.checkAllChildren}))return b=c,!0});return b}};return f});