// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/grid/coreUtils/GridCellRenderer","dojo/_base/declare dojo/aspect ./GridDataUtil ./GridStyleUtil ./GridCellContentScaler ./GridCellContentSynchronizer ../../supportClasses/conditionalStyling/ConditionalStyleUtil ../../supportClasses/templateJsonUtils/fieldInfo/FieldInfoRenderer esri/dijit/geoenrichment/ReportPlayer/core/sections/SectionTypes esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/ViewModes ./GridQueryUtil ./tooltip/GridCellTooltipBuilder ../../../_devConfig".split(" "),
function(r,w,f,x,t,y,u,n,z,h,v,A,B){function l(a){return a[a.parentGrid.hasRealBorders?"getContentWidth":"getWidth"]()}function p(a){return a[a.parentGrid.hasRealBorders?"getContentHeight":"getHeight"]()}var C={color:"#FF0000"},m=r(null,{_parentState:null,constructor:function(a,b,c){var d=this;t.fitContentInsideCell(a);this._setParentState(a);c.forEach(function(c){var e=c[1];b.own(w.after(a,c[0],function(){d._checkParentChanged(e,a)&&(t.fitContentInsideCell(a),y.syncParentFieldInfoWithElementState(a,
b))}))})},_setParentState:function(a){var b=a.getFullStyle();this._parentState={width:a.getWidth(),height:a.getHeight(),horizontalAlign:b.horizontalAlign,verticalAlign:b.verticalAlign}},_checkParentChanged:function(a,b){var c;switch(a){case "width":a=b.getWidth();this._parentState.width!==a&&(this._parentState.width=a,c=!0);break;case "height":a=b.getHeight();this._parentState.height!==a&&(this._parentState.height=a,c=!0);break;case "horizontalAlign":case "verticalAlign":if(a=b.getFullStyle(),this._parentState.horizontalAlign!==
a.horizontalAlign||this._parentState.verticalAlign!==a.verticalAlign)this._parentState.horizontalAlign=a.horizontalAlign,this._parentState.verticalAlign=a.verticalAlign,c=!0}return c}});return r(null,{renderCellContent:function(a){var b=a.parentGrid,c=f.getFieldInfo(a);if(B.emulateErrors.reportContainerRenderError)throw Error("Error test: something crashed whend building the UI layout!");if(c){if(c.isChart){this._placeChartInCell(b,a);return}if(c.isImage||c.isShape){this._renderCellTooltip(a);this._placeImageOrShapeInCell(b,
a,c.isImage);return}if(c.isReportSection){this._placeReportSectionInCell(b,a);return}if(c.isInfographic){this._placeInfographicInCell(b,a);return}c.isMissing&&a.setStyle(C);b=this._getRenderedContent(a,c)}else b=a.gridData[a.column.field],b={formattedValue:null===b||void 0===b||"number"===typeof b&&isNaN(b)?"":b,value:b,formatFunction:null,isUnavailableData:!1,conditionalStyle:null};this._applyRenderedContent(a,b);a.setContent(null);this._renderCellTooltip(a)},_renderCellTooltip:function(a){a.viewModel.dynamicReportInfo&&
A.setDynamicTooltipToCell(a,a.viewModel.dynamicReportInfo.templateVariableProvider)},updateViewMode:function(a){var b=f.getFieldInfo(a);b&&(b.hasVariable||b.script||b.alias||b.isRichText)&&this._applyRenderedContent(a,this._getRenderedContent(a,b))},_getRenderedContent:function(a,b){a=this._prepareRenderContextForFieldCell(a,b);return n.renderFieldInfoInTableCell(b,a)},_prepareRenderContextForFieldCell:function(a,b){var c=a.parentGrid,d=c.getSpecificViewMode(),e=c.getViewMode()===h.PREVIEW_VALUES;
!b||"SiteNote"!==b.name&&"SiteNotes"!==b.name||(e=!0);d&&(d.richText===h.PREVIEW_VALUES&&b&&b.isRichText?e=!0:d.variable===h.PREVIEW_VALUES&&b&&(b.hasVariable||b.script)&&(e=!0));b=e;d=c.getViewMode()===h.EDIT;return{previewValues:b,previewConditionalStyle:!d,getPreviewValueFunction:c.getPreviewValueFunction,fieldData:c.viewModel.dynamicReportInfo&&c.viewModel.dynamicReportInfo.fieldData,currentFeatureIndex:c.getFeatureIndexForCell(a),rowIndex:a.gridData&&a.gridData.index,isGraphicReport:c.viewModel.isGraphicStyle,
isMultiFeature:c.viewModel.dynamicReportInfo&&c.viewModel.dynamicReportInfo.isMultiFeature}},_applyRenderedContent:function(a,b){if(b){f.setFieldCellContent(a,b.formattedValue);if(!b.isUnavailableData)if("number"===typeof b.value&&(f.setNumericCellValue(a,b.value),a.setNumberValue(b.value,b.formatFunction,a.parentGrid.enableNumberAnimation)),b.conditionalStyle)a.setStyle(b.conditionalStyle.style),"string"===typeof b.conditionalStyle.formattedValue&&f.setFieldCellContent(a,b.conditionalStyle.formattedValue),
a.__hasConditionalStyle=!0;else if(!1===b.conditionalStyle||a.__hasConditionalStyle)delete a.__hasConditionalStyle,a.setStyle(x.combineCellStyle(a.parentGrid,a.gridData,a.column));a.parentGrid&&a.parentGrid.viewModel.dynamicReportInfo&&a.setUrl(f.getFieldCellUrl(a))}},_placeChartInCell:function(a,b){var c={viewModel:a.viewModel,theme:a.theme,currentFeatureIndex:a.getFeatureIndexForCell(b),parentWidget:b,onContentLoadingStart:a.onContentLoadingStart.bind(a),onContentLoadingEnd:a.onContentLoadingEnd.bind(a)};
return this._createChartPageFromParams(a,b,c)},_createChartPageFromParams:function(a,b,c){var d=f.getFieldInfo(b).chartJson;a=a.viewModel.layoutBuilder.createElement("chart",{node:b.getContentContainerNode(),placeFunc:function(a){b.setContent(a)},json:d,creationParams:c});new m(b,a,[["onWidthChanged","width"],["onHeightChanged","height"]]);return a},_placeImageOrShapeInCell:function(a,b,c){var d=f.getFieldInfo(b),e=d[c?"imageJson":"shapeJson"],q=l(b),h=p(b);if(c){if(d.triggerJson&&a.viewModel.dynamicReportInfo){var g=
n.getValueFromFieldData(d.triggerJson.fieldInfo,{fieldData:a.viewModel.dynamicReportInfo.fieldData,currentFeatureIndex:a.getFeatureIndexForCell(b)});u.processImageJsonForTrigger(e,g.value,d.triggerJson);g.isUnavailableData||"number"!==typeof g.value||(f.setNumericCellValue(b,g.value),b.setNumberValue(g.value,g.formatFunction,!1))}else d.triggerJson&&(g=n.getConditionalStylePreview(d,b.gridData.index))&&"number"===typeof g.value&&(u.processImageJsonForTrigger(e,g.value,d.triggerJson),f.setNumericCellValue(b,
g.value));e.style.width&&e.style.height&&!e.fitParent&&Math.round(e.style.width)!==Math.round(q)&&Math.round(e.style.height)!==Math.round(h)?e.fitParent=!1:(e.fitParent=!0,e.style.width=q,e.style.height=h)}else e.style.width=q,e.style.height=h;var k,d={viewModel:a.viewModel,theme:a.theme,parentWidget:b,currentFeatureIndex:a.getFeatureIndexForCell(b),alignParams:b.getFullStyle(),imageTriggerJson:d.triggerJson,getPreviewValueFunction:a.getPreviewValueFunction,applyThemeStyle:a.applyThemeStyle,onInitialized:function(){if(b.domNode){var a=
l(b),c=p(b);k&&k.resize&&k.resize({w:a,h:c},b.getFullStyle())}},onContentLoadingStart:a.onContentLoadingStart.bind(a),onContentLoadingEnd:a.onContentLoadingEnd.bind(a)};k=this._createImageOrShapeFromParams(a,b,e,c,d);new m(b,k,[["onWidthChanged","width"],["onHeightChanged","height"],["setStyle","horizontalAlign"]]);return k},_createImageOrShapeFromParams:function(a,b,c,d,e){return a.viewModel.layoutBuilder.createElement(d?"image":"shape",{node:b.getContentContainerNode(),placeFunc:function(a){b.setContent(a)},
relativeParent:b.domNode,json:c,creationParams:e})},_placeReportSectionInCell:function(a,b){var c={"class":"adjustableGrid_inCellSection"};c.json=f.getFieldInfo(b).sectionJson;c.viewModel=a.viewModel;c.theme=a.theme;c.viewPortContainer=a.viewPortContainer;c.parentWidget=b;c.currentFeatureIndex=a.getFeatureIndexForCell(b);c.initialWidth=l(b);c.noContentOffset=v.cellHasFloatingTableParent(b);c.hasFixedLayout=!1;c.initialViewMode=a.getViewMode();c.onContentLoadingStart=a.onContentLoadingStart.bind(a);
c.onContentLoadingEnd=a.onContentLoadingEnd.bind(a);return this._createReportSectionFromParams(a,b,c)},_createReportSectionFromParams:function(a,b,c){c.parentGridCell=b;c.isPagePanelSection=a.isReportContainerPageGird;a=c.json&&c.json.stack&&c.json.type!==z.EMPTY?a.viewModel.layoutBuilder.createElement("section",c,b.getContentContainerNode()):a.viewModel.layoutBuilder.createElement("emptySection",c,b.getContentContainerNode());b.setContent(a);new m(b,a,[["onWidthChanged","width"],["onHeightChanged",
"height"]]);return a},_placeInfographicInCell:function(a,b){var c=f.getFieldInfo(b).infographicJson,d={viewModel:a.viewModel,theme:a.theme,parentWidget:b,currentFeatureIndex:a.getFeatureIndexForCell(b),width:l(b),height:p(b),adjustElementsWhenResized:v.cellHasFloatingTableParent(b),onContentLoadingStart:a.onContentLoadingStart.bind(a),onContentLoadingEnd:a.onContentLoadingEnd.bind(a)};b=this._createInfographicFromParams(a,b,c,d);b.setViewMode&&b.setViewMode(a.getViewMode());return b},_createInfographicFromParams:function(a,
b,c,d){a=a.viewModel.layoutBuilder.createElement("infographic",{node:b.getContentContainerNode(),placeFunc:function(a){b.setContent(a)},json:c,creationParams:d});new m(b,a,[["onWidthChanged","width"],["onHeightChanged","height"]]);return a}})});