// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/infographics/locator/LocatorTableInfographic","dojo/_base/declare dojo/when dojo/string ../paginatableTable/PaginatableTableInfographic ../paginatableTable/SectionJsonsBuilder ./ExportToExcelUtil esri/dijit/geoenrichment/utils/InvokeUtil esri/dijit/geoenrichment/utils/RegExpUtil esri/dijit/geoenrichment/utils/WaitingUtil dojo/i18n!esri/nls/jsapi".split(" "),function(c,e,k,f,g,l,h,m,n,d){d=d.geoenrichment.dijit.ReportPlayer.LocatorTableInfographic;
c=c(f,{noDataText:d.noLocatorData,_locatorPointsController:null,_areaName:null,_areaShortName:null,_stats:null,_unitedSectionJson:null,updateInfographic:function(a){if(this.domNode)return a.locatorCalculatorInfo&&this.viewModel.dynamicReportInfo&&(this.viewModel.dynamicReportInfo.isMultiFeature?(this._areaName=this.viewModel.dynamicReportInfo.combinedAreasInfo.name,this._areaShortName=this.viewModel.dynamicReportInfo.combinedAreasInfo.shortName):(this._areaName=this.viewModel.dynamicReportInfo.analysisAreas[this.currentFeatureIndex].name,
this._areaShortName=this.viewModel.dynamicReportInfo.analysisAreas[this.currentFeatureIndex].shortName),this._locatorPointsController=this.viewModel.getLocatorPointsController(a.locatorCalculatorInfo,this.currentFeatureIndex),this.own(this._locatorPointsController)),this.inherited(arguments)},_doUpdateContent:function(){this.domNode&&this.width&&(this.inherited(arguments),this._registerLocatorPointsController())},_buildSectionJsonsAndStat:function(){var a=this,b=g.buildSectionJsonsAndStat({headerSectionJson:this._currentInfographicJson.headerSectionJson,
dataSectionJson:this._currentInfographicJson.dataSectionJson,calculatorDataArray:this._getCalculatorDataArray(),filterRanges:this._filterRanges,searchTextRe:this._searchTextRe,sorting:this._sorting,minRowHeight:this.minRowHeight,scaleToFitHeight:this._currentInfographicJson.scaleToFitHeight,height:this.height,width:this.width,hasTitle:!!this._currentInfographicJson.titleSectionJson,titleHeight:this._getTitleHeight(),hasFooter:this._currentInfographicJson.showNumberOfLocations,footerHeight:f.BOTTOM_AREA_HEIGHT,
setAttributeVisibleAt:function(b,d){a._locatorPointsController&&a._locatorPointsController.setPointVisibleAt(b,d)}});this._stats=b&&b.stats;this._unitedSectionJson=b&&b.unitedSectionJson;return b},_resizeSection:function(a){this.isEditMode&&this.inherited(arguments);var b=a.getTables()[0];this._locatorPointsController&&this._locatorPointsController.registerLocatorTable(b)},_getCalculatorDataArray:function(){return this._locatorPointsController.getCalculatorDataArray()},_renderFootNote:function(){var a=
this.getNumPointsShown()||0;this.footnoteDiv.innerHTML=this._currentInfographicJson.showNumberOfLocations&&a?1===a?d.oneClosestLocations:k.substitute(d.numClosestLocations,{numPoints:a}):""},_getFooterHeight:function(){return!this._isSinglePage||this._currentInfographicJson.showNumberOfLocations?f.BOTTOM_AREA_HEIGHT:0},_registerLocatorPointsController:function(){this._locatorPointsController&&this._locatorPointsController.setLocatorTableCallbacks({getCellForPointAtFunc:this._getCellForPointAt.bind(this),
getPointIndexForCellFunc:this._getPointIndexForCellFunc.bind(this)})},_getPointIndexForCellFunc:function(a){return a&&g.getAttributeIndexForGridData(a.gridData)},_getCellForPointAt:function(a){var b=-1,d;this._sectionJsons.some(function(c,e){return c.stack[0].data.data.some(function(f){if(g.getAttributeIndexForGridData(f)===a)return b=e,d=c,!0})});if(-1!==b){this.pagination.set("currentPage",b,!0);var c;this._getSectionByJson(d).getTables()[0].getFieldCells().some(function(b){if(g.getAttributeIndexForGridData(b.gridData)===
a)return c=b,!0});return c}},_filterRanges:null,_searchText:null,_searchTextRe:null,getFilterRanges:function(){return e(this._updatePromise,function(){return this._stats&&this._stats.ranges}.bind(this))},setFilterRanges:function(a){this._filterRanges=a;h.invoke(this,"_doUpdateContent",50)},setSearchText:function(a){this._searchTextRe=(this._searchText=a)&&m.createRegExp(a,"i",!0);h.invoke(this,"_doUpdateContent",50)},getNumPointsTotal:function(){return this._stats&&this._stats.numAttributesTotal},
getNumPointsShown:function(){return this._stats&&this._stats.numAttributesShown},getVisualState:function(){return this._filterRanges||this._searchText||this._sorting||this._columnWidths?{filterRanges:this._filterRanges,searchText:this._searchText,sorting:this._sorting,columnWidths:this._columnWidths}:null},setVisualState:function(a){a&&(a.filterRanges&&this.setFilterRanges(a.filterRanges),a.searchText&&this.setSearchText(a.searchText),a.sorting&&this._setSorting(a.sorting),a.columnWidths&&(this._columnWidths=
a.columnWidths,h.invoke(this,"_doUpdateContent",50)))},canExportToExcel:function(){return this.viewModel.canExportToExcel()},exportToExcel:function(){var a=this;return e(this._updatePromise,function(){return e(a.viewModel.pepareExportToExcelParameters({layerID:a._locatorPointsController.getLayerID(),hasMaps:a._locatorPointsController.getMapInfos()&&a._locatorPointsController.getMapInfos().length}),function(b){return n.showProgressPromise(a.domNode,e(a.prepareExportToExcelParameters(b),function(b){return a.viewModel.exportToExcel(b)}))})})},
prepareExportToExcelParameters:function(a){a=a||{};return l.prepareExportParameters({areaName:this._areaName,areaShortName:this._areaShortName,layerName:this._locatorPointsController.getLayerName(),layerID:this._locatorPointsController.getLayerID(),sectionJson:this._unitedSectionJson,mapInfos:this._locatorPointsController.getMapInfos(),exportMaps:a.exportMaps})},_destroySections:function(){this.inherited(arguments);this._stats=null}});c.MIN_ROW_HEIGHT=f.MIN_ROW_HEIGHT;return c});