// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/printing/PrintableContainer","dojo/_base/declare dojo/Deferred dojo/when dojo/dom-class dojo/dom-construct esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/async/AsyncQueue ./_PrintSettingsSupport ../PlayerResizeModes ../PlayerViewModes".split(" "),function(q,r,c,t,h,k,e,u,v,l){return q(u,{domNode:null,_player:null,_viewModel:null,_visualState:null,_initRollBackFunc:null,_pageSettingsRollBackFunc:null,_pageSettings:null,_pageFitParams:null,
_headerFooterParams:null,_allowDataDrilling:!1,_commandId:null,constructor:function(b,a){this._player=b;this._viewModel=a;this.domNode=b.printableDiv},initialize:function(b){var a=this;this._commandId=b.commandId;return c(function(){function w(){var n=e.executeFunctions([function(){f&&h.destroy(f);d&&d.resolve();k.showNodeFromBackground(a.domNode)},function(){a.getAllReportContainers().forEach(function(a,b){a.showPageAt&&a.showPageAt(m[b])})},function(){a._setPrintMode(!1);a._setAnimationSuspended(!1);
return a._player.resize()},function(){if(g)return a._player.viewMode=g,a._player.refresh({rerenderContent:!0,waitUntilAllContentIsReady:!1})}],0);b.onShowWaiting(n);return n}var m=[],f,g;a._player.playerToolbar.closePopup();a._setAnimationSuspended(!0);var d,p=c(function(){return e.executeFunctions([function(){a._player.resizeMode===v.FIT_WINDOW?f=h.create("div",{innerHTML:a._player.domNode.innerHTML,"class":"esriGEAbsoluteStretched esriGEReportPlayerPrintViewCopy"},a._player.printBackgroundView):
(d=new r,b.onShowWaiting(d.promise))},function(){if(a._player.viewMode!==l.FULL_PAGES)return g=a._player.viewMode,a._player.viewMode=l.FULL_PAGES,a._player.refresh({rerenderContent:!0,waitUntilAllContentIsReady:!0})},function(){a._setPrintMode(!0);return e.executeFunctions(a.getAllReportContainers().map(function(a,b){return function(){a.resetZoom&&a.resetZoom();m[b]=a.getCurrentPageIndex&&a.getCurrentPageIndex();a.showAllPages&&a.showAllPages();a.collapseContent&&a.collapseContent()}}),0)},function(){k.hideNodeInBackground(a.domNode,
"reportPlayerBeingPrinted")}],0)}(),function(){a._initRollBackFunc=w;return a._player.isContentLoading()});b.onShowWaiting(p);return p}(),function(){return c(a._checkPrintSettings(b),function(b){return"cancel"===b?null:a})})},_setPrintMode:function(b){t[b?"add":"remove"](this.domNode,"esriGEReportPlayerPrintNode esriGEReportPlayer");this._player.setPrintMode(b)},_animationAllowedMemo:void 0,_setAnimationSuspended:function(b){b?(this._animationAllowedMemo=this._viewModel.animationAllowed,this._viewModel.animationAllowed=
!1):this._viewModel.animationAllowed=this._animationAllowedMemo},getCurrentReportContainer:function(){return this._player.getCurrentReportContainer()},getAllReportContainers:function(){return this._player.getAllReportContainers()},getFitParams:function(){return this._pageFitParams},getHeaderFooterParams:function(){return this._headerFooterParams},getDocumentOptions:function(){return this._pageSettings||this.getCurrentReportContainer().documentOptions},getSelectedCommandId:function(){return this._commandId},
allowDataDrilling:function(){return this._allowDataDrilling},getNumberOfPages:function(){return this._player.getNumberOfPages()},stop:function(){var b=this;return c(this._pageSettingsRollBackFunc&&this._pageSettingsRollBackFunc(),function(){return c(b._initRollBackFunc&&b._initRollBackFunc())})}})});