// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/map/layers/locator/LocatorPointsBuilder","dojo/_base/Color dojo/_base/lang dojo/when esri/graphic esri/layers/GraphicsLayer esri/renderers/SimpleRenderer esri/renderers/jsonUtils esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/jsonUtils esri/geometry/jsonUtils esri/dijit/PopupTemplate ../LayerInfoLoader ../../Projector ../../symbols/HighlightedSymbolGenerator ../../../../../dataProvider/supportClasses/AreasInfoTemplateBuilder dojo/i18n!esri/nls/jsapi".split(" "),
function(l,r,t,u,y,v,z,m,n,A,B,C,D,w,E,F,p){p=p.geoenrichment.dijit.ReportPlayer.ReportPlayer;var k={},q={_defaultLocatorSymbol:null,_defaultLocatorSymbolHighlighted:null,getDefaultLocatorSymbol:function(){this._defaultLocatorSymbol||(this._defaultLocatorSymbol=new m(m.STYLE_CIRCLE,10,new n(n.STYLE_SOLID,new l([255,0,0,1]),2),new l([255,0,0,.75])));return this._defaultLocatorSymbol},getDefaultLocatorSymbolHighlighted:function(){this._defaultLocatorSymbolHighlighted||(this._defaultLocatorSymbolHighlighted=
new m(m.STYLE_CIRCLE,11,new n(n.STYLE_SOLID,new l([255,255,255,1]),2),new l([255,50,50,1])));return this._defaultLocatorSymbolHighlighted}};k.addLocatorPoints=function(b,a){b.locatorPointsControllers&&b.locatorPointsControllers.forEach(function(d){var c=d.getCalculatorDataArray();if(c&&c.length){var e=d.getRendererJson(b.calculatorFieldName),f=new y,l=e?z.fromJson(r.clone(e)):new v(q.getDefaultLocatorSymbol());f.setRenderer(l);var g=[],x=[],G=e?A.fromJson(r.clone(e.symbol)):q.getDefaultLocatorSymbol();
c.forEach(function(a,c){if(a.Point||a.Polygon){var e=d.getVariableObjects().map(function(b){return{label:b.alias,value:a[b.fieldName]}}),e=new C({title:"",fieldInfos:[],description:F.buildAttributesTable(null,e)}),h=r.mixin({},a);delete h.Point;delete h.Polygon;h.__pointIndex=c;c=B.fromJson(JSON.parse(a.Point||a.Polygon));h=new u({attributes:h});w.needProject(c,b.map)?(g.push(h),x.push(c)):(h.setGeometry(c),f.add(h));h.setSymbol(G);h.setInfoTemplate(e)}});k._registerLayer(f,b.map,d,b);a.registerLayerInfo({layer:f,
type:a.LOCATOR_POINTS,preferredIndex:d.getLayerIndex(b.calculatorFieldName),geometryType:c[0].Point?"esriGeometryPoint":"esriGeometryPolygon"});k._provideNameForLayer(f,d,b);t(w.projectGeometries(x,b.map),function(b){b.forEach(function(b,a){a=g[a];a.setGeometry(b);f.add(a)})})}})};k._registerLayer=function(b,a,d,c){var e=d.getRendererJson(c.calculatorFieldName);E.getHighlightSymbol({rendererJson:e,defaultHighlightSymbol:q.getDefaultLocatorSymbolHighlighted()}).then(function(f){var e=f.symbol,g;f.frameSymbol&&
(g=new u,g.setSymbol(f.frameSymbol));d.setLocatorPointsLayer(c.calculatorFieldName,b,a,{getPointIndexForGraphicFunc:function(b){return b.attributes&&b.attributes.__pointIndex},getGraphicForPointAtFunc:function(a){var c;b.graphics.some(function(b){if(b.attributes&&b.attributes.__pointIndex===a)return c=b,!0});return c},setGraphicHighlightedFunc:function(a,c){g&&b.remove(g);!c&&a.__originalSymbol?(a.setSymbol(a.__originalSymbol),delete a.__originalSymbol):c&&!a.__originalSymbol&&(a.__originalSymbol=
a.symbol,a.setSymbol(e),b.remove(a),g&&(g.setGeometry(a.geometry),b.add(g)),b.add(a))}})})};k._provideNameForLayer=function(b,a,d){var c=a.getLayerUrl(),e=a.getLayerID();a=(a=a.getLayerName(d.calculatorFieldName))&&{name:a};c?t(a||D.getInfo(c),function(a){b.name=a&&a.name||p.locatorLayerLegendTitle;b.onVisibilityChange()}):t(a||d.geClient&&d.geClient.getLayerInfo(d.countryID,e),function(a){b.name=a&&a.name||p.locatorLayerLegendTitle;b.onVisibilityChange()})};k.getDefaultLocatorRenderer=function(){return new v(q.getDefaultLocatorSymbol())};
return k});