// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/dataProvider/commands/CreateHTMLCommand","require dojo/_base/declare dojo/promise/all dojo/Deferred dojo/when ./createHTML/CommandMode ../../PlayerCommands ./supportClasses/ProgressSteps dojo/i18n!esri/nls/jsapi".split(" "),function(w,x,y,z,e,p,A,f,g){function B(){var d=new z;w(["dijit/Dialog","./createHTML/HTMLToSVGBuilder","./createHTML/HTMLStringBuilder","esri/dijit/geoenrichment/utils/FileUtil","./mapToImage/MapToImageUtil"],function(b,e,a,f,c){m=
b;q=e;u=a;v=f;k=c;d.resolve()});return d.promise}g=g.geoenrichment.dijit.ReportPlayer.ReportPlayer;var m,q,u,v,k;return x(null,{id:A.HTML,errorMessage:g.exportInfographicError,exportMapErrorMessage:g.exportMapError,_player:null,_saveFiles:!0,_stopPrintableContainer:!0,_printableContainer:null,_mode:p.SVG_IN_HTML,_requestSizeLimit:0,_mergePageIndexes:!0,_currentProgressBack:null,execute:function(d,b,g){var a=this;return B().then(function(){function m(){return e(l&&l.undo(),function(){return e(a._stopPrintableContainer&&
c&&c.stop(),function(b){a._stepFinished(f.UNSET_LAYOUT);return b})})}this._player=d;var c,l;this._currentProgressBack=g;var n={svgInHtmlString:null,svgStrings:null,documentOptions:null,additionalFiles:null};return e(function(){function h(){return y([c.getFitParams(),c.getHeaderFooterParams(),c.getDocumentOptions()]).then(function(a){return{fitParams:a[0],headerFooterParams:a[1],documentOptions:a[2]}})}c=b.printableContainer;a._printableContainer=c;k.enableCaching();return e(k.replaceMapWithImage(d,
{saveImagesAsDataUrl:!0,printMapTaskUrl:b.printMapTaskUrl}),function(b){l=b;k.clearCaching();a._stepFinished(f.REPLACE_MAPS);return h()})}(),function(h){if(c)return e(u.buildHtmlStringForPlayer(c,h.headerFooterParams,h.documentOptions,a._mergePageIndexes),function(c){function g(c,d){if(!b.returnAsHtmlText&&!b.returnAsSvgText&&a._saveFiles&&c)return a._confirmSaveFile(d,function(){return v.saveTextFile(c,d)})}function l(){var b=k+".svg";return e(q.htmlToSvg(c.domString,h.fitParams,a._requestSizeLimit,
t),function(a){n.svgStrings=a;return g(a[0],b)})}function m(){var b=k+".html";return e(q.htmlToSvgInHtml(c.domString,k,h.fitParams,a._requestSizeLimit,t),function(a){n.svgInHtmlString=a;return g(a,b)})}if(c.domString){a._stepFinished(f.PREPARE_DOM);var k=d.getReportTitle(),t=function(b,c){a._stepFinished(f.RENDER_PAGE,b+1,c)};n.documentOptions=h.documentOptions;var r=a._mode;b.returnAsHtmlText&&(r=p.SVG_IN_HTML);b.returnAsSvgText&&(r=p.SVG);switch(r){case p.SVG:return l(h);case p.SVG_IN_HTML:return m(h)}}})}).otherwise(function(c){if(!b.skipErrorNotification)return a._handleError(c)}).always(function(){return e(m(),
function(){return l&&l.errors.length?(!b.skipErrorNotification&&a._handleExportMapError(l.errors[0]),null):b.returnAsHtmlText?n.svgInHtmlString:b.returnAsSvgText?n.svgStrings:n})})}.bind(this))},_stepFinished:function(d,b,e){if(this._currentProgressBack){var a=0;switch(d){case f.REPLACE_MAPS:a=10;break;case f.PREPARE_DOM:a=20;break;case f.RENDER_PAGE:a=20+70*b/e;break;case f.UNSET_LAYOUT:a=100}this._currentProgressBack(a/100)}},_handleError:function(d){console.log(d);(new m({title:"Error",content:this.errorMessage})).show()},
_handleExportMapError:function(d){console.log(d);(new m({title:"Error",content:this.exportMapErrorMessage})).show()},_confirmSaveFile:function(d,b,e){return b()}})});