// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/builder/columnBarLine/_LineChartSeriesCalculator","dojo/_base/lang ../../ThemeCalculator ../../ChartTypes ../../ChartLineStyles ../../ChartLineMarkers ../../AxisUtil ../utils/ChartDataUtil ../utils/TooltipInfoBuilder ../ChartPlots esri/dijit/geoenrichment/utils/ColorUtil ./_AxisBuilder ./_PointLabelUtil".split(" "),function(F,u,C,y,G,H,D,I,J,K,L,B){var M={calcLineStyle:function(a,g,m,c){var b=c.comparisonInfo,k=c.visualProperties;g=u.calcColorForPoint({point:null,
seriesItem:a,pointIndex:0,seriesIndex:g,numSeries:m.length,chartType:C.LINE,themeSettings:c.themeSettings,isComparisonSeries:a.isComparisonSeries,comparisonInfo:b,isMultiFeature:c.isMultiFeatureChart});m=k.lineThickness||1;k=k.fillLineArea?k.lineAreaOpacity:1;c=y.SOLID;var e=void 0;a.isComparisonSeries&&b&&(b.lineThickness&&(m=b.lineThickness),b.lineStyle&&(c=b.lineStyle),e=b.lineMarker?G.getMarkerPath(b.lineMarker):u.getComparisonSymbol());1>k&&g&&(g=K.toColor(g),g.a=k);return{color:g,width:m,style:y.toGFXValue(c),
marker:e}}};return{calcSeriesLine:function(a){var g=a.chart,m=a.chartType,c=a.visualProperties,b=a.seriesItems,k=1===b.length,e=a.seriesItemsWithComparison||b,q=a.isSecondaryPlot,z=a.reverseXY||m===C.VERTICAL_LINE,N=a.comparisonInfo,b=a.themeSettings,v=a.viewModel,r=[],f={minYValue:Infinity,maxYValue:-Infinity,stackedValues:c.isStacked?[]:null,crossSeriesStats:null},A=a.primaryPlotStat&&a.primaryPlotStat.pointIndexToTooltipsHash||{},n=e.map(function(c,h){return this._collectStatisticsForSeries(a,
c,q?2*h+1:h,f)},this);f.crossSeriesStats=a.isMultiFeatureChart&&this._collectCrossSeriesStats(n);e.forEach(function(b,h){if(b.points.length){var w=M.calcLineStyle(b,q?2*h+1:h,e,a),E={name:b.label,data:[],isComparisonSeries:b.isComparisonSeries,params:{plot:q?J.SECONDARY:void 0,stroke:{color:w.color,width:w.width,style:w.style},fill:w.color,outline:!1}},x=n[h];b.points.forEach(function(d,e){function r(){return q&&!a.oppositeDirections&&2===a.primarySeries.length?0===h?-.15:.15:0}var n=x.values[e],
t=n||0,p=e+1;B.updatePointIndexToLabelMap(g,p,d,v);var l=a.isMultiFeatureChart&&f.crossSeriesStats[e],l=I.getTooltipInfo({yValue:n,pointLabel:B.getPointLabel(d,v),seriesLabel:b.label,minInSeriesValue:x.minInSeries,maxInSeriesValue:x.maxInSeries,sumInSeriesValue:x.valuesSum,absSumInSeriesValue:x.absValuesSum,avgInSeriesValue:x.avgInSeries,minInAreasValue:l&&l.min,maxInAreasValue:l&&l.max,sumInAreasValue:l&&l.sum,absSumInAreasValue:l&&l.absSum,avgInAreasValue:l&&l.avg,visualProperties:c,chartType:m,
isMultiFeature:a.isMultiFeatureChart,color:w.color,conditionalStyling:null,fieldInfo:d.fieldInfo,isThisAreaSpecific:N&&!a.isMultiFeatureChart?!b.isComparisonSeries:void 0,isThisAreaSingleSeries:k,decimals:d.value&&d.value.decimals}),u=A[p]=A[p]||[];u.push(l);l.getGroup=function(){return u};d={originalValue:n,isUnavailableData:isNaN(n),unsortedIndex:e,seriesIndex:h,name:B.getPointLabel(d,v),_valuesSumsInSeries:x.absValuesSum,point:d,fill:"#FFFFFF",stroke:{color:w.color,width:1,style:y.toGFXValue(y.SOLID)},
outline:!1,tooltip:l};v.isGraphicStyle?w.marker&&(d.marker=w.marker):d.marker=void 0;z?(d.x=t*(q&&a.oppositeDirections&&1===h?-1:1),d.y=p+r(),d.valueProp="x"):(d.x=p+r(),d.y=t*(q&&a.oppositeDirections&&1===h?-1:1),d.valueProp="y");c.yAxis.showValuesAsWeightsInSeries&&(d[z?"x":"y"]/=x.absValuesSum/100);E.data.push(d)});r.push(E)}},this);f.stackedValues&&(f.stackedValues.sort(function(a,h){return h-a}),f.minYValue=f.stackedValues[f.stackedValues.length-1],f.maxYValue=f.stackedValues[0]);if(q){if(a.primaryPlotStat&&
(b=H.getPrettifyYAxisParameters(Math.min(f.minYValue,a.primaryPlotStat.minYValue),Math.max(f.maxYValue,a.primaryPlotStat.maxYValue),{baseLineValue:c.yAxis.baseLineValue,renderColumnBarsInOppositeDirections:a.oppositeDirections,previewBelowZero:!v.dynamicReportInfo}),F.mixin(g.axes.y.opt,{majorTickStep:b.majorTickStep,minorTickStep:b.minorTickStep,min:b.min,max:b.max})),1===a.primarySeries.length){var p=z?"y":"x",t=[];a.primarySeries[0].data.forEach(function(a){var h=r[0].data[a.unsortedIndex];h[p]=
a.x;t.push(h)});r[0].data=t}}else L.prettifyYAxis(f.minYValue,f.maxYValue,c.yAxis.baseLineValue,g,c,m,b,v);return r},_collectStatisticsForSeries:function(a,g,m,c){var b=a.chartType,k=a.viewModel,e=a.visualProperties,q=a.currentFeatureIndex,z=a.isMultiFeatureChart,u=a.comparisonFeatureIds,v=a.isSecondaryPlot,r=a.ge,f=[],A=0,n=0,p=1E6,t=-1E6,y=2===a.seriesItems.length&&a.oppositeDirections&&v?D.CHART_DATA_SMOOTH:null;g.points.forEach(function(a,c){a=D.getPointValue({point:a,index:c,seriesIndex:m,maxValue:!1,
chartType:b,visualProperties:e,viewModel:k,currentFeatureIndex:z?m:q,chartData:y,isComparisonSeries:g.isComparisonSeries,comparisonFeatureId:u&&u[0],ge:r,allowNegativeValuesInPreview:!1});a=(f[c]=a)||0;A+=a;n+=Math.abs(a);p=Math.min(p,a);t=Math.max(t,a)});g.points.forEach(function(a,b){a=f[b];a=e.yAxis.showValuesAsWeightsInSeries?a/n*100:a;c.stackedValues?(c.stackedValues[b]=c.stackedValues[b]||0,c.stackedValues[b]+=a):(c.minYValue=Math.min(a,c.minYValue),c.maxYValue=Math.max(a,c.maxYValue))});return{values:f,
valuesSum:A,absValuesSum:n,minInSeries:p,maxInSeries:t,avgInSeries:A/g.points.length}},_collectCrossSeriesStats:function(a){return a.length?a[0].values.map(function(g,m){var c=0,b=0,k=1E6,e=-1E6;a.forEach(function(a){a=a.values[m]||0;c+=a;b+=Math.abs(a);k=Math.min(k,a);e=Math.max(e,a)});return{sum:c,absSum:b,min:k,max:e,avg:c/a.length}}):[]}}});