// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/reportContainerGrid/utils/ZoomUtil",["dojo/_base/lang","dojo/sniff","esri/dijit/geoenrichment/utils/animation/Animator","esri/dijit/geoenrichment/utils/DomUtil","esri/dijit/geoenrichment/utils/ObjectUtil"],function(m,l,n,k,g){function p(a){if(a.__zoomInfo&&1!==a.__zoomInfo.scale){var b=a.__zoomInfo;b.isFitPageScale=g.compareEqual(b.scale,c._getFitPageScale(b.originalW,b.originalH,a),2);b.isFitPageWidthScale=g.compareEqual(b.scale,c._getFitPageWidthScale(b.originalW,
a),2);b.isFitPageHeightScale=g.compareEqual(b.scale,c._getFitPageHeightScale(b.originalH,a),2);return b}return a.__zoomInfo={scale:1,originalW:a.getScrollableContainer().offsetWidth,originalH:a.getScrollableContainer().offsetHeight,isFitPageScale:!1,isFitPageWidthScale:!1,isFitPageHeightScale:!1}}function f(a,b,d,e){if(b){e=e||c.getZoomInfo(a).scale;var f=Math.max(.2,Math.min(10,b.scale))||1;a.__zoomInfo=b;a.__zoomAnimation&&a.__zoomAnimation.stop();if(d&&d.showAnimation)return a.__zoomAnimation=
n.animateProperty({duration:200,properties:{p:{start:e,end:f,easing:"linear"}},progressFunction:function(b,d,c){h(a,d,1===c)},endFunction:function(){delete a.__zoomAnimation}}),a.__zoomAnimation.promise;h(a,f,!0)}else a.__zoomInfo=null,h(a,1,!0)}function h(a,b,d){var c=a.scalableContainer.style,f=1!==b?"0% 0%":"",g=1!==b?"scale("+b+")":"",h=l("webkit")?"webkitTransformOrigin":"transformOrigin",k=l("webkit")?"webkitTransform":"transform";c[h]=f;c[k]=g;a.__zoomInfo&&(a.__zoomInfo.scale=b);a._syncFillerContainer();
d&&a.emitZoomChangedEvent()}var c={getZoomInfo:function(a){return m.mixin({},p(a))},setZoomInfo:function(a,b,c){return f(a,b,c)},zoomIn:function(a,b){var d=c.getZoomInfo(a);d.scale+=.2;return f(a,d,b)},zoomOut:function(a,b){var d=c.getZoomInfo(a);d.scale-=.2;return f(a,d,b)},zoomToFitPage:function(a,b){var d=c.getZoomInfo(a).scale;c.reset(a);var e=c.getZoomInfo(a);e.scale=c._getFitPageScale(e.originalW,e.originalH,a);return f(a,e,b,d)},zoomToFitPageWidth:function(a,b){var d=c.getZoomInfo(a).scale;
c.reset(a);var e=c.getZoomInfo(a);e.scale=c._getFitPageWidthScale(e.originalW,a);return f(a,e,b,d)},zoomToFitPageHeight:function(a,b){var d=c.getZoomInfo(a).scale;c.reset(a);var e=c.getZoomInfo(a);e.scale=c._getFitPageHeightScale(e.originalH,a);return f(a,e,b,d)},_getFitPageScale:function(a,b,d){var e=d.getCurrentPageDim();a=(a-c._getPrettyOffset(d).w)/e.w;b=(b-c._getPrettyOffset(d).h)/e.h;return Math.min(a,b)},_getFitPageWidthScale:function(a,b){return(a-c._getPrettyOffset(b).w-k.getScrollbarSize().w)/
b.getCurrentPageDim().w},_getFitPageHeightScale:function(a,b){return(a-c._getPrettyOffset(b).h-k.getScrollbarSize().h)/b.getCurrentPageDim().h},setZoomPercent:function(a,b,d){var e=c.getZoomInfo(a);e.scale=b/100;return f(a,e,d)},setBestZoom:function(a){var b=c.getZoomInfo(a),d=a.getCurrentPageDim();(b.originalW<d.w||b.originalH<d.h)&&c.zoomToFitPage(a)},_getPrettyOffset:function(a){return{w:30+a.renderOptions.minLeft+a.renderOptions.minRight,h:30+a.renderOptions.minTop+a.renderOptions.minBottom}},
reset:function(a){f(a,null)}};return c});