// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/Scalebar","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/has dojo/query ../kernel ../lang ../domUtils ../units ../SpatialReference ../WKIDUnitConversion ../geometry/Point ../geometry/ScreenPoint ../geometry/Polyline ../geometry/geodesicUtils ../geometry/webMercatorUtils ../geometry/screenUtils ../geometry/normalizeUtils dojo/i18n!../nls/jsapi".split(" "),function(m,k,l,g,n,p,E,u,F,h,
G,v,w,x,y,q,z,A,B,t,r,C,D,H){m=m(null,{declaredClass:"esri.dijit.Scalebar",map:null,mapUnit:null,scalebarUnit:null,unitsDictionary:[],domNode:null,screenPt1:null,screenPt2:null,localStrings:H.widgets.scalebar,constructor:function(a,b){this.metricScalebar=p.create("div",{innerHTML:"\x3cdiv class\x3d'esriScaleLabelDiv'\x3e\x3cdiv class\x3d'esriScalebarLabel esriScalebarLineLabel esriScalebarSecondNumber'\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d'esriScalebarLine esriScalebarMetricLine'\x3e\x3c/div\x3e"});
this.englishScalebar=p.create("div",{innerHTML:"\x3cdiv class\x3d'esriScalebarLine esriScalebarEnglishLine'\x3e\x3c/div\x3e\x3cdiv class\x3d'esriScaleLabelDiv'\x3e\x3cdiv class\x3d'esriScalebarLabel esriScalebarLineLabel esriScalebarSecondNumber'\x3e\x3c/div\x3e\x3c/div\x3e"});this.domNode=p.create("div");a=a||{};if(a.map){if(a.scalebarUnit){if("english"!==a.scalebarUnit&&"metric"!==a.scalebarUnit&&"dual"!==a.scalebarUnit){console.error("scalebar unit only accepts english or metric or dual");return}this.scalebarUnit=
a.scalebarUnit}else this.scalebarUnit="english";if(a.scalebarStyle){if("ruler"!==a.scalebarStyle&&"line"!==a.scalebarStyle){console.error("scalebar style must be ruler or line");return}this.scalebarStyle=a.scalebarStyle}else this.scalebarStyle="ruler";this.background=a.background;switch(this.scalebarUnit){case "english":"ruler"===this.scalebarStyle&&(this.englishScalebar.innerHTML="\x3cdiv class\x3d'esriScalebarRuler'\x3e\x3cdiv class\x3d'esriScalebarRulerBlock upper_firstpiece'\x3e\x3c/div\x3e\x3cdiv class\x3d'esriScalebarRulerBlock upper_secondpiece'\x3e\x3c/div\x3e\x3cdiv class\x3d'esriScalebarRulerBlock lower_firstpiece'\x3e\x3c/div\x3e\x3cdiv class\x3d'esriScalebarRulerBlock lower_secondpiece'\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d'scaleLabelDiv'\x3e\x3cdiv class\x3d'esriScalebarLabel' style\x3d'left: -3%'\x3e0\x3c/div\x3e\x3cdiv class\x3d'esriScalebarLabel esriScalebarFirstNumber'\x3e\x3c/div\x3e\x3cdiv class\x3d'esriScalebarLabel esriScalebarSecondNumber'\x3e\x3c/div\x3e\x3c/div\x3e");
this.domNode.appendChild(this.englishScalebar);break;case "metric":"ruler"===this.scalebarStyle&&(this.metricScalebar.innerHTML="\x3cdiv class\x3d'esriScalebarRuler'\x3e\x3cdiv class\x3d'esriScalebarRulerBlock upper_firstpiece'\x3e\x3c/div\x3e\x3cdiv class\x3d'esriScalebarRulerBlock upper_secondpiece'\x3e\x3c/div\x3e\x3cdiv class\x3d'esriScalebarRulerBlock lower_firstpiece'\x3e\x3c/div\x3e\x3cdiv class\x3d'esriScalebarRulerBlock lower_secondpiece'\x3e\x3c/div\x3e\x3c/div\x3e\x3cdiv class\x3d'scaleLabelDiv'\x3e\x3cdiv class\x3d'esriScalebarLabel' style\x3d'left: -3%'\x3e0\x3c/div\x3e\x3cdiv class\x3d'esriScalebarLabel esriScalebarFirstNumber'\x3e\x3c/div\x3e\x3cdiv class\x3d'esriScalebarLabel esriScalebarSecondNumber'\x3e\x3c/div\x3e\x3c/div\x3e");
this.domNode.appendChild(this.metricScalebar);break;case "dual":this.domNode.appendChild(this.metricScalebar),this.domNode.appendChild(this.englishScalebar)}this.map=a.map;b?b.appendChild(this.domNode):(this.map.container.appendChild(this.domNode),a.attachTo?n.add(this.domNode,"scalebar_"+a.attachTo):n.add(this.domNode,"scalebar_bottom-left"));n.add(this.domNode,"esriScalebar");if(this.map.loaded)this._getDistance(this.map.extent),this._checkBingMaps();else var f=g.connect(this.map,"onLoad",this,
function(){g.disconnect(f);f=null;this._getDistance(this.map.extent);this._checkBingMaps()});this._mapOnPan=g.connect(this.map,"onPan",this,this._getDistance);this._mapOnExtentChange=g.connect(this.map,"onExtentChange",this,this._getDistance);l.forEach(this.map.layerIds,function(a,b){"esri.virtualearth.VETiledLayer"===this.map.getLayer(a).declaredClass&&g.connect(this.map.getLayer(a),"onVisibilityChange",k.hitch(this,function(a){this._checkBingMaps()}))},this);this._mapOnLayerAdd=g.connect(this.map,
"onLayerAdd",k.hitch(this,function(a){"esri.virtualearth.VETiledLayer"===a.declaredClass&&g.connect(a,"onVisibilityChange",k.hitch(this,function(a){this._checkBingMaps()}));this._checkBingMaps()}));this._mapOnLayerRemove=g.connect(this.map,"onLayerRemove",k.hitch(this,this._checkBingMaps))}else console.error("scalebar: unable to find the 'map' property in parameters")},hide:function(){this._hidden=!0;w.hide(this.domNode)},show:function(){this._hidden=!1;w.show(this.domNode)},destroy:function(){g.disconnect(this._mapOnPan);
g.disconnect(this._mapOnExtentChange);g.disconnect(this._mapOnLayerAdd);g.disconnect(this._mapOnLayerRemove);this.hide();this.map=null;p.destroy(this.domNode)},_checkBingMaps:function(){n.contains(this.domNode,"scalebar_bottom-left")&&(u.set(this.domNode,"left","25px"),l.forEach(this.map.layerIds,function(a,b){"esri.virtualearth.VETiledLayer"===this.map.getLayer(a).declaredClass&&this.map.getLayer(a).visible&&(a="95px",this.map._mapParams.nav&&(a="115px"),u.set(this.domNode,"left",a))},this))},_getDistance:function(a){var b=
E.position(this.domNode,!0).y-this.map.position.y,b=b>this.map.height?this.map.height:b,b=0>b?0:b,f=new A(0,b),b=new A(this.map.width,b),c,e;this.mapUnit="esriDecimalDegrees";var d=C.toMapPoint(a,this.map.width,this.map.height,f),g=C.toMapPoint(a,this.map.width,this.map.height,b),f=new z(a.xmin,(a.ymin+a.ymax)/2,this.map.spatialReference),b=new z(a.xmax,(a.ymin+a.ymax)/2,this.map.spatialReference);if(3857===this.map.spatialReference.wkid||102100===this.map.spatialReference.wkid||102113===this.map.spatialReference.wkid||
this.map.spatialReference.wkt&&-1!=this.map.spatialReference.wkt.indexOf("WGS_1984_Web_Mercator"))d=r.webMercatorToGeographic(d,!0),g=r.webMercatorToGeographic(g,!0),f=r.webMercatorToGeographic(f,!0),b=r.webMercatorToGeographic(b,!0);else if(v.isDefined(q[this.map.spatialReference.wkid])||this.map.spatialReference.wkt&&0===this.map.spatialReference.wkt.indexOf("PROJCS")){this.mapUnit="linearUnit";a=Math.abs(a.xmax-a.xmin);if(v.isDefined(q[this.map.spatialReference.wkid]))c=q.values[q[this.map.spatialReference.wkid]];
else{c=this.map.spatialReference.wkt;e=c.lastIndexOf(",")+1;var h=c.lastIndexOf("]]");c=parseFloat(c.substring(e,h))}a*=c;e=a/1609;c=a/1E3;a/=1E3}"esriDecimalDegrees"===this.mapUnit&&(c=t.isSupported(this.map.spatialReference)?this.map.spatialReference.wkid:4326,a=new B(new y({wkid:c})),a.addPath([d,g]),d=D._straightLineDensify(a,10),a=t.geodesicLengths([d],x.KILOMETERS)[0],d=new B(new y({wkid:c})),d.addPath([f,b]),f=D._straightLineDensify(d,10),t.geodesicLengths([f],x.KILOMETERS),e=a/1.609,c=a);
"english"===this.scalebarUnit?this._getScaleBarLength(e,"mi"):"metric"===this.scalebarUnit?this._getScaleBarLength(c,"km"):"dual"===this.scalebarUnit&&(this._getScaleBarLength(e,"mi"),this._getScaleBarLength(c,"km"))},_getScaleBarLength:function(a,b){a=50*a/this.map.width;var f=0,c=b;.1>a&&("mi"===b?(a*=5280,c="ft"):"km"===b&&(a*=1E3,c="m"));for(;1<=a;)a/=10,f++;var e,d;.5<a?(e=1,d=.5):.3<a?(e=.5,d=.3):.2<a?(e=.3,d=.2):.15<a?(e=.2,d=.15):.1<=a&&(e=.15,d=.1);b=e/a>=a/d?d:e;this._drawScaleBar(b/a*50,
Math.pow(10,f)*b,c)},_drawScaleBar:function(a,b,f){var c=2*Math.round(a),e,d;"mi"===f||"ft"===f?(this.englishScalebar.style.width=c+"px",a=h(".esriScalebarFirstNumber",this.englishScalebar),e=h(".esriScalebarSecondNumber",this.englishScalebar),d=h(".esriScalebarMetricLineBackground",this.englishScalebar)):(this.metricScalebar.style.width=c+"px",a=h(".esriScalebarFirstNumber",this.metricScalebar),e=h(".esriScalebarSecondNumber",this.metricScalebar),d=h(".esriScalebarMetricLineBackground",this.metricScalebar));
l.forEach(d,function(a,b){a.style.width=c-2+"px"},this);l.forEach(a,function(a,c){a.innerHTML=b},this);l.forEach(e,function(a,c){a.innerHTML="esriUnknown"!==this.mapUnit?2*b+this.localStrings[f]:2*b+"Unknown Unit"},this)}});F("extend-esri")&&k.setObject("dijit.Scalebar",m,G);return m});