// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/plots/_ClusteredBarsBase","dojo/_base/lang dojo/_base/array dojo/_base/declare dojo/has dojox/charting/plot2d/CartesianBase dojox/charting/plot2d/_PlotEvents dojox/charting/plot2d/common dojox/lang/utils dojox/lang/functional dojox/lang/functional/reversed ./labelsRendering/_BarsLabelRenderingFix ./animation/_ClusteredBarsAnimation ./_MinVisibleBar".split(" "),function(u,w,D,E,F,G,x,C,H,I,J,K,L){var M=I.lambda("item.purgeGroup()");return D("dojox.charting.plot2d.Bars",
[F,G,J,K,L],{_mainShapes:null,_animationInfos:null,defaultParams:{gap:0,animate:null,enableCache:!1},optionalParams:{minBarSize:1,maxBarSize:1,stroke:{},outline:{},shadow:{},fill:{},filter:{},styleFunc:null,font:"",fontColor:"",labelHorizontalAlign:null},constructor:function(a,b){this.opt=u.clone(u.mixin(this.opt,this.defaultParams));C.updateWithObject(this.opt,b);C.updateWithPattern(this.opt,b,this.optionalParams);this.animate=this.opt.animate;this.renderingOptions={"shape-rendering":"crispEdges"}},
getSeriesStats:function(){var a=x.collectSimpleStats(this.series,function(a){return null==a}),b;a.hmin-=.5;a.hmax+=.5;b=a.hmin;a.hmin=a.vmin;a.vmin=b;b=a.hmax;a.hmax=a.vmax;a.vmax=b;return a},render:function(a,b){if(!this.chart.isPreRenderMode){if(this.zoom&&!this.isDataDirty())return this.performZoom(a,b);this.dirty=this.isDirty();this.resetEvents();var e;this.dirty&&(w.forEach(this.series,M),this._eventSeries={},this.cleanGroup(),e=this.getGroup(),H.forEachRev(this.series,function(a){a.cleanGroup(e)}));
var d=this.chart.theme,h=this._hScaler.scaler.getTransformerFromModel(this._hScaler),f=this._vScaler.scaler.getTransformerFromModel(this._vScaler),g=h(Math.max(d.series.baseLineValue||0,this._hScaler.bounds.lower)),m=this.events(),p=this.getBarProperties();this._mainShapes=[];this._animationInfos=[];for(var A=this.extractValues(this._vScaler),A=this.rearrangeValues(A,h,g),r=this.series.length-1;0<=r;--r){var c=this.series[r];if(this.dirty||c.dirty){c.cleanGroup();this.opt.enableCache&&(c._rectFreePool=
(c._rectFreePool?c._rectFreePool:[]).concat(c._rectUsePool?c._rectUsePool:[]),c._rectUsePool=[]);var y=d.next("bar",[this.opt,c]);if(c.hidden)c.dyn.fill=y.series.fill,c.dyn.stroke=y.series.stroke;else{var u=Array(c.data.length);e=c.group;for(var v=w.some(c.data,function(a){return"number"===typeof a||a&&!a.hasOwnProperty("x")}),x=v?Math.min(c.data.length,Math.ceil(this._vScaler.bounds.to)):c.data.length,l=v?Math.max(0,Math.floor(this._vScaler.bounds.from-1)):0;l<x;++l){var k=c.data[l];if(null!=k){var q=
this.getValue(k,l,r,v);h(q.y);var B=A[r][l],n;this.opt.styleFunc||"number"!==typeof k?(n="number"!==typeof k?[k]:[],this.opt.styleFunc&&n.push(this.opt.styleFunc(k)),n=d.addMixin(y,"bar",n,!0)):n=d.post(y,"bar");if(1<=p.height){var t={x:b.l+g+Math.min(B,0),y:a.height-b.b-f(q.x+1.5)+p.gap+p.thickness*this._getYShift(r,d),width:Math.abs(B),height:p.height},t=this._drawBar(e,k,t,n,a,b,c,g),z=t.shape;z.value=k;this._mainShapes.push(z);t=t.rect;m&&(q={element:"bar",index:l,run:c,shape:z,cx:q.y,cy:q.x+
1.5,x:v?l:c.data[l].x,y:v?c.data[l]:c.data[l].y},this._connectEvents(q),u[l]=q);this.createLabel(e,k,t,n,a,b);this.animate&&(k={shape:z,hoffset:b.l+g,hsize:-B},this._animationInfos.push(k),this._animateBar(k))}}}this._eventSeries[c.name]=u;c.dirty=!1}}else d.skip(),this._reconnectEvents(c.name)}this._renderLabels(n,a,b,e);this.dirty=!1;E("dojo-bidi")&&this._checkOrientation(this.group,a,b);return this}},getMainShapes:function(){return this._mainShapes},_drawBar:function(a,b,e,d,h,f,g,m){},_getYShift:function(a,
b){return b.series.renderColumnBarsInOppositeDirections?a>=this.series.length/2?a-this.series.length/2:a:a},getValue:function(a,b,e,d){d?(e="number"===typeof a?a:a.y,a=b):(e=a.y,a=a.x-1);return{y:e,x:a}},extractValues:function(a){for(var b=[],e=this.series.length-1;0<=e;--e){var d=this.series[e];if(this.dirty||d.dirty){var h=w.some(d.data,function(a){return"number"==typeof a||a&&!a.hasOwnProperty("x")}),f=h?Math.max(0,Math.floor(a.bounds.from-1)):0,h=h?Math.min(d.data.length,Math.ceil(a.bounds.to)):
d.data.length,g=b[e]=[];g.min=f;for(g.max=h;f<h;++f){var m=d.data[f];g[f]=this.isNullValue(m)?0:"number"==typeof m?m:m.y}}}return b},rearrangeValues:function(a,b,e){for(var d=0,h=a.length;d<h;++d){var f=a[d];if(f)for(var g=f.min,m=f.max;g<m;++g){var p=f[g];f[g]=this.isNullValue(p)?0:b(p)-e}}return a},getBarProperties:function(){var a=x.calculateBarSize(this._vScaler.bounds.scale,this.opt,this._getClusterSize());return{gap:a.gap,height:a.size,thickness:a.size}},_getClusterSize:function(){var a=this.series.length;
w.forEach(this.series,function(b){b.hidden&&a--});return this.chart.theme.series.renderColumnBarsInOppositeDirections?Math.round(a/2):a}})});