// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/plots/Ring","dojo/_base/lang dojo/_base/declare dojox/charting/plot2d/Base dojox/charting/plot2d/_PlotEvents dojox/charting/plot2d/common dojox/gfx dojox/gfx/matrix dojox/lang/functional dojox/lang/utils dojo/has ./animation/_RingAnimation".split(" "),function(q,x,y,z,A,v,J,m,w,E,B){var K={createPath:function(c,b,g,h,l,f,p,d,m){var n=function(d){var k={cx:g.cx,cy:g.cy,r:b},m=c.createCircle(k).setStroke({color:p.series.ringBackgroundColor||
"#DDDDDD",width:f}),e=h+2*d*Math.PI,n=g.cx+b*Math.cos(h),q=g.cy+b*Math.sin(h),v=g.cx+b*Math.cos(e),r=g.cy+b*Math.sin(e);return{shape:c.createPath().moveTo(n,q).arcTo(b,b,0,.5<d,!0,v,r).setStroke({color:l,width:f}),bgShape:m,end:e,ac:k}};m.push({sliceIndex:d,func:n});return n}},n=x([y,z,B],{_animationInfos:null,defaultParams:{labels:!0,ticks:!1,fixed:!0,precision:1,labelOffset:20,labelStyle:"default",htmlLabels:!0,radGrad:"native",fanSize:5,startAngle:0,animate:null},optionalParams:{radius:0,omitLabels:!1,
stroke:{},outline:{},shadow:{},fill:{},filter:{},styleFunc:null,font:"",fontColor:"",labelWiring:{}},_lastRenderResults:null,constructor:function(c,b){this.opt=q.clone(this.defaultParams);w.updateWithObject(this.opt,b);w.updateWithPattern(this.opt,b,this.optionalParams);this.axes=[];this.run=null;this.dyn=[];this.runFilter=[]},clear:function(){this.inherited(arguments);this.dyn=[];this.run=null;return this},setAxis:function(c){return this},addSeries:function(c){this.run=c;return this},getSeriesStats:function(){return q.delegate(A.defaultStats)},
getRequiredColors:function(){return this.run?this.run.data.length:0},getRenderResults:function(){return this._lastRenderResults},render:function(c,b){function g(a){return v._base._getTextBox(a,{font:l.series.font}).w}if(!this.dirty)return this;this.resetEvents();this.dirty=!1;this._eventSeries={};this.cleanGroup();var h=this.group,l=this.chart.theme;if(!this.run||!this.run.data.length)return this;var f=(c.width-b.l-b.r)/2,p=(c.height-b.t-b.b)/2,d=Math.min(f,p),q="font"in this.opt?this.opt.font:l.series.font,
w=J._degToRad(90),k,x=this.events(),u=this.run.data.map(function(a,b){"number"!==typeof a&&a.hidden&&(this.runFilter.push(b),a.hidden=!1);return this.runFilter.some(function(a){return a===b})?"number"===typeof a?0:{y:0,text:a.text}:a},this);this.dyn=[];"radius"in this.opt&&(d=this.opt.radius);var e={cx:b.l+f,cy:b.t+p,r:d},f=m.map(u,"x ? Math.max(x.y, 0) : 0");if(m.every(f,"\x3c\x3d 0"))return h.createCircle(e).setStroke(l.series.stroke),this.dyn=f.map(function(){return{}}),this;f=m.map(f,"/this",
m.foldl(f,"+",0));if(this.opt.labels)if(k=f.map(function(a,b){if(0>a)return"";b=u[b];return"text"in b?b.text:this._getLabel(100*a)+"%"},this),k[0]&&-1!==k[0].indexOf(n.LABEL_SEPARATOR)){var C=0;k.forEach(function(a){a=a.split(n.LABEL_SEPARATOR)[0];a=g(a);C=Math.max(C,a)});var y=g("\x26nbsp;");k=k.map(function(a){a=a.split(n.LABEL_SEPARATOR);for(var b=Math.round((C-g(a[0]))/y),d="",e=0;e<b+4;e++)d+="\x26nbsp;";return"\x3cdiv\x3e\x3cspan\x3e"+a[0]+"\x3c/span\x3e"+d+"\x3cspan\x3e"+a[1]+"\x3c/span\x3e\x3c/div\x3e"})}else k=
k.map(function(a){return"\x3cdiv\x3e"+a+"\x3c/div\x3e"});var z=m.map(u,function(a,b){b=[this.opt,this.run];null!=a&&"number"!==typeof a&&b.push(a);this.opt.styleFunc&&b.push(this.opt.styleFunc(a));return l.next("slice",b,!0)},this),r=0;if(this.opt.labels){k.forEach(function(a){r=Math.max(r,g(a))});var t=e.cx+d+r+b.r-c.width;0<t&&(p=e.cx-d,p>t?e.cx-=t:(t=(t-p)/2,e.cx-=p+t,d-=t))}e.cx-=e.cx-d-(c.width-(2*d+r))/2;var F=Array(f.length),D=Math.min(d/10,.5*d/f.length),G=d,d=d-D/2,H=[],I=[];this._animationInfos=
[];f.some(function(a,b){a=Math.max(a,.001);var c=u[b],f=z[b],g;g=f.series.fill;a=K.createPath(h,d,e,w,g,D,f,b,this._animationInfos)(a);shape=a.shape;I.push(a.ac);this.dyn.push({fill:g,stroke:f.series.stroke});x&&(c={element:"slice",index:b,run:this.run,shape:shape,x:b,y:"number"===typeof c?c:c.y,cx:e.cx,cy:e.cy,cr:d},this._connectEvents(c),F[b]=c);H.push({x:e.cx,y:e.cy+d});d-=D+3;return!1},this);if(this.opt.labels){E("dojo-bidi")&&this.chart.isRightToLeft();var A=v._base._getTextBox("a",{font:q}).h;
H.forEach(function(a,b){h.createPath().moveTo(a.x-5,a.y).lineTo(a.x+G-5,a.y).setStroke(l.series.labelWiring);this.renderLabel(h,a.x+G,a.y+A/3,k[b],l,!0,"left")},this);l.series.show100PercentLabel&&this._show100PercentLabel(l,d,h,e)}var B=0;this._eventSeries[this.run.name]=m.map(u,function(a){return 0>=a?null:F[B++]});E("dojo-bidi")&&this._checkOrientation(this.group,c,b);this._lastRenderResults={labels:this.opt.labels,slicePies:I,maxLabelWidth:r};this.opt.animate&&this._renderAnimation(u,l,d,h,e,
f);return this},_show100PercentLabel:function(c,b,g,h){c={series:q.mixin({},c.series)};c.series.font=c.series.font.replace(/\s\w*px/," "+Math.min(50,.6*b)+"px");b=v._base._getTextBox("100%",{font:c.series.font});this.renderLabel(g,h.cx-b.w/2,h.cy+b.h/3,"100%",c,!0,"left").style.opacity="0.5"}});n.LABEL_SEPARATOR="\x26nbsp;";return n});