// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/conversion/portalToEditorUtils/parsers/ChartConverterPtoE","dojo/_base/lang esri/dijit/geoenrichment/utils/ColorUtil esri/dijit/geoenrichment/utils/ImageUtil esri/dijit/geoenrichment/utils/JsonXmlConverter ../../../charts/utils/ChartJsonUtil ../../ConversionUtil esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/ChartTypes esri/dijit/geoenrichment/ReportPlayer/core/charts/legends/ChartLegendTypes ./_FieldInfoBuilder dojo/i18n!esri/nls/jsapi".split(" "),
function(u,z,H,k,A,c,B,F,x,q){function y(a,c){return void 0===a?c:Number(a)||c}function e(a,c){a=Number(a);return isNaN(a)?c:a}function I(a,c,e){return k.queryJson(a,"series").filter(function(a){return a.tags&&a.tags[0]&&"point"===a.tags[0].name}).map(function(d){if(!d.tags)return null;d.attributes=d.attributes||{};return{label:d.attributes.Text||"",color:C(d.attributes.color),thickness:d.attributes.thickness,points:d.tags.map(function(d,h){d.attributes=d.attributes||{};var e=a.attributes.type===
B.GAUGE&&1===h;if((h=(h=(h=d.tags&&d.tags[0])&&h.attributes&&h.attributes.f)&&x.getCalculatorOrScriptFieldInfo(h,c))||e){h&&h.isMissing&&(e=d.attributes.Text,!e&&c.variableProvider.isPlayerOnly&&(e=(e=c.variableProvider.toCalculator(h.templateName))&&e.variable.alias),h.alias=e?e+" ("+q.missingVariable+")":q.missingVariable);var e=(e=d.attributes.CaptionField)&&x.getCalculatorOrScriptFieldInfo(e,c),f=k.queryJson(d,"pointIcon")[0],f=f&&c.parsers.getParser("field").parseField(f.tags[0],f,null,c);return A.createChartPoint(h,
d.attributes.Text||"",C(d.attributes.color),f,e)}}).filter(function(a){return!!a})}}).filter(function(a){return a&&a.points&&!!a.points.length})}function G(a,c){var f={gridLines:a.gridlines,gridLinesCentered:a.gridlinesCentered,gridLinesOpacity:y(a.gridlinesOpacity,1),gridLinesColor:a.gridlinesColor,gridLinesThickness:e(a.gridlinesThickness),gridLinesStyle:a.gridlinesStyle,gridStripes:a.gridStripes,gridStripesColor:a.gridStripesColor,gridStripesColorAlt:a.gridStripesColorAlt};c&&u.mixin(f,{baseLine:a.baseLine,
baseLineColor:a.baseLineColor,baseLineOpacity:y(a.baseLineOpacity,1),baseLineThickness:e(a.baseLineThickness),baseLineStyle:a.baseLineStyle,baseLineValue:a.baseLineValue});return f}function J(a){return(a=k.queryJson(a,"BackImage")[0])&&a.tags&&a.tags[0].text?H.base64DataToDataURL(a.tags[0].text):null}function K(a){if("string"!==typeof a)return 0;a=a.replace("%","");return"0"===a?0:a.replace("0.","").length}function C(a){a&&"string"===typeof a&&(a=6===a.length&&-1===a.indexOf("#")?"#"+a:z.toCSSColor(a));
return a}q=q.geoenrichment.dijit.ReportPlayer.ReportPlayer;return{portalToEditor:function(a,q,f){var d=k.queryJson(a,"comparisonInfo")[0],r;if(d){var h=d.attributes.name,v=f.templateJson.metadata.comparisonCalculatorsHash[h];v&&(r={calculatorName:h,chartType:d.attributes.chartType,color:d.attributes.color,lineThickness:e(d.attributes.lineThickness),lineStyle:d.attributes.lineStyle,lineMarker:d.attributes.lineMarker,levels:v.levels})}var w=I(a,f,r);if(!w.length)return null;var b=a.attributes,t=k.queryJson(a,
"chartTitle")[0],d=k.queryJson(a,"legend")[0],m=k.queryJson(a,"xAxis")[0],n=k.queryJson(a,"yAxis")[0],h=k.queryJson(a,"chartIcon"),h=k.queryJson(a,"chartIcon"),v=k.queryJson(a,"floatingIcon"),D=k.queryJson(a,"floatingText"),E=k.queryJson(a,"trigger");t.attributes=t.attributes||{};d.attributes=d.attributes||{};var p=m&&m.attributes||{},l=n&&n.attributes||{},x=p,y=l;f.isGraphicReport&&1.3>f.revisionVersion&&(x=l,y=p);w.forEach(function(a){a.thickness=e(a.thickness)});var g;B.isColumnBarLike(b.type)&&
(g=1<w[0].thickness?"Large":1>w[0].thickness?"Small":"Medium");var m=m&&m.tags&&m.tags[0].attributes&&m.tags[0].attributes,n=n&&n.tags&&n.tags[0].attributes&&n.tags[0].attributes,z=J(a);g={isChart:!0,type:b._type||b.type,isMultiFeatureChart:!!b.isMultiFeatureChart,seriesItems:w,visualProperties:{width:c.ptToPx(b.width),height:c.ptToPx(b.height),backgroundColor:C(b.backColor),panelBackgroundColor:b.panelBackgroundColor,barBorders:b.barBorders,dataLabels:b.dataLabels,view3D:!!b.view3D,origin:e(b.origin),
lineThickness:B.isLineLike(b.type)&&w[0].thickness||void 0,columnThickness:g,backgroundImageData:z,dataLabelsDecimals:K(b.CustomPercentFormat||b.CustomValueFormat),title:{text:t.attributes.text,align:t.attributes.align&&t.attributes.align.toLowerCase(),style:c.ptToPxObj(c.parseStyleString(t.attributes.style)),verticalShift:c.ptToPx(t.attributes.verticalShift||0)},xAxis:u.mixin({show:"None"!==p.placement,showTicks:p.ticks,style:c.ptToPxObj(c.parseStyleString(p.style)),title:m&&m.text,titleStyle:m&&
c.ptToPxObj(c.parseStyleString(m.style)),placement:"OtherSide"===p.placement?"OtherSide":void 0,labelsAngle:e(p.labelsAngle),showLine:p.line,lineColor:p.lineColor,ticksInside:p.ticksInside},G(x,!1)),yAxis:u.mixin({show:"None"!==l.placement,showTicks:l.ticks,style:c.ptToPxObj(c.parseStyleString(l.style)),title:n&&n.text,titleStyle:n&&c.ptToPxObj(c.parseStyleString(n.style)),placement:"OtherSide"===l.placement?"OtherSide":void 0,labelsAngle:e(l.labelsAngle),showLine:l.line,lineColor:l.lineColor,ticksInside:l.ticksInside,
showPercentIndicator:l.showPercentIndicator,showValuesAsWeightsInSeries:l.showValuesAsWeightsInSeries},G(y,!0)),legend:{type:d.attributes.type||F.SERIES},dataLabelsStyle:c.ptToPxObj(c.parseStyleString(b.dataLabelsStyle)),isStacked:b.isStacked,showColumnBarBackground:b.showColumnBarBackground,columnBarBackgroundColor:b.columnBarBackgroundColor,renderColumnBarsInOppositeDirections:b.renderColumnBarsInOppositeDirections,columnBarGap:b.columnBarGap?c.ptToPx(b.columnBarGap):void 0,fillLineArea:b.fillLineArea,
lineAreaOpacity:b.lineAreaOpacity,donutHolePercent:e(b.donutHolePercent),donutGap:e(b.donutGap),donutArcPercent:e(b.donutArcPercent),gaugeHolePercent:e(b.gaugeHolePercent),gaugeRangeMin:e(b.gaugeRangeMin),gaugeRangeMax:e(b.gaugeRangeMax),gaugeGap:e(b.gaugeGap),gaugeStartAngle:e(b.gaugeStartAngle),gaugeArcPercent:e(b.gaugeArcPercent),gaugeLabelStyle:c.ptToPxObj(c.parseStyleString(b.gaugeLabelStyle))||void 0,gaugeLabelPlacement:b.gaugeLabelPlacement||void 0,gaugeShowArrow:b.gaugeShowArrow||void 0,gaugeArrowLineColor:b.gaugeArrowLineColor||
void 0,gaugeArrowFillColor:b.gaugeArrowFillColor||void 0,gaugeConditionalStylingIgnoreOthers:b.gaugeConditionalStylingIgnoreOthers||void 0,gaugeConditionalStylingLabel:b.gaugeConditionalStylingLabel||void 0,gaugeShowFromToLabels:b.gaugeShowFromToLabels||void 0,gaugeFromLabelStyle:c.ptToPxObj(c.parseStyleString(b.gaugeFromLabelStyle))||void 0,gaugeToLabelStyle:c.ptToPxObj(c.parseStyleString(b.gaugeToLabelStyle))||void 0,ringBackgroundColor:b.ringBackgroundColor,showWholePictures:b.showWholePictures,
dataLabelsInside:b.dataLabelsInside,dataLabelsStackedInColumns:b.dataLabelsStackedInColumns,dataLabelsHorizontalAlign:b.dataLabelsHorizontalAlign,showAxisIcons:b.showAxisIcons,showChartIcons:b.showChartIcons,sorting:b.sorting}};g.visualProperties.legend.type===F.MIN_MAX?u.mixin(g.visualProperties.legend,{minMax:{placement:d.attributes.placement,placementOffset:e(d.attributes.placementOffset),titleStyle:c.ptToPxObj(c.parseStyleString(d.attributes.titleStyle)),minVariableLabelStyle:c.ptToPxObj(c.parseStyleString(d.attributes.minVariableLabelStyle)),
maxVariableLabelStyle:c.ptToPxObj(c.parseStyleString(d.attributes.maxVariableLabelStyle))}}):u.mixin(g.visualProperties.legend,{series:{placement:d.attributes.placement,placementOffset:e(d.attributes.placementOffset),hasBorder:d.attributes.hasBorder,labelParts:d.attributes.labelParts,style:c.ptToPxObj(c.parseStyleString(d.attributes.style))}});1.2>f.revisionVersion&&(void 0!==g.visualProperties.donutGap&&(g.visualProperties.donutGap/=2*Math.PI),void 0!==g.visualProperties.gaugeGap&&(g.visualProperties.gaugeGap/=
2*Math.PI));h&&h.length&&(g.visualProperties.chartIcons=h.map(function(a){return a.tags&&a.tags[0]?f.parsers.getParser("field").parseField(a.tags[0],a,null,f):null}));v&&v.length&&(g.visualProperties.floatingIcons=v.map(function(a){return f.parsers.getParser("section").parseTable(a.tags[0],f)}));D&&D.length&&(g.visualProperties.floatingTexts=D.map(function(a){return f.parsers.getParser("section").parseTable(a.tags[0],f)}));E&&E.length&&(g.visualProperties.conditionalStyling=f.parsers.getParser("field").parseFieldTrigger(E[0]));
g.comparisonInfo=r;r={};q.attributes&&q.attributes.style&&u.mixin(r,c.parseStyleString(q.attributes.style));c.ptToPxObj(r);A.provideDefaultValueForMissing(g,{font:r});A.cleanUpJson(g);f.postProcessChartJson(a,g);return g}}});