// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/conversion/portalToEditorUtils/parsers/TableParser","dojo/_base/lang esri/dijit/geoenrichment/utils/JsonXmlConverter esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/templateJsonUtils/fieldInfo/RichTextJsonUtil ../../../supportClasses/DocumentOptions ../../ConversionUtil ../../../sections/SectionTypes ./AlignParser ./_HiddenCellsCollector esri/dijit/geoenrichment/utils/ColorUtil".split(" "),function(E,x,F,G,f,l,H,y,I){function J(a,c,b,d,
l){if(a.spannedWidths||a.spannedHeights){var p=a.spannedWidths?a.spannedWidths.split(";").map(function(a){return f.ptToPx(a)}):[f.ptToPx(a.width)];a=a.spannedHeights?a.spannedHeights.split(";").map(function(a){return f.ptToPx(a)}):[f.ptToPx(a.height)];for(var m=0;m<p.length;m++)for(var r=0;r<a.length;r++){var g=b[l+m],n=c[d+r],g=n.style.fields[g.field]=n.style.fields[g.field]||{};g.width=p[m];g.height=a[r]}}}var u={parseTableCellAttributes:function(a,c,b){b=b.tableDefaultStyles;c=c||{};a.overrideStyle&&
(c.overrideStyle=a.overrideStyle);a.pad&&(c.horizontalPadding=f.ptToPx(a.pad));a.vpad&&(c.verticalPadding=f.ptToPx(a.vpad));a.angle&&(c.angle=Number(a.angle)||0);H.parseAlign(a,c);a.width&&(c.width=f.ptToPx(a.width));a.height&&(c.height=f.ptToPx(a.height));E.mixin(c,f.ptToPxObj(f.parseStyleString(a.style)));if(c.overrideStyle&&b){b=b.getStyle(c.overrideStyle);for(var d in b)delete c[d]}u._parseBorderProperties(a,c);return c},_SIDES:["Top","Right","Bottom","Left"],_parseBorderProperties:function(a,
c){u._SIDES.forEach(function(b){if(a["border"+b+"Width"]){a["border"+b+"Color"]&&(c["border"+b+"Color"]=a["border"+b+"Color"]);a["border"+b+"Width"]&&(c["border"+b+"Width"]=f.ptToPx(a["border"+b+"Width"]));a["border"+b+"Style"]&&(c["border"+b+"Style"]=a["border"+b+"Style"]);var d=a["border"+b+"Opacity"];c["border"+b+"Opacity"]=d?Number(d):1}})}},p={getElement:function(a,c,b){var d=f.pxToPt(G.getPageBox(c.templateJson.documentOptions).contentW);if((!b||!b.doNotFixWidthsForPage)&&a.attributes.widths&&
Number(a.attributes.width)>d){b=f.splitTrim(a.attributes.widths,";",!0);var B=Number(a.attributes.width)-d,C=Number(b[b.length-1]);C>B&&(b[b.length-1]=C-B,a.attributes.widths=b.join(";"),a.attributes.width=d)}var m=0,r=a.attributes.widths?f.splitTrim(a.attributes.widths,";",!0).map(function(a){return{field:"field"+m++,style:{width:f.ptToPx(a)}}}):[],g=Number(a.attributes.fixedColumns)||0,n=Number(a.attributes.dynamicColumns)||0,e=[],t,v,z,w;(function(){a.tags&&(1.1<=c.revisionVersion?a.tags.forEach(function(a){if("tr"===
a.name)e.push(a);else switch(a.attributes.type){case l.TABLE_BACKGROUND:t=a;break;case l.TABLE_FOREGROUND:v=a;break;case l.TABLE_BACKGROUND_FLOATING_PANELS:z=a;break;case l.TABLE_FOREGROUND_FLOATING_PANELS:case l.TABLE_FLOATING_PANELS:w=a}}):a.tags.forEach(function(a){"tr"===a.name?e.push(a):"background"===a.name?t=a:"foreground"===a.name?v=a:"floatingElements"===a.name&&(w=a)}))})();if(e){var A=e.map(function(){return{style:{fields:{}},fieldInfos:{}}}),D=y.collectHiddenCells(e,c);e.forEach(function(a,
b){var k=A[b];a.attributes&&a.attributes.height&&(k.style.height=f.ptToPx(a.attributes.height));if(a.tags&&a.tags.length){var d=0;if(n){var l=[],p=[],e=0;a.tags.forEach(function(a){for(;y.isHidden(D,e,b);)e++;e<g?l.push(a):p.push(a);e++});var m=Math.round((r.length-g)/n);a.tags=l;for(var t=0;t<m;t++)a.tags=a.tags.concat(p)}a.tags.forEach(function(a){function l(a){a=a.tags&&1===a.tags.length&&a.tags[0];if(!a||!a.tags)return null;"b"===a.name?g.fontWeight="bold":"i"===a.name?g.fontStyle="italic":"u"===
a.name&&(g.textDecoration="underline");return"b"===a.name||"i"===a.name||"u"===a.name?l(a)||{tag:a.tags[0],parentTag:a}:null}function p(a){x.isRichText(a)?k.fieldInfos[e]=F.createFieldInfoFromRichText(a):k[e]=x.unrichHTML(a)}for(;y.isHidden(D,d,b);)d++;if(r[d]){var e=r[d].field,h=a.attributes||{},g=k.style.fields[e]={};u.parseTableCellAttributes(h,g,c);h.width&&J(h,A,r,b,d);var m=Number(h.colspan),h=Number(h.rowspan);m&&(k.columnSpans=k.columnSpans||{},k.columnSpans[e]=m);h&&(k.rowSpans=k.rowSpans||
{},k.rowSpans[e]=h);var n=function(a){var c,b,d;if(a.tags&&a.tags.length)if(d=a.tags.filter(function(a){return"br"!==a.name}),(b=d[0])&&"trigger"===b.name&&d[1]&&"d"===d[1].name)c=b,b=d[1];else{var e=l(a);b=e&&e.tag||d[0];a=e&&e.parentTag||a}return{firstTag:b,triggerTag:c,parentTag:a,hasMultipleTags:d&&1<d.length}}(a);a=n.firstTag;var m=n.parentTag,h=n.triggerTag,n=n.hasMultipleTags,q;if(n&&!h){var t=c.parsers.getParser("field").parseRichTextTag(m,c);t&&(k.fieldInfos[e]=t,q=!0)}if(a&&!q)if(c.isGraphicReport&&
"section"===a.name&&!a.attributes.style&&g.backgroundColor&&!I.isTransparent(g.backgroundColor)&&(a.attributes.style=f.composeStyleString({backgroundColor:g.backgroundColor}),delete g.backgroundColor),h=c.parsers.getParser("field").parseField(a,m,h,c),!1===h)q=!0;else if("number"===typeof h)k[e]=h+"",q=!0;else if(h)k.fieldInfos[e]=h,q=!0;else if("chart"===a.name)q=!0;else if("img"===a.name)q=!0;else if("text"===a.name)k[e]=a.attributes.name,q=!0;else if("a"===a.name&&a.tags&&a.tags[0].text){if(h=
a.attributes.href)k.urls=k.urls||{},k.urls[e]=h,k[e]=a.tags[0].text,q=!0}else a.text&&!n&&(p(a.text),q=!0);q||p(x.getInnerHTML(m));d++}})}})}d={id:"table",backgroundSectionJson:t&&p._parseTableBackgroundForeground(t,c,!0),foregroundSectionJson:v&&p._parseTableBackgroundForeground(v,c,!1),backgroundFloatingTablesSectionJson:z&&p._parseFloatingPanels(z,c,!0),foregroundFloatingTablesSectionJson:w&&p._parseFloatingPanels(w,c,!1),data:{columns:r,data:A||[]},style:{width:f.ptToPx(a.attributes.width),left:f.ptToPx(a.attributes.left),
spaceBefore:f.ptToPx(a.attributes.spaceBefore),spaceAfter:f.ptToPx(a.attributes.spaceAfter),alternatingStyle:a.attributes.alternatingStyle,opacity:a.attributes.opacity?Number(a.attributes.opacity):void 0,fixedCellsOpacity:a.attributes.fixedCellsOpacity?Number(a.attributes.fixedCellsOpacity):void 0},attributes:{}};g&&(d.attributes.fixedColumns=g);n&&(d.attributes.dynamicColumns=n);a.attributes.fixedRows&&(d.attributes.fixedRows=Number(a.attributes.fixedRows)||0);a.attributes.dynamicRows&&(d.attributes.dynamicRows=
Number(a.attributes.dynamicRows)||0);d.attributes.inSectionRole=a.attributes.inSectionRole;return d},_parseTableBackgroundForeground:function(a,c,b){a.attributes=a.attributes||{};a.attributes.type=b?l.TABLE_BACKGROUND:l.TABLE_FOREGROUND;return c.parsers.getParser("section").parseSection(a,c,{doNotFixWidthsForPage:!0})},_parseFloatingPanels:function(a,c,b){a.attributes=a.attributes||{};a.attributes.type=b?l.TABLE_BACKGROUND_FLOATING_PANELS:l.TABLE_FOREGROUND_FLOATING_PANELS;return c.parsers.getParser("section").parseSection(a,
c,{doNotFixWidthsForPage:!0})}};p.parseTableCellAttributes=u.parseTableCellAttributes;return p});