// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
var __extends=this&&this.__extends||function(){var p=function(k,g){p=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(g,n){g.__proto__=n}||function(g,n){for(var k in n)n.hasOwnProperty(k)&&(g[k]=n[k])};return p(k,g)};return function(k,g){function q(){this.constructor=k}p(k,g);k.prototype=null===g?Object.create(g):(q.prototype=g.prototype,new q)}}();
define("esri/arcade/featureset/sources/FeatureLayerMemoryMap","require exports dojo/Deferred dojo/promise/all ../../../graphic ../support/FeatureSet ../support/IdSet ../support/shared ../../../geometry/geometryEngineAsync".split(" "),function(p,k,g,q,n,t,r,l,m){return function(k){function d(a){var b=k.call(this,a)||this;b.declaredClass="esri.layers.featureset.sources.FeatureLayerMemory";b._removeGeometry=!1;b._overrideFields=null;b.allf=null;a.spatialReference&&(b.spatialReference=a.spatialReference);
b._transparent=!0;b._maxProcessing=1E3;b._layer=a.layer;b._wset=null;if(!1===b._layer.loaded)throw Error("Can only create Feature FeatureSets from Loaded FeatureLayers. Use FeatureLayer or FeatureCollection classes");void 0!==a.outFields&&(b._overrideFields=a.outFields);void 0!==a.includeGeometry&&(b._removeGeometry=!1===a.includeGeometry);return b}__extends(d,k);d.prototype._maxQueryRate=function(){return l.defaultMaxRecords};d.prototype.end=function(){return this._layer};d.prototype.optimisePagingFeatureQueries=
function(a){};d.prototype.load=function(){if(null===this._loadPromise){var a=new g;this._loadPromise=a;this._initialiseFeatureSet();a.resolve(this)}return this._loadPromise.promise};d.prototype._initialiseFeatureSet=function(){if(!this._layer.getMap())throw Error("Can only use featuresets with layers attached to map");null==this.spatialReference&&(this.spatialReference=this._layer.getMap().spatialReference);this.geometryType=this._layer.geometryType;this.fields=this._layer.fields.slice(0);var a=this._layer.getOutFields();
if(1!==a.length||"*"!==a[0]){for(var b=[],c=0,f=this.fields;c<f.length;c++){var e=f[c];if("esriFieldTypeOID"===e.type)b.push(e);else for(var h=0,d=a;h<d.length;h++){var g=d[h];if(g.toLowerCase()===e.name.toLowerCase()){b.push(e);break}}}this.fields=b}if(null!==this._overrideFields)if(1===this._overrideFields.length&&"*"===this._overrideFields[0])this._overrideFields=null;else{b=[];a=[];c=0;for(f=this.fields;c<f.length;c++)if(e=f[c],"esriFieldTypeOID"===e.type)b.push(e),a.push(e.name);else for(h=0,
d=this._overrideFields;h<d.length;h++)if(g=d[h],g.toLowerCase()===e.name.toLowerCase()){b.push(e);a.push(e.name);break}this.fields=b;this._overrideFields=a}this.objectIdField=this._layer.objectIdField;this._databaseType=l.FeatureServiceDatabaseType.Standardised;this.typeIdField=this._layer.typeIdField;this.types=this._layer.types};d.prototype._isInFeatureSet=function(a){return l.IdState.InFeatureSet};d.prototype._transformSetWithIdChanges=function(a){};d.prototype._candidateIdTransform=function(a){return a};
d.prototype._getSet=function(a){var b=this,c=new g;null===this._wset?this._ensureLoaded().then(l.callback(function(){b._getFilteredSet("",null,null,null,a).then(function(a){b._wset=a;c.resolve(a)},l.errback(c))},c),l.errback(c)):c.resolve(this._wset);return c.promise};d.prototype._getFilteredSet=function(a,b,c,d,e){var h=this,f=new g;try{this._ensureLoaded().then(l.callback(function(){if(null===h._wset){var d=[];h._allFeatures().forEach(function(a){void 0===a.geometry&&(a.geometry=null);var b=a.attributes[h._layer.objectIdField];
d.push(b);h._featureCache[b]=a});h._wset=new r([],d,!1,null)}var g=h._wset._known.slice(0);h._checkCancelled(e);h.fetchAndRefineFeaturesByWhere(g,c,e).then(l.callback(function(c){h._checkCancelled(e);null!==b?h.fetchAndRefineFeaturesSpatially(c,b,a,e).then(l.callback(function(a){f.resolve(new r([],a,!1,null))},f),l.errback(f)):f.resolve(new r([],c,!1,null))},f),l.errback(f))},f),l.errback(f))}catch(u){f.reject(u)}return f.promise};d.prototype.executeSpatialRelationTest=function(a,b,c,f){if(null===
a.geometry)return a=new g,a.resolve(!1),a.promise;switch(b){case "esriSpatialRelEnvelopeIntersects":return b=l.shapeExtent(c),a=l.shapeExtent(a.geometry),m.intersects(b,a);case "esriSpatialRelIntersects":return m.intersects(c,a.geometry);case "esriSpatialRelContains":return m.contains(c,a.geometry);case "esriSpatialRelOverlaps":return m.overlaps(c,a.geometry);case "esriSpatialRelWithin":return m.within(c,a.geometry);case "esriSpatialRelTouches":return m.touches(c,a.geometry);case "esriSpatialRelCrosses":return m.crosses(c,
a.geometry);case "esriSpatialRelRelation":return m.relate(c,a.geometry,f)}};d.prototype.executeWhereTest=function(a,b){return b.testFeature(a)};d.prototype.fetchAndRefineFeaturesSpatially=function(a,b,c,f){var e=new g,d=[];f=[];var k="";0<=c.indexOf("esriSpatialRelRelation")&&(k=c.split(":")[1],c="esriSpatialRelRelation");for(var m=0;m<a.length;m++){var n=this._featureFromCache(a[m]);f.push(this.executeSpatialRelationTest(n,c,b,k))}if(0===f.length)return e.resolve(d),e.promise;q(f).then(l.callback(function(b){for(var c=
0;c<a.length;c++)!0===b[c]&&d.push(a[c]);e.resolve(d)},e),l.errback(e));return e.promise};d.prototype.fetchAndRefineFeaturesByWhere=function(a,b,c){c=new g;var d=[];if(null===b)c.resolve(a);else{for(var e=0;e<a.length;e++){var h=this._featureFromCache(a[e]);this.executeWhereTest(h,b)&&d.push(a[e])}c.resolve(d)}return c.promise};d.prototype._getFeatures=function(a,b,c,d){d=new g;var e=[];-1!==b&&void 0===this._featureCache[b]&&e.push(b);for(var f=a._lastFetchedIndex;f<a._known.length&&!(a._lastFetchedIndex+=
1,void 0===this._featureCache[a._known[f]]&&(a._known[f]!==b&&e.push(a._known[f]),e.length>c));f++);0===e.length?d.resolve("success"):d.reject(Error("Unaccounted for Features. Not in Feature Collection"));return d.promise};d.prototype._refineSetBlock=function(a,b,c){b=new g;b.resolve(a);return b.promise};d.prototype._stat=function(a,b,c,d,e,h,k){a=new g;a.resolve({calculated:!1});return a.promise};d.prototype._canDoAggregates=function(a,b,c,d,e){a=new g;a.resolve(!1);return a.promise};d._cloneAttr=
function(a){var b={},c;for(c in a)b[c]=a[c];return b};d.prototype.cloneAttr=function(a){for(var b={},c=0,d=this.fields;c<d.length;c++){var e=d[c];b[e.name]=a[e.name]}return b};d.prototype._allFeatures=function(){var a=this;null==this.allf&&(this.allf=[],this._layer.graphics.forEach(function(b){a.allf.push(new n(!0===a._removeGeometry?null:b.geometry,null,a.cloneAttr(b.attributes)))}));return this.allf};d.prototype.canBeBigDataFeatureSet=function(){return!1};d.prototype.shouldBeResolvedAsBigData=function(){return!1};
return d}(t)});