// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
var __extends=this&&this.__extends||function(){var z=function(t,n){z=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(n,x){n.__proto__=x}||function(n,x){for(var t in x)x.hasOwnProperty(t)&&(n[t]=x[t])};return z(t,n)};return function(t,n){function A(){this.constructor=t}z(t,n);t.prototype=null===n?Object.create(n):(A.prototype=n.prototype,new A)}}();
define("esri/arcade/featureset/sources/FeatureLayerDynamicMap","require exports dojo/Deferred ../../../graphic ../../../IdentityManager ../support/FeatureSet ../support/IdSet ../support/shared ../support/stats ../support/sha ../../../layers/FeatureLayer ../../../tasks/query ../../../tasks/QueryTask ../../../tasks/StatisticDefinition".split(" "),function(z,t,n,A,x,E,y,k,F,G,H,w,B,C){return function(t){function d(a){var b=t.call(this,a)||this;b.declaredClass="esri.layers.featureset.sources.FeatureLayerDynamic";
b._removeGeometry=!1;b._overrideFields=null;b.formulaCredential=null;b._pageJustIds=!1;b._requestStandardised=!1;a.spatialReference&&(b.spatialReference=a.spatialReference);b._transparent=!0;b._maxProcessing=1E3;b._layer=a.layer;b._wset=null;if(!1===b._layer.loaded)throw Error("Can only create FeatureSets from Loaded FeatureLayers. Use FeatureLayer or FeatureCollection classes");void 0!==a.outFields&&(b._overrideFields=a.outFields);void 0!==a.includeGeometry&&(b._removeGeometry=!1===a.includeGeometry);
return b}__extends(d,t);d.prototype._maxQueryRate=function(){return k.defaultMaxRecords};d.prototype.convertQueryToLruCacheKey=function(a){a=k.stableStringify(a.toJson());return(new G(a,"TEXT")).getHash("SHA-1","B64")};d.prototype.end=function(){return this._layer};d.prototype.load=function(){if(null===this._loadPromise){var a=new n;this._loadPromise=a;this._initialiseFeatureSet();a.resolve(this)}return this._loadPromise.promise};d.prototype.optimisePagingFeatureQueries=function(a){this._pageJustIds=
a};d.prototype._initialiseFeatureSet=function(){if(!this._layer.getMap())throw Error("Can only use featuresets with layers attached to map");null==this.spatialReference&&(this.spatialReference=this._layer.getMap().spatialReference);this.geometryType=this._layer.geometryType;this.fields=this._layer.fields.slice(0);var a=this._layer.getOutFields();if(1!==a.length||"*"!==a[0]){for(var b=[],f=0,l=this.fields;f<l.length;f++){var h=l[f];if("esriFieldTypeOID"===h.type)b.push(h);else for(var c=0,g=a;c<g.length;c++){var e=
g[c];if(e.toLowerCase()===h.name.toLowerCase()){b.push(h);break}}}this.fields=b}if(null!==this._overrideFields)if(1===this._overrideFields.length&&"*"===this._overrideFields[0])this._overrideFields=null;else{b=[];a=[];f=0;for(l=this.fields;f<l.length;f++)if(h=l[f],"esriFieldTypeOID"===h.type)b.push(h),a.push(h.name);else for(c=0,g=this._overrideFields;c<g.length;c++)if(e=g[c],e.toLowerCase()===h.name.toLowerCase()){b.push(h);a.push(h.name);break}this.fields=b;this._overrideFields=a}this._layer&&(!0===
this._layer.useStandardizedQueries?this._databaseType=k.FeatureServiceDatabaseType.Standardised:(b=this._layer.version,void 0!==b&&null!==b&&10.5<=b&&(this._databaseType=k.FeatureServiceDatabaseType.Standardised,this._requestStandardised=!0)));this.objectIdField=this._layer.objectIdField;this.typeIdField=this._layer.typeIdField;this.types=this._layer.types};d.prototype._isInFeatureSet=function(a){return k.IdState.InFeatureSet};d.prototype._refineSetBlock=function(a,b){b=new n;b.resolve(a);return b.promise};
d.prototype._candidateIdTransform=function(a){return a};d.prototype._transformSetWithIdChanges=function(a){};d.prototype._getSet=function(a){var b=this,f=new n;null===this._wset?this._ensureLoaded().then(k.callback(function(){b._getFilteredSet("",null,null,null,a).then(k.callback(function(a){b._wset=a;f.resolve(a)},f),k.errback(f))},f),k.errback(f)):f.resolve(this._wset);return f.promise};d.prototype._runDatabaseProbe=function(a){var b=this,f=new n;this._ensureLoaded().then(k.callback(function(){var l=
new w;l.where=a.replace("OBJECTID",b._layer.objectIdField);b.executeQuery(l,"executeForIds").then(k.callback(function(a){f.resolve(!0)},f),function(a){try{f.resolve(!1)}catch(c){f.reject(c)}})},f),k.errback(f));return f.promise};d.prototype.pbfSupportedForQuery=function(a){return this._layer._canFetchPBFForQuery(a)};d.prototype.executeQuery=function(a,b){var f=new B(this._layerUrl()),l="execute"===b&&this.pbfSupportedForQuery(a);l&&(a.quantizationParameters={mode:"edit"});var h=null;if(this.recentlyUsedQueries){var c=
this.convertQueryToLruCacheKey(a);(h=this.recentlyUsedQueries.getFromCache(c))&&h.isRejected()&&(h=null,this.recentlyUsedQueries.removeFromCache(c));null===h&&(h=!0!==l?f[b](a):f[b](a,null,null,{format:"pbf"}),this.recentlyUsedQueries.addToCache(c,h))}null===h&&(h=!0!==l?f[b](a):f[b](a,null,null,{format:"pbf"}));return h};d.prototype._canUsePagination=function(){return void 0!==this._layer.advancedQueryCapabilities&&null!==this._layer.advancedQueryCapabilities&&!0===this._layer.advancedQueryCapabilities.supportsPagination?
!0:!1};d.prototype._cacheableFeatureSetSourceKey=function(){return this._layer.url};d.prototype._getFilteredSet=function(a,b,f,l,h){var c=this,g=new n;this.databaseType().then(k.callback(function(e){if(c.isTable()&&b&&null!==a&&""!==a)e=new y([],[],!0,null),g.resolve(e);else{if(c._canUsePagination())return c._getFilteredSetUsingPaging(a,b,f,l,h).then(k.callback(function(a){g.resolve(a)},g),k.errback(g)),g.promise;var m="",r=!1;null!==l&&void 0!==c._layer.advancedQueryCapabilities&&null!==c._layer.advancedQueryCapabilities&&
!0===c._layer.advancedQueryCapabilities.supportsOrderBy&&(m=l.constructClause(),r=!0);var p=new w;c._requestStandardised&&(p.sqlFormat="standard");p.where=null===f?null===b?"1\x3d1":"":f.toWhereClause(e);p.spatialRelationship=c._makeRelationshipEnum(a);p.outSpatialReference=c.spatialReference;p.orderByFields=""!==m?m.split(","):null;p.geometry=null===b?"":b;p.relationParam=c._makeRelationshipParam(a);c.executeQuery(p,"executeForIds").then(k.callback(function(a){null===a&&(a=[]);c._checkCancelled(h);
a=new y([],a,r,null);g.resolve(a)},g),k.errback(g))}},g),k.errback(g));return g.promise};d.prototype._expandPagedSet=function(a,b,f,l,h){return this._expandPagedSetFeatureSet(a,b,f,l,h)};d.prototype._getFilteredSetUsingPaging=function(a,b,f,l,h){var c=this,g=new n;try{var e="",m=!1;null!==l&&void 0!==this._layer.advancedQueryCapabilities&&null!==this._layer.advancedQueryCapabilities&&!0===this._layer.advancedQueryCapabilities.supportsOrderBy&&(e=l.constructClause(),m=!0);this.databaseType().then(k.callback(function(l){l=
null===f?null===b?"1\x3d1":"":f.toWhereClause(l);c._layer.getDefinitionExpression()&&(l=""!==l?"(("+c._layer.getDefinitionExpression()+") AND ("+l+"))":c._layer.getDefinitionExpression());var p=c._maxQueryRate();void 0!==c._layer.maxRecordCount&&c._layer.maxRecordCount<p&&(p=c._layer.maxRecordCount);var d=null;if(!0===c._pageJustIds)d=new y([],["GETPAGES"],m,{spatialRel:c._makeRelationshipEnum(a),relationParam:c._makeRelationshipParam(a),outFields:c._layer.objectIdField,resultRecordCount:p,resultOffset:0,
geometry:null===b?"":b,where:l,orderByFields:e,returnGeometry:"false",returnIdsOnly:"false",internal:{set:[],lastRetrieved:0,fullyResolved:!1}});else{var r=!0;!0===c._removeGeometry&&(r=!1);var u=null!==c._overrideFields?c._overrideFields:c._fieldsIncludingObjectId(c._layer.getOutFields()),d=new y([],["GETPAGES"],m,{spatialRel:c._makeRelationshipEnum(a),relationParam:c._makeRelationshipParam(a),outFields:u.join(","),resultRecordCount:p,resultOffset:0,geometry:null===b?"":b,where:l,orderByFields:e,
returnGeometry:r,returnIdsOnly:"false",internal:{set:[],lastRetrieved:0,fullyResolved:!1}})}c._expandPagedSet(d,p,0,1,h).then(k.callback(function(a){g.resolve(d)},g),k.errback(g))},g),k.errback(g))}catch(r){g.reject(r)}return g.promise};d.prototype._clonePageDefinition=function(a){return null===a?null:!0!==a.groupbypage?{groupbypage:!1,spatialRel:a.spatialRel,relationParam:a.relationParam,outFields:a.outFields,resultRecordCount:a.resultRecordCount,resultOffset:a.resultOffset,geometry:a.geometry,where:a.where,
orderByFields:a.orderByFields,returnGeometry:a.returnGeometry,returnIdsOnly:a.returnIdsOnly,internal:a.internal}:{groupbypage:!0,spatialRel:a.spatialRel,relationParam:a.relationParam,outFields:a.outFields,resultRecordCount:a.resultRecordCount,useOIDpagination:a.useOIDpagination,generatedOid:a.generatedOid,groupByFieldsForStatistics:a.groupByFieldsForStatistics,resultOffset:a.resultOffset,outStatistics:a.outStatistics,geometry:a.geometry,where:a.where,orderByFields:a.orderByFields,returnGeometry:a.returnGeometry,
returnIdsOnly:a.returnIdsOnly,internal:a.internal}};d.prototype._getPhysicalPage=function(a,b,f){var l=this,h=new n;try{var c=a.pagesDefinition.internal.lastRetrieved,g=new w;this._requestStandardised&&(g.sqlFormat="standard");g.spatialRelationship=a.pagesDefinition.spatialRel;g.relationParam=a.pagesDefinition.relationParam;g.outFields=a.pagesDefinition.outFields.split(",");g.num=a.pagesDefinition.resultRecordCount;g.start=a.pagesDefinition.internal.lastRetrieved;g.geometry=a.pagesDefinition.geometry;
g.where=a.pagesDefinition.where;g.orderByFields=""!==a.pagesDefinition.orderByFields?a.pagesDefinition.orderByFields.split(","):null;g.returnGeometry=a.pagesDefinition.returnGeometry;g.outSpatialReference=this.spatialReference;this.executeQuery(g,"execute").then(k.callback(function(b){l._checkCancelled(f);a.pagesDefinition.internal.lastRetrieved!==c&&h.resolve("done");for(var m=0;m<b.features.length;m++)void 0===b.features[m].geometry&&(b.features[m].geometry=null),a.pagesDefinition.internal.set[c+
m]=b.features[m].attributes[l._layer.objectIdField];if(!1===l._pageJustIds)for(m=0;m<b.features.length;m++)l._featureCache[b.features[m].attributes[l._layer.objectIdField]]=b.features[m];b.features.length!==a.pagesDefinition.resultRecordCount&&(a.pagesDefinition.internal.fullyResolved=!0);a.pagesDefinition.internal.lastRetrieved=c+a.pagesDefinition.resultRecordCount;h.resolve("done")},h),k.errback(h))}catch(e){h.reject(e)}return h.promise};d.prototype._fieldsIncludingObjectId=function(a){if(null===
a)return[this.objectIdField];a=a.slice(0);if(-1<a.indexOf("*"))return a;for(var b=!1,f=0;f<a.length;f++)if(a[f].toUpperCase()===this.objectIdField.toUpperCase()){b=!0;break}!1===b&&a.push(this.objectIdField);return a};d.prototype._getFeatures=function(a,b,f,l){var h=this,c=new n,g=[];try{-1!==b&&void 0===this._featureCache[b]&&g.push(b);if(!0===this._checkIfNeedToExpandKnownPage(a,this._maxProcessingRate(),l))return this._expandPagedSet(a,this._maxProcessingRate(),0,0,l).then(k.callback(function(m){h._getFeatures(a,
b,f,l).then(k.callback(function(a){c.resolve(a)},c),k.errback(c))},c),k.errback(c)),c.promise;for(var e=0,m=a._lastFetchedIndex;m<a._known.length;m++){a._lastFetchedIndex+=1;e++;if(void 0===this._featureCache[a._known[m]]){var d=!1;if(null!==this._layer._mode&&void 0!==this._layer._mode){var p=this._layer._mode;if(void 0!==p._featureMap[a._known[m]]){var D=p._featureMap[a._known[m]];null!==D&&(d=!0,this._featureCache[a._known[m]]=D)}}if(!1===d&&(a._known[m]!==b&&g.push(a._known[m]),g.length>=this._maxProcessingRate()-
1))break}if(e>=f&&0===g.length)break}if(0===g.length)c.resolve("success");else try{var q=new w;this._requestStandardised&&(q.sqlFormat="standard");q.objectIds=g;q.outFields=null!==this._overrideFields?this._overrideFields:this._fieldsIncludingObjectId(this._layer.getOutFields());q.returnGeometry=!0;!0===this._removeGeometry&&(q.returnGeometry=!1);q.outSpatialReference=this.spatialReference;this.executeQuery(q,"execute").then(k.callback(function(a){h._checkCancelled(l);if(void 0!==a.error)c.reject(Error(a.error));
else{for(var b=0;b<a.features.length;b++)void 0===a.features[b].geometry&&(a.features[b].geometry=null),h._featureCache[a.features[b].attributes[h._layer.objectIdField]]=a.features[b];c.resolve("success")}},c),k.errback(c))}catch(u){c.reject(u)}}catch(u){c.reject(u)}return c.promise};d.prototype._layerUrl=function(){return this._layer.url};d.prototype._getDistinctPages=function(a,b,f,l,h,c,g,e,m){var d=this,p=new n;this._ensureLoaded().then(k.callback(function(){for(var n=f.parseTree.column,q=0;q<
d._layer.fields.length;q++)if(d._layer.fields[q].name.toLowerCase()===n.toLowerCase()){n=d._layer.fields[q].name;break}d.databaseType().then(k.callback(function(u){var q=new w;d._requestStandardised&&(q.sqlFormat="standard");u=null===c?null===h?"1\x3d1":"":c.toWhereClause(u);d._layer.getDefinitionExpression()&&(u=""!==u?"(("+d._layer.getDefinitionExpression()+") AND ("+u+"))":d._layer.getDefinitionExpression());q.where=u;q.spatialRelationship=d._makeRelationshipEnum(l);q.relationParam=d._makeRelationshipParam(l);
q.geometry=null===h?null:h;q.returnDistinctValues=!0;q.returnGeometry=!1;q.outFields=[n];d.executeQuery(q,"execute").then(k.callback(function(q){d._checkCancelled(m);if(q.hasOwnProperty("features")){for(var u=!1,r=0;r<d._layer.fields.length;r++)if(d._layer.fields[r].name===n){"esriFieldTypeDate"===d._layer.fields[r].type&&(u=!0);break}for(r=0;r<q.features.length;r++){if(u){var v=q.features[r].attributes[n];null!==v?e.push(new Date(v)):e.push(v)}else e.push(q.features[r].attributes[n]);if(e.length>=
g)break}0===q.features.length?p.resolve(e):q.features.length===d._layer.maxRecordCount&&e.length<g?d._getDistinctPages(a+q.features.length,b,f,l,h,c,g,e,m).then(k.callback(function(a){p.resolve({calculated:!0,result:a})},p),k.errback(p)):p.resolve(e)}else p.reject(Error("Unnexected Result querying statistics from layer"))},p),k.errback(p))},p),k.errback(p))},p),k.errback(p));return p.promise};d.prototype._distinctStat=function(a,b,f,l,h,c,g,e){this._getDistinctPages(0,b,f,l,h,c,g,[],e).then(k.callback(function(b){a.resolve({calculated:!0,
result:b})},a),k.errback(a))};d.prototype.isTable=function(){return!1};d.prototype._countstat=function(a,b,f,l,h,c){var g=this;this.databaseType().then(k.callback(function(b){var c=new w;g._requestStandardised&&(c.sqlFormat="standard");g.isTable()&&l&&null!==f&&""!==f?a.resolve(0):(b=null===h?null===l?"1\x3d1":"":h.toWhereClause(b),g._layer.getDefinitionExpression()&&(b=""!==b?"(("+g._layer.getDefinitionExpression()+") AND ("+b+"))":g._layer.getDefinitionExpression()),c.where=b,c.where=b,c.spatialRelationship=
g._makeRelationshipEnum(f),c.relationParam=g._makeRelationshipParam(f),c.geometry=null===l?null:l,c.returnGeometry=!1,new B(g._layerUrl()),g.executeQuery(c,"executeForCount").then(k.callback(function(b){a.resolve({calculated:!0,result:b})},a),k.errback(a)))},a),k.errback(a))};d.prototype._stats=function(a,b,f,l,h,c,g,e){var m=this;this._ensureLoaded().then(k.callback(function(){var d=m._layer.advancedQueryCapabilities&&!0===m._layer.advancedQueryCapabilities.supportsSqlExpression,p=m._layer.advancedQueryCapabilities&&
!0===m._layer.advancedQueryCapabilities.supportsStatistics,n=m._layer.advancedQueryCapabilities&&!0===m._layer.advancedQueryCapabilities.supportsDistinct;"count"===b?n?m._countstat(a,b,l,h,c,e):a.resolve({calculated:!1}):!1===p||!1===f.isSingleField()&&!1===d||!1===f.isStandardized()?""!==l||null!==c?a.resolve({calculated:!1}):m._manualStat(b,f,g,e).then(k.callback(function(b){a.resolve(b)},a),k.errback(a)):"distinct"===b?!1===n?""!==l||null!==c?a.resolve({calculated:!1}):m._manualStat(b,f,g,e).then(k.callback(function(b){a.resolve(b)},
a),k.errback(a)):m._distinctStat(a,b,f,l,h,c,g,e):m.databaseType().then(k.callback(function(g){if(m.isTable()&&h&&null!==l&&""!==l)a.resolve({calculated:!0,result:null});else{var e=new w;m._requestStandardised&&(e.sqlFormat="standard");var d=null===c?null===h?"1\x3d1":"":c.toWhereClause(g);m._layer.getDefinitionExpression()&&(d=""!==d?"(("+m._layer.getDefinitionExpression()+") AND ("+d+"))":m._layer.getDefinitionExpression());e.where=d;e.spatialRelationship=m._makeRelationshipEnum(l);e.relationParam=
m._makeRelationshipParam(l);e.geometry=null===h?null:h;d=new C;d.statisticType=F.decodeStatType(b);d.onStatisticField=f.toWhereClause(g);d.outStatisticFieldName="FORMULA_STAT_RESULT";e.returnGeometry=!1;e.outStatistics=[d];m.executeQuery(e,"execute").then(k.callback(function(b){if(b.hasOwnProperty("features")&&0!==b.features.length){for(var c=!1,e=0;e<b.fields.length;e++)if("FORMULA_STAT_RESULT"===b.fields[e].name.toUpperCase()){"esriFieldTypeDate"===b.fields[e].type&&(c=!0);break}c?(c=b.features[0].attributes.FORMULA_STAT_RESULT,
null!==c&&(c=new Date(b.features[0].attributes.FORMULA_STAT_RESULT)),a.resolve({calculated:!0,result:c})):a.resolve({calculated:!0,result:b.features[0].attributes.FORMULA_STAT_RESULT})}else a.reject(Error("Unnexected Result querying statistics from layer"))},a),k.errback(a))}},a),k.errback(a))},a),k.errback(a))};d.prototype._stat=function(a,b,f,d,h,c,g){var e=new n;try{this._stats(e,a,b,f,d,h,c,g)}catch(m){e.reject(m)}return e.promise};d.prototype._canDoAggregates=function(a,b,d,l,h){var c=this,g=
new n;this._ensureLoaded().then(k.callback(function(a){a=!1;var e=c._layer.advancedQueryCapabilities&&!0===c._layer.advancedQueryCapabilities.supportsSqlExpression;void 0!==c._layer.advancedQueryCapabilities&&null!==c._layer.advancedQueryCapabilities&&!0===c._layer.advancedQueryCapabilities.supportsStatistics&&!0===c._layer.advancedQueryCapabilities.supportsOrderBy&&(a=!0);if(a)for(var d=0;d<b.length-1;d++)null!==b[d].workingexpr&&(!1===b[d].workingexpr.isStandardized()?a=!1:!1===b[d].workingexpr.isSingleField()&&
!1===e&&(a=!1));!1===a?g.resolve(!1):g.resolve(!0)},g),k.errback(g));return g.promise};d.prototype._makeRelationshipEnum=function(a){return 0<=a.indexOf("esriSpatialRelRelation")?"esriSpatialRelRelation":a};d.prototype._makeRelationshipParam=function(a){return 0<=a.indexOf("esriSpatialRelRelation")?a.split(":")[1]:""};d.prototype._getAggregatePagesDataSourceDefinition=function(a,b,d,l,h,c,g){var e=this,f=new n;this._ensureLoaded().then(k.callback(function(m){e.databaseType().then(k.callback(function(m){var k=
"",p=!1,n=!1;null!==c&&void 0!==e._layer.advancedQueryCapabilities&&null!==e._layer.advancedQueryCapabilities&&!0===e._layer.advancedQueryCapabilities.supportsOrderBy&&(k=c.constructClause(),n=!0);void 0!==e._layer.advancedQueryCapabilities&&null!==e._layer.advancedQueryCapabilities&&!1===e._layer.advancedQueryCapabilities.supportsPagination&&(n=!1,p=!0,k=e._layer.objectIdField);for(var r=[],v=0;v<b.length;v++){var t=new C;t.onStatisticField=null!==b[v].workingexpr?b[v].workingexpr.toWhereClause(m):
"";t.outStatisticFieldName=b[v].field;t.statisticType=b[v].toStatisticsName();r.push(t)}""===k&&(k=a.join(","));v=e._maxQueryRate();void 0!==e._layer.maxRecordCount&&e._layer.maxRecordCount<v&&(v=e._layer.maxRecordCount);m=null===h?null===l?"1\x3d1":"":h.toWhereClause(m);e._layer.getDefinitionExpression()&&(m=""!==m?"(("+e._layer.getDefinitionExpression()+") AND ("+m+"))":e._layer.getDefinitionExpression());k=new y([],["GETPAGES"],n,{groupbypage:!0,spatialRel:e._makeRelationshipEnum(d),relationParam:e._makeRelationshipParam(d),
outFields:["*"],useOIDpagination:p,generatedOid:g,resultRecordCount:v,resultOffset:0,groupByFieldsForStatistics:a,outStatistics:r,geometry:null===l?null:l,where:m,orderByFields:k,returnGeometry:!1,returnIdsOnly:!1,internal:{lastMaxId:-1,set:[],lastRetrieved:0,fullyResolved:!1}});f.resolve(k)},f),k.errback(f))},f),k.errback(f));return f.promise};d.prototype._getAgregagtePhysicalPage=function(a,b,d){var f=this,h=new n;try{var c=a.pagesDefinition.where;!0===a.pagesDefinition.useOIDpagination&&(c=""!==
c?"("+c+") AND ("+a.pagesDefinition.generatedOid+"\x3e"+a.pagesDefinition.internal.lastMaxId.toString()+")":a.pagesDefinition.generatedOid+"\x3e"+a.pagesDefinition.internal.lastMaxId.toString());var g=a.pagesDefinition.internal.lastRetrieved,e=new w;this._requestStandardised&&(e.sqlFormat="standard");e.where=c;e.spatialRelationship=a.pagesDefinition.spatialRel;e.relationParam=a.pagesDefinition.relationParam;e.outFields=a.pagesDefinition.outFields;e.outStatistics=a.pagesDefinition.outStatistics;e.geometry=
a.pagesDefinition.geometry;e.groupByFieldsForStatistics=a.pagesDefinition.groupByFieldsForStatistics;e.num=a.pagesDefinition.resultRecordCount;e.start=a.pagesDefinition.internal.lastRetrieved;e.returnGeometry=a.pagesDefinition.returnGeometry;e.orderByFields=""!==a.pagesDefinition.orderByFields?a.pagesDefinition.orderByFields.split(","):null;if(this.isTable()&&e.geometry&&e.spatialRelationship)return h.resolve([]),h.promise;this.executeQuery(e,"execute").then(k.callback(function(b){f._checkCancelled(d);
if(b.hasOwnProperty("features")){var c=[];if(a.pagesDefinition.internal.lastRetrieved!==g)h.resolve([]);else{for(var e=0;e<b.features.length;e++)void 0===b.features[e].geometry&&(b.features[e].geometry=null),a.pagesDefinition.internal.set[g+e]=b.features[e].attributes[a.pagesDefinition.generatedOid];for(e=0;e<b.features.length;e++)c.push(new A({attributes:b.features[e].attributes,geometry:null}));!0===a.pagesDefinition.useOIDpagination?0===b.features.length?a.pagesDefinition.internal.fullyResolved=
!0:a.pagesDefinition.internal.lastMaxId=b.features[b.features.length-1].attributes[a.pagesDefinition.generatedOid]:b.features.length!==a.pagesDefinition.resultRecordCount&&(a.pagesDefinition.internal.fullyResolved=!0);a.pagesDefinition.internal.lastRetrieved=g+a.pagesDefinition.resultRecordCount;h.resolve(c)}}else h.reject(Error("Unnexected Result querying aggregates from layer"))},h),k.errback(h))}catch(m){h.reject(m)}return h.promise};d.create=function(a,b,f,k){a={url:a,outFields:null===b?["*"]:
b};null!==f&&""!==f&&(a.token=f);f=new H(a);return new d({layer:f,spatialReference:k})};d.prototype.canBeBigDataFeatureSet=function(){return!0};d.prototype.shouldBeResolvedAsBigData=function(){return!1};d.prototype.expressAsArcadeScriptImpl=function(a,b,d){this.arcadeAssignNextScriptStepIdentifiers(d);a=this.arcadeAssignNextGlobalIdentifier(d);var f=null,h=x.findCredential(this._layer.url);h&&(f=h.oken);b[a]={name:a,type:"FeatureLayer",params:{url:this._layer.url,token:f,definitionExpression:this._layer.getDefinitionExpression(),
fields:this._layer.getOutFields()}};d.featuresetsyms.push(a);return""};return d}(E)});