// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
var __extends=this&&this.__extends||function(){var t=function(n,h){t=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(h,r){h.__proto__=r}||function(h,r){for(var n in r)r.hasOwnProperty(n)&&(h[n]=r[n])};return t(n,h)};return function(n,h){function u(){this.constructor=n}t(n,h);n.prototype=null===h?Object.create(h):(u.prototype=h.prototype,new u)}}();
define("esri/arcade/featureset/sources/FeatureLayerMemory","require exports dojo/Deferred dojo/promise/all ../../../graphic ../support/FeatureSet ../support/IdSet ../support/shared ../../../geometry/Geometry ../../../geometry/geometryEngineAsync ../../../geometry/jsonUtils ../../../layers/Field".split(" "),function(t,n,h,u,r,x,v,f,y,p,z,w){return function(n){function c(a){var b=n.call(this,a)||this;b.source=[];a.spatialReference&&(b.spatialReference=a.spatialReference);b.types=a.types;b.geometryType=
a.geometryType;b.typeIdField=a.typeIdField;b.objectIdField=a.objectIdField;b.fields=a.fields.slice(0);b.source=a.source;b._transparent=!0;b._maxProcessing=1E3;b._wset=null;return b}__extends(c,n);c.prototype._maxQueryRate=function(){return f.defaultMaxRecords};c.prototype.load=function(){if(null===this._loadPromise){var a=new h;this._loadPromise=a;this._initialiseFeatureSet();a.resolve(this)}return this._loadPromise.promise};c.prototype._initialiseFeatureSet=function(){this._databaseType=f.FeatureServiceDatabaseType.Standardised};
c.prototype.optimisePagingFeatureQueries=function(a){};c.prototype._allFeatures=function(){return this.source};c.prototype._isInFeatureSet=function(a){return f.IdState.InFeatureSet};c.prototype.isTable=function(){return null===this.geometryType||""===this.geometryType};c.prototype._transformSetWithIdChanges=function(a){};c.prototype._candidateIdTransform=function(a){return a};c.prototype._getSet=function(a){var b=this,d=new h;null===this._wset?this._ensureLoaded().then(f.callback(function(){b._getFilteredSet("",
null,null,null,a).then(function(a){b._wset=a;d.resolve(a)},f.errback(d))},d),f.errback(d)):d.resolve(this._wset);return d.promise};c.prototype._getFilteredSet=function(a,b,d,k,q){var g=this,e=new h;try{this._ensureLoaded().then(f.callback(function(){if(g.isTable()&&b&&null!==a&&""!==a){var k=new v([],[],!0,null);e.resolve(k)}else{if(null===g._wset){var c=[];g._allFeatures().forEach(function(a){void 0===a.geometry&&(a.geometry=null);var b=a.attributes[g.objectIdField];c.push(b);g._featureCache[b]=
a});g._wset=new v([],c,!1,null)}k=g._wset._known.slice(0);g._checkCancelled(q);g.fetchAndRefineFeaturesByWhere(k,d,q).then(f.callback(function(d){g._checkCancelled(q);null!==b?g.fetchAndRefineFeaturesSpatially(d,b,a,q).then(f.callback(function(a){e.resolve(new v([],a,!1,null))},e),f.errback(e)):e.resolve(new v([],d,!1,null))},e),f.errback(e))}},e),f.errback(e))}catch(m){e.reject(m)}return e.promise};c.prototype.executeSpatialRelationTest=function(a,b,d,k){if(null===a.geometry)return a=new h,a.resolve(!1),
a.promise;switch(b){case "esriSpatialRelEnvelopeIntersects":return b=f.shapeExtent(d),a=f.shapeExtent(a.geometry),p.intersects(b,a);case "esriSpatialRelIntersects":return p.intersects(d,a.geometry);case "esriSpatialRelContains":return p.contains(d,a.geometry);case "esriSpatialRelOverlaps":return p.overlaps(d,a.geometry);case "esriSpatialRelWithin":return p.within(d,a.geometry);case "esriSpatialRelTouches":return p.touches(d,a.geometry);case "esriSpatialRelCrosses":return p.crosses(d,a.geometry);case "esriSpatialRelRelation":return p.relate(d,
a.geometry,k)}};c.prototype.executeWhereTest=function(a,b){return b.testFeature(a)};c.prototype.fetchAndRefineFeaturesSpatially=function(a,b,d,k){var c=new h,g=[];k=[];var e="";0<=d.indexOf("esriSpatialRelRelation")&&(e=d.split(":")[1],d="esriSpatialRelRelation");for(var m=0;m<a.length;m++){var A=this._featureFromCache(a[m]);k.push(this.executeSpatialRelationTest(A,d,b,e))}if(0===k.length)return c.resolve(g),c.promise;u(k).then(f.callback(function(b){for(var d=0;d<a.length;d++)!0===b[d]&&g.push(a[d]);
c.resolve(g)},c),f.errback(c));return c.promise};c.prototype.fetchAndRefineFeaturesByWhere=function(a,b,d){d=new h;var c=[];if(null===b)d.resolve(a);else{for(var q=0;q<a.length;q++){var g=this._featureFromCache(a[q]);this.executeWhereTest(g,b)&&c.push(a[q])}d.resolve(c)}return d.promise};c.prototype._getFeatures=function(a,b,d,c){c=new h;var k=[];-1!==b&&void 0===this._featureCache[b]&&k.push(b);for(var g=a._lastFetchedIndex;g<a._known.length&&!(a._lastFetchedIndex+=1,void 0===this._featureCache[a._known[g]]&&
(a._known[g]!==b&&k.push(a._known[g]),k.length>d));g++);0===k.length?c.resolve("success"):c.reject(Error("Unaccounted for Features. Not in Feature Collection"));return c.promise};c.prototype._refineSetBlock=function(a,b,d){b=new h;b.resolve(a);return b.promise};c.prototype._stat=function(a,b,d,c,q,g,e){a=new h;a.resolve({calculated:!1});return a.promise};c.prototype._canDoAggregates=function(a,b,d,c,q){a=new h;a.resolve(!1);return a.promise};c._cloneAttr=function(a){var b={},c;for(c in a)b[c]=a[c];
return b};c.create=function(a,b){var d=b.toJson(),k=a.layerDefinition.objectIdField,h=a.layerDefinition.geometryType;void 0===h&&(h=a.featureSet.geometryType);void 0===h&&(h="");var g=a.featureSet.features;if(""===k||void 0===k){for(var e=!1,m=0,f=a.layerDefinition.fields;m<f.length;m++){var l=f[m];if("oid"===l.type||"esriFieldTypeOID"===l.type){k=l.name;e=!0;break}}if(!1===e){k="FID";e=!0;for(m=0;e;){for(var f=!0,n=0,p=a.layerDefinition.fields;n<p.length;n++)if(l=p[n],l.name===k){f=!1;break}!0===
f?e=!1:(m++,k="FID"+m.toString())}a.layerDefinition.fields.push({type:"esriFieldTypeOID",name:k,alias:k});l=[];for(e=0;e<g.length;e++)l.push({geometry:a.featureSet.features[e].geometry,attributes:a.featureSet.features[e].attributes?this._cloneAttr(a.featureSet.features[e].attributes):{}}),l[e].attributes[k]=e;g=l}}e=[];m=0;for(f=a.layerDefinition.fields;m<f.length;m++)l=f[m],l instanceof w?e.push(l):e.push(new w(l));m=[];for(f=0;f<g.length;f++)l=g[f],l.geometry&&!1===l.geometry instanceof y&&void 0===
l.geometry.spatialReference&&(l.geometry.spatialReference=d),m.push(new r(null===l.geometry||void 0===l.geometry?null:z.fromJson(l.geometry),null,l.attributes));return new c({source:m,types:a.types,typeIdField:a.typeIdField,fields:e,objectIdField:k,geometryType:h,spatialReference:b})};c.prototype.canBeBigDataFeatureSet=function(){return!1};c.prototype.shouldBeResolvedAsBigData=function(){return!1};return c}(x)});