// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
var __extends=this&&this.__extends||function(){var B=function(r,n){B=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(n,y){n.__proto__=y}||function(n,y){for(var r in y)y.hasOwnProperty(r)&&(n[r]=y[r])};return B(r,n)};return function(r,n){function C(){this.constructor=r}B(r,n);r.prototype=null===n?Object.create(n):(C.prototype=n.prototype,new C)}}();
define("esri/arcade/featureset/sources/FeatureLayerDynamic","require exports dojo/Deferred ../../../graphic ../../../request ../../../SpatialReference ../../../urlUtils ../support/FeatureSet ../support/IdSet ../support/shared ../support/stats ../support/sha ../../../geometry/Extent ../../../layers/FeatureType ../../../layers/Field ../../../tasks/query ../../../tasks/QueryTask ../../../tasks/StatisticDefinition ../support/cache ../../../sniff".split(" "),function(B,r,n,C,y,H,I,J,A,e,K,L,M,N,D,v,E,
F,z,G){var O=!!G("esri-pbf"),P=!!G("esri-featurelayer-pbf"),R=function(){function e(b,a,c,d){void 0===c&&(c=null);this.url=b;this.outFields=a;this.spatialReference=c;this.token=d;this._url=null;this.supportsFormatPBF=!1;this._queryTask=this._loadPromise=null;this.currentVersion=0;this.useStandardizedQueries=!1;this.fields=[];this._url=I.urlToObject(b)}e.prototype._canFetchPBFForQuery=function(b){return O&&P&&this.supportsFormatPBF&&!b.outStatistics};e.prototype._loadMetaData=function(b){var a=new n;
if(null!==z.applicationCache){var c=z.applicationCache.getLayerInfo(b);if(null!==c)return c}null!==z.applicationCache&&z.applicationCache.setLayerInfo(b,a.promise);y({url:b,content:{f:"json"},callbackParamName:"callback",load:function(d){a.resolve(d)},error:function(d){null!==z.applicationCache&&z.applicationCache.clearLayerInfo(b);a.reject(d)}});return a.promise};e.prototype.load=function(){var b=this;if(null===this._loadPromise){var a=new n;this._loadPromise=a;var c=this._url.path;this._loadMetaData(c).then(function(d){try{b._queryTask=
new E(c);b.objectIdField=d.objectIdField;if(!b.objectIdField)for(var e=d.fields,l=0;l<e.length;l++){var f=e[l];if("esriFieldTypeOID"===f.type){b.objectIdField=f.name;break}}b.globalIdField=d.globalIdField;b.geometryType=d.geometryType;b.typeIdField=d.typeIdField;b.fullExtent=new M(d.fullExtent);b.advancedQueryCapabilities=d.advancedQueryCapabilities||{supportsStatistics:d.supportsStatistics,supportsOrderBy:d.supportsAdvancedQueries,supportsDistinct:d.supportsAdvancedQueries};if(d.supportedQueryFormats)for(var e=
0,g=d.supportedQueryFormats.split(",");e<g.length;e++)if("pbf"===g[e].replace(/^\s+|\s+$/gm,"").toLowerCase()){b.supportsFormatPBF=!0;break}!0===d.useStandardizedQueries&&(b.useStandardizedQueries=!0);void 0!==d.currentVersion&&(b.currentVersion=d.currentVersion);if(d.types){b.types=[];for(var g=0,k=d.types;g<k.length;g++){var h=k[g],t=new N(h);b.types.push(t)}}d.spatialReference&&!b.spatialReference&&(b.spatialReference=new H(d.spatialReference));if(1===b.outFields.length&&"*"===b.outFields[0])for(var m=
0,x=d.fields;m<x.length;m++){var h=x[m],q=new D(h);b.fields.push(q)}else for(x=0,m=d.fields;x<m.length;x++)if(h=m[x],"esriFieldTypeOID"===h.type)q=new D(h),b.fields.push(q);else{d=!1;for(var k=0,w=b.outFields;k<w.length;k++){var u=w[k];if(h.name.toUpperCase()===u.toUpperCase()){d=!0;break}}d&&(q=new D(h),b.fields.push(q))}b.definitionExpression="";a.resolve(b)}catch(Q){a.reject(Q)}},function(d){a.reject(d)})}return this._loadPromise.promise};e.prototype.queryIds=function(b){var a=new n;this._queryTask.executeForIds(b,
function(c){a.resolve(c)},function(c){a.reject(c)});return a.promise};return e}();return function(r){function b(a){var c=r.call(this,a)||this;c._layer=null;c._removeGeometry=!1;c.formulaCredential=null;c._pageJustIds=!1;c._requestStandardised=!1;a.spatialReference&&(c.spatialReference=a.spatialReference);c._layer=new R(a.url,a.outFields,c.spatialReference,a.token);c._transparent=!0;c._maxProcessing=1E3;c._wset=null;void 0!==a.includeGeometry&&(c._removeGeometry=!1===a.includeGeometry);return c}__extends(b,
r);b.prototype.optimisePagingFeatureQueries=function(a){this._pageJustIds=a};b.prototype._maxQueryRate=function(){return e.defaultMaxRecords};b.prototype.convertQueryToLruCacheKey=function(a){a=e.stableStringify(a.toJson());return(new L(a,"TEXT")).getHash("SHA-1","B64")};b.prototype.load=function(){var a=this;if(null===this._loadPromise){var c=new n;this._loadPromise=c;this._layer.load().then(function(){a._initialiseFeatureSet();c.resolve(a)},function(a){c.reject(a)})}return this._loadPromise.promise};
b.prototype._initialiseFeatureSet=function(){null==this.spatialReference&&(this.spatialReference=this._layer.spatialReference);this.geometryType=this._layer.geometryType;void 0===this.geometryType&&(this.geometryType="");this.fields=this._layer.fields.slice(0);if(!0===this._layer.useStandardizedQueries)this._databaseType=e.FeatureServiceDatabaseType.Standardised;else{var a=this._layer.currentVersion;void 0!==a&&null!==a&&10.5<=a&&(this._databaseType=e.FeatureServiceDatabaseType.Standardised,this._requestStandardised=
!0)}this.objectIdField=this._layer.objectIdField;this.typeIdField=this._layer.typeIdField;this.types=this._layer.types};b.prototype._isInFeatureSet=function(a){return e.IdState.InFeatureSet};b.prototype._refineSetBlock=function(a,c){c=new n;c.resolve(a);return c.promise};b.prototype._candidateIdTransform=function(a){return a};b.prototype._transformSetWithIdChanges=function(a){};b.prototype._getSet=function(a){var c=this,d=new n;null===this._wset?this._ensureLoaded().then(e.callback(function(){c._getFilteredSet("",
null,null,null,a).then(e.callback(function(a){c._wset=a;d.resolve(a)},d),e.errback(d))},d),e.errback(d)):d.resolve(this._wset);return d.promise};b.prototype._runDatabaseProbe=function(a){var c=this,d=new n;this._ensureLoaded().then(e.callback(function(){var b=new v;b.where=a.replace("OBJECTID",c._layer.objectIdField);c._layer.queryIds(b).then(e.callback(function(a){d.resolve(!0)},d),function(a){try{d.resolve(!1)}catch(f){d.reject(f)}})},d),e.errback(d));return d.promise};b.prototype._canUsePagination=
function(){return void 0!==this._layer.advancedQueryCapabilities&&null!==this._layer.advancedQueryCapabilities&&!0===this._layer.advancedQueryCapabilities.supportsPagination?!0:!1};b.prototype._cacheableFeatureSetSourceKey=function(){return this._layer.url};b.prototype._getFilteredSet=function(a,c,d,b,l){var f=this,g=new n;this.databaseType().then(e.callback(function(k){if(f.isTable()&&c&&null!==a&&""!==a)k=new A([],[],!0,null),g.resolve(k);else if(f._canUsePagination())f._getFilteredSetUsingPaging(a,
c,d,b,l).then(e.callback(function(a){g.resolve(a)},g),e.errback(g));else{var h="",p=!1;null!==b&&void 0!==f._layer.advancedQueryCapabilities&&null!==f._layer.advancedQueryCapabilities&&!0===f._layer.advancedQueryCapabilities.supportsOrderBy&&(h=b.constructClause(),p=!0);var m=new v;f._requestStandardised&&(m.sqlFormat="standard");m.where=null===d?null===c?"1\x3d1":"":d.toWhereClause(k);m.spatialRelationship=f._makeRelationshipEnum(a);m.outSpatialReference=f.spatialReference;m.orderByFields=""!==h?
h.split(","):null;m.geometry=null===c?null:c;m.relationParam=f._makeRelationshipParam(a);f.executeQuery(m,"executeForIds").then(e.callback(function(a){null===a&&(a=[]);f._checkCancelled(l);a=new A([],a,p,null);g.resolve(a)},g),e.errback(g))}},g),e.errback(g));return g.promise};b.prototype._expandPagedSet=function(a,c,d,b,e){return this._expandPagedSetFeatureSet(a,c,d,b,e)};b.prototype._getFilteredSetUsingPaging=function(a,c,d,b,l){var f=this,g=new n;try{var k="",h=!1;null!==b&&void 0!==this._layer.advancedQueryCapabilities&&
null!==this._layer.advancedQueryCapabilities&&!0===this._layer.advancedQueryCapabilities.supportsOrderBy&&(k=b.constructClause(),h=!0);this.databaseType().then(e.callback(function(b){b=null===d?null===c?"1\x3d1":"":d.toWhereClause(b);f._layer.definitionExpression&&(b=""!==b?"(("+f._layer.definitionExpression+") AND ("+b+"))":f._layer.definitionExpression);var m=f._maxQueryRate();void 0!==f._layer.maxRecordCount&&f._layer.maxRecordCount<m&&(m=f._layer.maxRecordCount);var p=null;if(!0===f._pageJustIds)p=
new A([],["GETPAGES"],h,{spatialRel:f._makeRelationshipEnum(a),relationParam:f._makeRelationshipParam(a),outFields:f._layer.objectIdField,resultRecordCount:m,resultOffset:0,geometry:null===c?"":c,where:b,orderByFields:k,returnGeometry:!1,returnIdsOnly:"false",internal:{set:[],lastRetrieved:0,fullyResolved:!1}});else{var t=!0;!0===f._removeGeometry&&(t=!1);var w=f._fieldsIncludingObjectId(f._layer.outFields),p=new A([],["GETPAGES"],h,{spatialRel:f._makeRelationshipEnum(a),relationParam:f._makeRelationshipParam(a),
outFields:w.join(","),resultRecordCount:m,resultOffset:0,geometry:null===c?"":c,where:b,orderByFields:k,returnGeometry:t,returnIdsOnly:"false",internal:{set:[],lastRetrieved:0,fullyResolved:!1}})}f._expandPagedSet(p,m,0,1,l).then(e.callback(function(a){g.resolve(p)},g),e.errback(g))},g),e.errback(g))}catch(t){g.reject(t)}return g.promise};b.prototype._clonePageDefinition=function(a){return null===a?null:!0!==a.groupbypage?{groupbypage:!1,spatialRel:a.spatialRel,relationParam:a.relationParam,outFields:a.outFields,
resultRecordCount:a.resultRecordCount,resultOffset:a.resultOffset,geometry:a.geometry,where:a.where,orderByFields:a.orderByFields,returnGeometry:a.returnGeometry,returnIdsOnly:a.returnIdsOnly,internal:a.internal}:{groupbypage:!0,spatialRel:a.spatialRel,relationParam:a.relationParam,outFields:a.outFields,resultRecordCount:a.resultRecordCount,useOIDpagination:a.useOIDpagination,generatedOid:a.generatedOid,groupByFieldsForStatistics:a.groupByFieldsForStatistics,resultOffset:a.resultOffset,outStatistics:a.outStatistics,
geometry:a.geometry,where:a.where,orderByFields:a.orderByFields,returnGeometry:a.returnGeometry,returnIdsOnly:a.returnIdsOnly,internal:a.internal}};b.prototype._getPhysicalPage=function(a,c,d){var b=this,l=new n;try{var f=a.pagesDefinition.internal.lastRetrieved,g=new v;this._requestStandardised&&(g.sqlFormat="standard");g.spatialRelationship=a.pagesDefinition.spatialRel;g.relationParam=a.pagesDefinition.relationParam;g.outFields=a.pagesDefinition.outFields.split(",");g.num=a.pagesDefinition.resultRecordCount;
g.start=a.pagesDefinition.internal.lastRetrieved;g.geometry=a.pagesDefinition.geometry;g.where=a.pagesDefinition.where;g.orderByFields=""!==a.pagesDefinition.orderByFields?a.pagesDefinition.orderByFields.split(","):null;g.returnGeometry=a.pagesDefinition.returnGeometry;g.outSpatialReference=this.spatialReference;this.executeQuery(g,"execute").then(e.callback(function(c){b._checkCancelled(d);a.pagesDefinition.internal.lastRetrieved!==f&&l.resolve("done");for(var h=0;h<c.features.length;h++)void 0===
c.features[h].geometry&&(c.features[h].geometry=null),a.pagesDefinition.internal.set[f+h]=c.features[h].attributes[b._layer.objectIdField];if(!1===b._pageJustIds)for(h=0;h<c.features.length;h++)b._featureCache[c.features[h].attributes[b._layer.objectIdField]]=c.features[h];c.features.length!==a.pagesDefinition.resultRecordCount&&(a.pagesDefinition.internal.fullyResolved=!0);a.pagesDefinition.internal.lastRetrieved=f+a.pagesDefinition.resultRecordCount;l.resolve("done")},l),e.errback(l))}catch(k){l.reject(k)}return l.promise};
b.prototype._fieldsIncludingObjectId=function(a){if(null===a)return[this.objectIdField];a=a.slice(0);if(-1<a.indexOf("*"))return a;for(var c=!1,b=0;b<a.length;b++)if(a[b].toUpperCase()===this.objectIdField.toUpperCase()){c=!0;break}!1===c&&a.push(this.objectIdField);return a};b.prototype._getFeatures=function(a,c,b,p){var d=this,f=new n,g=[];try{-1!==c&&void 0===this._featureCache[c]&&g.push(c);if(!0===this._checkIfNeedToExpandKnownPage(a,this._maxProcessingRate(),p))return this._expandPagedSet(a,
this._maxProcessingRate(),0,0,p).then(e.callback(function(h){d._getFeatures(a,c,b,p).then(e.callback(function(a){f.resolve(a)},f),e.errback(f))},f),e.errback(f)),f.promise;for(var k=0,h=a._lastFetchedIndex;h<a._known.length;h++){a._lastFetchedIndex+=1;k++;if(void 0===this._featureCache[a._known[h]]){var t=!1;if(null!==this._layer._mode&&void 0!==this._layer._mode){var m=this._layer._mode;if(void 0!==m._featureMap[a._known[h]]){var x=m._featureMap[a._known[h]];null!==x&&(t=!0,this._featureCache[a._known[h]]=
x)}}if(!1===t&&(a._known[h]!==c&&g.push(a._known[h]),g.length>=this._maxProcessingRate()-1))break}if(k>=b&&0===g.length)break}if(0===g.length)f.resolve("success");else try{var q=new v;this._requestStandardised&&(q.sqlFormat="standard");q.objectIds=g;q.outFields=this._fieldsIncludingObjectId(this._layer.outFields);q.returnGeometry=!0;!0===this._removeGeometry&&(q.returnGeometry=!1);q.outSpatialReference=this.spatialReference;this.executeQuery(q,"execute").then(e.callback(function(a){d._checkCancelled(p);
if(void 0!==a.error)f.reject(Error(a.error));else{for(var c=0;c<a.features.length;c++)void 0===a.features[c].geometry&&(a.features[c].geometry=null),d._featureCache[a.features[c].attributes[d._layer.objectIdField]]=a.features[c];f.resolve("success")}},f),e.errback(f))}catch(w){f.reject(w)}}catch(w){f.reject(w)}return f.promise};b.prototype._layerUrl=function(){return this._layer.url};b.prototype.pbfSupportedForQuery=function(a){return this._layer._canFetchPBFForQuery(a)};b.prototype.executeQuery=
function(a,c){var b=new E(this._layerUrl()),e="execute"===c&&this.pbfSupportedForQuery(a);e&&(a.quantizationParameters={mode:"edit"});var l=null;if(this.recentlyUsedQueries){var f=this.convertQueryToLruCacheKey(a);(l=this.recentlyUsedQueries.getFromCache(f))&&l.isRejected()&&(l=null,this.recentlyUsedQueries.removeFromCache(f));null===l&&(l=!0!==e?b[c](a):b[c](a,null,null,{format:"pbf"}),this.recentlyUsedQueries.addToCache(f,l))}null===l&&(l=!0!==e?b[c](a):b[c](a,null,null,{format:"pbf"}));return l};
b.prototype._getDistinctPages=function(a,c,b,p,l,f,g,k,h){var d=this,m=new n;this._ensureLoaded().then(e.callback(function(){for(var n=b.parseTree.column,q=0;q<d._layer.fields.length;q++)if(d._layer.fields[q].name.toLowerCase()===n.toLowerCase()){n=d._layer.fields[q].name;break}d.databaseType().then(e.callback(function(q){var u=new v;d._requestStandardised&&(u.sqlFormat="standard");q=null===f?null===l?"1\x3d1":"":f.toWhereClause(q);d._layer.definitionExpression&&(q=""!==q?"(("+d._layer.definitionExpression+
") AND ("+q+"))":d._layer.definitionExpression);u.where=q;u.spatialRelationship=d._makeRelationshipEnum(p);u.relationParam=d._makeRelationshipParam(p);u.geometry=null===l?null:l;u.returnDistinctValues=!0;u.returnGeometry=!1;u.outFields=[n];d.executeQuery(u,"execute").then(e.callback(function(q){d._checkCancelled(h);if(q.hasOwnProperty("features")){for(var u=!1,t=0;t<d._layer.fields.length;t++)if(d._layer.fields[t].name===n){"esriFieldTypeDate"===d._layer.fields[t].type&&(u=!0);break}for(t=0;t<q.features.length;t++){if(u){var w=
q.features[t].attributes[n];null!==w?k.push(new Date(w)):k.push(w)}else k.push(q.features[t].attributes[n]);if(k.length>=g)break}0===q.features.length?m.resolve(k):q.features.length===d._layer.maxRecordCount&&k.length<g?d._getDistinctPages(a+q.features.length,c,b,p,l,f,g,k,h).then(e.callback(function(a){m.resolve({calculated:!0,result:a})},m),e.errback(m)):m.resolve(k)}else m.reject(Error("Unnexected Result querying statistics from layer"))},m),e.errback(m))},m),e.errback(m))},m),e.errback(m));return m.promise};
b.prototype._distinctStat=function(a,b,d,p,l,f,g,k){this._getDistinctPages(0,b,d,p,l,f,g,[],k).then(e.callback(function(b){a.resolve({calculated:!0,result:b})},a),e.errback(a))};b.prototype.isTable=function(){return null===this._layer.geometryType||""===this._layer.geometryType||void 0===this._layer.geometryType};b.prototype._countstat=function(a,b,d,p,l,f){var c=this;this.databaseType().then(e.callback(function(b){var h=new v;c._requestStandardised&&(h.sqlFormat="standard");c.isTable()&&p&&null!==
d&&""!==d?a.resolve({calculated:!0,result:0}):(b=null===l?null===p?"1\x3d1":"":l.toWhereClause(b),c._layer.definitionExpression&&(b=""!==b?"(("+c._layer.definitionExpression+") AND ("+b+"))":c._layer.definitionExpression),h.where=b,h.where=b,h.spatialRelationship=c._makeRelationshipEnum(d),h.relationParam=c._makeRelationshipParam(d),h.geometry=null===p?null:p,h.returnGeometry=!1,c.executeQuery(h,"executeForCount").then(e.callback(function(b){a.resolve({calculated:!0,result:b})},a),e.errback(a)))},
a),e.errback(a))};b.prototype._stats=function(a,b,d,p,l,f,g,k){var c=this;this._ensureLoaded().then(e.callback(function(){var h=c._layer.advancedQueryCapabilities&&!0===c._layer.advancedQueryCapabilities.supportsSqlExpression,m=c._layer.advancedQueryCapabilities&&!0===c._layer.advancedQueryCapabilities.supportsStatistics,n=c._layer.advancedQueryCapabilities&&!0===c._layer.advancedQueryCapabilities.supportsDistinct;"count"===b?n?c._countstat(a,b,p,l,f,k):a.resolve({calculated:!1}):!1===m||!1===d.isSingleField()&&
!1===h||!1===d.isStandardized()?""!==p||null!==f?a.resolve({calculated:!1}):c._manualStat(b,d,g,k).then(e.callback(function(b){a.resolve(b)},a),e.errback(a)):"distinct"===b?!1===n?""!==p||null!==f?a.resolve({calculated:!1}):c._manualStat(b,d,g,k).then(e.callback(function(b){a.resolve(b)},a),e.errback(a)):c._distinctStat(a,b,d,p,l,f,g,k):c.databaseType().then(e.callback(function(k){if(c.isTable()&&l&&null!==p&&""!==p)a.resolve({calculated:!0,result:null});else{var h=new v;c._requestStandardised&&(h.sqlFormat=
"standard");var g=null===f?null===l?"1\x3d1":"":f.toWhereClause(k);c._layer.definitionExpression&&(g=""!==g?"(("+c._layer.definitionExpression+") AND ("+g+"))":c._layer.definitionExpression);h.where=g;h.spatialRelationship=c._makeRelationshipEnum(p);h.relationParam=c._makeRelationshipParam(p);h.geometry=null===l?null:l;g=new F;g.statisticType=K.decodeStatType(b);g.onStatisticField=d.toWhereClause(k);g.outStatisticFieldName="FORMULA_STAT_RESULT";h.returnGeometry=!1;h.outStatistics=[g];c.executeQuery(h,
"execute").then(e.callback(function(b){if(b.hasOwnProperty("features")&&0!==b.features.length){for(var c=!1,d=0;d<b.fields.length;d++)if("FORMULA_STAT_RESULT"===b.fields[d].name.toUpperCase()){"esriFieldTypeDate"===b.fields[d].type&&(c=!0);break}c?(c=b.features[0].attributes.FORMULA_STAT_RESULT,null!==c&&(c=new Date(b.features[0].attributes.FORMULA_STAT_RESULT)),a.resolve({calculated:!0,result:c})):a.resolve({calculated:!0,result:b.features[0].attributes.FORMULA_STAT_RESULT})}else a.reject(Error("Unnexected Result querying statistics from layer"))},
a),e.errback(a))}},a),e.errback(a))},a),e.errback(a))};b.prototype._stat=function(a,b,d,e,l,f,g){var c=new n;try{this._stats(c,a,b,d,e,l,f,g)}catch(h){c.reject(h)}return c.promise};b.prototype._canDoAggregates=function(a,b,d,p,l){var c=this,g=new n;this._ensureLoaded().then(e.callback(function(a){a=!1;var d=c._layer.advancedQueryCapabilities&&!0===c._layer.advancedQueryCapabilities.supportsSqlExpression;void 0!==c._layer.advancedQueryCapabilities&&null!==c._layer.advancedQueryCapabilities&&!0===c._layer.advancedQueryCapabilities.supportsStatistics&&
!0===c._layer.advancedQueryCapabilities.supportsOrderBy&&(a=!0);if(a)for(var e=0;e<b.length-1;e++)null!==b[e].workingexpr&&(!1===b[e].workingexpr.isStandardized()?a=!1:!1===b[e].workingexpr.isSingleField()&&!1===d&&(a=!1));!1===a?g.resolve(!1):g.resolve(!0)},g),e.errback(g));return g.promise};b.prototype._makeRelationshipEnum=function(a){return 0<=a.indexOf("esriSpatialRelRelation")?"esriSpatialRelRelation":a};b.prototype._makeRelationshipParam=function(a){return 0<=a.indexOf("esriSpatialRelRelation")?
a.split(":")[1]:""};b.prototype._getAggregatePagesDataSourceDefinition=function(a,b,d,p,l,f,g){var c=this,h=new n;this._ensureLoaded().then(e.callback(function(k){c.databaseType().then(e.callback(function(e){var k="",m=!1,n=!1;null!==f&&void 0!==c._layer.advancedQueryCapabilities&&null!==c._layer.advancedQueryCapabilities&&!0===c._layer.advancedQueryCapabilities.supportsOrderBy&&(k=f.constructClause(),n=!0);void 0!==c._layer.advancedQueryCapabilities&&null!==c._layer.advancedQueryCapabilities&&!1===
c._layer.advancedQueryCapabilities.supportsPagination&&(n=!1,m=!0,k=c._layer.objectIdField);for(var t=[],r=0;r<b.length;r++){var v=new F;v.onStatisticField=null!==b[r].workingexpr?b[r].workingexpr.toWhereClause(e):"";v.outStatisticFieldName=b[r].field;v.statisticType=b[r].toStatisticsName();t.push(v)}""===k&&(k=a.join(","));r=c._maxQueryRate();void 0!==c._layer.maxRecordCount&&c._layer.maxRecordCount<r&&(r=c._layer.maxRecordCount);e=null===l?null===p?"1\x3d1":"":l.toWhereClause(e);c._layer.definitionExpression&&
(e=""!==e?"(("+c._layer.definitionExpression+") AND ("+e+"))":c._layer.definitionExpression);k=new A([],["GETPAGES"],n,{groupbypage:!0,spatialRel:c._makeRelationshipEnum(d),relationParam:c._makeRelationshipParam(d),outFields:["*"],useOIDpagination:m,generatedOid:g,resultRecordCount:r,resultOffset:0,groupByFieldsForStatistics:a,outStatistics:t,geometry:null===p?null:p,where:e,orderByFields:k,returnGeometry:!1,returnIdsOnly:!1,internal:{lastMaxId:-1,set:[],lastRetrieved:0,fullyResolved:!1}});h.resolve(k)},
h),e.errback(h))},h),e.errback(h));return h.promise};b.prototype._getAgregagtePhysicalPage=function(a,b,d){var c=this,l=new n;try{var f=a.pagesDefinition.where;!0===a.pagesDefinition.useOIDpagination&&(f=""!==f?"("+f+") AND ("+a.pagesDefinition.generatedOid+"\x3e"+a.pagesDefinition.internal.lastMaxId.toString()+")":a.pagesDefinition.generatedOid+"\x3e"+a.pagesDefinition.internal.lastMaxId.toString());var g=a.pagesDefinition.internal.lastRetrieved,k=new v;this._requestStandardised&&(k.sqlFormat="standard");
k.where=f;k.spatialRelationship=a.pagesDefinition.spatialRel;k.relationParam=a.pagesDefinition.relationParam;k.outFields=a.pagesDefinition.outFields;k.outStatistics=a.pagesDefinition.outStatistics;k.geometry=a.pagesDefinition.geometry;k.groupByFieldsForStatistics=a.pagesDefinition.groupByFieldsForStatistics;k.num=a.pagesDefinition.resultRecordCount;k.start=a.pagesDefinition.internal.lastRetrieved;k.returnGeometry=a.pagesDefinition.returnGeometry;k.orderByFields=""!==a.pagesDefinition.orderByFields?
a.pagesDefinition.orderByFields.split(","):null;if(this.isTable()&&k.geometry&&k.spatialRelationship)return l.resolve([]),l.promise;this.executeQuery(k,"execute").then(e.callback(function(b){c._checkCancelled(d);if(b.hasOwnProperty("features")){var e=[];if(a.pagesDefinition.internal.lastRetrieved!==g)l.resolve([]);else{for(var f=0;f<b.features.length;f++)void 0===b.features[f].geometry&&(b.features[f].geometry=null),a.pagesDefinition.internal.set[g+f]=b.features[f].attributes[a.pagesDefinition.generatedOid];
for(f=0;f<b.features.length;f++)e.push(new C({attributes:b.features[f].attributes,geometry:null}));!0===a.pagesDefinition.useOIDpagination?0===b.features.length?a.pagesDefinition.internal.fullyResolved=!0:a.pagesDefinition.internal.lastMaxId=b.features[b.features.length-1].attributes[a.pagesDefinition.generatedOid]:b.features.length!==a.pagesDefinition.resultRecordCount&&(a.pagesDefinition.internal.fullyResolved=!0);a.pagesDefinition.internal.lastRetrieved=g+a.pagesDefinition.resultRecordCount;l.resolve(e)}}else l.reject(Error("Unnexected Result querying aggregates from layer"))},
l),e.errback(l))}catch(h){l.reject(h)}return l.promise};b.create=function(a,c,d,e){return new b({url:a,outFields:null===c?["*"]:c,token:null!==d&&""!==d?d:null,spatialReference:e})};b.prototype.canBeBigDataFeatureSet=function(){return!0};b.prototype.shouldBeResolvedAsBigData=function(){return!1};b.prototype.expressAsArcadeScriptImpl=function(a,b,d){this.arcadeAssignNextScriptStepIdentifiers(d);a=this.arcadeAssignNextGlobalIdentifier(d);b[a]={name:a,type:"FeatureLayer",params:{url:this._layer.url,
token:this._layer.token,definitionExpression:this._layer.definitionExpression,fields:this._layer.outFields}};d.featuresetsyms.push(a);return""};return b}(J)});