// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/utils/DomUtil","dojo/_base/lang dojo/dom-attr dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/Deferred dojo/domReady!".split(" "),function(q,p,l,h,m,f,r){function t(){k||(k=h.create("div",{class:"esriGEOffscreen"},document.body));return k}var e={isHidden:function(a){return a&&l.contains(a,"esriGEHidden")},hasVisibleChildren:function(a){if(!a||!a.children.length)return!1;for(var b=0;b<a.children.length;b++)if(!e.isHidden(a.children[b]))return!0;
return!1},hide:function(a){return e.addTag(a,"esriGEHidden")},show:function(a){return e.removeTag(a,"esriGEHidden")},addTag:function(a,b){return e.applyCallback(a,function(a){a&&l.add(a,b)})},removeTag:function(a,b){return e.applyCallback(a,function(a){a&&l.remove(a,b)})},applyCallback:function(a,b,c){c&&(b=q.hitch(c,b));Array.isArray(a)?a.forEach(b):b(a);return a},getChildIndex:function(a,b){if(!a||!a.children||!b)return-1;for(var c=0;c<a.children.length;c++)if(a.children[c]===b)return c;return-1},
getChildren:function(a){if(!a||!a.children)return null;for(var b=[],c=0;c<a.children.length;c++)b.push(a.children[c]);return b},getChildNodes:function(a){if(!a||!a.childNodes)return null;for(var b=[],c=0;c<a.childNodes.length;c++)b.push(a.childNodes[c]);return b},isChildOf:function(a,b,c){var d=!1,g=function(a){if(c&&!c(a))return!1;a.parentNode===b?d=!0:a.parentNode&&g(a.parentNode)};a&&g(a);return d},isNodeInLayout:function(a){return e.isChildOf(a,document.body,function(a){return!e.isHidden(a)&&
"none"!=f.get(a,"display")})},enableContent:function(a,b,c){if(a){c=c||{};var d=a.children.length-1;if(!(0>d)){d=a.children[d];l.contains(d,"esriGEDisabledContent")||(d=null);if(b)d&&a.removeChild(d);else if(d=d||h.create("div",{class:"esriGEDisabledContent"+(c.overlayClass?" "+c.overlayClass:"")},a),!1!==c.fitParent&&(a=m[c.marginBox?"getMarginBox":"getContentBox"](a).h))a=a.toString()+"px",f.set(d,{height:a,marginTop:"-"+a});return d}}},enableContentAbsolute:function(a,b,c){if(a){c=c||{};var d=
f.get(a,"position");"relative"!==d&&"absolute"!==d&&f.set(a,"position","relative");return e.enableContent(a,b,{overlayClass:"esriGEAbsoluteStretched "+(c.overlayClass||"")+(c.isTransparent?" esriGEDisabledContentTransparent ":""),fitParent:!1})}}},k;e.hideNodeInBackground=function(a,b){if(a){if(a._hideNodeInBackgroundUndoController)return a._hideNodeInBackgroundUndoController;var c=h.create("div",null,a,"after"),d=h.create("div",{style:"position: absolute; left: 0px; top: 0px;"},t());h.place(a,d);
b="DomUtil.hideNodeInBackground"+(b?"."+b:"");p.set(c,"_bg_memo_node",b);p.set(d,"_bg_temp_node",b);b={undo:function(){c&&(c.parentNode&&h.place(a,c,"replace"),h.destroy(c),h.destroy(d),k.children.length||(h.destroy(k),k=null),c=null,delete a._hideNodeInBackgroundUndoController)},remove:function(){this.undo()}};return a._hideNodeInBackgroundUndoController=b}};e.showNodeFromBackground=function(a){a&&a._hideNodeInBackgroundUndoController&&a._hideNodeInBackgroundUndoController.undo()};e.position=function(a){function b(a){for(var b=
{x:0,y:0};a.offsetParent;)b.x+=a.offsetLeft,b.y+=a.offsetTop,a=a.offsetParent,b.x+=f.get(a,"borderLeftWidth"),b.y+=f.get(a,"borderTopWidth");return b}function c(a){return f.get(a,"width")+f.get(a,"paddingLeft")+f.get(a,"paddingRight")+f.get(a,"borderLeftWidth")+f.get(a,"borderRightWidth")}function d(a){return f.get(a,"height")+f.get(a,"paddingTop")+f.get(a,"paddingBottom")+f.get(a,"borderTopWidth")+f.get(a,"borderBottomWidth")}if(a){var g;if(a instanceof SVGElement&&a.getBBox)return g=(g=a.ownerSVGElement&&
a.ownerSVGElement.parentNode)&&b(g),a=a.getBBox(),{x:(a.x||0)+g.x,y:(a.y||0)+g.y,w:a.width||0,h:a.height||0};g=b(a);return{x:g.x,y:g.y,w:c(a),h:d(a)}}};e.uniteNodeBoxes=function(a,b){var c=1E6,d=1E6,g=-1E6,f=-1E6;a.forEach(function(a){a=e.position(a);c=Math.min(c,a.x);d=Math.min(d,a.y);g=Math.max(g,a.x+a.w);f=Math.max(f,a.y+a.h)});a={x:c,y:d,w:g-c,h:f-d};b&&(b=e.position(b),a.x-=b.x,a.y-=b.y);return a};e.getNodesBox=function(a){var b=1E6,c=-1E6,d=1E6,g=-1E6;a.forEach(function(a){a=m.position(a);b=
Math.min(b,a.x);d=Math.min(d,a.y);c=Math.max(c,a.x+a.w);g=Math.max(g,a.y+a.h)});return{x:b,y:d,w:c-b,h:g-d}};e.traverseChildren=function(a,b){function c(a){if(a&&a.children)for(var d=0;d<a.children.length;d++){var e=a.children[d];if(b(e))break;c(e)}}c(a)};e.scrollToListNode=function(a,b,c){var d=b.offsetTop+b.clientHeight,e=d-(a.scrollTop+a.clientHeight);0<e&&(a.scrollTop+=e);c&&(d-=b.clientHeight-c.offsetTop,e=a.scrollTop-d,0<e&&(a.scrollTop-=e))};var n;e.getScrollbarSize=function(){if(!n){var a=
h.create("div",null,document.body);a.style.width="100px";a.style.height="100px";a.style.overflow="scroll";a.style.position="absolute";a.style.top="9999px";n={w:a.offsetWidth-a.clientWidth,h:a.offsetHeight-a.clientHeight};h.destroy(a)}return n};e.hasScrollbars=function(a){var b=f.getComputedStyle(a);return{w:"scroll"===b.overflowX||a.offsetWidth>a.clientWidth&&"auto"===b.overflowX,h:"scroll"===b.overflowY||a.offsetHeight>a.clientHeight&&"auto"===b.overflowY}};e.getMeasureContext=function(a){a=a||{};
a.style=a.style?a.style+" ":"";a.style+="display: inline-block; position: absolute; left: 0; top: 0;";return{div:h.create("div",a,document.body),measureText:function(a){this.div.innerHTML=a;a=m.getMarginBox(this.div);delete a.l;delete a.t;return a},destroy:function(){h.destroy(this.div)}}};e.getTextBox=function(a,b){b=e.getMeasureContext(b);a=b.measureText(a);b.destroy();return a};e.stealFocus=function(){var a=new r;try{var b=h.create("input",{type:"text",style:"position: absolute; left: 0px; top: 0px;"});
h.place(b,document.body);b.select();h.destroy(b)}catch(c){}setTimeout(a.resolve,0);return a.promise};e.getWindowBox=function(){for(var a=[],b=0,c=document.body.children.length;b<c;b++){var d=document.body.children[b];e.isHidden(d)||(e.hide(d),a.push(d))}b={w:document.body.clientWidth,h:document.body.clientHeight};a.forEach(function(a){e.show(a)});return b};return e});