// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/utils/TooltipUtil","dojo/dom-class dojo/dom-geometry dojo/on dojo/mouse dojo/sniff dijit/Tooltip ./DeviceUtil ./DnDUtil ./DomUtil ./MouseUtil dojo/domReady!".split(" "),function(p,k,g,q,n,l,r,u,v,t){var c={};l.show("",document.body);l.hide(document.body);var b=dijit.byId("dijit__MasterTooltip_0");b.addCustomClasses=function(a){b.removeCustomClasses();a&&(p.add(b.domNode,a),b._customClasses=a)};b.removeCustomClasses=function(){b._customClasses&&p.remove(b.domNode,b._customClasses);
delete b._customClasses};b.orient=function(a,c,e,f,h){b.connectorNode.style.top="";var g=f.h;f=f.w;a.className="dijitTooltip "+{"MR-ML":"dijitTooltipRight","ML-MR":"dijitTooltipLeft","TM-BM":"dijitTooltipAbove","BM-TM":"dijitTooltipBelow","BL-TL":"dijitTooltipBelow dijitTooltipABLeft","TL-BL":"dijitTooltipAbove dijitTooltipABLeft","BR-TR":"dijitTooltipBelow dijitTooltipABRight","TR-BR":"dijitTooltipAbove dijitTooltipABRight","BR-BL":"dijitTooltipRight","BL-BR":"dijitTooltipLeft"}[c+"-"+e];b.addCustomClasses(b._customClasses);
b.domNode.style.width="auto";var d=k.position(b.domNode);if(n("ie")||n("trident"))d.w+=2;k.setMarginBox(b.domNode,{w:Math.min(Math.max(f,1),d.w)});"B"==e.charAt(0)&&"B"==c.charAt(0)?(a=k.position(a),c=b.connectorNode.offsetHeight,a.h>g?(b.connectorNode.style.top=g-(h.h+c>>1)+"px",b.connectorNode.style.bottom=""):(b.connectorNode.style.bottom=Math.min(Math.max(h.h/2-c/2,0),a.h-c)+"px",b.connectorNode.style.top="")):(b.connectorNode.style.top="",b.connectorNode.style.bottom="");return Math.max(0,d.w-
f)};c.hideTooltipForNode=function(a){a&&(c._tooltipCleanUp(a),p.remove(a,"esriMapsAnalystSimpleTextTooltip"),l.hide(a))};c._tooltipCleanUp=function(a){a.__setTooltipToNodeMouseLeaveHandle&&a.__setTooltipToNodeMouseLeaveHandle.remove();clearInterval(a.__setTooltipToNodeInLayoutHandle);clearInterval(a.__setTooltipToNodeMouseOverHandle);a.__setTooltipToNodeClickHandle&&a.__setTooltipToNodeClickHandle.remove();a.__setTooltipToNodeMouseLeaveMasterHandle&&a.__setTooltipToNodeMouseLeaveMasterHandle.remove()};
c.setTooltipToNode=function(a,d,e){function f(){function f(){b.addCustomClasses(h);l.show(n,a,e.position||["after","before"])}c._tooltipCleanUp(a);if(!k){var n="function"==typeof d?d():d;if(n){p.add(a,"esriMapsAnalystSimpleTextTooltip");f();var m=c.hideTooltipForNode.bind(c,a);r.isMobileDevice()?a.__setTooltipToNodeMouseLeaveHandle=g(document.body,"touchstart",function(b){t.isMouseOver(a,{event:b})||m()}):a.__setTooltipToNodeMouseLeaveHandle=g.once(a,q.leave,function(){!e.stayOnHover&&m()});e.ignoreNodeRemoval||
(a.__setTooltipToNodeInLayoutHandle=setInterval(function(){!v.isNodeInLayout(a)&&m()},300));r.isMobileDevice()||(a.__setTooltipToNodeMouseOverHandle=setInterval(function(){e.stayOnHover&&t.isMouseOver(b.domNode)||t.isMouseOver(a)||m()},300),a.__setTooltipToNodeClickHandle=g(a,"click",function(a){a.stopPropagation();e.hideOnClick?m():f()}),e.stayOnHover&&(a.__setTooltipToNodeMouseLeaveMasterHandle=g(b.domNode,q.leave,m)))}}}if(a){e=e||{};var h=Array.isArray(e.classes)?e.classes.join(" "):e.classes,
h=(h||"")+" esriGETooltip";e.isComplexTooltip&&(h+=" esriGETooltipComplex");a.__setTooltipToNodeClasses=h;c.hideTooltipForNode(a);delete a.title;a.__setTooltipToNodeMouseEnterHandle&&a.__setTooltipToNodeMouseEnterHandle.remove();if(d){var k=!1;r.isMobileDevice()?a.__setTooltipToNodeMouseEnterHandle=u.addNoDragClickHandler(a,f):a.__setTooltipToNodeMouseEnterHandle=g(a,q.enter,f);return{remove:function(){d=null;c.hideTooltipForNode(a)},suspend:function(){c.hideTooltipForNode(a);k=!0},resume:function(){k=
!1}}}}};var d=null;c.autoTooltip=function(a){g(a,".TrimWithEllipses:mouseover",function(){this!==d&&this.offsetWidth<this.scrollWidth&&(d=this,l.show(d.textContent,d,["above","below"]),g.once(d,"mouseout, mousedown, touchstart",function(){l.hide(d);d=null}))})};return c});