// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/_ChartComparisonSupport","dojo/_base/declare ../comparison/ComparisonSelect ./utils/ChartTypes ../../dataProvider/supportClasses/ge/LocalGEChart ./dummyData/DummyGE esri/dijit/geoenrichment/utils/DomUtil dojo/i18n!esri/nls/jsapi".split(" "),function(g,h,f,k,l,d,b){b=b.geoenrichment.dijit.ReportPlayer.ChartContainer;return g(null,{comparisonSelect:null,_comparisonValue:null,_additionalFeatures:null,_ge:null,_stdPolygonsController:null,_initChartComparisonSelect:function(){var a=
this;this._additionalFeatures=[];d.hide(this.comparisonSelectBlock);if(this._currentComparisonInfo){this._updateComparisonLabel();var m=this._getGeoenrichment().getData().features;this.comparisonSelect=(new h({fields:this._getGeoenrichment().getAttributeFields(),canAddFeatures:this._canAddRemoveFeatures(),addFeatureMessage:b.addToChart,featureIsAlreadyAddedMessage:b.alreadyAdded,canRemoveFeatures:this._canAddRemoveFeatures(),removeFeatureMessage:b.removeFromChart,onFeatureSelected:function(e,c){a._setComparisonId(c)},
isFeatureAdded:function(e,c){return a._comparisonValue===c||-1!==a._additionalFeatures.indexOf(c)},canRemoveFeature:function(e,c){return a._comparisonValue!==c},onAddFeature:function(e,c){a._additionalFeatures.push(c);a._updateSeries();a._syncWithShownFeatures()},onRemoveFeature:function(e,c){a._additionalFeatures.splice(a._additionalFeatures.indexOf(c),1);a._updateSeries();a._syncWithShownFeatures()}})).placeAt(this.comparisonSelectDiv);this.own(this.comparisonSelect);this.comparisonSelect.setFeatures(m);
this._comparisonValue=this.comparisonSelect.setDefaultValue();this.comparisonSelect.get("options").length?(d.show(this.comparisonSelectBlock),d.enableContent(this.comparisonSelectBlock,!!this.viewModel.dynamicReportInfo),this.viewModel.dynamicReportInfo&&(this._stdPolygonsController=this.viewModel.getStdPolygonsController(this._currentComparisonInfo.calculatorName,this.currentFeatureIndex),this.own(this._stdPolygonsController),this._syncWithShownFeatures())):(this.comparisonSelect.destroy(),this._currentComparisonInfo=
null)}},_canAddRemoveFeatures:function(){return this._isMultiFeatureChart&&!f.isLineLike(this._currentChartType)},_updateComparisonLabel:function(){if(this._currentComparisonInfo){var a;a=this._canAddRemoveFeatures()?b.selectOrAddGeographyToCompare:this._isTableView?b.compareWith:f.isColumnBarLike(this._getComparisonChartType())?b.comparisonLabelBars:b.comparisonLabelDots;this.comparisonLabel.innerHTML=a;this.comparisonLabel.style.color=this.viewModel.getDocumentDefaultStyles(this.theme).color}},
_allAttributesCache:null,_syncWithShownFeatures:function(){if(this._stdPolygonsController){this._stdPolygonsController.setAttributeFields(this._getGeoenrichment().getAttributeFields());var a=this._getGeoenrichment().getAllGeographyAttributes({ignoreFilters:!0});this._allAttributesCache||(this._allAttributesCache={},a.forEach(function(a){this._allAttributesCache[a.StdGeographyID]=a},this));var b=this._getComparisonFeatureIds().map(function(a){return this._allAttributesCache[a]},this);this._stdPolygonsController.setShownFeatureAttributes(b);
this._stdPolygonsController.setAllFeatureAttributes(a)}},_createDummyGE:function(){return l.getInstance()},_getComparisonChartType:function(){return this._currentComparisonInfo&&this._currentComparisonInfo.chartType||this._currentChartType},_getGeoenrichment:function(){return this._currentComparisonInfo?this._ge?this._ge:this._ge=this.viewModel.dynamicReportInfo?new k(this._originalSeriesItems,this._currentComparisonInfo.calculatorName,this.viewModel.dynamicReportInfo.fieldData.areaData,this._isMultiFeatureChart,
this.viewModel.dynamicReportInfo.analysisAreas.map(function(a){return a.shortName||a.name}),this.currentFeatureIndex):this._createDummyGE():null},_setComparisonId:function(a){this._comparisonValue=a;this.comparisonSelect.get("options").length?this.comparisonSelect.get("value")!==this._comparisonValue&&this.comparisonSelect.set("value",this._comparisonValue):this._comparisonValue=null;this._updateSeries();this._syncWithShownFeatures()},_setFilterRangesForComparison:function(a){if(!this._currentComparisonInfo)return!1;
this._getGeoenrichment().setFilterRanges(a);a=this._getGeoenrichment().getData().features;this.comparisonSelect.setFeatures(a);this._setComparisonId(this.comparisonSelect.setDefaultValue());d[this.comparisonSelect.get("options").length?"show":"hide"](this.comparisonSelectBlock);return!0},_getComparisonFeatureIds:function(){if(!this._currentComparisonInfo)return null;var a={};this._getGeoenrichment().getData().features.forEach(function(b){a[b.attributes.StdGeographyID]=!0});var b=this._additionalFeatures.filter(function(b){return a[b]}).slice();
this._comparisonValue&&-1===b.indexOf(this._comparisonValue)&&b.push(this._comparisonValue);return b}})});