// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/comparison/ComparisonSelect","dojo/_base/declare dojo/on dojo/dom-class dojo/dom-construct esri/dijit/geoenrichment/OnDemandSelect ../../dataProvider/supportClasses/AreasInfoTemplateBuilder ./ComparisonListUtil esri/dijit/geoenrichment/utils/DeviceUtil esri/dijit/geoenrichment/utils/TooltipUtil".split(" "),function(g,h,k,e,l,n,c,m,d){var p=g(l.itemRenderers.DefaultItemRenderer,{createLabelNode:!0,fields:null,addFeatureMessage:null,featureIsAlreadyAddedMessage:null,
removeFeatureMessage:null,canAddFeatures:!1,canRemoveFeatures:!1,_createImageNode:function(b,a){var f=this;if(b.isArea){if(this.fields&&!m.isMobileDevice()){var c=e.create("div",{"class":"esriGESpaceBeforeBig dijitInline esriGEComparisonSelect_infoIcon"},a);d.setTooltipToNode(c,function(){return f._buildGeographyTooltip(b)},{isComplexTooltip:!0})}this.canRemoveFeatures&&(c=e.create("div",{"class":"esriGESpaceBeforeBig dijitInline esriGEComparisonSelect_removeButton"},a),this.isAdded(b)&&this.canRemoveFeature(b)?
(h(c,"click",function(a){a.stopPropagation();f.onRemoveFeature(b)}),d.setTooltipToNode(c,this.removeFeatureMessage)):k.add(c,"disabled"));this.canAddFeatures&&(a=e.create("div",{"class":"esriGESpaceBeforeBig dijitInline esriGEComparisonSelect_addButton"},a),this.isAdded(b)?(k.add(a,"disabled"),d.setTooltipToNode(a,this.featureIsAlreadyAddedMessage)):(h(a,"click",function(a){a.stopPropagation();f.onAddFeature(b)}),d.setTooltipToNode(a,this.addFeatureMessage)))}},_buildGeographyTooltip:function(b){var a=
this.fields.map(function(a){return{label:a.label,value:a.formatFunction(b.attributes[a.name])}});return n.buildAttributesTable(null,a,{padding:10,maxHeight:document.body.clientHeight-40})},isAdded:function(b){},onAddFeature:function(b){},canRemoveFeature:function(b){},onRemoveFeature:function(b){}});return g(l,{listClass:"esriGEOnDemandSelectSpacedOut esriGEOnDemandSelectVeryTallList600",fields:null,addFeatureMessage:null,featureIsAlreadyAddedMessage:null,removeFeatureMessage:null,canAddFeatures:!1,
canRemoveFeatures:!1,showTitleForSingleGroup:!1,buildRendering:function(){var b=this;m.isMobileDevice()&&(this.listClass+=" esriGEComparisonSelectListMobile");var a=new p;a.fields=this.fields;a.addFeatureMessage=this.addFeatureMessage;a.featureIsAlreadyAddedMessage=this.featureIsAlreadyAddedMessage;a.canAddFeatures=this.canAddFeatures;a.isAdded=function(a){return b.isFeatureAdded(a.levelId,a.value)};a.onAddFeature=function(a){b.closePopup();b.onAddFeature(a.levelId,a.value)};a.canRemoveFeatures=this.canRemoveFeatures;
a.removeFeatureMessage=this.removeFeatureMessage;a.canRemoveFeature=function(a){return b.canRemoveFeature(a.levelId,a.value)};a.onRemoveFeature=function(a){b.closePopup();b.onRemoveFeature(a.levelId,a.value)};this.itemRenderer=a;this.inherited(arguments)},setGroups:function(b){this.set("options",c.getOptionsFromGroups(b,{hideTitleForSingleGroup:!this.showTitleForSingleGroup}))},setFeatures:function(b){this.set("options",c.getListOptionsFromFeatures(b))},setDefaultValue:function(b){var a=c.getDefaultOptionValue(this.options);
this.set("value",a);if(b&&b.emitEvent)this.onChange();return a},isFeatureAdded:function(b,a){return!1},canRemoveFeature:function(b,a){return!0},onChange:function(){var b=this.getSelectedItem();b&&this.onFeatureSelected(b.levelId,b.value)},getFeatureIndexById:function(b){return c.getFeatureIndexInOptionsById(this.options,b)},selectFeatureByIndex:function(b){b=c.getOptionValueByFeatureIndex(this.options,b||0);this.set("value",b);return b},getNumFeatures:function(){return c.getNumFeaturesFromOptions(this.options)},
getSelectedAttributes:function(){var b=this.getSelectedItem();return b&&b.attributes},onFeatureSelected:function(b,a){},onAddFeature:function(b,a){},onRemoveFeature:function(b,a){}})});