// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/analysis/customgp/editors/SelectFeatureSetFromLayer.html":'\x3cdiv class\x3d"esriAnalysis"\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"inputNode" class\x3d"fullSpread"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"layerChooseNode" class\x3d"left ${cssClass.layerChooseCtr}"\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv class\x3d"left" style\x3d"width:30%;min-width:40px"\x3e\r\n      \x3cspan data-dojo-attach-point\x3d"selectBtnNode"\x3e\x3c/span\x3e\r\n      \x3cspan data-dojo-attach-point\x3d"drawBtnNode"\x3e\x3c/span\x3e\r\n    \x3c/div\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"featuresetNode"\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/analysis/customgp/editors/SelectFeatureSetFromLayer","dojo/_base/declare dojo/Deferred dojo/Evented dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/on dijit/_TemplatedMixin ../BaseEditor ../common/dijit/DrawLayer dijit/form/Select dijit/form/ToggleButton dojo/text!./SelectFeatureSetFromLayer.html esri/dijit/analysis/utils esri/tasks/query esri/toolbars/draw esri/layers/FeatureLayer esri/graphic esri/symbols/PictureMarkerSymbol esri/symbols/jsonUtils ../../AnalysisRegistry".split(" "),
function(m,y,n,d,e,k,l,p,q,r,t,z,u,f,A,g,v,w,B,h,x){return m([q,p,n],{templateString:u,editorName:"SelectFeatureSetFromLayer",cssClass:{featureSetSelect:"fullSpread esriAnalysisSelect",layerChooseCtr:"layerChooseCtr"},constructor:function(a){this.inherited(arguments);a.cssClass&&d.mixin(this.cssClass,a.cssClass)},postCreate:function(){this.inherited(arguments);this._analysisSelect=this.spatialFilterByFeatures=new t({"class":this.cssClass.featureSetSelect});this.analysisLayers=this.config.analysisLayers;
this.param&&this.param.defaultValue&&this.param.defaultValue.geometryType&&(this.analysisLayers=e.filter(this.analysisLayers,function(a){return this.param.defaultValue&&this.param.defaultValue.geometryType===a.geometryType},this));this.analysisLayer||(this.analysisLayer=this.analysisLayers[0]);f.populateAnalysisLayers(this,"analysisLayer","analysisLayers",{posIncrement:1});this.showBrowseLayers=this.widget?this.widget.showBrowseLayers:!0;this.showReadyToUseLayers=this.widget?this.widget.showReadyToUseLayers:
!0;this.portalUrl=this.config.portalUrl;this.showGeoAnalyticsParams=this.config.showGeoAnalyticsParams;f.addReadyToUseLayerOption(this,[this._analysisSelect]);this.own(l(this.spatialFilterByFeatures,"change",d.hitch(this,this._onLayerChanged)));this.spatialFilterByFeatures.placeAt(this.layerChooseNode);var a;if(this.showDrawOption=void 0===this.config.showDrawOption?!0:this.config.showDrawOption)a=(a=this.param.defaultValue.geometryType&&this.param.defaultValue.geometryType.toLowerCase())&&(-1!==
a.indexOf("polygon")?"polygon":-1!==a.indexOf("point")?"point":"polyline"),this._drawBtn=new r({types:a||["polygon","point","polyline"],selectBtnNode:this.selectBtnNode,drawBtnNode:this.drawBtnNode}),l(this._drawBtn,"change",d.hitch(this,this._handleDrawBtnChange)),this._type=a,this._updateDrawnLayerName(),this._initDefaultSymbols();this.on("add-ready-to-use-layer",d.hitch(this,function(a){this.widget&&this.widget.emit("add-ready-to-use-layer",a)}))},_updateDrawnLayerName:function(){var a=[],b=this.widget&&
this.widget.drawLayer;b&&0<b.length&&(a=e.filter(b,function(a){return a.geometryType&&-1!==a.geometryType.toLowerCase().indexOf(this._type)},this));a=0===a.length?"":"_"+a.length;"point"===this._type?this.set("drawnLayerName",this.widget&&this.widget.drawPointLayerName?this.widget.drawPointLayerName:this.nls.drawnPointLayer):"polyline"===this._type?this.set("drawnLayerName",this.widget&&this.widget.drawLineLayerName?this.widget.drawLineLayerName:this.nls.drawnPolylineLayer):"polygon"===this._type?
this.set("drawnLayerName",this.widget&&this.widget.drawPolyLayerName?this.widget.drawPolyLayerName:this.nls.drawnPolygonLayer):this.set("drawnLayerName",this.widget&&this.widget.drawnLayerName?this.widget.drawnLayerName:this.nls.drawnLayerName);""!==a&&this._type&&this.set("drawnLayerName",this.get("drawnLayerName")+a)},_handleDrawBtnChange:function(a,b){this._type!=b&&(this._featureLayer=null,this._type=b);a?(this.emit("drawtool-activate",{}),this._featureLayer||this._createFeatColl(),this._drawtoolbar.activate("point"===
this._type?g.POINT:"polyline"===this._type?g.FREEHAND_POLYLINE:g.POLYGON)):this._drawtoolbar.deactivate()},_onLayerChanged:function(a){var b;"browse"===a?(a=this._browsedlg.browseItems.get("query"),this.param&&this.param.defaultValue&&this.param.defaultValue.geometryType&&(b=this.param.defaultValue.geometryType.toLowerCase(),b=-1!==b.indexOf("point")?"point":-1!==b.indexOf("polygon")?"polygon":"line",a.custom=['tags:"'+b+'"'],this._browsedlg.browseItems.set("query",a)),this._browsedlg.show()):"browselayers"===
a?(this.showGeoAnalyticsParams&&(a=this._browseLyrsdlg.browseItems.get("query"),a.types.push('type:"Big Data File Share"'),this._browseLyrsdlg.browseItems.set("query",a)),this.param&&this.param.defaultValue&&this.param.defaultValue.geometryType&&(this._browseLyrsdlg.browseItems.plugIn.geometryTypes=[this.param.defaultValue.geometryType]),this._browseLyrsdlg.show()):(this.analysisLayer=this.analysisLayers[a-1],this.emit("analysislayer-change",{analysisLayer:this.analysisLayer}))},_handleBrowseItemsSelect:function(a){a&&
a.selection&&f.addAnalysisReadyLayer({item:a.selection,layers:this.analysisLayers,layersSelect:this._analysisSelect,browseDialog:a.dialog||this._browsedlg,posIncrement:1,widget:this})},_createFeatColl:function(){this._updateDrawnLayerName();this._initDefaultSymbols();var a=this.createFeatureCollection(this.drawnLayerName);this._featureLayer=new v(a,{id:this.drawnLayerName});this.map.addLayer(this._featureLayer);k.connect(this._featureLayer,"onClick",d.hitch(this,function(a){this.map.infoWindow.setFeatures([a.graphic])}));
this.widget&&this.widget.set("drawLayer",this._featureLayer)},createFeatureCollection:function(a){var b,c=x.GeometryTypes[this._type.charAt(0).toUpperCase()+this._type.substr(1)];b={layerDefinition:null,featureSet:{features:[],geometryType:this.param.defaultValue.geometryType||c}};b.layerDefinition={objectIdField:"OBJECTID",templates:[],type:"Feature Layer",drawingInfo:{},name:a,hasAttachments:!1,capabilities:"Query",types:[],geometryType:this.param.defaultValue.geometryType||c,fields:this.param.defaultValue.fields||
[]};return b},_getRandomColor:function(){return[Math.floor(256*Math.random()),Math.floor(256*Math.random()),Math.floor(256*Math.random()),Math.floor(256*Math.random())]},_initDefaultSymbols:function(){var a=this.drawnLayerName&&-1!==this.drawnLayerName.search(/_[0-9]$/),b={style:"esriSMSCircle",color:a?this._getRandomColor():[0,0,128,128],name:"Circle",outline:{color:a?this._getRandomColor():[0,0,128,255],width:1},type:"esriSMS",size:18},c={style:"esriSLSSolid",color:a?this._getRandomColor():[79,
129,189,255],width:3,name:"Blue 1",type:"esriSLS"},a={style:"esriSFSSolid",color:a?this._getRandomColor():[79,129,189,128],type:"esriSFS",outline:{style:"esriSLSSolid",color:a?this._getRandomColor():[54,93,141,255],width:1.5,type:"esriSLS"}};this.pointSymbol=h.fromJson(b);this.polylineSymbol=h.fromJson(c);this.polygonSymbol=h.fromJson(a)},_createGraphic:function(a){var b=a.type,c=null,c="point"===b||"multipoint"===b?this.pointSymbol:"line"===b||"polyline"===b?this.polylineSymbol:this.polygonSymbol;
return new w(a,c)},_addFeatures:function(a){a=this._createGraphic(a);var b=[];this.map.graphics.add(a);b.push(a);this._featureLayer.applyEdits(b,null,null);if(0===this.analysisLayers.length||this.analysisLayers[this.analysisLayers.length-1]!==this._featureLayer)a=this.analysisLayers.push(this._featureLayer),b=this._analysisSelect.getOptions(),this._analysisSelect.removeOption(b),b=e.map(b,function(a){a.selected=!1;return a}),b.push({value:a,label:this._featureLayer.name,selected:!0}),this._analysisSelect.addOption(b),
this._onLayerChanged(a);this._drawBtn.set("checked",!1)},clear:function(){this._featureLayer&&(this.map.removeLayer(this._featureLayer),e.forEach(this.analysisLayers,function(a,b){a===this._featureLayer&&(this._analysisSelect.removeOption({value:b+1,label:this._featureLayer.name}),this.analysisLayers.splice(b,1))},this));this._handleDrawBtnChange(!1)},_setDrawnLayerNameAttr:function(a){this.drawnLayerName=a},_getDrawnLayerNameAttr:function(){return this._featureLayer?this._featureLayer.name:this.drawnLayerName},
_getDrawLayerAttr:function(){return this._featureLayer},getGPValue:function(){var a=this.analysisLayers[this._analysisSelect.get("value")-1];return this.wrapValueToDeferred(f.constructAnalysisInputLyrObj(a,!0))},_setMapAttr:function(a){this.map=a;this._drawtoolbar=new g(this.map);k.connect(this._drawtoolbar,"onDrawEnd",d.hitch(this,this._addFeatures))},_setAnalysisLayerAttr:function(a){this._set("analysisLayer",a)},_getAnalysisLayerAttr:function(){return this.analysisLayers[this._analysisSelect.get("value")-
1]}})});