// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/analysis/_AnalysisOptions","dojo/_base/declare dojo/_base/lang dojo/dom-attr dojo/_base/json dojo/dom-class dojo/dom-construct dojo/dom-style dojo/aspect dojo/has dojo/_base/array dojo/_base/window dojo/on dojo/query dojo/number ./Settings ./SettingsViewModel ./utils ./BrowseLayerMixin dijit/Dialog dijit/form/NumberTextBox dojo/i18n!../../nls/jsapi ../../lang ../../kernel".split(" "),function(h,c,l,m,q,r,f,n,u,v,w,t,x,y,z,A,b,B,C,D,k,g,E){h=h([B],{declaredClass:"esri.dijit.analysis._AnalysisOptions",
showSelectFolder:!1,showChooseExtent:!0,showHelp:!0,showCredits:!0,returnFeatureCollection:!1,showCloseIcon:!0,showSelectAnalysisLayer:!0,map:null,showReadyToUseLayers:!0,showAnalysisBusyIndicator:!0,showGeoAnalyticsParams:!1,showBrowseLayers:!1,showAnalysisModeLabel:!1,distanceDefaultUnits:"Miles",showSettings:!1,showOutputType:!1,context:{},includeRouteLayers:!1,doSaveJobInfo:!1,doSaveInStorage:!1,showCreditCalcBusyIndicator:!0,useArcGISComponents:!1,constructor:function(a){a.rerun&&this._initRerunProps(a)},
isAdmin:function(a){return g.isDefined(a.role)&&("org_admin"===a.role||"account_admin"===a.role)},isOwner:function(a,b){return a.owner?a.owner===b.id:a.userId?a.userId===b.username:a.credential?a.credential.userId===b.username:!0},_initRerunProps:function(a){a.OutputName&&a.OutputName.serviceProperties?a.outputLayerName=a.OutputName.serviceProperties.name:a.resultName&&(a.outputLayerName=a.resultName);a.timeStepReference&&(a.timeReference=a.timeStepReference);this.set("extentCheck",a.extentCheck);
this._numberFormatHandle=n.before(D,"_setValueAttr",function(a,b,d){a=y.format(a);return[a,b,d]});this.on("close",c.hitch(this,function(){this._numberFormatHandle&&(this._numberFormatHandle.remove(),this._numberFormatHandle=null)}))},_setShowSelectFolderAttr:function(a){!0===a&&a===this.get("returnFeatureCollection")&&(a=!a);this.showSelectFolder=a;this._webMapFolderSelect&&this._webMapFolderSelect.set("required",a);this._chooseFolderRow&&f.set(this._chooseFolderRow,"display",!0===this.showSelectFolder?
"block":"none");a&&this._webMapFolderSelect&&this.getFolderStore().then(c.hitch(this,function(a){this.folderStore=a;b.setupFoldersUI({folderStore:this.folderStore,folderId:this.folderId,folderName:this.folderName,folderSelect:this._webMapFolderSelect,username:this.portalUser?this.portalUser.username:""})}))},_getShowSelectFolderAttr:function(){return this.showSelectFolder},_setShowChooseExtentAttr:function(a){this.showChooseExtent=a},_getShowChooseExtentAttr:function(){return this.showChooseExtent},
_setExtentCheckAttr:function(a){this.extentCheck=a;g.isDefined(this._useExtentCheck)&&g.isDefined(a)&&this._useExtentCheck.set("checked",a)},_setMapAttr:function(a){this.map=a},_getMapAttr:function(){return this.map},_setShowHelpAttr:function(a){this.showHelp=a},_getShowHelpAttr:function(){return this.showHelp},_setReturnFeatureCollectionAttr:function(a){this.returnFeatureCollection=a;this.set("showSelectFolder",!a)},_getReturnFeatureCollectionAttr:function(){return this.returnFeatureCollection},
_setShowCreditsAttr:function(a){(this.showCredits=a)&&this._showCreditsLink&&this._usageForm&&(this._onCreditsClickHandle=t.pausable(this._showCreditsLink,"click",c.hitch(this,this._handleShowCreditsClick)))},_getShowCreditsAttr:function(){return this.showCredits},_setShowCloseIconAttr:function(a){this.showCloseIcon=a},_getShowCloseIconAttr:function(){return this.showCloseIcon},_setShowSelectAnalysisLayerAttr:function(a){this.showSelectAnalysisLayer=a;this._analysisSelect&&this._analysisSelect.set("required",
a)},_getShowSelectAnalysisLayerAttr:function(){return this.showSelectAnalysisLayer},_setIsSingleTenantAttr:function(a){this.isSingleTenant=a},_getIsSingleTenantAttr:function(){return this.isSingleTenant},_setAllowChooseLabelAttr:function(a){this.allowChooseLabel=a},_getAllowChooseLabelAttr:function(){return this.allowChooseLabel},_setTitleAttr:function(a){this.title=a;this._toolTitle&&l.set(this._toolTitle,"innerHTML",a)},_getTitleAttr:function(){return this.title=l.get(this._toolTitle,"innerHTML")},
_setShowReadyToUseLayersAttr:function(a){this.showReadyToUseLayers=a},_getShowReadyToUseLayersAttr:function(a){return this.showReadyToUseLayers},_setFolderIdAttr:function(a){this.folderId=a},_getFolderIdAttr:function(){this._webMapFolderSelect&&this.folderStore&&(this.folderId=this._webMapFolderSelect.item?this.folderStore.getValue(this._webMapFolderSelect.item,"id"):"");return this.folderId},_setFolderNameAttr:function(a){this.folderName=a},_getFolderNameAttr:function(){this._webMapFolderSelect&&
this.folderStore&&this._webMapFolderSelect.item&&(this.folderName=this.folderStore.getValue(this._webMapFolderSelect.item,"name"));return this.folderName},_setHelperServicesAttr:function(a){this.helperServices=a},_getHelperServicesAttr:function(a){return this.helperServices},_getPortalSelfAttr:function(){return this.portalSelf},_setPortalSelfAttr:function(a){this.portalSelf=a},_setShowAnalysisBusyIndicatorAttr:function(a){a&&this.own(this.on("start",c.hitch(this,function(){this.showLoadingIndicator()})),
this.on("job-fail, job-result, job-cancel",c.hitch(this,function(){this.hideLoadingIndicator()})),this.on("job-status",c.hitch(this,function(a){"esriJobFailed"===a.jobStatus&&this.hideLoadingIndicator()})))},_setShowGeoAnalyticsParamsAttr:function(a){this.showGeoAnalyticsParams=a},_getShowGeoAnalyticsParamsAttr:function(){return this.showGeoAnalyticsParams},_setShowBrowseLayersAttr:function(a){this.showBrowseLayers=a},_getShowBrowseLayersAttr:function(){return this.showBrowseLayers},showLoadingIndicator:function(){this.get("showAnalysisBusyIndicator")&&
(this._saveBtn.set("iconClass","esriLoading"),this.set("disableRunAnalysis",!0))},hideLoadingIndicator:function(){this.get("showAnalysisBusyIndicator")&&(this._saveBtn.set("iconClass",""),this.set("disableRunAnalysis",!1))},_setDistanceDefaultUnitsAttr:function(a){this.distanceDefaultUnits=a},_getDistanceDefaultUnitsAttr:function(){return this.distanceDefaultUnits},_setAnalysisModeAttr:function(a){this.analysisMode=a},_setShowAnalysisModeLabelAttr:function(a){this.showAnalysisModeLabel=a;this._titleLbl&&
this._analysisModeLblNode&&(f.set(this._titleLbl,"display",this.showAnalysisModeLabel?"none":"block"),f.set(this._analysisModeLblNode,"display",this.showAnalysisModeLabel?"flex":"none"),this.showAnalysisModeLabel&&("standard"===this.analysisMode?this.analysisModeLabel=this.i18n.standard:"bigdata"===this.analysisMode||this.showGeoAnalyticsParams?this.analysisModeLabel=this.i18n.bigData:"raster"===this.analysisMode&&(this.analysisModeLabel=this.i18n.raster),l.set(this._analysisModeCrumb,"innerHTML",
this.analysisModeLabel)))},_getTimeReferenceAttr:function(){if(this._timeRefDay){var a,b,c="",d="",p="";a=this._timeRefDay.get("value");b=this._timeRefTime.get("value");a&&(c=a.toDateString(),p="Date");b&&(d=b.toTimeString(),p="DateTime");this.set("timeReferenceType",p);a=d&&-1!==d.indexOf("GMT")?c+" "+d.substring(0,d.indexOf("GMT")+3):d?c+" "+d.split(" ")[0]+" GMT":c+" GMT";this.timeReference=(new Date(a)).getTime()}return this.timeReference},_setTimeReferenceAttr:function(a){a=new Date(a+6E4*(new Date(a)).getTimezoneOffset());
this._timeRefDay&&this._timeRefDay.set("value",a);this._timeRefTime&&"DateTime"===this.timeReferenceType&&this._timeRefTime.set("value",a)},_setTimeReferenceTypeAttr:function(a){this.timeReferenceType=a},_setSLayersAttr:function(a){this.sLayers=a},_setContextAttr:function(a){this.context=a},_setIncludeRouteLayersAttr:function(a){this.includeRouteLayers=a},_getIncludeRouteLayersAttr:function(){return this.includeRouteLayers},_setShowSettingsAttr:function(a){this.showSettings=a;var F=this.analysisMode&&
("raster"===this.analysisMode||"bigdata"===this.analysisMode);if(a){if(!b.settingsDlg){a=w.doc.createDocumentFragment();a=r.create("div",{style:"width:200px;height:200px;"},a);var e=v.filter(this.sLayers,function(a){return a.type?"Table"!==a.type:!0});b.settingsVM=new A({showHelp:!0,showCloseIcon:!1,showOverwriteResultOption:!1,showCloseAnalysisOption:!0,showStoreAnalysisOption:!0,showCoordinateSystems:this.analysisMode&&("raster"===this.analysisMode||"bigdata"===this.analysisMode),showProcessSR:this.analysisMode&&
"bigdata"===this.analysisMode,showOutSR:this.analysisMode&&"raster"===this.analysisMode,showExtent:!0,showRasterSettings:this.analysisMode&&"raster"===this.analysisMode,showGeoAnalyticsSettings:this.analysisMode&&"bigdata"===this.analysisMode,showHeader:!1,layers:e,showJobsHistory:!1,jobsHistoryItem:null});this.signInPromise.then(c.hitch(this,function(){b.settingsVM.set("portalUrl",this.portalUrl)}));b.settings=new z({viewModel:b.settingsVM},a);this.i18n||(this.i18n={},c.mixin(this.i18n,k.common),
c.mixin(this.i18n,k.analysisTools),c.mixin(this.i18n,k.analysisMsgCodes),c.mixin(this.i18n,k.analysisSettings));b.settingsDlg=new C({title:this.i18n.analysisEnv,content:b.settings,style:"width:400px;"});b.settingsDlg.own(b.settings.on("ok-settings",c.hitch(this,function(){b.settingsDlg.hide()})),b.settings.on("cancel-settings",c.hitch(this,function(){b.settingsDlg.hide()})))}b.settingsDlg&&(b.settingsVM.set("showRasterSettings",this.analysisMode&&"raster"===this.analysisMode),b.settingsVM.set("showGeoAnalyticsSettings",
this.analysisMode&&"bigdata"===this.analysisMode),b.settingsVM.set("showCoordinateSystems",this.analysisMode&&("raster"===this.analysisMode||"bigdata"===this.analysisMode)),b.settingsVM.set("showProcessSR",this.analysisMode&&"bigdata"===this.analysisMode),b.settingsVM.set("showOutSR",this.analysisMode&&"raster"===this.analysisMode),this.domNode&&x("[esriHelpTopic\x3d'toolDescription']",this.domNode).forEach(c.hitch(this,function(a){a&&(this._settingsLink=r.create("a",{href:"#","class":"esriAnalysisSettingsIcon"},
a,"before"),t(this._settingsLink,"click",c.hitch(this,this._handleSettingsLinkClick)))})),this._settingWatchers||(this._settingWatchers=!0,a=this.get("context"),b.settingsVM.extent&&(a.extent=b.settingsVM.extent,this._useExtentCheck&&this._useExtentCheck.set("checked",!1)),b.settingsVM.outSR&&(a.outSR=b.settingsVM.outSR),b.settingsVM.processSR&&(a.processSR=b.settingsVM.processSR),b.settingsVM.extent&&(a.extent=b.settingsVM.extent,this._useExtentCheck&&this._useExtentCheck.set("checked",!1)),b.settingsVM.cellSize&&
(a.cellSize=b.settingsVM.cellSize),b.settingsVM.mask&&(a.mask=b.settingsVM.mask),b.settingsVM.snapRaster&&(a.snapRaster=b.settingsVM.snapRaster),this.set("returnFeatureCollection",!F&&b.settingsVM.returnFeatureCollection),this.set("context",a),b.settingsVM.watch("outSR",c.hitch(this,function(a,b,c){if(a=this.get("context"))a.outSR=c,this.set("context",a)})),b.settingsVM.watch("processSR",c.hitch(this,function(a,b,c){if(a=this.get("context"))a.processSR=c,this.set("context",a)})),b.settingsVM.watch("extent",
c.hitch(this,function(a,b,c){if(a=this.get("context"))a.extent=c,this.set("context",a);this._useExtentCheck&&this._useExtentCheck.set("checked",!g.isDefined(c))})),b.settingsVM.watch("cellSize",c.hitch(this,function(a,b,c){if(a=this.get("context"))a.cellSize=c,this.set("context",a)})),b.settingsVM.watch("mask",c.hitch(this,function(a,b,c){if(a=this.get("context"))a.mask=c,this.set("context",a)})),b.settingsVM.watch("snapRaster",c.hitch(this,function(a,b,c){if(a=this.get("context"))a.snapRaster=c,
this.set("context",a)})),b.settingsVM.watch("returnFeatureCollection",c.hitch(this,function(a,b,c){this.set("returnFeatureCollection",!(this.analysisMode&&("raster"===this.analysisMode||"bigdata"===this.analysisMode))&&c)}))))}},_setShowOutputTypeAttr:function(a){this.showOutputType=a},_setDoSaveJobInfoAttr:function(a){this.doSaveJobInfo=a},_setDoSaveInStorageAttr:function(a){this.doSaveInStorage=a},_getResultNameAttr:function(a){this.resultName="";this.outputLayerInput?this.resultName=this.outputLayerInput.get("value"):
this._outputLayerInput&&(this.resultName=this._outputLayerInput.get("value"));return this.resultName},_setArcadeEditorAttr:function(a){this.arcadeEditor=a},_setShowCreditCalcBusyIndicatorAttr:function(a){var b=[];this.showCredits&&this._showCreditsLink&&this._usageForm&&(a?(b.push(n.before(this,"_handleShowCreditsClick",c.hitch(this,function(){var a=this._form&&this._form.validate();"DeriveNewLocations"===this.toolName||"FindExistingLocations"===this.toolName?a=a&&this.expressionGrid.validate():"EnrichLayer"==
this.toolName&&(a=a&&this.validateSelectedGrid());a?this._pauseCreditLinkClick(this._onCreditsClickHandle,!0):this._pauseCreditLinkClick(this._onCreditsClickHandle,!1)}))),b.push(n.after(this._usageForm,"_setContentAttr",c.hitch(this,function(){this._pauseCreditLinkClick(this._onCreditsClickHandle,!1)})))):b.forEach(function(a){a.remove();a=null}))},_setuseArcGISComponentsAttr:function(a){this.useArcGISComponents=a},_getuseArcGISComponentsAttr:function(a){return this.useArcGISComponents},_handleSettingsLinkClick:function(){this.showSettingsDlg()},
showSettingsDlg:function(a){a&&a.preventDefault();this._hasPCSWarnShown&&this.showGeoAnalyticsParams&&this._errorMessagePane&&b.hideMessages(this._errorMessagePane);b.settingsDlg.show()},_handleModeCrumbClick:function(a){a.preventDefault();this._onClose(!1)},_onFocus:function(){this.map&&"function"===typeof this.map.disableKeyboardNavigation&&this.map.disableKeyboardNavigation();this.emit("focus");this.inherited(arguments)},_onBlur:function(){this.map&&"function"===typeof this.map.enableKeyboardNavigation&&
this.map.enableKeyboardNavigation();this.emit("blur");this.inherited(arguments)},_handleAtrrValueUpdate:function(a,c,e){"0"!==e&&(a=this.get("statisticSelect"),(e=this.getOptions(e))&&e.type&&b.addStatisticsOptions({selectWidget:a,type:e.type,showGeoAnalyticsParams:this.showGeoAnalyticsParams}))},_pauseCreditLinkClick:function(a,b){b?(a.pause(),f.set(this._showCreditsLink,{color:"grey",cursor:"none"}),q.add(this._showCreditsLink,"esriAnalysisTextDisabled esriLoadingBar2")):(a.resume(),f.set(this._showCreditsLink,
{color:"#21759B",cursor:"pointer"}),q.remove(this._showCreditsLink,"esriAnalysisTextDisabled esriLoadingBar2"))},constructAnalysisInputLyrObj:function(a,c){c=g.isDefined(c)?c:this.isSingleTenant&&"ExtractData"!==this.toolName;return b.constructAnalysisInputLyrObj(a,c,!this.showGeoAnalyticsParams)},_addBarrierstoJobParams:function(a,b){a instanceof Object&&(b.pointBarrierLayer&&(a.pointBarrierLayer=m.toJson(this.constructAnalysisInputLyrObj(b.pointBarrierLayer))),b.lineBarrierLayer&&(a.lineBarrierLayer=
m.toJson(this.constructAnalysisInputLyrObj(b.lineBarrierLayer))),b.polygonBarrierLayer&&(a.polygonBarrierLayer=m.toJson(this.constructAnalysisInputLyrObj(b.polygonBarrierLayer))));return a}});u("extend-esri")&&c.setObject("dijit.analysis._AnalysisOptions",h,E);return h});