// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/analysis/AnalysisBase","require dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/json dojo/has dojo/json dojo/Deferred dojo/promise/all dojo/when dojo/data/ItemFileWriteStore dojo/string dojo/Evented dojo/_base/kernel dojo/Stateful ../../kernel ../../lang ../../request ../../tasks/Geoprocessor dojo/i18n!../../nls/jsapi ./utils ./storageUtils ./ItemTypes ../../IdentityManager".split(" "),function(v,r,d,l,g,B,F,m,z,G,H,w,C,D,E,h,f,k,x,t,n,A,y){r=r([E,C],{declaredClass:"esri.dijit.analysis.AnalysisBase",
isOutputLayerItemUpdated:!1,analysisGpServer:null,toolName:null,portalUrl:null,jobParams:null,itemParams:null,gp:null,resultParameter:null,signInPromise:null,getResultLyrInfos:!1,checkCreditLimits:!1,useGPCreditTask:!0,_isGPCreditSync:!0,_jobInfo:null,_popupInfo:null,_toolServiceUrl:null,_counter:null,_analysisType:"feature",doRefreshItem:!0,doSaveJobInfo:!1,doSaveInStorage:!1,_doDeleteViewResult:!1,outputName:"OutputName",constructor:function(a){this.isOutputLayerItemUpdated=!1;this._rids=[];this._counter=
0;this._popupInfo=[];a.analysisGpServer?this._signIn(a.analysisGpServer):a.portalUrl&&(this.portalUrl=a.portalUrl,this._signIn(a.portalUrl,!0));this.i18n={};d.mixin(this.i18n,t.common);d.mixin(this.i18n,t.analysisTools);d.mixin(this.i18n,t.analysisMsgCodes);d.mixin(this.i18n,t.analysisSettings);this.signInPromise.then(d.hitch(this,this._initErrorHelpMap))},execute:function(a){this.jobParams=a.jobParams;this.jobParams.actualOutputName=this.outputName;this.jobParams[this.outputName]?this.itemParams=
a.itemParams:(this.itemParams=null,this.jobParams.resultName=this.get("resultName"));this._analysisType=a.analysisType||"feature";f.isDefined(a.isSpatioTemporalDataStore)&&(this._isSpatioTemporalDataStore=n.settingsVM&&n.settingsVM.datastore&&"CopyToDataStore"!==this.toolName?"BDS"===n.settingsVM.datastore:a.isSpatioTemporalDataStore);this.signInPromise.then(d.hitch(this,this._checkUser))},_checkUser:function(){var a;if(a=h.id.findCredential(this.portalUrl).userId)a=this.portalUrl+"/sharing/rest/community/users/"+
a,k({url:a,content:{f:"json"}}).then(d.hitch(this,this._handleUserProfileResponse),d.hitch(this,function(a){this.emit("job-fail",{message:a.message+(a.details?a.details.toString():""),jobParams:this.jobParams})}))},getUserProfile:function(){var a=new m;this.userProfile?a.resolve(this.userProfile):this.signInPromise.then(d.hitch(this,function(b){if(b=b.userId)b=this.portalUrl+"/sharing/rest/community/users/"+b,k({url:b,content:{f:"json"}}).then(d.hitch(this,function(b){this.userProfile=b;a.resolve(b)}),
d.hitch(this,function(b){a.reject(b)}))}));return a.promise},_handleUserProfileResponse:function(a){var b=this.jobParams.outputType&&this.jobParams.outputType===y.FLAYERVIEW;if(f.isDefined(a)&&f.isDefined(a.orgId))if(-1===l.indexOf(["account_admin","account_publisher","org_admin","org_publisher"],a.role))this.emit("job-fail",{message:this.i18n.pubRoleMsg,messageCode:"AB_0001",jobParams:this.jobParams});else if(f.isDefined(a.availableCredits)&&this.get("checkCreditLimits")&&!b){var c,b={},e;for(c in this.jobParams)this.jobParams.hasOwnProperty(c)&&
("object"===typeof this.jobParams[c]?b[c]=g.toJson(this.jobParams[c]):-1!==l.indexOf(["measurementtype"],c.toLowerCase())&&"StraightLine"!==this.jobParams[c]?(e=g.fromJson(this.jobParams[c]),b[c]=e?e.name.replace(/[\s~`!#$%\^&*+=\-\[\]\\';,\/{}|\\":<>\?]/g,""):"DrivingTime"):b[c]=this.jobParams[c]);this.getCreditsEstimate(this.toolName,b).then(d.hitch(this,function(b){var c=b&&f.isDefined(b.cost)?b.cost:b.maximumCost;f.isDefined(c)&&a.availableCredits>c?f.isDefined(this.itemParams)?this._checkServiceName(a.orgId):
(this.emit("start",this.jobParams),this._submitGpJob()):b&&(b.messageCode||b.message)?(c=f.isDefined(this.i18n[b.messageCode])?this.i18n[b.messageCode]:b.message,c=f.isDefined(b.params)?w.substitute(c,b.params):c,this.emit("job-fail",{message:c,messageCode:"AB_0001",jobParams:this.jobParams})):this.emit("job-fail",{message:this.i18n.insufficientCreditsMsg,messageCode:"AB_0001",jobParams:this.jobParams})}))}else f.isDefined(this.itemParams)?this._checkServiceName(a.orgId):(this.emit("start",this.jobParams),
this._submitGpJob());else this.emit("job-fail",{message:this.i18n.orgUsrMsg,jobParams:this.jobParams})},_checkServiceName:function(a){var b;h.id.findCredential(this.portalUrl);a=this.portalUrl+"/sharing/rest/portals/"+a+"/isServiceNameAvailable";b=g.fromJson(this.jobParams[this.outputName]);f.isDefined(b.serviceProperties)&&f.isDefined(b.serviceProperties.name)&&(b.serviceProperties.name=b.serviceProperties.name.replace(/[\s]|\-|\./g,"_"),this.jobParams[this.outputName]=g.toJson(b));k({url:a,content:{name:b.serviceProperties.name,
type:"raster"===this._analysisType?"Image Service":"Feature Service",f:"json"}}).then(d.hitch(this,function(a){a.available?("raster"===this._analysisType?this._createImageService():this._createService(),this.emit("start",this.jobParams)):this.emit("job-fail",{message:this.i18n.servNameExists,type:"warning",messageCode:"AB_0002",jobParams:this.jobParams})}),d.hitch(this,function(a){this.emit("job-fail",{message:a.message+(a.details?a.details.toString():""),jobParams:this.jobParams})}))},_createService:function(){var a,
b,c,e=this._submitGpJob;a=h.id.findCredential(this.portalUrl).userId;b=g.fromJson(this.jobParams[this.outputName]);a&&(c=this.itemParams.folder,a=this.portalUrl+"/sharing/rest/content/users/"+a+(c&&"/"!==c?"/"+c:"")+"/createService",b={createParameters:g.toJson({currentVersion:10.2,serviceDescription:"",hasVersionedData:!1,supportsDisconnectedEditing:!1,hasStaticData:!0,maxRecordCount:2E3,supportedQueryFormats:"JSON",capabilities:"Query",description:"",copyrightText:"",allowGeometryUpdates:!1,syncEnabled:!1,
editorTrackingInfo:{enableEditorTracking:!1,enableOwnershipAccessControl:!1,allowOthersToUpdate:!0,allowOthersToDelete:!0},xssPreventionInfo:{xssPreventionEnabled:!0,xssPreventionRule:"InputOnly",xssInputRule:"rejectInvalid"},tables:[],name:b.serviceProperties.name}),outputType:"featureService",f:"json"},this._isSpatioTemporalDataStore&&(c=g.fromJson(b.createParameters),c.options={dataSourceType:"spatiotemporal"},b.createParameters=g.toJson(c)),this.jobParams.outputType&&this.jobParams.outputType===
y.FLAYERVIEW&&(c=g.fromJson(b.createParameters),d.mixin(b,this._getViewCreateParams()),b.createParameters=g.toJson(c),e=this._addViewDefinition),k({url:a,content:b},{usePost:!0}).then(d.hitch(this,e),d.hitch(this,this._handleCreateServiceError)))},_createImageService:function(){var a,b,c;a=h.id.findCredential(this.portalUrl).userId;b=g.fromJson(this.jobParams[this.outputName]);a&&(c=this.itemParams.folder,a=this.portalUrl+"/sharing/rest/content/users/"+a+(c&&"/"!==c?"/"+c:"")+"/createService",b={createParameters:g.toJson({name:b.serviceProperties.name,
description:"",capabilities:"Image",properties:{path:"@",description:"",copyright:""}}),outputType:"imageService",f:"json"},k({url:a,content:b},{usePost:!0}).then(d.hitch(this,this._submitGpJob),d.hitch(this,this._handleCreateServiceError)))},_handleCreateServiceError:function(a){this.emit("job-fail",{message:a.message+(a.details?a.details.toString():""),jobParams:this.jobParams})},_getViewCreateParams:function(){return{isView:!0}},_addViewDefinition:function(a){var b,c;this.itemParams&&(this.currentGpItemId=
a.itemId,b=g.fromJson(this.jobParams[this.outputName]),b.serviceProperties&&(b.serviceProperties.serviceUrl=a.serviceurl),b.itemProperties={itemId:a.itemId},this.itemParams.folder&&(b.itemProperties.folderId=this.itemParams.folder),this.jobParams[this.outputName]=g.toJson(b));this.getViewParams({jobParams:this.jobParams,resultService:{url:a.serviceurl,itemId:a.itemId}}).then(d.hitch(this,function(b){c=b;var e={jobId:"ViewJob_"+(new Date).getTime(),jobStatus:"esriJobSubmitted",jobParams:this.jobParams};
this._addToDefinition(a.serviceurl,c).then(d.hitch(this,function(a){var b={value:{}};this._doDeleteViewResult||(this._jobInfo.jobStatus="esriJobSucceeded",setTimeout(d.hitch(this,function(){this.itemParams.properties={jobUrl:a.serviceurl+"/jobs/"+this._jobInfo.jobId,jobType:"GPServer",jobId:this._jobInfo.jobId,jobStatus:"completed"};this._readItem()}),300),this.doSaveJobInfo&&this.saveJobInfo(this._jobInfo),b.outputLayerName=g.fromJson(this.jobParams[this.outputName]).serviceProperties.name,b.value.itemId=
this.currentGpItemId,b.analysisInfo={toolName:this.toolName,secondaryOutputs:this.secondaryOutputs,jobParams:this.jobParams},this.emit("job-result",b))}),d.hitch(this,this._gpJobFailed));this.emit("job-submit",this.jobParams);setTimeout(d.hitch(this,function(){this._jobInfo=e;this._jobInfo.jobStatus="esriJobExecuting";this._readItem();this.emit("job-status",this._jobInfo)},0))}),d.hitch(this,this._gpJobFailed))},_addToDefinition:function(a,b){a=a.replace("/rest/services","/rest/admin/services")+"/addToDefinition";
var c=h.id.findCredential(this.portalUrl);b={f:"json",addToDefinition:g.toJson(b),token:c.token};return k({url:a,content:b},{usePost:!0})},_getAdminLayerInfo:function(a){a=a.replace("/rest/services","/rest/admin/services");var b;b={f:"json",token:h.id.findCredential(this.portalUrl).token};return k({url:a,content:b})},_getSelf:function(a){return k({url:a+"/sharing/rest/portals/self",content:{culture:D.locale,f:"json"},callbackParamName:"callback",timeout:0},{})},_submitGpJob:function(a){var b;this.itemParams&&
(this.currentGpItemId=a.itemId,b=g.fromJson(this.jobParams[this.outputName]),b.serviceProperties&&(b.serviceProperties.serviceUrl=a.serviceurl),b.itemProperties={itemId:a.itemId},this.itemParams.folder&&(b.itemProperties.folderId=this.itemParams.folder),this.jobParams[this.outputName]=g.toJson(b));this.rerun&&this.context&&this._useExtentCheck&&!this._useExtentCheck.get("checked")&&(this.context=null);this.context&&((a=g.fromJson(this.jobParams.context))||(a={}),this.context.outSR&&!a.outSR&&(a.outSR=
this.context.outSR),this.context.processSR&&!a.processSR&&(a.processSR=this.context.processSR),this.context.extent&&!a.extent&&(a.extent=this.context.extent),"raster"===this._analysisType&&(this.context.cellSize&&!a.cellSize&&(a.cellSize=this.context.cellSize),this.context.mask&&!a.mask&&(a.mask=this.context.mask),this.context.snapRaster&&!a.snapRaster&&(a.snapRaster=this.context.snapRaster)),this.jobParams.context=g.toJson(a));this.analysisGpServer?(this._toolServiceUrl&&this.gp||this.set("toolServiceUrl",
this.analysisGpServer+"/"+this.toolName),this.gp.setUpdateDelay(3E3),this.itemParams||delete this.jobParams.resultName,a=d.mixin({},this.jobParams),a.actualOutputName&&delete a.actualOutputName,this.gp.submitJob(a,d.hitch(this,this._gpJobComplete),d.hitch(this,this._gpJobStatus),d.hitch(this,this._gpJobFailed)),this.itemParams||(this.jobParams.resultName=this.get("resultName")),this.emit("job-submit",this.jobParams)):this._getSelf(this.portalUrl).then(d.hitch(this,function(a){this.analysisGpServer=
a.helperServices.analysis&&a.helperServices.analysis.url?a.helperServices.analysis.url:null;this.set("toolServiceUrl",this.analysisGpServer+"/"+this.toolName);this.gp.setUpdateDelay(3E3);this.itemParams||delete this.jobParams.resultName;this.gp.submitJob(this.jobParams,d.hitch(this,this._gpJobComplete),d.hitch(this,this._gpJobStatus),d.hitch(this,this._gpJobFailed));this.itemParams||(this.jobParams.resultName=this.get("resultName"));this.emit("job-submit",this.jobParams)}))},_updateItem:function(a){var b,
c,e;if(b=h.id.findCredential(this.portalUrl).userId)return c=this.itemParams.folder,b=this.portalUrl+"/sharing/rest/content/users/"+b+(c&&"/"!==c?"/"+c:"")+"/items/"+this.currentGpItemId+"/update",a&&(e=a.item.properties),f.isDefined(e)||(e={}),f.isDefined(e.jobUrl)||(e.jobUrl=this._toolServiceUrl+"/jobs/"+this._jobInfo.jobId,e.jobType="GPServer",e.jobId=this._jobInfo.jobId,e.jobStatus="processing",this.itemParams.properties=e),e=d.mixin({f:"json"},this.itemParams),a&&e.folder===a.item.folder&&delete e.folder,
a&&a.item&&e.tags===a.item.tags.toString()&&delete e.tags,a&&a.item&&e.snippet===a.item.snippet&&delete e.snippet,a&&a.item&&e.description===a.item.description&&delete e.description,e.properties&&(e.properties=g.toJson(e.properties)),e.text&&(e.text=g.toJson(e.text)),a=k({url:b,content:e},{usePost:!0}),a.then(d.hitch(this,this._handleItemUpdate),d.hitch(this,this._handleUpdateItemError)),a},_handleItemUpdate:function(a){this.isOutputLayerItemUpdated=!0},_handleItemDataUpdate:function(a){},_handleUpdateItemError:function(a){this.isOutputLayerItemUpdated=
!0;this.emit("job-fail",{message:a.message+(a.details?a.details.toString():""),jobParams:this.jobParams})},_handleErrorResponse:function(a){this.emit("job-fail",a)},_refreshItem:function(){var a,b;(a=h.id.findCredential(this.portalUrl).userId)?(b=this.itemParams.folder,a=this.portalUrl+"/sharing/rest/content/users/"+a+(b&&"/"!==b?"/"+b:"")+"/items/"+this.currentGpItemId+"/refresh",a=k({url:a,content:{f:"json"}},{usePost:!0})):(a=new m,a.resolve());return a.promise},_handleItemRefresh:function(a){},
_readItem:function(){var a,b;if(a=h.id.findCredential(this.portalUrl).userId)return b=this.itemParams.folder,a=this.portalUrl+"/sharing/rest/content/users/"+a+(b&&"/"!==b?"/"+b:"")+"/items/"+this.currentGpItemId,a=k({url:a,content:{f:"json"}}),a.then(d.hitch(this,this._updateItem))},getItemInfo:function(a){if(h.id.findCredential(this.portalUrl).userId)return a=this.portalUrl+"/sharing/rest/content/items/"+a,k({url:a,content:{f:"json"}})},_gpJobStatus:function(a){a.jobParams=this.jobParams;a.resultParameter=
this.resultParameter;a.returnProcessInfo=this.jobParams.returnProcessInfo;a.getResultLyrInfos=this.getResultLyrInfos;a.currentGpItemId=this.currentGpItemId;a.itemParams=this.itemParams;"esriJobFailed"===a.jobStatus||"esriJobSucceeded"===a.jobStatus?(a.messages&&(a.message=this._buildErrorMsg(a)),this._checkTimer&&(clearInterval(this._checkTimer),this._checkTimer=null,this._gpJobComplete(a)),"esriJobFailed"===a.jobStatus&&this._deleteItem(!1)):"esriJobCancelled"===a.jobStatus&&(this.itemParams?this._deleteItem(!0):
this.emit("job-cancel",a));this.doSaveJobInfo&&this.saveJobInfo(a);this.emit("job-status",a);this._jobInfo=a;this.itemParams&&!this.isOutputLayerItemUpdated&&this._readItem()},_updateRefreshItem:function(a){var b=[],c=a[0];b.push(this._readItem(this.doRefreshItem));z(b).then(d.hitch(this,function(a){c.outputLayerName=g.fromJson(this.jobParams[this.outputName]).serviceProperties.name;c.value.itemId=this.currentGpItemId;c.analysisInfo={toolName:this.toolName,secondaryOutputs:this.secondaryOutputs,jobParams:this.jobParams};
this.doRefreshItem?this._refreshItem().always(d.hitch(this,function(){this.emit("job-result",c)})):this.emit("job-result",c)}),d.hitch(this,this._handleDeleteItemError))},_gpJobComplete:function(a){var b;"esriJobSucceeded"===a.jobStatus&&(a.jobParams=this.jobParams,this.emit("job-success",a),z(this._getGpResultData(a)).then(d.hitch(this,function(c){c=l.filter(c,function(a){var b=!0;f.isDefined(a.value.empty)?b=a.value.empty:f.isDefined(a.value.url)||f.isDefined(a.value.itemId)?b=!1:f.isDefined(a.value.featureSet)&&
(b=!1);if(!b)return a});0===c.length?(this.currentGpItemId&&this._deleteItem(!1),this.emit("job-fail",{message:this.i18n.emptyResultInfoMsg,type:"warning",jobParams:this.jobParams})):(f.isDefined(this.itemParams)&&this.itemParams.properties&&this.itemParams.properties.jobStatus&&"processing"===this.itemParams.properties.jobStatus&&(this.itemParams.properties.jobStatus="completed"),l.forEach(c,function(a){if(a.value.featureSet&&!a.value.url)a.value.featureSet.spatialReference=a.value.layerDefinition.spatialReference;
else if(a.value.url&&-1!==a.value.url.indexOf("/FeatureServer/")&&a.value.layerInfo&&a.value.layerInfo.popupInfo){var b=a.value.url.match(/[0-9]+$/g)[0];this._popupInfo[b]=a.value.layerInfo.popupInfo}},this),b=c[0],b.results=c,this.jobParams.returnProcessInfo?this.gp.getResultData(a.jobId,"ProcessInfo").then(d.hitch(this,function(a){var e=[];l.forEach(a.value,function(a){e.push(g.fromJson(a))},this);this.currentGpItemId?(this.itemParams.description=n.buildReport(e),this._updateRefreshItem(c)):(b.analysisReport=
n.buildReport(e),b.outputLayerName=this.jobParams.resultName,this.emit("job-result",b))})):this.currentGpItemId?this._updateRefreshItem(c):(b.outputLayerName=this.jobParams.resultName,this.emit("job-result",b)))})))},_gpJobFailed:function(a){d.clone(a).jobParams=this.jobParams;this._checkTimer&&(clearInterval(this._checkTimer),this._checkTimer=null);a.messages&&(a.message=this._buildErrorMsg(a));this.emit("job-fail",a)},_getGpResultData:function(a){var b=[],c=[];"string"===typeof this.resultParameter?
c.push(this.resultParameter):this.resultParameter instanceof Array&&(c=this.resultParameter);l.forEach(c,function(c,d){b.push(this.gp.getResultData(a.jobId,c))},this);return b},cancel:function(a){this.jobParams.outputType&&this.jobParams.outputType===y.FLAYERVIEW?(this._doDeleteViewResult=!0,this._deleteItem(!0)):this.gp.cancelJob(a.jobId).then(d.hitch(this,function(a){"esriJobCancelled"===a.jobStatus&&(this.itemParams?this._deleteItem(!0):this.emit("job-cancel",a))}),function(a){})},checkJobStatus:function(a){this.signInPromise.then(d.hitch(this,
function(){this.gp.setUpdateDelay(3E3);this._checkTimer=setInterval(d.hitch(this,this._checkStatus,a,d.hitch(this,this._gpJobStatus),d.hitch(this,this._gpJobFailed)),3E3)}))},_checkStatus:function(a,b,c){this.gp.checkJobStatus(a,b,c)},_deleteItem:function(a){var b,c;(b=h.id.findCredential(this.portalUrl).userId)&&this.itemParams&&(c=f.isDefined(this.itemParams.folder)?this.itemParams.folder:"",b=this.portalUrl+"/sharing/rest/content/users/"+b+(c&&"/"!==c?"/"+c:"")+"/items/"+this.currentGpItemId+"/delete",
k({url:b,content:{f:"json"}},{usePost:!0}).then(d.hitch(this,this._handleItemDelete,a),d.hitch(this,this._handleDeleteItemError)))},_handleItemDelete:function(a,b){a&&this.emit("job-cancel",b)},_handleDeleteItemError:function(a){this.emit("job-fail",{message:a.message+(a.details?a.details.toString():""),jobParams:this.jobParams})},_initFolderStore:function(a,b){this._fportal=this.portalSelf?new a.Portal({url:this.portalUrl,self:this.portalSelf}):new a.Portal(this.portalUrl);this._fportal.signIn().then(d.hitch(this,
function(a){this.portalUser=a;this.portalUser.getFolders().then(d.hitch(this,function(a){a=n.createFolderStore(a,this.portalUser.username);b.resolve(a)}))}))},getFolderStore:function(){var a=new m,b,c,e,f;this.folderStore?a.resolve(this.folderStore):this.signInPromise.then(d.hitch(this,function(d){b=["../../arcgis/Portal"];c=this._counter++;e=this;this._rids&&this._rids.push(c);v(b,function(b){f=e._rids?l.indexOf(e._rids,c):-1;-1!==f&&(e._rids.splice(f,1),e._initFolderStore(b,a))})}));return a},_checkToolUrl:function(){var a=
new m;this.analysisGpServer?(this._toolServiceUrl&&this.gp||this.set("toolServiceUrl",this.analysisGpServer+"/"+this.toolName),a.resolve({success:!0})):this._getSelf(this.portalUrl).then(d.hitch(this,function(b){(this.analysisGpServer=b.helperServices.analysis&&b.helperServices.analysis.url?b.helperServices.analysis.url:null)&&this.set("toolServiceUrl",this.analysisGpServer+"/"+this.toolName);a.resolve({success:!0})}));return a},getCreditsEstimate:function(a,b){this.start=window.performance.now();
var c,e,f,p,h,q;e=new m;this._checkToolUrl().then(d.hitch(this,function(u){this._toolServiceUrl?h=this._toolServiceUrl:(p=this.portalUrl&&-1!==this.portalUrl.indexOf("dev")?"dev":this.portalUrl&&-1!==this.portalUrl.indexOf("qa")?"qa":"",h="http://analysis"+p+".arcgis.com/arcgis/rest/services/tasks/GPServer/"+this.toolName);!this.showGeoAnalyticsParams&&-1!==l.indexOf(["AggregatePoints","SummarizeWithin"],a)&&b.binType?(c=h.replace(a,"TessellationCredit"),b.pointLayer?b.inputLayer=b.pointLayer:b.summaryLayer&&
(b.inputLayer=b.summaryLayer),u={jobParams:b,resultParameter:"creditOutput",def:e},this._getGPCreditEstimate(c,u)):this.useGPCreditTask?(c=(q=this.portalSelf||this._portal)&&q.helperServices&&q.helperServices.creditEstimation&&q.helperServices.creditEstimation.url?q.helperServices.creditEstimation.url+"/EstimateCredits":h.replace("/tasks/GPServer/"+a,"/Estimate/GPServer/EstimateCredits"),u={jobParams:{taskName:a,taskParameters:g.toJson(b)},resultParameter:"creditEstimate",def:e,isGPCreditSync:this._isGPCreditSync},
this._getGPCreditEstimate(c,u)):(c=h.replace("/"+a,"/exts/Estimate/"+a),f=d.mixin({f:"json"},b),k({url:c,content:f},{usePost:!0}).then(d.hitch(this,function(a){this.end=window.performance.now();console.log("Analysis Credit Estimator SOE Sync Time : "+(this.end-this.start)+" milliseconds");e.resolve(a)}),function(a){e.resolve(a)}))}));return e},_getGPCreditEstimate:function(a,b){this.creditGP=new x(a);this.creditGP.setUpdateDelay(1E3);b.isGPCreditSync?this.creditGP.execute(b.jobParams,d.hitch(this,
this._getGPCreditResult,b.def,b.resultParameter,b.isGPCreditSync),d.hitch(this,this._creditGPJobFailed,b.def,b.isGPCreditSync)):this.creditGP.submitJob(b.jobParams,d.hitch(this,this._getGPCreditResult,b.def,b.resultParameter,b.isGPCreditSync),d.hitch(this,this._creditGPJobFailed,b.def,b.isGPCreditSync),d.hitch(this,this._creditGPJobFailed,b.def,b.isGPCreditSync))},_getGPCreditResult:function(a,b,c,e){c?(this.end=window.performance.now(),console.log("Analysis Credit Estimator GP Sync Time : "+(this.end-
this.start)+" milliseconds"),a.resolve(e[0].value)):this.creditGP.getResultData(e.jobId,b).then(d.hitch(this,function(a,b){b&&b.value&&b.value.credits&&(b.value.cost=b.value.credits);this.end=window.performance.now();console.log("Analysis Credit Estimator GP Async Time : "+(this.end-this.start)+" milliseconds");a.resolve(b.value)},a),d.hitch(this,function(a,b){a.resolve(b)},a))},_creditGPJobFailed:function(a,b,c){if(b){if(400===c.code||-1!==c.code.indexOf("IdentityManagerBase."))c.messages=c.details,
a.resolve(c)}else"esriJobFailed"!==c.jobStatus&&"esriJobCancelled"!==c.jobStatus||a.resolve(this._buildErrorMsg(c))},_signIn:function(a,b){var c,e,g,p;this.signInPromise=new m;b?(b=["../../arcgis/Portal"],c=this._counter++,e=this,this._rids&&this._rids.push(c),v(b,d.hitch(this,function(b){g=e._rids?l.indexOf(e._rids,c):-1;-1!==g&&(e._rids.splice(g,1),this._portal=this.portalSelf?new b.Portal({url:a,self:this.portalSelf}):new b.Portal(a),this._portal.signIn().then(d.hitch(this,function(a){this.portalUser=
a;this._portal.helperServices&&this._portal.helperServices.analysis&&this._portal.helperServices.analysis.url?(this.analysisGpServer=this._portal.helperServices.analysis.url,this.showGeoAnalyticsParams&&this._portal.helperServices.geoanalytics&&(this.analysisGpServer=this._portal.helperServices.geoanalytics.url),k({url:this.analysisGpServer,content:{f:"json"},callbackParamName:"callback"}).then(d.hitch(this,function(a){p=h.id.findCredential(this.analysisGpServer);this.signInPromise.resolve(p)}),d.hitch(this,
function(a){this.signInPromise.reject(a)}))):this.signInPromise.resolve(a)}),d.hitch(this,this._handleSignInError)))}))):k({url:a,content:{f:"json"},callbackParamName:"callback"}).then(d.hitch(this,function(b){var c;b=h.id.findCredential(a);f.isDefined(b)?(c=h.id.findServerInfo(this._toolServiceUrl),f.isDefined(c)&&f.isDefined(c.owningSystemUrl)&&(this.portalUrl=c.owningSystemUrl),this.signInPromise.resolve(b)):h.id.getCredential(a).then(d.hitch(this,function(b){b=h.id.findCredential(a);c=h.id.findServerInfo(this._toolServiceUrl);
f.isDefined(c)&&f.isDefined(c.owningSystemUrl)&&(this.portalUrl=c.owningSystemUrl);this.signInPromise.resolve(b)}),d.hitch(this,this._handleSignInError))}),d.hitch(this,this._handleSignInError));return this.signInPromise},_handleSignInError:function(a){this.emit("job-fail",{message:this.i18n.analysisSignInErrorMsg,messageCode:"AB_0003"});this.signInPromise.reject(a)},_buildErrorMsg:function(a){var b="",c=[],e,d;this.errorHelpMap||this._initErrorHelpMap();c=l.filter(a.messages,function(a){if(("esriJobMessageTypeError"===
a.type||"esriJobMessageTypeWarning"===a.type)&&-1!==a.description.indexOf("messageCode"))return a.description},this);0<c.length&&l.forEach(c,function(c){try{e=g.fromJson(c.description)}catch(I){e=c.description}d="";"esriJobMessageTypeWarning"===c.type&&(a.type="warning");e.messageCode?(d=f.isDefined(this.i18n[e.messageCode])?this.i18n[e.messageCode]:e.message,d=f.isDefined(e.params)?w.substitute(d,e.params):d,b+=d+"\x26nbsp;",(c=this._addLearnMoreErrorLink(e.messageCode))&&(b+=c)):e.error&&e.error.messageCode?
(d=f.isDefined(this.i18n[e.error.messageCode])?this.i18n[e.error.messageCode]:e.error.message,d=f.isDefined(e.error.params)?w.substitute(d,e.error.params):d,b+=d+"\x26nbsp;",(c=this._addLearnMoreErrorLink(e.error.messageCode))&&(b+=c)):b+=e+"\x26nbsp;"},this);return b},_toolServiceUrlSetter:function(a){this._toolServiceUrl=a;this.gp=new x(a)},_setToolServiceUrlAttr:function(a){this._toolServiceUrl=a;this.gp=new x(a)},checkCreditLimitsAttr:function(a){this.checkCreditLimits=a},replaceTag:function(a){return{"\x26":"\x26amp;",
"\x3c":"\x26lt;","\x3e":"\x26gt;"}[a]||a},safetagsReplace:function(a){return a.replace(/[<>]/g,this.replaceTag)},saveJobInfo:function(a){var b;if(this.doSaveJobInfo&&this.currentGpItemId&&-1!==l.indexOf(["esriJobSucceeded"],a.jobStatus)){d.mixin(a.jobParams,{extentCheck:this._useExtentCheck&&this._useExtentCheck.get("checked")});l.forEach(a.messages,function(a){a.description=this.safetagsReplace(a.description)},this);a={toolName:this.toolName,jobParams:a.jobParams,timestamp:Date.now(),portalUrl:this.portalUrl,
jobInfo:{jobId:a.jobId,jobStatus:a.jobStatus,messages:a.messages,analysisServer:"bigdata"===this.analysisMode?"geoanalytics":"default"===this.analysisMode?"standard":this.analysisMode}};"CopyToDataStore"===this.toolName&&(a.jobParams.isSpatioTemporalDataStore=this._isSpatioTemporalDataStore);"bigdata"===this.analysisMode&&a.jobParams.timeStepReference&&(a.jobParams.timeReferenceType=this.get("timeReferenceType"));for(b in a.jobParams)if(a.jobParams.hasOwnProperty(b)&&f.isDefined(a.jobParams[b])){if("object"===
typeof a.jobParams[b]&&a.jobParams[b].serviceToken||"string"===typeof a.jobParams[b]&&-1!==a.jobParams[b].indexOf("serviceToken")){var c="string"===typeof a.jobParams[b]?g.fromJson(a.jobParams[b]):a.jobParams[b];c&&c.serviceToken&&(delete c.serviceToken,a.jobParams[b]="string"===typeof a.jobParams[b]?g.toJson(c):c)}if("object"===typeof a.jobParams[b]&&!d.isArray(a.jobParams[b])&&a.jobParams[b].filter||"string"===typeof a.jobParams[b]&&-1!==a.jobParams[b].search(/[<>]/g))"object"===typeof a.jobParams[b]&&
a.jobParams[b].filter&&!d.isArray(a.jobParams[b])?a.jobParams[b].filter=this.safetagsReplace(a.jobParams[b].filter):"string"===typeof a.jobParams[b]&&-1!==a.jobParams[b].search(/[<>]/g)&&(a.jobParams[b]=this.safetagsReplace(a.jobParams[b]))}b=h.id.findCredential(this.portalUrl);this.currentGpItemId&&(b={id:this.currentGpItemId,folderId:this.itemParams.folder,owner:b.userId},A.addToItemResource(b,a));this.doSaveInStorage&&A.addToStorage(a)}},_initErrorHelpMap:function(){if(this.isSingleTenant){var a=
v.toUrl("./help/errorhelpmap_enterprise.json");k({url:a}).then(d.hitch(this,function(a){this.errorHelpMap=a.map}))}},_addLearnMoreErrorLink:function(a){if(this.isSingleTenant){var b;a=this.errorHelpMap[a];var c=this&&this.portalSelf?this.portalSelf.helpBase:null,d=this.analysisGpServer&&-1!==this.analysisGpServer.indexOf("dev")?"dev":this.analysisGpServer&&-1!==this.analysisGpServer.indexOf("qa")?"uat":"";f.isDefined(a)&&(b="http://doc"+d+".arcgis.com/en/arcgis-online/analyze/"+a,this.isSingleTenant&&
c?b=c+"index.html#"+a:this.isSingleTenant&&!c&&(b="http://server"+d+".arcgis.com/en/portal/latest/use/"+a));b&&(b="\x3cbr/\x3e\x3cbr/\x3e\x3cdiv class\x3d'esriHelpPopup'\x3e\x3ca class\x3d'action zoomTo' href\x3d'"+b+"' target\x3d'_help'\x3e"+this.i18n.learnMore+"\x3c/a\x3e\x3c/div\x3e\x3cbr/\x3e\x3cbr/\x3e");return b}}});B("extend-esri")&&d.setObject("dijit.analysis.AnalysisBase",r,h);return r});