// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/infographics/simpleInfographic/_DataDrillingSupport","dojo/_base/declare dojo/on dojo/when dojo/dom-class dojo/dom-construct dojo/dom-style dojo/query ./SimpleInfographicViewModes ../../grid/coreUtils/GridDataUtil ./dataDrilling/DataDrillingLibrary ../utils/InfographicJsonUtil esri/dijit/geoenrichment/utils/DelayUtil esri/dijit/geoenrichment/utils/DeviceUtil esri/dijit/geoenrichment/utils/DnDUtil esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/TooltipUtil esri/dijit/geoenrichment/utils/WaitingUtil ../../sections/SectionTypes ../../supportClasses/ViewModes ./DataDrillingBackgroundUtil ./DataDrillingExportUtil dojo/i18n!esri/nls/jsapi".split(" "),
function(A,k,n,B,m,w,C,u,D,x,y,q,r,z,l,v,E,F,G,H,t,p){p=p.geoenrichment.dijit.ReportPlayer.Infographics;return A(null,{_drillingSections:null,_drillingSectionsButtons:null,postCreate:function(){var a=this;this.inherited(arguments);k(this.backToMainViewButton,"click",function(){a._setViewMode(u.VIEW_MAIN,!0)});r.isMobileDevice()&&this.own(k(window,"resize, orientationchange",function(){a._setViewMode(u.VIEW_MAIN,!1)}));l.hide([this.exportButton,this.printButton]);this.viewModel.dynamicReportInfo&&
(t.canExportDataDrilling(this)&&(v.setTooltipToNode(this.exportButton,p.exportInfographic),l.show(this.exportButton),k(this.exportButton,"click",function(){t.exportDataDrilling(a)})),t.canPrintDataDrilling(this)&&(v.setTooltipToNode(this.printButton,p.printInfographic),l.show(this.printButton),k(this.printButton,"click",function(){t.printDataDrilling(a)})))},_getCountryID:function(){return this.viewModel.dynamicReportInfo.infographicOptions.countryID},_addDataDrillingHandlers:function(a,b){var d=
this,f=D.getFieldInfo(b.getFirstCell()),c=(b=y.getDataDrilling(this._currentInfographicJson,f.templateName))&&b.sectionJson?b:null,e=(b=b&&b.isStandard&&x.getDrillingOptions(this._getCountryID(),b.standardId||f))&&b[0];if(c||e)a.getTables().forEach(function(a){a.getFieldCells().forEach(function(a){v.setTooltipToNode(a.domNode,null)})}),this._setUpDataDrillingButton(a,function(a){a=d._setViewMode(u.VIEW_DATA_DRILLING,!0,a);c?d._renderCustomSectionJson({customDDPanelInfo:c,fieldInfo:f,animationPromise:a}):
d._loadStandardDataDrillingView({fieldInfo:f,optionName:e.name,calcState:null,sectionVisualState:null,animationPromise:a})})},_setUpDataDrillingButton:function(a,b){function d(){var b=m.create("div",{"class":"simpleInfographic_drillDataButton"},a.domNode);m.create("div",{"class":"dijitInline simpleInfographic_drillDataButtonIcon esriGESpaceAfterBig"},b);var d=m.create("div",{"class":"dijitInline simpleInfographic_drillDataButtonLabel",innerHTML:p.drillForMoreData},b),c=[];a.getTables().forEach(function(a){c.push(a.domNode)});
var g=l.uniteNodeBoxes(c,a.domNode);w.set(b,{left:g.x+"px",top:g.y+"px",width:g.w+"px",height:g.h+"px",lineHeight:g.h+"px"});var e=l.position(b);e.w>g.w&&w.set(b,"left",g.x-(e.w-g.w)/2+"px");d.style.maxWidth=g.w-70+"px";d.style.whiteSpace="normal";d.style.lineHeight="20px";f._drillingSectionsButtons.push({destroy:function(){m.destroy(b)}});return b}var f=this,c;if(r.isMobileDevice()){var e=function(a){c.style.opacity=a?1:0;h=a;g&&g.remove()},h=!1,g;z.addNoDragClickHandler(a.domNode,function(){h||
(c=c||d(),e(!0),setTimeout(function(){g=z.addNoDragClickHandler(c,function(){e(!1);b(c)});k.once(document.body,"touchend",function(){e(!1)})}))},{detectLongPress:!0,ignoreReleaseIfLongPressHappened:!0,longPressCallback:function(){c=c||d();e(!0);b(c);setTimeout(function(){e(!1)})}})}else a.own(k.once(this.domNode,"mouseover",function(){c=c||d();k(c,"click",function(){b(c)})}))},_dataDrillingState:null,_loadStandardDataDrillingView:function(a){var b=a.fieldInfo,d=a.optionName,f=a.calcState,c=a.sectionVisualState,
e=a.animationPromise,h=this;this._dataDrillingState={fieldInfo:b,optionName:d,calcState:f,sectionVisualState:c};this._destroyDrillingSections();this._showDDProgress(!0);return n(function(){var a=h._getDataDrillingPanelDimensions(),c=y.getDataDrilling(h._currentInfographicJson,b.templateName),e=x.getDrillingOptionInfo(h._getCountryID(),c.standardId||b,d,a.w,a.h,f),a=e.enrichInfos;return n(a&&a.length&&h.viewModel.enrichFieldData(a),function(){return e})}(),function(a){return n(h._renderStandardOptionInfo({drillingDataOptionInfo:a,
fieldInfo:b,animationPromise:e,optionName:d,calcState:f,sectionVisualState:c}),function(){h._showDDProgress(!1)})})},_renderStandardOptionInfo:function(a){var b=a.drillingDataOptionInfo,d=a.fieldInfo,f=a.animationPromise,c=a.optionName,e=a.sectionVisualState,h=this,g;this._destroyDrillingSections();var k=this._getDataDrillingPanelSectionParams();k.json={type:F.DETAILS,stack:[b.tableJson]};k.calculationStatesGroup=b.calculationStatesGroup;k.onCalculationStateChanged=function(a){h._loadStandardDataDrillingView({fieldInfo:d,
optionName:c,calcState:a,sectionVisualState:g.getVisualState(),animationPromise:null})};return n(f,function(){return q.delay(function(){g=h._createDataDrillingSection(k);g.fitContentNicely();g.domNode.style.opacity="0.01";return q.delay(function(){g.setVisualState(e);g.domNode.style.opacity="";g.notifyShown()},100)})})},_renderCustomSectionJson:function(a){var b=a.customDDPanelInfo,d=a.animationPromise,f=a.sectionVisualState,c=this;this._destroyDrillingSections();this._dataDrillingState=null;var e,
h=this._getDataDrillingPanelSectionParams();h.json=b.sectionJson;this._showDDProgress(!0);return n(d,function(){return q.delay(function(){e=c._createDataDrillingSection(h);e.fitContentNicely();e.domNode.style.opacity="0.01";return q.delay(function(){e.setVisualState(f);e.domNode.style.opacity="";e.notifyShown();c._showDDProgress(!1)})})})},_getDataDrillingPanelSectionParams:function(){var a={"class":"infographicContainer_dataDrillingSection"};a.initialWidth=this._getDataDrillingPanelDimensions().w;
a.viewModel=this.viewModel;a.theme=this.theme;a.parentWidget=this;a.hasFixedLayout=!1;a.isDataDrillingView=!0;a.currentFeatureIndex=this.currentFeatureIndex||0;a.initialViewMode=G.PREVIEW_VALUES;m.empty(this.dynamicSettingsToolbarRoot);a.dynamicSettingsToolbarRoot=this.dynamicSettingsToolbarRoot;return a},_createDataDrillingSection:function(a){var b=this._getDataDrillingPanelDimensions();a=this.viewModel.layoutBuilder.createElement("section",a,this.drilledDataViewDivScaler);this._drillingSections.push(a);
a.setResizedHeight(b.h);B[C(".sectionDynamicSettings_settingsButton",this.dataDrillingViewDiv)[0]?"add":"remove"](this.dataDrillingViewDiv,"hasChartSettingsButton");this._setUpDDPanelBackgroundColor();b.scale&&(a.notifyPanelScaleChanged(b.scale),this._applyScaleToDataDrillingToolbarButtons(b.buttonScale||b.scale));return a},_applyScaleToDataDrillingToolbarButtons:function(a){var b=1/a;[this.dynamicSettingsToolbarRoot,this.exportButton,this.printButton,this.backToMainViewButton].forEach(function(a,
f){a.style.transformOrigin=this.viewModel.showDataDrillingInsidePanel?"100% 0":"100% 100%";a.style.transform="scale("+b+")";a.style["webkit-transform"]="scale("+b+")";0<f&&(f=(this.viewModel.showDataDrillingInsidePanel?5:26)*b,f+=32*(b-1),a.style.marginLeft=f+"px")},this)},_setUpDDPanelBackgroundColor:function(){var a=this.viewModel.getDocumentDefaultStyles(this.theme),a=a.backgroundImage&&a.backgroundImage.data;this.viewModel.showDataDrillingInsidePanel&&!a||H.setUpDDPanelBackgroundColor({viewModel:this.viewModel,
theme:this.theme,infographicJson:this._currentInfographicJson,node:this.dataDrillingViewDiv})},_getDataDrillingPanelDimensions:function(){if(this.viewModel.showDataDrillingInsidePanel){var a=1/this.parentWidget.parentWidget.parentWidget.parentWidget.getPanelScale(),b=this.width/a,d=this.height/a,f=400>b,c=500>d;this.dataDrillingViewDiv.style.overflowX=f?"auto":"hidden";this.dataDrillingViewDiv.style.overflowY=c?"auto":"hidden";return{scale:a,buttonScale:1/a,w:Math.max(b,400)-(c?l.getScrollbarSize().w/
a:0),h:Math.max(d,500)-(f?l.getScrollbarSize().h/a:0)}}b=document.body.clientWidth-(r.isLandscape()?80:40);d=document.body.clientHeight-80;a=Math.max(.7,Math.min(1,b/400,d/500));return r.isMobileDevice()?{w:b/a,h:d/a,scale:a,yOffset:10,animateFromCenter:!0}:{w:Math.min(b/a,700),h:Math.min(d/a,600),scale:a,yOffset:600<d-30?0:15}},_showDDProgress:function(a){E[a?"showProgress":"removeProgress"](this.viewModel.showDataDrillingInsidePanel?this.domNode:this.dataDrillingViewDiv)},_getDataDrillingState:function(){return this._dataDrillingState},
_setDataDrillingState:function(a){a&&this._loadStandardDataDrillingView({fieldInfo:a.fieldInfo,optionName:a.optionName,calcState:a.calcState,sectionVisualState:a.sectionVisualState,animationPromise:null})},_destroyDrillingSections:function(){this._drillingSections=this._drillingSections||[];this._drillingSections.forEach(function(a){a.destroy()});this._drillingSections.length=0;this.domNode&&m.empty(this.drilledDataViewDivScaler)},_destroyDrillingSectionsButtons:function(){this._drillingSectionsButtons=
this._drillingSectionsButtons||[];this._drillingSectionsButtons.forEach(function(a){a.destroy()});this._drillingSectionsButtons.length=0}})});