// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/lang","dojo/_base/array dojo/_base/json dojo/_base/kernel dojo/_base/lang dojo/date dojo/has dojo/number dojo/date/locale ./kernel".split(" "),function(k,v,w,g,x,y,z,A,n){function r(a,c,b){return[g.isString(a)?a.split(""):a,c||w.global,g.isString(b)?new Function("item","index","array",b):b]}function l(a){return void 0!==a&&null!==a}function p(a){return l(a)?a:""}function m(a,c,b){var d=b.match(/([^\(]+)(\([^\)]+\))?/i),e=g.trim(d[1]);b=c[a];var d=v.fromJson((d[2]?g.trim(d[2]):"()").replace(/^\(/,
"({").replace(/\)$/,"})")),f=d.utcOffset;if(-1===k.indexOf(B,e))e=g.getObject(e),g.isFunction(e)&&(b=e(b,a,c,d));else if("number"===typeof b||"string"===typeof b&&b&&!isNaN(Number(b)))switch(b=Number(b),e){case "NumberFormat":return z.format(b,d);case "DateString":a=new Date(b);if(d.local||d.systemLocale)return d.systemLocale?a.toLocaleDateString()+(d.hideTime?"":" "+a.toLocaleTimeString()):a.toDateString()+(d.hideTime?"":" "+a.toTimeString());a=a.toUTCString();d.hideTime&&(a=a.replace(/\s+\d\d\:\d\d\:\d\d\s+(utc|gmt)/i,
""));return a;case "DateFormat":return a=new Date(b),l(f)&&(a=x.add(a,"minute",a.getTimezoneOffset()-f)),A.format(a,d)}return p(b)}function q(a,c){var b;if(c)for(b in a)a.hasOwnProperty(b)&&(void 0===a[b]?delete a[b]:a[b]instanceof Object&&q(a[b],!0));else for(b in a)a.hasOwnProperty(b)&&void 0===a[b]&&delete a[b];return a}var B=["NumberFormat","DateString","DateFormat"],t=/<\/?[^>]+>/g,u={valueOf:function(a,c){for(var b in a)if(a[b]==c)return b;return null},stripTags:function(a){if(a){var c=typeof a;
if("string"===c)a=a.replace(t,"");else if("object"===c)for(var b in a)(c=a[b])&&"string"===typeof c&&(c=c.replace(t,"")),a[b]=c}return a},substitute:function(a,c,b){var d,e,f;l(b)&&(g.isObject(b)?(d=b.first,e=b.dateFormat,f=b.numberFormat):d=b);if(c&&"${*}"!==c)return g.replace(c,g.hitch({obj:a},function(a,b){a=b.split(":");return 1<a.length?(b=a[0],a.shift(),m(b,this.obj,a.join(":"))):e&&-1!==k.indexOf(e.properties||"",b)?m(b,this.obj,e.formatter||"DateString"):f&&-1!==k.indexOf(f.properties||"",
b)?m(b,this.obj,f.formatter||"NumberFormat"):p(this.obj[b])}),/\$\{([^\}]+)\}/g);c=[];for(var h in a)if(b=a[h],e&&-1!==k.indexOf(e.properties||"",h)?b=m(h,a,e.formatter||"DateString"):f&&-1!==k.indexOf(f.properties||"",h)&&(b=m(h,a,f.formatter||"NumberFormat")),c.push(h+" \x3d "+p(b)+"\x3cbr/\x3e"),d)break;return c.join("")},filter:function(a,c,b){c=r(a,b,c);b={};var d;a=c[0];for(d in a)c[2].call(c[d],a[d],d,a)&&(b[d]=a[d]);return b},startsWith:function(a,c,b){b=b||0;return a.indexOf(c,b)===b},endsWith:function(a,
c,b){if("number"!==typeof b||!isFinite(b)||Math.floor(b)!==b||b>a.length)b=a.length;b-=c.length;a=a.indexOf(c,b);return-1!==a&&a===b},isDefined:l,fixJson:q,isObject:function(a){return a&&"object"===typeof a},isString:function(a){return"string"===typeof a},mixin:function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b]);return a},clone2DArray:function(a){if(a=a?a.slice(0):null){var c,b=a.length;for(c=0;c<b;c++)a[c]=a[c]?a[c].slice(0):null}return a},clone3DArray:function(a){if(a=a?a.slice(0):null){var c,
b=a.length;for(c=0;c<b;c++){a[c]=a[c]?a[c].slice(0):null;var d=a[c];if(d){var e,f=d.length;for(e=0;e<f;e++)d[e]=d[e]?d[e].slice(0):null}}}return a}};y("extend-esri")&&(g.mixin(n,u),n._isDefined=l,n._getParts=r,n._sanitize=q);return u});