// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/RasterFunctionEditor/RFxRasterInput","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/has ../../kernel dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dijit/form/ComboBox dojo/store/Memory ./utils ../analysis/utils dojo/i18n!../../nls/jsapi".split(" "),function(c,d,f,g,h,k,l,m,r,n,p,e,q){c=c([k,l,m],{templateString:"\x3cdiv style\x3d'width:100%'\x3e\x3cdiv data-dojo-type\x3d'dijit/form/ComboBox' data-dojo-attach-point\x3d'_comboBox'data-dojo-attach-event\x3d'onChange: _handleComboBoxChange'\x3e\x3c/div\x3e\x3c/div\x3e",
declaredClass:"esri.dijit.RasterFunctionEditor.RFxRasterInput",allowScalar:!1,selectDefault:!0,showBrowseRasterLayers:!0,constructor:function(a){this.inherited(arguments);d.mixin(this,a);this._i18n=q.widgets.rasterFunctionEditor},startup:function(){this._initStore();this._comboBox.set("validator",d.hitch(this,this.validator));this._comboBox.set("placeHolder",this._i18n.rfxRasterInput.selectLayer);this.on("add-ready-to-use-layer",d.hitch(this,function(a){this.emit("add-layer",a)}));this.inherited(arguments)},
validator:function(a,b){if((b=this._getStoreItems(a))&&0<b.length)return!0;if(this.allowScalar)return!isNaN(+a)},_handleComboBoxChange:function(a){"separator"===a||""===a?this.value?this._comboBox.set("displayedValue",this.value.name):this._comboBox.reset():"browselayers"===a?(this._browseLyrsdlg.browseItems.plugIn.layerTypes=["Image Service"],this._browseLyrsdlg.browseItems.plugIn.checkLayerType=!0,this._browseLyrsdlg.browseItems.plugIn.checkGeometryType=!1,this._browseLyrsdlg.show()):this.value&&
a===this.value.name||(this.value=this.get("value"),this.emit("change",this.value))},getSelectedLayer:function(a){a=a||this._comboBox&&this._comboBox.value;if(null!==a&&void 0!==a&&this._comboBox&&(a=a.name?a:{name:a},a=(a=this._comboBox.store&&this._comboBox.store.query(a))&&a[0]))return this.inputLayers[a.id]},_getFormattedValue:function(a){return null===a||void 0===a?"":a.type&&"scalar"===a.type.toLowerCase()?String(a.value):a.url&&a.name?a.name:a},_setInputLayersAttr:function(a){this.inputLayers=
a;this._initStore()},_setAllowScalarAttr:function(a){this.allowScalar=!!a;this.allowScalar||(this._comboBox.textbox.readOnly=!0)},_setValueAttr:function(a){this.value=a;a=this._getFormattedValue(a);this._comboBox.set("value",a)},_getValueAttr:function(){var a=this._comboBox.value,b=this.getSelectedLayer(a);return b?p.getRasterJsonFromLayer(b):{type:"Scalar",value:+a}},_getStoreItems:function(a){return this._comboBox.store&&this._comboBox.store.query({name:a})},_initStore:function(){var a=[];f.forEach(this.inputLayers,
function(b,c){a.push({id:c,name:b.name,label:b.name,url:b.url})},this);var b=new n({data:a,idProperty:"id"});this._comboBox.set("labelAttr","label");this._comboBox.set("labelType","html");this._comboBox.set("store",b);this._comboBox.reset();e.addReadyToUseLayerOption(this,[this._comboBox]);this.selectDefault&&a.length&&this.set("value",a[0])},_handleBrowseItemsSelect:function(a){a&&a.selection&&e.addAnalysisReadyLayer({item:a.selection,layers:this.inputLayers,layersSelect:this._comboBox,posIncrement:1,
browseDialog:a.dialog||this._browsedlg,widget:this})},_setBrowsePropertiesAttr:function(a){this.map=a.map?a.map:this.map;this.portalUrl=a.portalUrl?a.portalUrl:this.portalUrl;this.portalSelf=a.portalSelf?a.portalSelf:this.portalSelf}});g("extend-esri")&&d.setObject("dijit.RasterFunctionEditor.RFxRasterInput",c,h);return c});