// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/RasterFunctionEditor/RFxWeightedSumTableEditor","dojo/_base/declare dojo/has ../../kernel dojo/i18n!../../nls/jsapi dgrid/OnDemandGrid dgrid/Keyboard dgrid/editor dojo/store/Memory dojo/store/Observable dojo/data/ObjectStore dojo/on dojo/_base/lang dojo/Evented dojo/_base/array dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dijit/form/NumberTextBox dijit/form/Select ./EditableGridMixin ./RFxRasterInput ./utils".split(" "),function(g,n,p,q,r,t,u,h,v,l,G,e,
w,k,x,y,z,A,B,C,D,m){var E=g([r,t]),F=["esriFieldTypeSmallInteger","esriFieldTypeInteger","esriFieldTypeSingle","esriFieldTypeDouble"];g=g([x,y,z,w,C],{templateString:"\x3cdiv\x3e\x3cdiv data-dojo-attach-point\x3d'gridNode'\x3e\x3c/div\x3e\x3c/div\x3e",baseClass:"esriRFxWeightedSumTableEditor",postCreate:function(){this.inherited(arguments);this._i18n=q.widgets.rasterFunctionEditor.rfxWeightedSumTableEditor;this._initStore();this._initGrid();this.attachGridEvents();this.own(this.on("change",e.hitch(this,
this._updateArgValues)))},_updateArgValues:function(){var a=this.inputArgs,c=this._store.data;if(a){var d=a.Rasters,b=a.Weights,f=a.Fields;d&&(d.value=[]);b&&(b.value=[]);f&&(f.value=[]);k.forEach(c,function(a){if("*"!==a.idNum){var c=a.layerSelect.getSelectedLayer(a.layerSelect.value.name);d&&d.value&&d.value.push(m.getRasterJsonFromLayer(c));b&&b.value&&b.value.push(a.weight);f&&f.value&&f.value.push(a.fieldSelect.value)}})}},_readArgValues:function(){if(this.inputArgs){var a,c=0,d=[],b=this.inputArgs,
f=b.Rasters,e=b.Weights,b=b.Fields;if(f&&e&&b&&(a=Math.min(f.value&&f.value.length,e.value&&e.value.length,b.value&&b.value.length),isNaN(a)))return d;for(;c<a;)d.push({layer:m.getLayerIdfromRasterValue(f.value[c],this.inputLayers),idNum:c+1,id:c+1,field:b.value[c],weight:e.value[c]}),c+=1;return d}},_onFieldChange:function(a){a&&a.fieldSelect&&("*"===a.idNum&&this._addBlankObject(),a.weight=1,a.field=a.fieldSelect.value,this._onDataChange())},_onLayerChange:function(a){if(a&&a.fieldSelect&&a.layerSelect){var c=
a.layerSelect,d=a.fieldSelect,b=c.value,c=c.getSelectedLayer(b.name);a.layer=b;c.getRasterAttributeTable({renderingRule:c.renderingRule}).then(e.hitch(this,function(b){b&&b.fields?(a.fieldStore=this._getFieldStore(b.fields),this._updateFieldStore(d,a.fieldStore)):this._updateFieldStore(d)}),e.hitch(this,function(a){this._updateFieldStore(d)}));a.weight=1;"*"===a.idNum&&this._addBlankObject();this._onDataChange()}},_getFieldStore:function(a){return a&&a.length?(a=k.filter(a,function(a){return-1<k.indexOf(F,
a.type)}),new l(new h({data:a,idProperty:"name"}))):new l(new h({data:[{name:"VALUE",alias:this._i18n.value}],idProperty:"name"}))},_initStore:function(){this._store=v(new h({data:this._readArgValues(),idProperty:"id"}))},_initGrid:function(){this._grid=new E({store:this._store,columns:[{field:"idNum",label:this._i18n.id},{field:"layer",label:this._i18n.layer,renderCell:e.hitch(this,function(a,c,d,b){b=new D({inputLayers:this.inputLayers,allowScalar:this.allowScalar,selectDefault:!1,browseProperties:this.browseProperties});
b.on("change",e.hitch(this,this._onLayerChange,a));b.on("add-layer",e.hitch(this,function(a){this.emit("add-layer",a)}));b.placeAt(d);b.startup();""!==c&&b.set("value",c,!1);a.layerSelect=b})},{field:"field",label:this._i18n.field,renderCell:e.hitch(this,function(a,c,d,b){b=new B({labelAttr:"alias",onChange:e.hitch(this,this._onFieldChange,a),store:a.fieldStore||this._getFieldStore()});try{b.attr("value",c,!1)}catch(f){}b.placeAt(d);b.startup();a.fieldSelect=b})},u({field:"weight",label:this._i18n.weight,
editor:A,editorArgs:{required:!0}})]},this.gridNode);this._addBlankObject()},_updateFieldStore:function(a,c){c?a.set("store",c):a.set("store",this._getFieldStore());this._grid.refresh()}});n("extend-esri")&&e.setObject("dijit.RasterFunctionEditor.RFxWeightedSumTableEditor",g,p);return g});