// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/geoenrichment/ReportPlayer/core/templates/InfographicsPage.html":'\x3cdiv class\x3d"esriGEReportPlayer_infographicsPage"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d\'paginationDiv\' class\x3d"esriGEReportPlayer_reportContainerGrid reportContainerPreviewMode"\x3e\x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d\'emptyPlaceholderDiv\' class\x3d"infographicsPage_emptyPlaceholder esriGEAbsoluteStretched esriGEHidden"\x3e${nls.noInfographicsToShow}\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/geoenrichment/ReportPlayer/core/infographics/InfographicsPage","dojo/_base/declare dojo/_base/lang dojo/Deferred dojo/dom-class dojo/dom-construct dojox/uuid/generateRandomUuid dijit/_WidgetBase dijit/_TemplatedMixin esri/dijit/geoenrichment/Pagination esri/dijit/geoenrichment/utils/ColorUtil esri/dijit/geoenrichment/utils/DeviceUtil esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/FitUtil esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/ViewModes ../themes/BackgroundThemeUtil ../supportClasses/templateJsonUtils/query/TemplateJsonQueryUtil ../sections/sectionUtils/SectionJsonUtil dojo/text!../templates/InfographicsPage.html dojo/i18n!esri/nls/jsapi".split(" "),
function(t,h,u,v,g,w,x,y,z,A,p,k,B,C,D,l,E,F,m){function n(a){var b=l.getParentBox(a);return b&&b.w?b:E.calcSectionJsonBox(a)}m=m.geoenrichment.dijit.ReportPlayer.Infographics;var q=p.isMobileDevice()?20:120,r=p.isMobileDevice()?10:60;return t([x,y],{templateString:F,nls:m,viewModel:null,theme:null,parentWidget:null,currentFeatureIndex:null,keepPagePosition:!0,renderBackgroundImage:!1,scaleSectionsToFit:!1,pagination:null,_sections:null,_currentMinWidth:0,_currentMinHeight:0,postCreate:function(){this.inherited(arguments);
this._sections=[];this._createPagination();v[this.scaleSectionsToFit?"add":"remove"](this.domNode,"scaleSectionsToFit")},_createPagination:function(){var a=this;this.pagination=(new z({createItemContainer:h.hitch(this,this._createItemContainer),updateItemContainer:h.hitch(this,this._updateItemContainer),detachChildrenUponHiding:!0,onNodePlaced:h.hitch(this,this._onNodePlaced),scrollAnimation:"slide",cyclicPagination:!0,onPageChanged:function(){a.onPageIndexChanged(a.getCurrentPageIndex())}})).placeAt(this.paginationDiv);
this.own(this.pagination);this.pagination.set("items",[]);this.pagination.startup()},_createItemContainer:function(){var a=g.create("div",{"class":"infographicPage_infographicRoot"});a.style.minWidth=this._currentMinWidth+"px";a.style.minHeight=this._currentMinHeight+"px";return a},_sectionsHash:null,_getSectionByJson:function(a){this._sectionsHash=this._sectionsHash||{};a._idInPagination||(a._idInPagination=w());return this._sectionsHash[a._idInPagination]},_putSectionToHash:function(a,b){this._sectionsHash&&
(this._sectionsHash[b._idInPagination]=a)},_updateItemContainer:function(a,b){this._createSectionNode(a,b)},_createSectionNode:function(a,b){if(a&&a.parentNode){g.empty(a);a.style.minWidth="";a.style.minHeight="";var d=g.create("div",{"class":"infographicPage_infographicRootSectionNode"},a),e=n(b);if(this.scaleSectionsToFit){a.style.width=this._currentMinWidth+2+"px";a.style.height=this._currentMinHeight+2+"px";var f=B.fitBox(e,{w:this._currentMinWidth,h:this._currentMinHeight});d.style.transform=
"scale("+f.ratio+")";d.style.webkitTransform="scale("+f.ratio+")";d.style.position="absolute";d.style.left=(this._currentMinWidth-e.w)/2+"px";d.style.top=(this._currentMinHeight-e.h)/2+"px"}else a.style.width=e.w+2+"px",a.style.height=e.h+2+"px";d.style.width=e.w+"px";d.style.height=e.h+"px";var c=this._getSectionByJson(b);c&&c.domNode?(c.placeAt(d),k.isNodeInLayout(a)&&this._onNodePlaced(a,b)):(c&&c.destroy(),c={"class":"adjustableGrid_inCellSection"},c.json=b,c.viewModel=this.viewModel,c.theme=
this.theme,c.parentWidget=this,c.initialWidth=e.w,c.hasFixedLayout=!1,c.currentFeatureIndex=this.currentFeatureIndex,c.isPagePanelSection=!0,c.initialViewMode=C.PREVIEW_VALUES,c=this.viewModel.layoutBuilder.createElement("section",c,d),this._sections.push(c),a=!l.getParentBox(b),c.setResizedHeight(e.h,{resizeContentProportionally:a}),c.setWidth(e.w,{resizeContentProportionally:a}),this._putSectionToHash(c,b));this._renderNodeBackground(d,b);c.domNode._panelScale=f?f.ratio:1;f&&c.notifyPanelScaleChanged(f.ratio);
return c}},_renderNodeBackground:function(a,b){var d=l.getParentStyle(b),e=this.viewModel.getDocumentDefaultStyles(this.theme);this.renderBackgroundImage&&e?(a=g.create("div",{"class":"esriGEAbsoluteStretched"},a,"first"),D.applyBackgroundImageFromSettings(a,e.backgroundImage,{documentOptions:this.parentWidget.documentOptions,pos:n(b)})||(a.style.backgroundColor=d&&d.backgroundColor&&!A.isTransparent(d.backgroundColor)?d.backgroundColor:e.backgroundColor)):a.style.backgroundColor=d&&d.backgroundColor},
_currentSection:null,_onNodePlaced:function(a,b){(b=this._getSectionByJson(b))&&b.notifyShown();this._currentSection=b;this._isAutoResizeMode&&this._resizePaginationToFitSelectedElement(a)},getCurrentSection:function(){return this._currentSection},getPanelScaleByNode:function(a){var b;this._sections.some(function(d){if(k.isChildOf(a,d.domNode))return b=d.domNode._panelScale,!0});return b},getCurrentPageIndex:function(){return this.pagination.get("currentPage")},setCurrentPageIndex:function(a){this.pagination.set("currentPage",
a)},showNextPage:function(){this.pagination.set("currentPage","next")},showPreviousPage:function(){this.pagination.set("currentPage","prev")},_prevPageState:null,_sectionJsons:null,getNumItems:function(){return this.pagination.items.length},setItems:function(a){return this._setItems(a)},_setItems:function(a,b){function d(){e._resizeContent();f.resolve()}var e=this;this._sectionJsons=a;var f=new u,c=this._prevPageState===b&&this.keepPagePosition,g=this.pagination.get("currentPage");this._calcMinWidthAndHeight();
this._destroySections();this.pagination.set("items",a);this._prevPageState=b;k[a.length?"hide":"show"](this.emptyPlaceholderDiv);c?(this._resizeContent(),this.pagination.set("currentPage",Math.max(g,0)),setTimeout(d,100)):d();return f.promise},_calcMinWidthAndHeight:function(){this.scaleSectionsToFit?(this._currentMinWidth=this._width-q-2,this._currentMinHeight=this._height-r-2):(this._currentMinHeight=this._currentMinWidth=0,this._sectionJsons&&this._sectionJsons.forEach(function(a){a=n(a);this._currentMinWidth=
Math.max(this._currentMinWidth,a.w);this._currentMinHeight=Math.max(this._currentMinHeight,a.h)},this))},setHeight:function(a){this.domNode.style.height=a+"px"},_width:0,_height:0,_isAutoResizeMode:!0,_isResizing:!1,_pendingResizeNode:null,resize:function(a,b){this._width=a;this._height=b;this._resizeContent()},_checkAutoResizeMode:function(){this._isAutoResizeMode=0===this._width&&0===this._height},_resizeContent:function(){this._checkAutoResizeMode();this._isResizing=!0;this._pendingResizeNode=
null;this._isAutoResizeMode?(this.domNode.style.width="auto",this.domNode.style.height="auto",this.paginationDiv.style.width=this._currentMinWidth+"px",this.paginationDiv.style.height=this._currentMinHeight+"px",this.pagination.resize(),this.paginationDiv.style.width="auto",this.paginationDiv.style.height="auto"):(this._calcMinWidthAndHeight(),this.domNode.style.width=this._width+"px",this.domNode.style.height=this._height+"px",this.paginationDiv.style.width=this._width+"px",this.paginationDiv.style.height=
this._height+"px",this.pagination.resize());this._isResizing=!1;if(this._pendingResizeNode&&this._isAutoResizeMode)this._resizePaginationToFitSelectedElement(this._pendingResizeNode);else this.onResized()},_resizePaginationToFitSelectedElement:function(a){this._isAutoResizeMode&&(this._isResizing?this._pendingResizeNode=a:(this._pendingResizeNode=null,this.paginationDiv.style.width=a.clientWidth+q+"px",this.paginationDiv.style.height=a.clientHeight+r+"px",this.onResized(!0)))},notifyShown:function(){this._currentSection&&
this._currentSection.notifyShown()},onPageIndexChanged:function(a){},onResized:function(a){},_destroySections:function(){this._sections.forEach(function(a){a.destroy()});this._sections.length=0},destroy:function(){this._destroySections();this.inherited(arguments)}})});