// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/infographics/InfographicsPageStack","dojo/_base/declare dojo/dom-class dojo/dom-construct dijit/_WidgetBase dijit/_TemplatedMixin ../themes/BackgroundThemeUtil esri/dijit/geoenrichment/utils/async/AsyncQueue esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/ViewModes ../supportClasses/templateJsonUtils/query/TemplateJsonQueryUtil ../sections/sectionUtils/SectionJsonUtil esri/dijit/geoenrichment/utils/ColorUtil dojo/i18n!esri/nls/jsapi".split(" "),
function(m,n,g,p,q,r,t,u,k,v,w,h){function l(a){var b=k.getParentBox(a);return b&&b.w?b:v.calcSectionJsonBox(a)}h=h.geoenrichment.dijit.ReportPlayer.Infographics;return m([p,q],{templateString:"\x3cdiv class\x3d'esriGEReportPlayer_infographicsPageStack'\x3e\x3c/div\x3e",nls:h,viewModel:null,theme:null,parentWidget:null,currentFeatureIndex:null,scaleSectionsToFit:!0,isVertical:!0,_asyncQueue:null,_sections:null,_maxWidth:0,_maxHeight:0,_panelIndexToScaleCache:null,postCreate:function(){this.inherited(arguments);
this._sections=[];this._panelIndexToScaleCache={};!this.isVertical&&n.add(this.domNode,"isHorizontal")},setItems:function(a){var b=this;this._destroySections();this._asyncQueue=new t;this._calcMaxSectionSize(a);a.forEach(function(a,d){b._asyncQueue.add(function(){b._createPanel(a,d)},{delayAfter:0})});return this._asyncQueue.getPromise()},_calcMaxSectionSize:function(a){this._maxHeight=this._maxWidth=0;a.forEach(function(a){if(a=l(a))this._maxWidth=Math.max(this._maxWidth,a.w),this._maxHeight=Math.max(this._maxHeight,
a.h)},this)},_createPanel:function(a,b){var e=g.create("div",{"class":"infographicPageStack_infographicRow "+(this.isVertical?"":"dijitInline")},this.domNode),d=g.create("div",{"class":"infographicPageStack_infographicSectionNode"},e),c={"class":"adjustableGrid_inCellSection"};c.json=a;c.viewModel=this.viewModel;c.theme=this.theme;c.parentWidget=this;c.initialWidth=this._maxWidth;c.hasFixedLayout=!1;c.currentFeatureIndex=this.currentFeatureIndex;c.isPagePanelSection=!0;c.initialViewMode=u.PREVIEW_VALUES;
c=this.viewModel.layoutBuilder.createElement("section",c,d);this._sections.push(c);var f=l(a);c.setResizedHeight(f.h);c.setWidth(f.w);d.style.width=f.w+"px";d.style.height=f.h+"px";this.scaleSectionsToFit?this._scaleSectionToFit(e,d,f,b):d.style.margin="10px";this._renderPanelBackground(d,a,f);this.onSectionCreated(c)},_scaleSectionToFit:function(a,b,e,d){var c;this.isVertical?(c=(this._maxWidth+2)/(e.w+2),a.style.width=this._maxWidth+"px",a.style.height=(e.h+2)*c+"px",a.style.marginBottom="10px"):
(c=(this._maxHeight+2)/(e.h+2),a.style.width=(e.w+2)*c+"px",a.style.height=this._maxHeight+"px",a.style.marginRight="10px");b.style.transform="scale("+c+")";b.style.webkitTransform="scale("+c+")";b.style.position="absolute";b.style.left="0px";b.style.top="0px";b.style.margin="0px";this._panelIndexToScaleCache[d]=c||1},_renderPanelBackground:function(a,b,e){b=k.getParentStyle(b);var d=this.viewModel.getDocumentDefaultStyles(this.theme);d?(a=g.create("div",{"class":"esriGEAbsoluteStretched"},a,"first"),
r.applyBackgroundImageFromSettings(a,d.backgroundImage,{documentOptions:this.parentWidget.documentOptions,pos:e})||(a.style.backgroundColor=b&&b.backgroundColor&&!w.isTransparent(b.backgroundColor)?b.backgroundColor:d.backgroundColor)):a.style.backgroundColor=b&&b.backgroundColor},getSections:function(){return this._sections},getPanelScaleAt:function(a){return this._panelIndexToScaleCache[a]||1},onSectionCreated:function(a){},notifyShown:function(){this._sections.forEach(function(a){a.notifyShown()})},
_destroySections:function(){this._asyncQueue&&this._asyncQueue.destroy();this._asyncQueue=null;this._sections.forEach(function(a){a.destroy()});this._sections.length=0;g.empty(this.domNode)},destroy:function(){this._destroySections();this.inherited(arguments)}})});