// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/map/MapBuilder","dojo/_base/declare dojo/_base/lang dojo/Deferred dojo/when dojo/dom-construct dojo/dom-geometry esri/arcgis/utils esri/graphicsUtils esri/dijit/HomeButton ./layers/MapContentBuilder ./legend/LegendBuilder ./MapLoadTracker ./StaticMap ./WebMapsUtil ./Popup ./Projector ./mobile/MobilePanUtil ../../../dataProvider/supportClasses/AreaDataUtil esri/dijit/geoenrichment/utils/DeviceUtil esri/dijit/geoenrichment/utils/ImageUtil esri/dijit/geoenrichment/utils/UrlUtil".split(" "),
function(k,q,l,h,r,t,u,m,v,w,x,y,z,n,A,p,B,C,D,E,F){k=k(null,{_mapInfos:null,_mapDivId:0,_mapImageInfos:null,renderMapsFromCalculators:!1,constructor:function(b){q.mixin(this,b);this.reset()},setArcgisUrl:function(b){b&&(u.arcgisUrl=F.combine(b,"/sharing/rest/content/items"))},reset:function(){this._mapInfos={};this._mapImageInfos=null},collectAreaMaps:function(b){var a=[];b=b||0;var c=this._mapInfos[b],d;for(d in c){var g=c[d],f=g.node;if(f.parentNode){var e=t.position(f);a.push({areaIndex:b,node:f,
x:e.x,y:e.y,position:-1,map:g.map,legend:g.legend,itemId:g.itemId})}}a.sort(function(a,c){return a.x-c.x});a.sort(function(a,c){return a.y-c.y});a.forEach(function(a,c){a.position=c});return a},collectAllAreasMaps:function(){var b=[],a;for(a in this._mapInfos)b=b.concat(this.collectAreaMaps(a));return b},setFallbackMapImageInfos:function(b){b?(this._mapImageInfos={},b.forEach(function(a){var c=a.areaIndex||0;(this._mapImageInfos[c]=this._mapImageInfos[c]||{})[a.itemId]=a},this)):this._mapImageInfos=
null},createMap:function(b,a){a.areaIndex=a.areaIndex||0;return h(this._doCreateMap(b,a),function(c){return a.waitForLoad?h(y.waitForLoad(c.map),function(){return c}):c})},_doCreateMap:function(b,a){var c=this;if(this.renderMapsFromCalculators&&a.calculatorFieldName){var d=C.getAreaDataValue({fieldName:a.calculatorFieldName,fieldData:a.fieldData,featureIndex:this.currentFeatureIndex});if(d)return this._createStaticMap({url:E.base64DataToDataURL(d)},b,a)}return h(n.getItem(a.webMapId),function(d){if(!d)return(new l).reject(Error("Can't load an item or the item is incorrect."));
var f=new l;try{c._createMapFromItem(d,b,a).then(f.resolve,f.reject)}catch(e){f.reject(e),console.log(e)}return f.promise}).otherwise(this._createFallbackStaticMap.bind(this,a,b))},_createMapFromItem:function(b,a,c){var d=this,g=D.isMobileDevice();return n.createMap(b,a,{defaultBasemapId:c.defaultBasemapId,additionalLayerInfos:c.additionalLayerInfos,mapOptions:{extent:c.extent||m.graphicsExtent(c.features).expand(c.expandFactor||1.5),sliderPosition:!1===c.sliderPosition?"none":c.sliderPosition||"top-right",
infoWindow:new A({getPlayerZoomScale:function(){return d.getPlayerZoomScale(a)}},r.create("div")),isMapNavigation:!g}}).then(function(b){var e=b&&b.map;return e?h(d._setInitialExtent(e,c),function(){return h(w.addLayersToMap(e,{features:c.features,featureIndexToAreaIndexMap:c.featureIndexToAreaIndexMap,analysisAreas:c.analysisAreas,locatorPointsControllers:c.locatorPointsControllers,stdPolygonsControllers:c.stdPolygonsControllers,thisAreasHighlightController:c.thisAreasHighlightController,geClient:c.geClient,
countryID:c.countryID,hierarchy:c.hierarchy,additionalLayerInfos:c.additionalLayerInfos,calculatorFieldName:c.calculatorFieldName,attachmentsStore:c.attachmentsStore}),function(){g&&B.setUpMapPan(e,c.onPanContainer);void 0===a.__mapDivId&&(a.__mapDivId=d._mapDivId++);var b={node:a,map:e,itemId:c.webMapId,legend:null};x.createLegend(e,a,c.legendController,{onCreated:function(a){b.legend=a},onDestroyed:function(){delete b.legend}});var f=(new v({map:e})).placeAt(a);f.startup();f.own(e.on("before-unload",
function(){f.destroy()}));return(d._mapInfos[c.areaIndex]=d._mapInfos[c.areaIndex]||{})[a.__mapDivId]=b})}):(new l).reject(Error("Can't create a map."))})},_setInitialExtent:function(b,a){a=a.extent||m.graphicsExtent(a.features).expand(a.expandFactor||1.5);return p.needProject(a,b)?h(p.projectGeometries(a,b),function(a){return b.setExtent(a)}):b.setExtent(a)},_createFallbackStaticMap:function(b,a){return this._createStaticMap(this._mapImageInfos&&this._mapImageInfos[b.areaIndex]&&this._mapImageInfos[b.areaIndex][b.webMapId],
a,b)},_createStaticMap:function(b,a,c){var d=b&&new z(b,a);return d&&d.load().then(function(){return d.loaded?{node:a,map:d,itemId:c.webMapId,legend:null}:null})},getPlayerZoomScale:function(b){}});k.EXPAND_FACTOR=1.5;return k});