// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/map/WebMapsUtil","dojo/_base/lang dojo/_base/Deferred dojo/when esri/kernel esri/arcgis/utils esri/geometry/Extent esri/request esri/dijit/geoenrichment/utils/UrlUtil".split(" "),function(g,r,l,t,m,p,u,n){var d={};n.isPageRunOnWebService()||(t.id.getCredential=function(){var a=new r;a.reject(Error("Can't get credentials"));return a});var q={_itemsCache:{},_siCache:{},loadItem:function(a){this._itemsCache[a]||(this._itemsCache[a]=m.getItem(a));
return l(this._itemsCache[a],function(a){return a&&g.clone(a)})},loadServiceInfo:function(a,b){this._siCache[a]||(this._siCache[a]=b({url:a,content:{f:"json"}}));return this._siCache[a]}};d.getItem=function(a){return q.loadItem(a)};d.isWebMapType=function(a){return a&&"Web Map"===a.type};d.createMap=function(a,b,e){e=e||{};if(a&&a.item)return d.isWebMapType(a.item)&&e.additionalLayerInfos&&d._addAdditionalLayerInfosToOperationalLayers(a.itemData.operationalLayers,e.additionalLayerInfos),l(!d.isWebMapType(a.item)&&
d.createItemDataForNonWebMapItem(a,{defaultBasemapId:e.defaultBasemapId,additionalLayerInfos:e.additionalLayerInfos}),function(){return m.createMap(a,b,{usePopupManager:!0,mapOptions:e.mapOptions||{}})})};d.createItemDataForNonWebMapItem=function(a,b){function e(){c.url=function(a){["FeatureServer","MapServer","ImageServer"].some(function(f){if(-1!==a.indexOf(f))return a=a.substr(0,a.lastIndexOf(f)+f.length),!0});return a}(c.url);var a=b.requestFunc||u;n.registerCORS(c.url);return q.loadServiceInfo(c.url,
a).then(function(a){return l(function(a,f){a.extent||(f=f.initialExtent||f.fullExtent||f.extent,!f||f instanceof p||(f=new p(f)),a.extent=f)}(c,a),function(){return a})})}function h(f){a.itemData={baseMap:null,operationalLayers:f};b.additionalLayerInfos&&d._addAdditionalLayerInfosToOperationalLayers(f,b.additionalLayerInfos);return l(d.provideDefaultBaseMapForItemData(a.itemData,b),function(){return a})}b=b||{};var c=a.item,k=a.itemData;if("Feature Service"===c.type)return e().then(function(a){for(var f=
[],e=0;e<a.layers.length;e++){var b=a.layers[e],d=b.id;f.unshift({url:c.url+"/"+d,capabilities:a.capabilities||"Query",id:"featureServiceLayer_"+d,visibility:b.defaultVisibility,mode:1,title:b.title,description:b.description})}return h(f)});if("Map Service"===c.type)return e().then(function(a){a=[g.mixin({url:c.url,id:"mapServiceLayer01",visibility:!0,opacity:1,title:a.title},k)];return h(a)});if("Image Service"===c.type)return e().then(function(a){a=[g.mixin({url:c.url,id:"imageServiceLayer01",visibility:!0,
opacity:1,title:a.title},k)];return h(a)});if("Vector Tile Service"===c.type)return e().then(function(a){a=[g.mixin({url:c.url,id:"vectorTileServiceLayer01",visibility:!0,opacity:1,title:a.title},k)];return h(a)});if("WMSServer"===c.type)return e().then(function(a){a=[g.mixin({url:c.url,id:"wmsLayer01",visibility:!0,opacity:1,title:a.title},k)];return h(a)});if("WMTS"===c.type)return e().then(function(a){a=[g.mixin({url:c.url,id:"wmtsLayer01",visibility:!0,opacity:1,title:a.title},k)];return h(a)});
if("WFS"===c.type)return e().then(function(a){a=[g.mixin({url:c.url,id:"wfsLayer01",visibility:!0,opacity:1,title:a.title},k)];return h(a)});if("KML"===c.type){n.registerCORS(c.url);var m=[g.mixin({url:c.url,id:"kmlLayer01",visibility:!0,opacity:1,title:"KML Layer",type:"KML"},k)];return h(m)}};d.provideDefaultBaseMapForItemData=function(a,b){b=b||{};if(!a.baseMap)return l(function(){var a={title:"My basemap",baseMapLayers:[{id:"basemapLayer01",opacity:b.hideBasemap?0:1,visibility:!b.hideBasemap,
url:"http://services.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer"}]};return b.defaultBasemapId?d.getItem(b.defaultBasemapId).then(function(b){return b&&b.itemData&&b.itemData.baseMap||a}):a}(),function(b){a.baseMap=b;return a})};d._addAdditionalLayerInfosToOperationalLayers=function(a,b){b.forEach(function(b,d){a.push({url:b.url,id:"additionalLayer"+d,visibility:!0,opacity:1})})};return d});