// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/dataProvider/supportClasses/AreasPreprocessor","dojo/_base/Color dojo/_base/lang dojo/when dojo/promise/all dojo/string esri/graphic esri/symbols/SimpleFillSymbol esri/symbols/SimpleLineSymbol esri/symbols/jsonUtils ./FeatureNameUtil ./tasks/EnrichAreasTask ./CustomReportsManager esri/dijit/geoenrichment/utils/GeometryUtil esri/dijit/geoenrichment/ReportPlayer/config dojo/i18n!esri/nls/jsapi".split(" "),function(h,k,f,l,v,w,x,m,n,y,p,q,r,g,t){var d={symbolizeFeature:function(b){function c(){var a=
new x;a.setOutline(new m(m.STYLE_SOLID,new h([105,134,68,.55]),2));a.setColor(new h([105,134,68,.55]));return a}b.symbol||b.setSymbol(c())},symbolizeAreas:function(b){b.forEach(function(b){b.feature&&d.symbolizeFeature(b.feature)})}},A={generalize:function(b){var c=[],a=[];b.forEach(function(b,z){!b.feature||b.geographies&&b.geographies.length||(c.push(b.feature),a.push(z))});return f(function(a){function b(a){var b=0;a.geometry.rings.forEach(function(a){b+=a.length});return b}var c,e,u=r.needGeneralizeGeometry(a,
g.generalization.factor,g.generalization.maxVerticesInAllFeatures,g.generalization.numVerticesPerFeature),d;u&&(c=!0,e=[],a=a.map(function(a,c){e.push(b(a));return new w(a.geometry,a.symbol,a.attributes)}),d=r.generalizeGeometry(a,u,g.generalization.numVerticesPerFeature,!0));return f(d,function(){c&&(console.log("Generalize features:"),a.forEach(function(a,c){console.log("#"+c+" "+e[c]+" \x3d\x3e "+b(a))}));return a})}(c),function(c){a.forEach(function(a){b[a].feature=c[a]})})}},B={provideGeographyFeatures:function(b){return f(b.hierarchy||
q.getCustomReportByID(b),function(c){return l(b.analysisAreas.map(function(a){if(!a.feature&&a.geographies&&a.geographies.length)return(new p).createFeatureForGeographies(a.geographies,{countryID:b.countryID,hierarchy:c&&c.hierarchy||c}).then(function(b){a.feature=b;a.name=a.name||a.feature.attributes.StdGeographyName;a.description=a.description||t.geoenrichment.dijit.ReportPlayer.ReportPlayer.geography;a.address=a.address||a.name;a.geographies[0].attributes&&k.mixin(a.feature.attributes,a.geographies[0].attributes);
(b=a.geographies[0].symbol)?(b=b.toJson?b:n.fromJson(b),a.feature.setSymbol(b)):d.symbolizeFeature(a.feature)})}))})}},C={provideBufferFeatures:function(b){var c=this;return f(b.hierarchy||q.getCustomReportByID(b),function(a){var e=b.analysisAreas.filter(function(a){return!a.feature&&a.buffer}),d=e.map(function(a){return a.buffer});return(new p).createFeaturesForBuffers(d,{countryID:b.countryID,hierarchy:a&&a.hierarchy||a}).then(function(a){a.forEach(function(a,b){b=e[b];b.feature=a;c._applyBufferParamsToArea(b)})})})},
_applyBufferParamsToArea:function(b){var c=b.buffer;if(!b.name){var a=t.geoenrichment.dijit.bufferTitle.pointRing;a[c.units]&&(b.name=v.substitute(a[c.units],{radius:c.radius}))}b.description=b.description||"Ring";c.attributes&&k.mixin(b.feature.attributes,c.attributes);(c=c.symbol)?(c=c.toJson?c:n.fromJson(c),b.feature.setSymbol(c)):d.symbolizeFeature(b.feature)}};return{preprocessAreas:function(b,c){b.analysisAreas=b.analysisAreas.filter(function(a){return a.feature&&a.feature.geometry&&"polygon"===
a.feature.geometry.type||a.geographies&&a.geographies.length||a.buffer});-1!==c.analysisAreasLimit&&(c.analysisAreasLimit=c.analysisAreasLimit||10,b.analysisAreas.length=Math.min(b.analysisAreas.length,c.analysisAreasLimit));b.analysisAreas.forEach(function(a){a.feature&&!a.feature.attributes&&(a.feature.attributes={})});b.analysisAreas.forEach(function(a){a.name=a.name||a.shortName;if(!a.name&&a.feature){var b=y.guessFeatureName(a.feature);b&&(a.name=a.shortName=b)}});c.symbolizeAreas&&d.symbolizeAreas(b.analysisAreas);
return f(A.generalize(b.analysisAreas),function(){return l([B.provideGeographyFeatures(b),C.provideBufferFeatures(b)])})}}});