// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/dataProvider/supportClasses/GEUtil","dojo/_base/declare dojo/_base/lang dojo/Deferred dojo/when dojo/promise/all dojox/uuid/generateRandomUuid esri/kernel esri/request esri/urlUtils esri/dijit/geoenrichment/utils/requests/FileContent esri/dijit/geoenrichment/utils/requests/UniversalClient esri/dijit/geoenrichment/utils/UrlUtil ./stdGeographies/StdGeographiesModel".split(" "),function(t,l,m,n,u,v,w,g,x,y,p,z,A){function B(){var a=w.id.credentials[0];return a&&
a.token}function f(a,c){a=x.urlToObject(a);c=l.mixin({f:"json",token:B()},a.query||{},c);for(var d in c){var b=c[d];b instanceof y||b&&"object"===typeof b&&(c[d]=JSON.stringify("function"===typeof b.toJson?b.toJson():b))}return{url:a.path,taskParams:c}}function e(a){h||(h=new r(k));return!a||h.initialized?h:h.initialize()}var r=t(null,{url:null,_geInfo:null,_capabilities:null,_supportedOperations:null,constructor:function(a){this.url=a},_initDfd:null,initialized:!1,initialize:function(){var a=this;
if(this._initDfd)return this._initDfd.promise;this._initDfd=new m;p.requestPublicFirst(f(this.url).url+"/Geoenrichment",{content:{f:"json"},handleAs:"json"}).then(function(c){a.initWithJson(c)});return this._initDfd.promise},initWithJson:function(a){this._geInfo=a;this._capabilities={};this._supportedOperations={};a.capabilities&&a.capabilities.forEach(function(a){this._capabilities[a.toLowerCase()]=!0},this);a.supportedOperations&&a.supportedOperations.forEach(function(a){this._supportedOperations[a.toLowerCase()]=
!0},this);this._initDfd=this._initDfd||new m;this._initDfd.resolve();this.initialized=!0},hasCapability:function(a){return this._capabilities[a.toLowerCase()]},supportsOperation:function(a){return this._supportedOperations[a.toLowerCase()]},enrich:function(a){a=f(this.url,a);a.taskParams.AddDerivativeVariables="all";return g({url:a.url+"/Geoenrichment/Enrich",content:a.taskParams,handleAs:"json"}).then(function(a){return a.results[0].value.FeatureSet||[]})},stdGeographyQuery:function(a){a=f(this.url,
a);return g({url:a.url+"/StandardGeographyQuery/execute",content:a.taskParams,handleAs:"json"}).then(function(a){return a.results[0].value.features||[]})},getDataCollections:function(a,c,d){d=f(this.url,d);return g({url:d.url+"/Geoenrichment/DataCollections/"+a+"/"+(c||"census"),content:d.taskParams,handleAs:"json"}).then(function(a){return a.DataCollections})},_contriesCache:{},getCountries:function(){var a=f(this.url);return g({url:a.url+"/Geoenrichment/Countries",content:a.taskParams,handleAs:"json"}).then(function(a){return a.countries})},
getCountryInfo:function(a){var c=this;if(!this._contriesCache[a]){var d=f(this.url);this._contriesCache[a]=g({url:d.url+"/Geoenrichment/Countries/"+a,content:d.taskParams,handleAs:"json"}).then(function(d){var b=d.countries[0],e={};return u(b.hierarchies.map(function(d){return n(c.getStdGeographyModel(a,d.ID),function(a){e[d.ID]=a})})).then(function(){return{country:b,geographiesModels:e}})})}return this._contriesCache[a]},_stdModelCache:null,getStdGeographyModel:function(a,c){c=c||"census";this._stdModelCache=
this._stdModelCache||{};var d=a+c;if(!this._stdModelCache[d]){var b=f(this.url);this._stdModelCache[d]=g({url:b.url+"/Geoenrichment/StandardGeographyLevels/"+a+"/"+c,content:b.taskParams,handleAs:"json"}).then(function(d){return new A({countryID:a,hierarchyID:c,levels:d.geographyLevels[0].hierarchies[0].levels})})}return this._stdModelCache[d]},formatReport:function(a){a=f(this.url,a);return p.request({url:a.url,urlSuffix:"Geoenrichment/FormatReport"},{handleAs:"bin",content:a.taskParams}).then(function(a){return a&&
a.data&&"text/plain"===a.data.type?null:a})},getReports:function(a){var c=f(this.url);return g({url:c.url+"/Geoenrichment/reports/"+a,content:c.taskParams,handleAs:"json"}).then(function(a){return a.reports})},_tasksHash:{},createReport:function(a){var c=f(this.url,a),d=v();this._tasksHash[d]={taskName:"createReport",taskParams:l.clone(a)};return p.request({url:c.url,urlSuffix:"Geoenrichment/createReport"},{handleAs:"xml"===a.format?"text":"bin",content:c.taskParams}).then(function(a){return{taskID:d,
result:a}})},consumeCredits:function(a){if(a=this._tasksHash[a])return a=l.clone(a),delete a.taskParams.forStorage,this[a.taskName](a.taskParams)},_dataLayersCache:{},getLayerInfos:function(a){this._dataLayersCache[a]||(this._dataLayersCache[a]=this._getLayerInfos(a));return this._dataLayersCache[a]},_getLayerInfos:function(a){var c=f(this.url);return g({url:c.url+"/Geoenrichment/DataLayers/"+a,content:c.taskParams,handleAs:"json"}).then(function(a){return a&&a.layers||[]}).otherwise(function(a){console.log(a);
return[]})},getLayerInfo:function(a,c){var b=a+"_"+c;this._dataLayersCache[b]||(this._dataLayersCache[b]=this._getLayerInfo(a,c));return this._dataLayersCache[b]},_getLayerInfo:function(a,c){var b=f(this.url);return g({url:b.url+"/Geoenrichment/DataLayers/"+a+"/"+c,content:b.taskParams,handleAs:"json"}).then(function(a){return a&&a.layer}).otherwise(function(a){console.log(a);return null})}}),b={},k,q=new m;b.setGeoenrichmentUrl=function(a){(k=a||k)&&z.registerCORS(k);!q.promise.isFulfilled()&&q.resolve()};
b.canMakeRequests=function(){return!!k};b.getInitPromise=function(){return q.promise};b.GEClient=r;var h;b.getClient=function(){return e()};b.initialize=function(){return e(!0)};b.initWithJson=function(a,c){b.setGeoenrichmentUrl(a);e().initWithJson(c)};b.enrich=function(a){return e().enrich(a)};b.stdGeographyQuery=function(a){return e().stdGeographyQuery(a)};b.getDataCollections=function(a,b,d){return e().getDataCollections(a,b,d)};b.formatReport=function(a){return e().formatReport(a)};b.createReport=
function(a){return e().createReport(a)};b.consumeCredits=function(a){return e().consumeCredits(a)};b.getLayerInfos=function(a){return e().getLayerInfos(a)};b.hasCapability=function(a){return n(e(!0),function(){return h&&h.hasCapability(a)})};b.supportsOperation=function(a){return n(e(!0),function(){return h&&h.supportsOperation(a)})};b.getCountryInfo=function(a){return e().getCountryInfo(a)};b.getStdGeographyModel=function(a,b){return e().getStdGeographyModel(a,b)};return b});