// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/utils/htmlToSvg/supportClasses/text/TextMeasurer","dojo/dom-construct dojo/dom-geometry ../dom-style ./TextStyleBuilder ../TransformUtil ./FlowCalculator ./ReplaceUtil ./SiblingsUtil".split(" "),function(g,q,f,z,v,A,w,x){var m={_linesNode:null,_wordNode:null,createTempLinesNode:function(a){this._linesNode=this._linesNode||this._createTempNode();return this._styleNode(this._linesNode,a,!0)},createTempWordNode:function(a){this._wordNode=this._wordNode||this._createTempNode();
return this._styleNode(this._wordNode,a)},_createTempNode:function(){var a=g.create("div",null,document.body);f.set(a,{position:"absolute",display:"inline-block"});return a},_styleNode:function(a,c,b){z.resetTextStyle(a);f.set(a,"width",b?c.style.cw+"px":"");f.set(a,"display","inline-block");f.set(a,c.style.getTextStyleObject());return a},dispose:function(a){a&&f.set(a,"display","none")},cleanUp:function(){this._linesNode&&g.destroy(this._linesNode);this._linesNode=null;this._wordNode&&g.destroy(this._wordNode);
this._wordNode=null}},B={getParagraphs:function(a,c){function b(a){return w.collapseMultipleSpaces(a.trim())}var d=c.style.getTextStyle("whiteSpace");(c="pre-wrap"===d||"pre"===d||"pre-line"===d)||(a=w.removeReturns(a));(d="pre-wrap"===d||"pre"===d)||(a=b(a));a=c?a.split(String.fromCharCode(10)):[a];1<a.length&&!d&&(a=a.map(b));return a}},t={measureWidth:function(a,c){c.innerHTML=a;return f.get(c,"width")}},h={getLinesForWords:function(a,c,b,d){function f(){var a=b.innerHTML;b.innerHTML="";a=a.split("");
return h.getLinesForWords(a,c,b,{checkBreaking:!1,separator:""}).lines}function p(a){a=a.split("");return h.getLinesForWords(a,c,b,{checkBreaking:!1,separator:"",clearLinesNodeBeforeMeasure:!d.isBreakAll}).lines}var e,u,n=0;d.checkBreaking&&(b.innerHTML="a",u=q.position(b).h);var k=0,l="";d.clearLinesNodeBeforeMeasure&&(b.innerHTML="");a.some(function(a){if(e){var m;d.checkBreaking&&(m=b.innerHTML);b.innerHTML+=d.separator+a;var r=q.position(b).h;if(0<k&&r>k){e.push({text:l,w:t.measureWidth(l,c),
lineHeight:n});var y;if(d.checkBreaking&&(r-k>1.2*u||d.isBreakAll)){b.innerHTML=l+d.separator;var g=p(a);b.innerHTML=m+d.separator+a;1<g.length&&(y=!0,g.forEach(function(a,b){b<g.length-1?0===b&&d.isBreakAll?(b=e[e.length-1],b.text+=d.separator+a.text,b.w=t.measureWidth(b.text,c)):e.push(a):(n=a.lineHeight,l=a.text)}),k=r)}y||(l=a,n=r-k,k=r)}else l+=d.separator+a,0===k&&(n=k=q.position(b).h)}else if(e=[],b.innerHTML=d.clearLinesNodeBeforeMeasure?a:b.innerHTML+a,l=a,n=k=q.position(b).h,d.checkBreaking&&
k>1.2*u){var h=f();1<h.length&&h.forEach(function(a,b){b<h.length-1?e.push(a):(n=a.lineHeight,l=a.text)})}});e.push({text:l,w:t.measureWidth(l,c),lineHeight:n});a=q.position(b).w;return{lines:e,textWidth:a,lineHeight:n}}},C={getLinesForParagraph:function(a,c,b,d){a=a.split(" ");var f="break-word"===c.style.getTextStyle("overflowWrap");c="break-all"===c.style.getTextStyle("wordBreak");return h.getLinesForWords(a,b,d,{checkBreaking:f||c,isBreakAll:c,clearLinesNodeBeforeMeasure:!0,separator:" "})}},
p={_node:null,_originalInnerHTML:null,_nextSiblingsHideInfo:null,setNode:function(a){this._node=a;this._nextSiblingsHideInfo=this._originalInnerHTML=null},doPresets:function(){this._originalInnerHTML=this._node.innerHTML;this.hideNextSibling()},undoPresets:function(){this.showNextSibling();this._node.innerHTML=this._originalInnerHTML},hideNextSibling:function(){this._nextSiblingsHideInfo||(this._nextSiblingsHideInfo=x.hideNextSiblings(this._node))},showNextSibling:function(){x.showNextSiblings(this._nextSiblingsHideInfo);
this._nextSiblingsHideInfo=null}};return{getLines:function(a,c,b){if(a.innerHTML&&a.innerHTML.trim()){b=v.disableTransform(a,c.parentVs);p.setNode(a);p.doPresets();var d=c.isSpanLike?a:m.createTempLinesNode(c),f=m.createTempWordNode(c),g,e=[];B.getParagraphs(a.innerHTML,c).forEach(function(a){a=C.getLinesForParagraph(a,c,f,d);g=a.textWidth;e=e.concat(a.lines)});if(c.isSpanLike){d.innerHTML=p._originalInnerHTML;a=q.position(d).h;p.showNextSibling();var h=q.position(d).h;h>a&&(e[e.length-1].lineHeight+=
(h-a)/2);p.hideNextSibling()}p.undoPresets();m.dispose(f);!c.isSpanLike&&m.dispose(d);v.restoreTransform(b);return{lines:e,textWidth:g}}},getSpanFlowOffsets:function(a,c){return A.getSpanFlowOffsets(a,c)},cleanUp:function(){m.cleanUp()}}});