// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
require({cache:{"esri/layers/labelLayerUtils/DynamicLabelClass":function(){define("dojo/_base/declare dojo/_base/lang dojo/has ../../kernel ../../geometry/Extent ../../geometry/Polygon".split(" "),function(C,B,H,E,D,F){C=C(null,{declaredClass:"esri.layers.labelLayerUtils.DynamicLabelClass",constructor:function(){this._preparedLabels=[];this._placedLabels=[];this._extent=null;this._y1=this._x1=this._y0=this._x0=this._ymax=this._ymin=this._xmax=this._xmin=0;this._scale=1},setMap:function(m,b){this._labelLayer=
b;this._xmin=m.extent.xmin;this._xmax=m.extent.xmax;this._ymin=m.extent.ymin;this._ymax=m.extent.ymax;this._scale=(this._xmax-this._xmin)/m.width},_process:function(m){this._preparedLabels=m;this._placedLabels=[];var b;for(m=this._preparedLabels.length-1;0<=m;m--){var a=this._preparedLabels[m],c=Math.min(a.labelWidth,a.labelHeight),h=a.labelWidth+0*c,c=a.labelHeight+0*c,g=(b=a.options)&&void 0!==b.lineLabelPlacement?b.lineLabelPlacement:"PlaceAtCenter",e=b&&void 0!==b.lineLabelPosition?b.lineLabelPosition:
"Above",f=b&&void 0!==b.pointPriorities?b.pointPriorities:"AboveRight",d=[2,2,1,3,0,2,3,3,2];"AboveLeft"==f?d=[1,2,2,2,0,3,2,3,3]:"AboveCenter"==f?d=[2,1,2,2,0,2,3,3,3]:"AboveRight"==f?d=[2,2,1,3,0,2,3,3,2]:"CenterLeft"==f?d=[2,2,3,1,0,3,2,2,3]:"CenterCenter"==f?d=[0,0,0,0,1,0,0,0,0]:"CenterRight"==f?d=[3,2,2,3,0,1,3,2,2]:"BelowLeft"==f?d=[2,3,3,2,0,3,1,2,2]:"BelowCenter"==f?d=[3,3,3,2,0,2,2,1,2]:"BelowRight"==f&&(d=[3,3,2,3,0,2,2,2,1]);var k=b&&void 0!==b.labelRotation?b.labelRotation:!0,f=Math.PI/
180*a.angle;b=b&&void 0!==b.howManyLabels?b.howManyLabels:"OneLabel";if("point"==a.geometry.type)this._generatePointPositions(a,a.geometry.x,a.geometry.y,a.text,f,h,c,a.symbolWidth,a.symbolHeight,d);else if("multipoint"==a.geometry.type)for(g=a.geometry,e=0;e<g.points.length;e++)this._generatePointPositions(a,g.points[e][0],g.points[e][1],a.text,f,h,c,a.symbolWidth,a.symbolHeight,d);else"polyline"==a.geometry.type?this._generateLinePositions(a,a.geometry,a.text,h,c,2*a.symbolHeight+c,g,e,k):"polygon"==
a.geometry.type&&this._generatePolygonPositions(a,b,a.geometry,a.text,f,h,c)}return this._placedLabels},_generatePointPositions:function(m,b,a,c,h,g,e,f,d,k){f=(f+g)*this._scale;d=(d+e)*this._scale;var n,p;for(n=1;3>=n;n++)for(p=1;9>=p;p++)if(k[p-1]==n)switch(p){case 1:if(this._findPlace(m,c,b-f,a+d,h,g,e))return;break;case 2:if(this._findPlace(m,c,b,a+d,h,g,e))return;break;case 3:if(this._findPlace(m,c,b+f,a+d,h,g,e))return;break;case 4:if(this._findPlace(m,c,b-f,a,h,g,e))return;break;case 5:if(this._findPlace(m,
c,b,a,h,g,e))return;break;case 6:if(this._findPlace(m,c,b+f,a,h,g,e))return;break;case 7:if(this._findPlace(m,c,b-f,a-d,h,g,e))return;break;case 8:if(this._findPlace(m,c,b,a-d,h,g,e))return;break;case 9:if(this._findPlace(m,c,b+f,a-d,h,g,e))return}},_generateLinePositions:function(m,b,a,c,h,g,e,f,d){var k=c*this._scale*c*this._scale,n,p,l;for(n=0;n<b.paths.length;n++){var x=b.paths[n],r=x.length,q=Math.floor((r-1)/2),w=0!==(r-1)%2?1:-1;"PlaceAtStart"==e&&(q=0,w=1);"PlaceAtEnd"==e&&(q=r-2,w=-1);for(;0<=
q&&q<r-1;){for(p=q;p<r;p++){var v=x[q][0],t=x[q][1],y=x[p][0]-v,u=x[p][1]-t;if(y*y+u*u>k){for(var z=Math.atan2(u,y);z>Math.PI/2;)z-=Math.PI;for(;z<-(Math.PI/2);)z+=Math.PI;var A=Math.sin(z),G=Math.cos(z),I=0,J=0;"Above"==f&&(I=g*A*this._scale,J=g*G*this._scale);"Below"==f&&(I=-g*A*this._scale,J=-g*G*this._scale);if(1==p-q){if(this._clipLine(v,t,x[p][0],x[p][1])&&(v=this._x1-this._x0,l=this._y1-this._y0,v*v+l*l>k&&(p=Math.atan2(l,v),y=c/2+2*h,t=y*this._scale*Math.cos(p),y=y*this._scale*Math.sin(p),
"PlaceAtStart"==e?(v=this._x0+t,l=this._y0+y):"PlaceAtEnd"==e?(v=this._x1-t,l=this._y1-y):(v=this._x0+v/2,l=this._y0+l/2),this._findPlace(m,a,v-I,l+J,d?-p:0,c,h))))return}else{var K=0;for(l=q;l<=p;l++)K=Math.max(K,Math.abs((x[l][1]-t)*G-(x[l][0]-v)*A));if(K<h&&this._findPlace(m,a,v+y/2-I,t+u/2+J,d?-z:0,c,h))return}break}}q+=w}}},_generatePolygonPositions:function(m,b,a,c,h,g,e){var f;if("ManyLabels"==b)for(b=0;b<a.rings.length;b++)f=a.rings[b],F.prototype.isClockwise(f)&&(f=this._findCentroid(f,this._xmin,
this._ymin,this._xmax,this._ymax),this._findPlace(m,c,f[0],f[1],h,g,e));else{f=this._findCentroidForFeature(a,this._xmin,this._ymin,this._xmax,this._ymax);var d=f[1],k=0;for(b=0;10>b;b++){k+=e/4;f=this._findCentroidForFeature(a,this._xmin,d+(k-e/4),this._xmax,d+(k+e/4));if(this._findPlace(m,c,f[0],f[1],h,g,e))break;f=this._findCentroidForFeature(a,this._xmin,d-(k+e/4),this._xmax,d-(k-e/4));if(this._findPlace(m,c,f[0],f[1],h,g,e))break}}},_findCentroid:function(m,b,a,c,h){var g=m.length,e=[0,0],f=
0,d=m[0][0],k=m[0][1];d>c&&(d=c);d<b&&(d=b);k>h&&(k=h);k<a&&(k=a);for(var n=1;n<g-1;n++){var p=m[n][0],l=m[n][1],x=m[n+1][0],r=m[n+1][1];p>c&&(p=c);p<b&&(p=b);l>h&&(l=h);l<a&&(l=a);x>c&&(x=c);x<b&&(x=b);r>h&&(r=h);r<a&&(r=a);var q=(p-d)*(r-k)-(x-d)*(l-k);e[0]+=q*(d+p+x);e[1]+=q*(k+l+r);f+=q}e[0]/=3*f;e[1]/=3*f;if(isNaN(e[0])||isNaN(e[1]))return e;a=[];this._fillBuffer(m,a,e);e[0]=this._sortBuffer(a,e[0],b,c);return e},_findCentroidForFeature:function(m,b,a,c,h){for(var g,e=0,f=[0,0],d=0;d<m.rings.length;d++){var k=
m.rings[d],n=k.length,p=k[0][0],l=k[0][1];p>c&&(p=c);p<b&&(p=b);l>h&&(l=h);l<a&&(l=a);for(g=1;g<n-1;g++){var x=k[g][0],r=k[g][1],q=k[g+1][0],w=k[g+1][1];x>c&&(x=c);x<b&&(x=b);r>h&&(r=h);r<a&&(r=a);q>c&&(q=c);q<b&&(q=b);w>h&&(w=h);w<a&&(w=a);var v=(x-p)*(w-l)-(q-p)*(r-l);f[0]+=v*(p+x+q);f[1]+=v*(l+r+w);e+=v}}f[0]/=3*e;f[1]/=3*e;if(isNaN(f[0])||isNaN(f[1]))return f;a=[];for(g=0;g<m.rings.length;g++)this._fillBuffer(m.rings[g],a,f);f[0]=this._sortBuffer(a,f[0],b,c);return f},_fillBuffer:function(m,b,
a){for(var c=m.length-1,h=m[0][1]>=m[c][1]?1:-1,g=0;g<=c;g++){var e=g,f=g+1;g==c&&(f=0);var d=m[e][0],e=m[e][1],k=m[f][0],f=m[f][1],n=f>=e?1:-1;if(e<=a[1]&&a[1]<=f||f<=a[1]&&a[1]<=e)a[1]!=e&&a[1]!=f?(b.push((a[1]-e)*(k-d)/(f-e)+d),h=n):a[1]==e&&a[1]!=f?(h!=n&&b.push(d),h=n):a[1]!=e&&a[1]==f?(b.push(k),h=n):a[1]==e&&a[1]==f&&(1==h&&b.push(d),b.push(k),h=n)}},_sortBuffer:function(m,b,a,c){var h=m.length;m.sort();if(0<h){for(var g=0,e=b=0;e<h-1;e+=2){var f=Math.abs(m[e+1]-m[e]);!(m[e]<=a&&m[e+1]<=a||
m[e]>=c&&m[e+1]>=c)&&f>g&&(g=f,b=e)}h=m[b];m=m[b+1];h>c&&(h=c);h<a&&(h=a);m>c&&(m=c);m<a&&(m=a);b=(h+m)/2}return b},_findPlace:function(m,b,a,c,h,g,e){if(isNaN(a)||isNaN(c))return!1;for(var f=0;f<this._placedLabels.length;f++){var d=this._placedLabels[f].angle,k=this._placedLabels[f].width*this._scale,n=this._placedLabels[f].height*this._scale,p=this._placedLabels[f].x-a,l=this._placedLabels[f].y-c;if(0===h&&0===d){if(this._findPlace2(-g*this._scale,-e*this._scale,g*this._scale,e*this._scale,p-k,
l-n,p+k,l+n))return!1}else{var x=new D(-g*this._scale,-e*this._scale,g*this._scale,e*this._scale,null),r=0,q=1;0!==h&&(r=Math.sin(h),q=Math.cos(h));var w=p*q-l*r,p=p*r+l*q,d=d-h,r=Math.sin(d),q=Math.cos(d),v=-k*q- -n*r,l=-k*r+-n*q,d=+k*q- -n*r,t=+k*r+-n*q,k=w+v,n=p-l,r=w+d,q=p-t,v=w-v,l=p+l,w=w-d,p=p+t,d=new F;d.addRing([[k,n],[r,q],[v,l],[w,p],[k,n]]);if(x.intersects(d))return!1}}for(;h>Math.PI/2;)h-=Math.PI;for(;h<-(Math.PI/2);)h+=Math.PI;f={};f.layer=m;f.text=b;f.angle=h;f.x=a;f.y=c;f.width=g;
f.height=e;this._placedLabels.push(f);return!0},_findPlace2:function(m,b,a,c,h,g,e,f){return(m>=h&&m<=e||a>=h&&a<=e||m<=h&&a>=e)&&(b>=g&&b<=f||c>=g&&c<=f||b<=g&&c>=f)?!0:!1},_clipLine:function(m,b,a,c){for(var h=this._code(m,b),g=this._code(a,c);0!==h||0!==g;){if(0!==(h&g))return!1;var e=a-m,f=c-b;0!==h?(m<this._xmin?(b+=f*(this._xmin-m)/e,m=this._xmin):m>this._xmax?(b+=f*(this._xmax-m)/e,m=this._xmax):b<this._ymin?(m+=e*(this._ymin-b)/f,b=this._ymin):b>this._ymax&&(m+=e*(this._ymax-b)/f,b=this._ymax),
h=this._code(m,b)):(a<this._xmin?(c+=f*(this._xmin-a)/e,a=this._xmin):a>this._xmax?(c+=f*(this._xmax-a)/e,a=this._xmax):c<this._ymin?(a+=e*(this._ymin-c)/f,c=this._ymin):c>this._ymax&&(a+=e*(this._ymax-c)/f,c=this._ymax),g=this._code(a,c))}this._x0=m;this._y0=b;this._x1=a;this._y1=c;return!0},_code:function(m,b){var a=0;m<this._xmin&&(a+=8);m>this._xmax&&(a+=4);b<this._ymin&&(a+=2);b>this._ymax&&(a+=1);return a}});H("extend-esri")&&B.setObject("layers.labelLayerUtils.DynamicLabelClass",C,E);return C})},
"esri/layers/labelLayerUtils/StaticLabelClass":function(){define("dojo/_base/declare dojo/_base/lang dojo/has ../../kernel ../../geometry/Extent ../../geometry/Point ../../geometry/Polygon".split(" "),function(C,B,H,E,D,F,m){return C(null,{declaredClass:"esri.layers.labelLayerUtils.StaticLabel",constructor:function(){this._preparedLabels=[];this._placedLabels=[];this._extent=null;this._ymax=this._ymin=this._xmax=this._xmin=0;this._scale=1;this._LINE_STEP_CONST=1.5;this._POLYGON_X_STEP_CONST=1;this._POLYGON_Y_STEP_CONST=
.75;this._OVERRUN=2},setMap:function(b,a){this._labelLayer=a;this._map=b;this._xmin=b.extent.xmin;this._xmax=b.extent.xmax;this._ymin=b.extent.ymin;this._ymax=b.extent.ymax;this._scale=(this._xmax-this._xmin)/b.width},_process:function(b){var a,c,h,g,e,f,d,k,n;this._preparedLabels=b;this._placedLabels=[];for(b=this._preparedLabels.length-1;0<=b;b--){a=this._preparedLabels[b];e=a.labelWidth;f=a.labelHeight;k=(d=a.options)&&d.lineLabelPlacement?d.lineLabelPlacement:"PlaceAtCenter";n=d&&d.lineLabelPosition?
d.lineLabelPosition:"Above";c=d&&d.labelRotation?d.labelRotation:!0;h=Math.PI/180*a.angle;g=d&&d.howManyLabels?d.howManyLabels:"OneLabel";var p=[];if("point"===a.geometry.type)this._generatePointPositions(a.geometry.x,a.geometry.y,a.text,h,e,f,a.symbolWidth,a.symbolHeight,d,p);else if("multipoint"===a.geometry.type)for(c=0;c<a.geometry.points.length;c++)this._generatePointPositions(a.geometry.points[c][0],a.geometry.points[c][1],a.text,h,e,f,a.symbolWidth,a.symbolHeight,d,p);else if("polyline"===
a.geometry.type)if("PlaceAtStart"===k)this._generateLinePositionsPlaceAtStart(a.geometry,!0,a.text,e,f,2*a.symbolHeight+f,k,n,c,p);else if("PlaceAtEnd"===k)this._generateLinePositionsPlaceAtEnd(a.geometry,!0,a.text,e,f,2*a.symbolHeight+f,k,n,c,p);else{d=[];var l=a.geometry.getExtent(),x=this._map.extent;if(l.getWidth()<e*this._scale/this._OVERRUN&&l.getHeight()<e*this._scale/this._OVERRUN)continue;else.5*l.getWidth()<x.getWidth()&&.5*l.getHeight()<x.getHeight()?this._generateLinePositionsPlaceAtCenter(a.geometry,
!1,.1*Math.min(this._map.width,this._map.height)*this._scale,a.text,e,f,2*a.symbolHeight+f,k,n,c,d):this._generateLinePositionsPlaceAtCenter(a.geometry,!0,.2*Math.min(this._map.width,this._map.height)*this._scale,a.text,e,f,2*a.symbolHeight+f,k,n,c,d);this._postSorting(x,d,p)}else if("polygon"===a.geometry.type){k=[];for(c=0;c<a.geometry.rings.length;c++)n=a.geometry.rings[c],1<a.geometry.rings.length&&!m.prototype.isClockwise(n)||(d=this._calcRingExtent(n),d.xmax-d.xmin<4*e*this._scale/this._OVERRUN&&
d.ymax-d.ymin<4*f*this._scale/this._OVERRUN||k.push(n));k.sort(function(a,b){return b.length-a.length});for(c=0;c<k.length;c++)this._generatePolygonPositionsForManyLabels(k[c],a.geometry.spatialReference,a.text,h,e,f,p)}for(c=0;c<p.length&&(k=p[c].x,n=p[c].y,void 0!==p[c].angle&&(h=p[c].angle),d=this._findPlace(a,a.text,k,n,h,e,f),"OneLabel"!==g||!d||!this._labelLayer._isWithinScreenArea(new F(k,n,a.geometry.spatialReference)));c++);}return this._placedLabels},_generatePointPositions:function(b,a,
c,h,g,e,f,d,k,n){c=k&&k.pointPriorities?k.pointPriorities:"AboveRight";g=(f+g)*this._scale;e=(d+e)*this._scale;switch(c.toLowerCase()){case "aboveleft":b-=g;a+=e;break;case "abovecenter":a+=e;break;case "aboveright":b+=g;a+=e;break;case "centerleft":b-=g;break;case "centercenter":break;case "centerright":b+=g;break;case "belowleft":b-=g;a-=e;break;case "belowcenter":a-=e;break;case "belowright":b+=g;a-=e;break;default:return}n.push({x:b,y:a})},_generateLinePositionsPlaceAtStart:function(b,a,c,h,g,
e,f,d,k,n){f=h*this._scale;var p=this._LINE_STEP_CONST*Math.min(this._map.width,this._map.height)*this._scale,l,m,r,q,w,v,t,y;for(l=0;l<b.paths.length;l++){var u=b.paths[l],z=f,A=0;for(m=0;m<u.length-1;m++)r=u[m][0],q=u[m][1],w=u[m+1][0],v=u[m+1][1],t=w-r,y=v-q,t=Math.sqrt(t*t+y*y),A+t>z?(A=this._generatePositionsOnLine(b.spatialReference,a,z,p,A,r,q,w,v,c,h,g,e,d,k,n),z=p):A+=t}},_generateLinePositionsPlaceAtEnd:function(b,a,c,h,g,e,f,d,k,m){f=h*this._scale;var p=this._LINE_STEP_CONST*Math.min(this._map.width,
this._map.height)*this._scale,l,n,r,q,w,v,t,y;for(l=0;l<b.paths.length;l++){var u=b.paths[l],z=f,A=0;for(n=u.length-2;0<=n;n--)r=u[n+1][0],q=u[n+1][1],w=u[n][0],v=u[n][1],t=w-r,y=v-q,t=Math.sqrt(t*t+y*y),A+t>z?(A=this._generatePositionsOnLine(b.spatialReference,a,z,p,A,r,q,w,v,c,h,g,e,d,k,m),z=p):A+=t}},_generateLinePositionsPlaceAtCenter:function(b,a,c,h,g,e,f,d,k,m,p){var l,n,r,q,w,v,t,y;for(d=0;d<b.paths.length;d++){var u=b.paths[d];if(!(2>u.length)){if(2==u.length){q=u[0];l=u[1];r=q[0];q=q[1];
u=l[0];v=l[1];w=(u-r)*(u-r)+(v-q)*(v-q);t=Math.atan2(v-q,u-r);v=Math.cos(t);t=Math.sin(t);u=[];y=r;for(var z=q;(y-r)*(y-r)+(z-q)*(z-q)<w;)u.push([y,z]),y+=c/2*v,z+=c/2*t;u.push(l)}var A=0;for(l=0;l<u.length-1;l++)r=u[l][0],q=u[l][1],w=u[l+1][0],v=u[l+1][1],t=w-r,y=v-q,A+=Math.sqrt(t*t+y*y);for(l=z=0;l<u.length-1;l++){r=u[l][0];q=u[l][1];w=u[l+1][0];v=u[l+1][1];t=w-r;y=v-q;t=Math.sqrt(t*t+y*y);if(z+t>A/2)break;z+=t}l==u.length-1&&l--;r=u[l][0];q=u[l][1];w=u[l+1][0];v=u[l+1][1];t=w-r;y=v-q;z=A/2-z;
t=Math.atan2(y,t);y=r+z*Math.cos(t);t=q+z*Math.sin(t);r=this._angleAndShifts(r,q,w,v,f,k,m);p.push({x:y+r.shiftX,y:t+r.shiftY,angle:r.angle});var A=y,G=t,z=0;for(n=l;n<u.length-1;n++)n==l?(r=A,q=G):(r=u[n][0],q=u[n][1]),w=u[n+1][0],v=u[n+1][1],t=w-r,y=v-q,t=Math.sqrt(t*t+y*y),z=z+t>c?this._generatePositionsOnLine(b.spatialReference,a,c,c,z,r,q,w,v,h,g,e,f,k,m,p):z+t;z=0;for(n=l;0<=n;n--)n==l?(r=A,q=G):(r=u[n+1][0],q=u[n+1][1]),w=u[n][0],v=u[n][1],t=w-r,y=v-q,t=Math.sqrt(t*t+y*y),z=z+t>c?this._generatePositionsOnLine(b.spatialReference,
a,c,c,z,r,q,w,v,h,g,e,f,k,m,p):z+t}}},_generatePositionsOnLine:function(b,a,c,h,g,e,f,d,k,n,p,l,m,r,q,w){n=Math.atan2(k-f,d-e);p=e;l=f;var v=p,t=l;do if(g=c-g,p+=g*Math.cos(n),l+=g*Math.sin(n),this._belongs(p,l,e,f,d,k))g=this._angleAndShifts(e,f,d,k,m,r,q),c=p+g.shiftX,t=l+g.shiftY,a?this._labelLayer._isWithinScreenArea(new D(c,t,c,t,b))&&w.push({x:c,y:t,angle:g.angle}):w.push({x:c,y:t,angle:g.angle}),v=p,t=l,g=0,c=h;else return b=d-v,k-=t,Math.sqrt(b*b+k*k);while(1)},_postSorting:function(b,a,c){if(b&&
0<a.length){var h=.5*(b.xmin+b.xmax);b=.5*(b.ymin+b.ymax);for(var g=a[0].x,e=a[0].y,f=Math.sqrt((g-h)*(g-h)+(e-b)*(e-b)),d=a[0].angle,k=0;k<a.length;k++){var n=a[k].x,m=a[k].y,l=Math.sqrt((n-h)*(n-h)+(m-b)*(m-b));l<f&&(g=n,e=m,f=l,d=a[k].angle)}c.push({x:g,y:e,angle:d})}},_belongs:function(b,a,c,h,g,e){if(g==c&&e==h)return!1;if(g>c){if(b>g||b<c)return!1}else if(b<g||b>c)return!1;if(e>h){if(a>e||a<h)return!1}else if(a<e||a>h)return!1;return!0},_angleAndShifts:function(b,a,c,h,g,e,f){for(b=Math.atan2(h-
a,c-b);b>Math.PI/2;)b-=Math.PI;for(;b<-(Math.PI/2);)b+=Math.PI;h=Math.sin(b);var d=Math.cos(b);c=a=0;"Above"==e&&(a=g*h*this._scale,c=g*d*this._scale);"Below"==e&&(a=-g*h*this._scale,c=-g*d*this._scale);g=[];g.angle=f?-b:0;g.shiftX=-a;g.shiftY=c;return g},_generatePolygonPositionsForManyLabels:function(b,a,c,h,g,e,f){g=this._findCentroidForRing(b);h=g[0];var d=g[1],k=this._calcRingExtent(b);g=k.xmin;e=k.ymin;var n=k.xmax,k=k.ymax,m=(k-e)/(this._map.height*this._scale);if(!(10<(n-g)/(this._map.width*
this._scale)&&10<m)){var l=!0;if(n-g>this._map.width*this._scale||k-e>this._map.height*this._scale)l=!1;var m=this._map.width*this._scale*(l?.1875:.5),l=this._map.height*this._scale*(l?.1875:.5),x=!0,r=!0,q=0;do{d+=(q%2?-1:1)*q*l;if(this._scanRingByX(c,a,b,h,d,g,n,m,f))break;d<e&&(x=!1);d>k&&(r=!1);q++}while(x||r)}},_scanRingByX:function(b,a,c,h,g,e,f,d,k){var m=!0,p=!0,l=0,x=1E3;do{h+=(l%2?-1:1)*l*d;var r=this._movePointInsideRing(c,h,g),q=this._labelLayer._isWithinScreenArea(new D(r,g,r,g,a)),w=
this._isPointWithinRing(b,c,r,g);if(q&&w)return k.push({x:r,y:g}),!0;h<e&&(m=!1);h>f&&(p=!1);l++;x--;if(0>=x)return!0}while(m||p);return!1},_movePointInsideRing:function(b,a,c){for(var h=[],g=b.length-1,e=b[0][1]>=b[g][1]?1:-1,f=0;f<=g;f++){var d=f,k=f+1;f==g&&(k=0);var m=b[d][0],d=b[d][1],p=b[k][0],k=b[k][1],l=k>=d?1:-1;if(d<=c&&c<=k||k<=c&&c<=d)c!=d&&c!=k?(h.push((c-d)*(p-m)/(k-d)+m),e=l):c==d&&c!=k?(e!=l&&h.push(m),e=l):c!=d&&c==k?(h.push(p),e=l):c==d&&c==k&&(1==e&&h.push(m),h.push(p),e=l)}h.sort(function(a,
b){return a-b});b=h.length;if(0<b){for(f=c=a=0;f<b-1;f+=2)g=Math.abs(h[f+1]-h[f]),g>a&&(a=g,c=f);a=(h[c]+h[c+1])/2}return a},_calcRingExtent:function(b){var a,c;c=new D;for(a=0;a<b.length-1;a++){var h=b[a][0],g=b[a][1];if(void 0===c.xmin||h<c.xmin)c.xmin=h;if(void 0===c.ymin||g<c.ymin)c.ymin=g;if(void 0===c.xmax||h>c.xmax)c.xmax=h;if(void 0===c.ymax||g>c.ymax)c.ymax=g}return c},_isPointWithinPolygon:function(b,a,c,h){var g;for(g=0;g<a.rings.length;g++)if(this._isPointWithinRing(b,a.rings[g],c,h))return!0;
return!1},_isPointWithinRing:function(b,a,c,h){var g,e,f,d,k=[],m=a.length;for(b=0;b<m-1;b++)if(g=a[b][0],e=a[b][1],f=a[b+1][0],d=a[b+1][1],g!=f||e!=d){if(e==d)if(h==e)k.push(g);else continue;g==f?(e<d&&h>=e&&h<d&&k.push(g),e>d&&h<=e&&h>d&&k.push(g)):(e=(f-g)/(d-e)*(h-e)+g,g<f&&e>=g&&e<f&&k.push(e),g>f&&e<=g&&e>f&&k.push(e))}k.sort(function(a,b){return a-b});for(b=0;b<k.length-1;b++)if(g=k[b],f=k[b+1],c>=g&&c<f)if(b%2)break;else return!0;return!1},_findCentroidForRing:function(b){for(var a=b.length,
c=[0,0],h=0,g=b[0][0],e=b[0][1],f=1;f<a-1;f++){var d=b[f][0],k=b[f][1],m=b[f+1][0],p=b[f+1][1],l=(d-g)*(p-e)-(m-g)*(k-e);c[0]+=l*(g+d+m);c[1]+=l*(e+k+p);h+=l}c[0]/=3*h;c[1]/=3*h;return c},_findCentroidForFeature:function(b){for(var a=0,c=[0,0],h=0;h<b.rings.length;h++)for(var g=b.rings[h],e=g.length,f=g[0][0],d=g[0][1],k=1;k<e-1;k++){var m=g[k][0],p=g[k][1],l=g[k+1][0],x=g[k+1][1],r=(m-f)*(x-d)-(l-f)*(p-d);c[0]+=r*(f+m+l);c[1]+=r*(d+p+x);a+=r}c[0]/=3*a;c[1]/=3*a;return c},_findPlace:function(b,a,
c,h,g,e,f){if(isNaN(c)||isNaN(h))return!1;for(var d=0;d<this._placedLabels.length;d++){var k=this._placedLabels[d].angle,n=this._placedLabels[d].width*this._scale,p=this._placedLabels[d].height*this._scale,l=this._placedLabels[d].x-c,x=this._placedLabels[d].y-h;if(0===g&&0===k){if(this._findPlace2(-e*this._scale,-f*this._scale,e*this._scale,f*this._scale,l-n,x-p,l+n,x+p))return!1}else{var r=new D(-e*this._scale,-f*this._scale,e*this._scale,f*this._scale,null),q=0,w=1;0!==g&&(q=Math.sin(g),w=Math.cos(g));
var v=l*w-x*q,l=l*q+x*w,k=k-g,q=Math.sin(k),w=Math.cos(k),t=-n*w- -p*q,x=-n*q+-p*w,k=+n*w- -p*q,y=+n*q+-p*w,n=v+t,p=l-x,q=v+k,w=l-y,t=v-t,x=l+x,v=v-k,l=l+y,k=new m;k.addRing([[n,p],[q,w],[t,x],[v,l],[n,p]]);if(r.intersects(k))return!1}}for(;g>Math.PI/2;)g-=Math.PI;for(;g<-(Math.PI/2);)g+=Math.PI;d={};d.layer=b;d.text=a;d.angle=g;d.x=c;d.y=h;d.width=e;d.height=f;this._placedLabels.push(d);return!0},_findPlace2:function(b,a,c,h,g,e,f,d){return(b>=g&&b<=f||c>=g&&c<=f||b<=g&&c>=f)&&(a>=e&&a<=d||h>=e&&
h<=d||a<=e&&h>=d)?!0:!1}})})},"*noref":1}});
define("esri/layers/LabelLayer","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/connect dojo/i18n!dojo/cldr/nls/number dojo/number dojo/has dojox/gfx/_base ../kernel ../lang ../graphic ../PopupInfo ../ArcadeExpression ../core/timerUtils ../symbols/TextSymbol ../symbols/ShieldLabelSymbol ../geometry/Extent ../geometry/Point ../geometry/webMercatorUtils ../renderers/SimpleRenderer ../arcadeProfiles/labelingProfile ./labelLayerUtils/DynamicLabelClass ./labelLayerUtils/StaticLabelClass ./GraphicsLayer ./LabelClass".split(" "),function(C,
B,H,E,D,F,m,b,a,c,h,g,e,f,d,k,n,p,l,x,r,q,w,v,t){function y(a){return"sizeInfo"===a.type}C=C(v,{declaredClass:"esri.layers.LabelLayer",constructor:function(a){this._refreshLabels=B.hitch(this,this._refreshLabels);this.id="labels";this.featureLayers=[];this._featureLayerInfos=[];this._preparedLabels=[];this._engineType="STATIC";this._mapEventHandlers=[];a&&(a.id&&(this.id=a.id),a.mode&&(this._engineType="DYNAMIC"===a.mode.toUpperCase()?"DYNAMIC":"STATIC"))},_setMap:function(a){this._mapEventHandlers.push(a.on("extent-change",
B.hitch(this,"_handleLevelChange")));var b=this.inherited(arguments);this.refresh();return b},_unsetMap:function(){var a;for(a=0;a<this._mapEventHandlers.length;a++)E.disconnect(this._mapEventHandlers[a]);this.refresh();f.clearTimeout(this._refreshHandle);this._refreshHandle=null;this.inherited(arguments)},setAlgorithmType:function(a){this._engineType=a&&"DYNAMIC"===a.toUpperCase()?"DYNAMIC":"STATIC";this.refresh()},addFeatureLayer:function(a,b,c,f){if(!this.getFeatureLayer(a.layerId)){var e=[];e.push(a.on("update-end",
B.hitch(this,"refresh")));e.push(a.on("suspend",B.hitch(this,"refresh")));e.push(a.on("resume",B.hitch(this,"refresh")));e.push(a.on("edits-complete",B.hitch(this,"refresh")));e.push(a.on("labeling-info-change",B.hitch(this,"refresh")));e.push(a.on("time-extent-change",B.hitch(this,"refresh")));e.push(a.on("show-labels-change",B.hitch(this,"refresh")));e.push(a.on("feature-reduction-change",B.hitch(this,"refresh")));this._featureLayerInfos.push({FeatureLayer:a,LabelExpressionInfo:c,LabelingOptions:f,
LabelRenderer:b,EventHandlers:e});this.featureLayers.push(a);this.refresh()}},getFeatureLayer:function(a){var b,c;for(b=0;b<this.featureLayers.length;b++)if(c=this.featureLayers[b],void 0!==c&&c.id==a)return c;return null},removeFeatureLayer:function(a){var b;a=this.getFeatureLayer(a);if(void 0!==a&&(b=H.indexOf(this.featureLayers,a),-1<b)){this.featureLayers.splice(b,1);for(a=0;a<this._featureLayerInfos[b].EventHandlers.length;a++)E.disconnect(this._featureLayerInfos[b].EventHandlers[a]);this._featureLayerInfos.splice(b,
1);this.refresh()}},removeAllFeatureLayers:function(){var a;for(a=0;a<this.featureLayers.length;a++){for(var b=0;b<this._featureLayerInfos[a].EventHandlers.length;b++)E.disconnect(this._featureLayerInfos[a].EventHandlers[b]);this.featureLayers=[];this._featureLayerInfos=[]}this.refresh()},getFeatureLayers:function(){return this.featureLayers},getFeatureLayerInfo:function(a){var b,c;for(b=0;b<this.featureLayers.length;b++)if(c=this.featureLayers[b],void 0!==c&&c.id==a)return this._featureLayerInfos[b];
return null},refresh:function(){null==this._refreshHandle&&(this._refreshHandle=f.setTimeout(this._refreshLabels,f.priority.LOW))},_handleLevelChange:function(a){a.levelChange&&this.clear();this.refresh()},_refreshLabels:function(a){this._refreshHandle=null;var b,c,e,f,g,d=[],h,u="DYNAMIC"===this._engineType?new q:new w;if(this._map){u.setMap(this._map,this);this._preparedLabels=[];for(a=0;a<this.featureLayers.length;a++)if(c=this.featureLayers[a],c.visible&&c.showLabels&&c.visibleAtMapScale&&!c._suspended)if(b=
this._featureLayerInfos[a],g=this._convertOptions(null),b.LabelRenderer){if(d=c.labelingInfo)if(h=d[0])f=this._getLabelExpression(h),g=this._convertOptions(h);e=b.LabelRenderer;b.LabelExpressionInfo&&(f=b.LabelExpressionInfo);b.LabelingOptions&&(g=this._convertOptions(null),void 0!==b.LabelingOptions.pointPriorities&&(d=b.LabelingOptions.pointPriorities,g.pointPriorities="above-center"==d||"AboveCenter"==d||"esriServerPointLabelPlacementAboveCenter"==d?"AboveCenter":"above-left"==d||"AboveLeft"==
d||"esriServerPointLabelPlacementAboveLeft"==d?"AboveLeft":"above-right"==d||"AboveRight"==d||"esriServerPointLabelPlacementAboveRight"==d?"AboveRight":"below-center"==d||"BelowCenter"==d||"esriServerPointLabelPlacementBelowCenter"==d?"BelowCenter":"below-left"==d||"BelowLeft"==d||"esriServerPointLabelPlacementBelowLeft"==d?"BelowLeft":"below-right"==d||"BelowRight"==d||"esriServerPointLabelPlacementBelowRight"==d?"BelowRight":"center-center"==d||"CenterCenter"==d||"esriServerPointLabelPlacementCenterCenter"==
d?"CenterCenter":"center-left"==d||"CenterLeft"==d||"esriServerPointLabelPlacementCenterLeft"==d?"CenterLeft":"center-right"==d||"CenterRight"==d||"esriServerPointLabelPlacementCenterRight"==d?"CenterRight":"AboveRight"),void 0!==b.LabelingOptions.lineLabelPlacement&&(g.lineLabelPlacement=b.LabelingOptions.lineLabelPlacement),void 0!==b.LabelingOptions.lineLabelPosition&&(g.lineLabelPosition=b.LabelingOptions.lineLabelPosition),void 0!==b.LabelingOptions.labelRotation&&(g.labelRotation=b.LabelingOptions.labelRotation),
void 0!==b.LabelingOptions.howManyLabels&&(g.howManyLabels=b.LabelingOptions.howManyLabels));e instanceof t&&(f=this._getLabelExpression(e),e=new x(e.symbol),g=this._convertOptions(e));this._addLabels(c,e,f,g)}else if(d=c.labelingInfo)for(b=d.length-1;0<=b;b--)if(h=d[b])e=new t(h instanceof t?h.toJson():h),f=this._getLabelExpression(h),g=this._convertOptions(h),this._addLabels(c,e,f,g);f=u._process(this._preparedLabels);this.clear();this.drawLabels(this._map,f)}},drawLabels:function(a,b){this._scale=
(a.extent.xmax-a.extent.xmin)/a.width;var c;for(c=0;c<b.length;c++){var e=b[c],f=e.x,g=e.y,u=e.text,k=e.angle,m=e.layer.labelSymbol;"polyline"==e.layer.geometry.type&&e.layer.options.labelRotation&&m.setAngle(180/Math.PI*k);m.setText(u);m instanceof d&&(u=m.getHeight(),f-=.25*u*this._scale*Math.sin(k),g-=.33*u*this._scale);k=new h(new p(f,g,a.extent.spatialReference));k.setParentGraphic(e.layer.graphic);k.setSymbol(m);this.add(k)}},_addLabels:function(a,b,c,e){var f,g,d,h;if(this._isWithinScaleRange(b.minScale,
b.maxScale)&&c&&""!==c){var u=this._map,k=!a.url&&!u.spatialReference.equals(a.spatialReference);for(f=0;f<a.graphics.length;f++)if(g=a.graphics[f],!1!==g.visible&&!g._suspended){d=g.geometry;if(k){if(!l.canProject(d,u))continue;d=l.project(d,u)}d&&this._isWhere(b.where,g.attributes)&&this._isWithinScreenArea(d)&&(h=this._buildLabelText(c,g,a.fields,e),this._addLabel(h,b,a.renderer,g,e,d,u))}}},_isWithinScreenArea:function(a){a="point"===a.type?new n(a.x,a.y,a.x,a.y,a.spatialReference):a.getExtent();
if(void 0===a)return!1;a=this._intersects(this._map,a);return null===a||0===a.length?!1:!0},_isWithinScaleRange:function(a,b){var c=this._map.getScale();return 0<a&&c>=a||0<b&&c<b?!1:!0},_isWhere:function(a,b){try{if(!a)return!0;if(a){var c=a.split(" ");if(3===c.length)return this._sqlEquation(b[this._removeQuotes(c[0])],c[1],this._removeQuotes(c[2]));if(7===c.length){var e=this._sqlEquation(b[this._removeQuotes(c[0])],c[1],this._removeQuotes(c[2])),f=c[3],g=this._sqlEquation(b[this._removeQuotes(c[4])],
c[5],this._removeQuotes(c[6]));switch(f){case "AND":return e&&g;case "OR":return e||g}}}return!1}catch(K){console.log("Error.: can't parse \x3d "+a)}},_sqlEquation:function(a,b,c){switch(b){case "\x3d":return a==c?!0:!1;case "\x3c\x3e":return a!=c?!0:!1;case "\x3e":return a>c?!0:!1;case "\x3e\x3d":return a>=c?!0:!1;case "\x3c":return a<c?!0:!1;case "\x3c\x3d":return a<=c?!0:!1}return!1},_removeQuotes:function(a){var b=a.indexOf('"'),c=a.lastIndexOf('"');if(-1!=b&&-1!=c)return a.substr(1,a.length-
2);b=a.indexOf("'");c=a.lastIndexOf("'");return-1!=b&&-1!=c?a.substr(1,a.length-2):a},_getSizeInfo:function(a){return a?a.sizeInfo||H.filter(a.visualVariables,y)[0]:null},_addLabel:function(a,c,e,f,g,h,m){var l,u,n,p;if(a&&""!==B.trim(a)&&c){a=a.replace(/\s+/g," ");l=c.getSymbol(f);l instanceof d?(l=new d(l.toJson()),l.setVerticalAlignment("baseline"),l.setHorizontalAlignment("center")):l=l instanceof k?new k(l.toJson()):new d;l.setText(a);c.symbol=l;if(n=this._getProportionalSize(c.sizeInfo,f.attributes))l instanceof
d?l.setSize(n):l instanceof k&&(l.setWidth(n),l.setHeight(n));p=n=0;if(e){u=e.getSymbol(f);var q=this._getSizeInfo(e);if((e=q?e.getSize(f,{sizeInfo:q,resolution:m.getResolutionInMeters()}):f.size)&&null!==e)n=p=e;else if(u)if("simplemarkersymbol"==u.type)p=n=u.size;else if("picturemarkersymbol"==u.type)n=u.width,p=u.height;else if("simplelinesymbol"==u.type||"cartographiclinesymbol"==u.type)n=u.width}e={};e.graphic=f;e.options=g;e.geometry=h;e.labelRenderer=c;e.labelSymbol=l;e.labelWidth=l.getWidth()/
2;e.labelHeight=l.getHeight()/2;e.symbolWidth=b.normalizedLength(n)/2;e.symbolHeight=b.normalizedLength(p)/2;e.text=a;e.angle=l.angle;this._preparedLabels.push(e)}},_buildLabelText:function(a,b,e,f){if(f.hasExpression)return a=r.getEvalOptions({expression:f.arcadeExpr,feature:b,layer:b.getLayer(),spatialReference:this._map.spatialReference}),b=b.evaluateExpression(f.arcadeExpr,a),c.isDefined(b)?""+b:"";var d=b.attributes;return a.replace(/{[^}]*}/g,function(a){var b,h=a;for(b=0;b<e.length;b++)if("{"+
e[b].name+"}"==a){var h=d[e[b].name],k=e[b].domain;if(k&&B.isObject(k)){if("codedValue"==k.type&&f.useCodedValues)for(b=h,a=0;a<k.codedValues.length;a++)if(k.codedValues[a].code==b){h=k.codedValues[a].name;break}break}k=e[b].type;if(f.fieldInfos){var l=f.fieldInfos;for(b=0;b<l.length;b++)if("{"+l[b].fieldName+"}"==a){a=l[b].format;"esriFieldTypeDate"==k?(a="DateFormat"+g.prototype._dateFormats[a.dateFormat?a.dateFormat:"shortDate"])&&(h=c.substitute({myKey:h},"${myKey:"+a+"}")):"esriFieldTypeInteger"!=
k&&"esriFieldTypeSingle"!=k&&"esriFieldTypeSmallInteger"!=k&&"esriFieldTypeLong"!=k&&"esriFieldTypeDouble"!=k||!a||(h=F.format(h,{places:a.places}),a.digitSeparator||D.group&&(h=h.replace(new RegExp("\\"+D.group,"g"),"")));break}}break}else h="";return null==h?"":h})},_getLabelExpression:function(a){var b="";a.labelExpressionInfo?b=a.labelExpressionInfo.value||a.labelExpressionInfo.expression:this._validSyntax(a.labelExpression)&&(b=this._convertLabelExpression(a.labelExpression));return b},_validSyntax:function(a){return/^(\s*\[[^\]]+\]\s*)+$/i.test(a)},
_convertLabelExpression:function(a){return a.replace(/\[/g,"{").replace(/\]/g,"}")},_getProportionalSize:function(a,b){if(!a)return null;b=c.substitute(b,"${"+a.field+"}",{first:!0});return!(a.minSize&&a.maxSize&&a.minDataValue&&a.maxDataValue&&b)||0>=a.maxDataValue-a.minDataValue?null:(a.maxSize-a.minSize)/(a.maxDataValue-a.minDataValue)*(b-a.minDataValue)+a.minSize},_convertOptions:function(a){var b=!0,c="shortDate",f=null,g=null,d="",h=!0,k,l;if(a&&(a.format&&(c=a.format.dateFormat,f={places:a.format.places,
digitSeparator:a.format.digitSeparator}),g=a.fieldInfos,d=a.labelPlacement,null!=a.useCodedValues&&(b=a.useCodedValues),a=a.labelExpressionInfo)){var m=a.expression;m&&!a.value&&(l=!0,k=new e({expression:m,returnType:"string",profile:r}))}if("always-horizontal"==d||"esriServerPolygonPlacementAlwaysHorizontal"==d)h=!1;return{useCodedValues:b,dateFormat:c,numberFormat:f,fieldInfos:g,pointPriorities:"above-center"==d||"esriServerPointLabelPlacementAboveCenter"==d?"AboveCenter":"above-left"==d||"esriServerPointLabelPlacementAboveLeft"==
d?"AboveLeft":"above-right"==d||"esriServerPointLabelPlacementAboveRight"==d?"AboveRight":"below-center"==d||"esriServerPointLabelPlacementBelowCenter"==d?"BelowCenter":"below-left"==d||"esriServerPointLabelPlacementBelowLeft"==d?"BelowLeft":"below-right"==d||"esriServerPointLabelPlacementBelowRight"==d?"BelowRight":"center-center"==d||"esriServerPointLabelPlacementCenterCenter"==d?"CenterCenter":"center-left"==d||"esriServerPointLabelPlacementCenterLeft"==d?"CenterLeft":"center-right"==d||"esriServerPointLabelPlacementCenterRight"==
d?"CenterRight":"AboveRight",lineLabelPlacement:"above-start"==d||"below-start"==d||"center-start"==d?"PlaceAtStart":"above-end"==d||"below-end"==d||"center-end"==d?"PlaceAtEnd":"PlaceAtCenter",lineLabelPosition:"above-after"==d||"esriServerLinePlacementAboveAfter"==d||"above-along"==d||"esriServerLinePlacementAboveAlong"==d||"above-before"==d||"esriServerLinePlacementAboveBefore"==d||"above-start"==d||"esriServerLinePlacementAboveStart"==d||"above-end"==d||"esriServerLinePlacementAboveEnd"==d?"Above":
"below-after"==d||"esriServerLinePlacementBelowAfter"==d||"below-along"==d||"esriServerLinePlacementBelowAlong"==d||"below-before"==d||"esriServerLinePlacementBelowBefore"==d||"below-start"==d||"esriServerLinePlacementBelowStart"==d||"below-end"==d||"esriServerLinePlacementBelowEnd"==d?"Below":"center-after"==d||"esriServerLinePlacementCenterAfter"==d||"center-along"==d||"esriServerLinePlacementCenterAlong"==d||"center-before"==d||"esriServerLinePlacementCenterBefore"==d||"center-start"==d||"esriServerLinePlacementCenterStart"==
d||"center-end"==d||"esriServerLinePlacementCenterEnd"==d?"OnLine":"Above",labelRotation:h,howManyLabels:"OneLabel",hasExpression:l,arcadeExpr:k}}});m("extend-esri")&&B.setObject("layers.LabelLayer",C,a);return C});