// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/layers/TrackManager","dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/has dojo/dom-construct dojox/gfx ../kernel ../graphic ../geometry/Polyline ./GraphicsLayer".split(" "),function(l,m,f,n,p,q,r,t,u,v){var w=-1!==q.renderer.toLowerCase().indexOf("canvas");l=l(null,{declaredClass:"esri.layers._TrackManager",constructor:function(a){this.layer=a;this.trackMap={};this.trackLineMap={}},initialize:function(a){this.map=a;a=this.layer;this.createTracklineContainer()&&(a.on("visibility-change",
m.hitch(this,function(a){this.container.setVisibility(a.visible);this.container.evaluateSuspension()})),a.on("scale-range-change",m.hitch(this,function(){this.container.setScaleRange(this.layer.minScale,this.layer.maxScale)})))},createTracklineContainer:function(){var a=this.layer;if("esriGeometryPoint"!==a.geometryType)return null;var b=this.map,c=a._getRenderer(),c=c&&c.trackRenderer,d=this.container=new v._GraphicsLayer({id:a.id+"_tracks",_child:!0,visible:a.visible,minScale:a.minScale,maxScale:a.maxScale});
d.loaded=!0;d.onLoad(d);d._setMap(b,a._div);w||(b=d._div.getNode(),a=a._div.getNode(),b&&a&&p.place(b,a,"first"));d.setRenderer(c);return d},addFeatures:function(a){var b=this.trackMap,c=this.layer,d=c._trackIdField,e=[];f.forEach(a,function(a){var c=a.attributes[d];(b[c]=b[c]||[]).push(a);-1===f.indexOf(e,c)&&e.push(c)});var g=c._startTimeField,h=c.objectIdField,k=function(a,c){var b=a.attributes[g],d=c.attributes[g];return b===d?a.attributes[h]<c.attributes[h]?-1:1:b<d?-1:1};f.forEach(e,function(a){b[a].sort(k)})},
trimTracks:function(a){function b(a){for(a=c[a]||[];a.length>d;)e.push(a.shift())}var c=this.trackMap,d=this.layer.maximumTrackPoints||0,e=[],g;if(!d)return e;if(a)f.forEach(a,function(a){b(a)});else for(g in c)c.hasOwnProperty(g)&&b(g);return e},drawTracks:function(a){function b(a){var b=e[a],k,f,l;f=c.trackLineMap[a];d.remove(f);delete c.trackLineMap[a];f=null;if(!b||2>b.length)return!1;f=[];for(k=b.length-1;0<=k;k--)(l=b[k].geometry)&&f.push([l.x,l.y]);b={};b[h]=a;1<f.length&&(f=new t(new u({paths:[f],
spatialReference:g}),null,b),d.add(f),c.trackLineMap[a]=f)}var c=this,d=this.container,e,g,h,k;if(d)if(e=this.trackMap,g=this.map.spatialReference,h=this.layer._trackIdField,a)f.forEach(a,function(a){b(a)});else for(k in e)e.hasOwnProperty(k)&&b(k)},refreshTracks:function(a){function b(a){var b,h;c.drawTracks([a]);if(g&&g.latestObservationRenderer)for(a=d[a]||[],b=a.length,h=0;h<b;h++)e._repaint(a[h],null,!0)}var c=this,d=this.trackMap,e=this.layer,g=e._getRenderer(),h;if(a)f.forEach(a,function(a){b(a)});
else for(h in d)d.hasOwnProperty(h)&&b(h);this.moveLatestToFront()},moveLatestToFront:function(a){f.forEach(this.getLatestObservations(a),function(a){var b=a._shape;b&&b._moveToFront();this._repaint(a,null,!0)},this.layer)},getLatestObservations:function(a){function b(a){a=e[a];return a[a.length-1]}var c=[],d=this.layer._getRenderer(),e=this.trackMap,g;if(!d.latestObservationRenderer)return c;if(a)f.forEach(a,function(a){c.push(b(a))});else for(g in e)e.hasOwnProperty(g)&&c.push(b(g));return c},clearTracks:function(a){var b=
this.getLatestObservations(a),c=this.container,d=this.trackMap,e,g;if(a)f.forEach(a,function(a){delete this.trackMap[a];c&&(g=this.trackLineMap[a],c.remove(g),delete this.trackLineMap[a])},this);else{if(c)for(e in d)g=this.trackLineMap[e],c.remove(g);this.trackMap={};this.trackLineMap={}}f.forEach(b,function(a){this._repaint(a,null,!0)},this.layer)},isLatestObservation:function(a){var b=this.trackMap[a.attributes[this.layer._trackIdField]];return b?b[b.length-1]===a:!1},destroy:function(){var a=this.container;
a&&(a.clear(),a._unsetMap(this.map,this.layer._div));this.map=this.layer=this.trackMap=this.container=null}});n("extend-esri")&&m.setObject("layers._TrackManager",l,r);return l});