// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/DataProviderGE","dojo/_base/declare dojo/_base/lang dojo/promise/all dojo/when ./dataProvider/_CommandSupport ./dataProvider/_SerializationSupport ./dataProvider/_ServerSerializationSupport ./dataProvider/supportClasses/AnalysisAreaUtil ./dataProvider/supportClasses/AnalysisAreaJsonUtil ./dataProvider/supportClasses/CustomReportsManager ./dataProvider/supportClasses/TemplateJsonLoader ./dataProvider/supportClasses/ReportDataProcessor ./dataProvider/supportClasses/InfographicOptionsProvider ./dataProvider/supportClasses/AreasPreprocessor ./dataProvider/supportClasses/GEUtil ./dataProvider/supportClasses/attachments/DefaultAttachmentsStore ./dataProvider/supportClasses/attachments/CustomAttachmentsStore ./dataProvider/supportClasses/PortalManager ./dataProvider/commands/mapToImage/MapToURLUtil ./core/themes/ThemeLibrary ./core/themes/ReportThemes esri/dijit/geoenrichment/ReportPlayer/countryConfig esri/dijit/geoenrichment/utils/ProjectionUtil".split(" "),
function(u,h,k,p,v,w,x,y,q,f,r,g,z,A,l,B,C,D,E,F,t,m,G){return u([v,w,x],{analysisAreasLimit:-1,cacheTemplates:!0,printMapTaskUrl:null,resetReportItemsCache:!0,_infographicOptionsProvider:null,constructor:function(b){h.mixin(this,b);this._infographicOptionsProvider=new z},_getAttachmentsStore:function(b){return(new B(b)).initialize()},getCustomReports:function(b){return f.getCustomReports(b)},_currentContext:null,getReportData:function(b,e){var c=this;e=e||function(){};var a=h.mixin({},b);a.variables&&
(a.hierarchy=a.hierarchy||"census");c.resetReportItemsCache&&f.resetCache();c._currentContext=a;a.analysisAreas=q.areasFromJson(a.analysisAreas);a.combinedAreasInfo=a.combinedAreasInfo&&q.combinedAreasInfoFromJson(a.combinedAreasInfo)||{};y.pppulateCombinedAreasInfo(a.combinedAreasInfo,a.analysisAreas);a.fieldData={runReportTaskID:null,metadata:{},areaData:[],errors:[]};return k([p(f.tryFindReportIdByAlias(a),function(b){a.reportID=b||a.reportID}),this._discoverPortal(a)]).then(function(){return p(A.preprocessAreas(a,
{analysisAreasLimit:c.analysisAreasLimit}),function(){e(.25);setTimeout(function(){c._onCreateReportStarted()});var b={initGE:l.initialize(),countryInfo:l.getCountryInfo(a.countryID),infographicOptions:c._infographicOptionsProvider.getInfographicOptions(a),attachmentsStore:a.attachmentsProvider?C(a.attachmentsProvider):c._getAttachmentsStore(a.analysisAreas)};a.reportID?(b.reportObject=f.getCustomReportByID(a),b.templateJsonInfo=r.getTemplateJsonByID(a,c.cacheTemplates),b.runReportResult=g.runReportAndGetData(a)):
a.variables&&(a.variables=a.variables.map(function(a){return a.toLowerCase()}),b.reportObject=f.getFakeCustomReportByContext(a),b.templateJsonInfo=r.createTemplateJsonFromVariables(a),b.runReportResult=g.runReportFromVariables(a));return k(b).then(function(b){var d=b.reportObject,c=b.infographicOptions,f=b.attachmentsStore,n=b.templateJsonInfo.templateJson,h=b.templateJsonInfo.templateVariableProvider,k=b.runReportResult;e(.75);if(!n||!d||!a.fieldData)return null;g.applyRunReportAndGetDataResults(k,
a);m.setCountry(b.countryInfo.country);m.setHierarchyID(d.hierarchy);m.setGeographiesModel(b.countryInfo.geographiesModels[m.getHierarchyID()]);return p(f&&g.populateReportDataFromAttachmentsStore(a,f),function(){e(1);n.theme||(n.theme=F.getReportThemeById(d.isGraphicReport?t.GRAPHIC:t.CLASSIC));return{isClassic:!d.isGraphicReport,isMultiFeature:d.isMultiFeature&&1<a.analysisAreas.length,reportType:d.type,reportTitle:d.title,templateJson:n,reportObject:d,fieldData:a.fieldData,analysisAreas:a.analysisAreas,
combinedAreasInfo:a.combinedAreasInfo,reverseAnalysisAreasOnMap:a.reverseAnalysisAreasOnMap,infographicOptions:c,attachmentsStore:f,geClient:l.getClient(),templateVariableProvider:h,config:{portalUrl:a.portalUrl,geoenrichmentUrl:a.geoenrichmentUrl,geometryServiceUrl:a.geometryServiceUrl,printMapTaskUrl:a.printMapTaskUrl,countryID:a.countryID,hierarchy:d.hierarchy,reportID:a.reportID,variables:a.variables}}})})})})},_discoverPortal:function(b){var e=this;return D.getPortalInfo(b.portalUrl).then(function(c){b.geoenrichmentUrl=
b.geoenrichmentUrl||c.portal.helperServices.geoenrichment.url;l.setGeoenrichmentUrl(b.geoenrichmentUrl);e._infographicOptionsProvider.setServerUrl(b);b.geometryServiceUrl=b.geometryServiceUrl||c.portal.helperServices.geometry.url;G.setGeometryServiceUrl(b.geometryServiceUrl);b.printMapTaskUrl=b.printMapTaskUrl||c.portal.helperServices.printTask.url;E.setPrintMapTaskUrl(b.printMapTaskUrl)})},reportDataToSingleAreaReportData:function(b,e){var c=e.currentFeatureIndex||0,a=h.mixin({},b.fieldData);a.areaData=
[a.areaData[c]];var f=[b.analysisAreas[c]],g=b.infographicOptions&&this._infographicOptionsProvider.getInfographicOptionsFromJson(b.infographicOptions.toJsonAt(c)),d=b.attachmentsStore;return{isClassic:b.isClassic,isMultiFeature:!1,reportType:b.reportType,reportTitle:e.reportTitle,templateJson:e.templateJson,reportObject:b.reportObject,fieldData:a,analysisAreas:f,combinedAreasInfo:null,reverseAnalysisAreasOnMap:!1,infographicOptions:g,attachmentsStore:d&&{getAttachments:function(){d.setCurrentAnalysisAreaIndex&&
d.setCurrentAnalysisAreaIndex(c);return d.getAttachments()},getAttributes:function(){d.setCurrentAnalysisAreaIndex&&d.setCurrentAnalysisAreaIndex(c);return d.getAttributes()},getNotes:function(){d.setCurrentAnalysisAreaIndex&&d.setCurrentAnalysisAreaIndex(c);return d.getNotes()}},geClient:b.geClient,templateVariableProvider:b.templateVariableProvider,config:b.config}},_getCurrentContext:function(){return this._currentContext},_onCreateReportStarted:function(){},enrichFieldData:function(b,e){return g.enrichFieldData(b,
e)}})});