// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/geoenrichment/ReportPlayer/templates/PlayerToolbarHolder.html":'\x3cdiv class\x3d"esriGEPlayerToolbar"\x3e\r\n\r\n    \x3c!--left--\x3e\r\n\r\n    \x3cdiv data-dojo-attach-point\x3d"infographicsSelectDiv" class\x3d"dijitInline playerToolbar_infographicsSelectDiv"\x3e\x3c/div\x3e\r\n    \r\n    \x3c!--center--\x3e\r\n    \r\n    \x3cdiv data-dojo-attach-point\x3d"areaTitleDiv" class\x3d"dijitInline playerToolbar_areaTitleDiv"\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"areaTitleInnerDiv" class\x3d"dijitInline playerToolbar_areaTitleInnerDiv TrimWithEllipses"\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n\r\n    \x3cdiv data-dojo-attach-point\x3d"areasSelectDiv" class\x3d"dijitInline playerToolbar_areasSelectDiv"\x3e\x3c/div\x3e\r\n\r\n    \x3c!--right--\x3e\r\n\r\n    \x3cdiv data-dojo-attach-point\x3d"rightSideControlsBlock" class\x3d"dijitInline playerToolbar_rightSideControlsBlock"\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"zoomSelectDiv" class\x3d"dijitInline dijitInline playerToolbar_zoomSelectDiv"\x3e\x3c/div\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"pageSelectDiv" class\x3d"dijitInline dijitInline playerToolbar_pageSelectDiv"\x3e\x3c/div\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"commandButtonsContainer" class\x3d"dijitInline playerToolbar_commandButtonsContainer"\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/geoenrichment/ReportPlayer/PlayerToolbar","dojo/_base/declare dojo/on dojo/string dojo/when dojo/dom-class dojo/dom-construct dijit/_WidgetBase dijit/_TemplatedMixin ./PlayerSelect ./PlayerCommands ./PlayerThemes ./supportClasses/ToolbarArranger ./supportClasses/ZoomUtil esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/InvokeUtil esri/dijit/geoenrichment/utils/MouseUtil esri/dijit/geoenrichment/utils/PopupUtil esri/dijit/geoenrichment/utils/TooltipUtil dojo/text!./templates/PlayerToolbarHolder.html dojo/i18n!esri/nls/jsapi".split(" "),
function(m,n,v,w,g,d,p,q,h,r,x,y,c,e,z,t,k,l,A,f){f=f.geoenrichment.dijit.ReportPlayer.PlayerToolbar;var B=m([p,q],{templateString:A,nls:f,formatAreaTitleFunc:null,formatAreaTitleMultiFunc:null,showAreaTitle:!1,stretchToolbarNode:null,areasSelect:null,pageSelect:null,zoomSelect:null,_toolbarArranger:null,_infographicSelect:null,postCreate:function(){e.hide(this.commandButtonsContainer);this._toolbarArranger=new y({showAreaTitle:this.showAreaTitle,stretchToolbarNode:this.stretchToolbarNode,domNode:this.domNode,
infographicsSelectDiv:this.infographicsSelectDiv,areaTitleDiv:this.areaTitleDiv,areaTitleInnerDiv:this.areaTitleInnerDiv,rightSideControlsBlock:this.rightSideControlsBlock,areasSelectDiv:this.areasSelectDiv,zoomSelectDiv:this.zoomSelectDiv,pageSelectDiv:this.pageSelectDiv,commandButtonsContainer:this.commandButtonsContainer});this._initAreaSelect();this._initPageSelect();this._initZoomSelect();l.autoTooltip(this.domNode)},_initAreaSelect:function(){var a=this;this.areasSelect=(new h({onChange:function(b){a.onShowAnalysisAreaAt(b.value);
a.onClosePopup()}})).placeAt(this.areasSelectDiv);this.own(this.areasSelect)},updateAreaSelect:function(a,b,c,u){var f=a.length,d=a.map(function(a,b){return{label:1===f?a.name:a.shortName||a.name||"",value:b}});this.areasSelect.set("options",d);this.areasSelect.set("value",c);e[1<f&&!u?"show":"hide"](this.areasSelectDiv);this._toolbarArranger.syncRightSideVisibility();u?this.formatAreaTitleMultiFunc?this.formatAreaTitleMultiFunc(this.areaTitleInnerDiv,b):this._formatAreaTitleMulti(b):(a=a[c],this.formatAreaTitleFunc?
this.formatAreaTitleFunc(this.areaTitleInnerDiv,a):this._formatAreaTitle(a))},_formatAreaTitle:function(a){this.areaTitleInnerDiv.innerHTML=a.locationName||a.name},_formatAreaTitleMulti:function(a){this.areaTitleInnerDiv.innerHTML=a.locationName||a.name||a.shortName||""},_pageControlsVisible:!0,_initPageSelect:function(){var a=this;this.pageSelect=(new h({onChange:function(b){a.onShowPageAt(b.value);a.onClosePopup()}})).placeAt(this.pageSelectDiv);this.own(this.pageSelect)},setPageControlsVisible:function(a){this._pageControlsVisible=
a;e[a?"show":"hide"](this.pageSelectDiv)},updatePageSelect:function(a,b){for(var c=[],d=0;d<a;d++)c.push({label:v.substitute(f.pageIndex,{index:d+1}),value:d});this.pageSelect.set("options",c);this.pageSelect.set("value",b);e[this._pageControlsVisible&&1<a?"show":"hide"](this.pageSelectDiv)},_initZoomSelect:function(){var a=this;this.zoomSelect=(new h({onChange:function(b){if(b.value===c.FIT_PAGE)a.onZoomToFitPage();else if(b.value===c.FIT_PAGE_WIDTH)a.onZoomToFitPageWidth();else if(b.value===c.FIT_PAGE_HEIGHT)a.onZoomToFitPageHeight();
else a.onSetZoomPercent(b.value);a.onClosePopup()}})).placeAt(this.zoomSelectDiv);this.own(this.zoomSelect);this.zoomSelect.set("options",c.getOptions());this.zoomSelect.set("value",100)},setZoomSupportsInfo:function(a){e[a.supported?"show":"hide"](this.zoomSelectDiv);this._toolbarArranger.syncRightSideVisibility();this.zoomSelect.store.data.forEach(function(b){b.hidden=!1;if(b.value===c.FIT_PAGE&&!a.canFitPage)b.hidden=!0;else if(b.value===c.FIT_PAGE_WIDTH&&!a.canFitPageWidth)b.hidden=!0;else if(b.value===
c.FIT_PAGE_HEIGHT&&!a.canFitPageHeight)b.hidden=!0;else if(b.isCustomBig||b.isCustomSmall)b.hidden=!b.value})},setZoomInfo:function(a){a=a.isFitPageScale?c.FIT_PAGE:a.isFitPageWidthScale?c.FIT_PAGE_WIDTH:a.isFitPageHeightScale?c.FIT_PAGE_HEIGHT:c.getClosestZoomAndUpdateOptions(100*a.scale,this.zoomSelect.get("options"));a!==this.zoomSelect.get("value")&&this.zoomSelect.set("value",a)},createCommandButton:function(a,b){return this.createCustomCommandButton({callback:b,buttonClass:a.id===r.PRINT?"playerPrintButton":
"playerExportButton",tooltip:a.id===r.PRINT?f.printInfographic:f.exportInfographic,visibleOnError:!1})},createCustomCommandButton:function(a){e.show(this.commandButtonsContainer);var b=d.create("div",{"class":"playerToolbar_commandButtonContainer dijitInline"},this.commandButtonsContainer,a.addFirst?"first":"last");b.__visibleOnError=a.visibleOnError;b=d.create("div",{"class":"playerToolbar_commandButton"},b);a.buttonClass&&g.add(b,a.buttonClass);a.tooltip&&l.setTooltipToNode(b,a.tooltip);n(b,"click",
a.callback);return b},setTheme:function(a){g.remove(this.domNode,"playerThemeDark playerThemeLight");g.add(this.domNode,a===x.DARK?"playerThemeDark":"playerThemeLight");this.areasSelect.setTheme(a);this.pageSelect.setTheme(a);this.zoomSelect.setTheme(a)},setErrorShown:function(a){if(a){e.hide([this.areaTitleDiv,this.areasSelectDiv,this.pageSelectDiv,this.zoomSelectDiv]);for(a=0;a<this.commandButtonsContainer.children.length;a++){var b=this.commandButtonsContainer.children[a];e[b.__visibleOnError?
"show":"hide"](b)}this.arrangeControls()}},arrangeControls:function(){this._toolbarArranger.arrangeControls()},hasVisibleControls:function(){return this._toolbarArranger.hasVisibleControls()},addInfographicsSelect:function(a){this._infographicSelect=a;a.placeAt(this.infographicsSelectDiv)},isMouseOver:function(){return t.isMouseOver(this.domNode)||this.areasSelect&&this.areasSelect.isMouseOver()||this.pageSelect&&this.pageSelect.isMouseOver()||this.zoomSelect&&this.zoomSelect.isMouseOver()||this._infographicSelect&&
this._infographicSelect.isMouseOver&&this._infographicSelect.isMouseOver()},setContentLoadPromise:function(a){e.enableContentAbsolute(this.commandButtonsContainer,!1);e.enableContentAbsolute(this.infographicsSelectDiv,!1);w(a,function(){e.enableContentAbsolute(this.commandButtonsContainer,!0);e.enableContentAbsolute(this.infographicsSelectDiv,!0)}.bind(this))},onShowPageAt:function(a){},onShowAnalysisAreaAt:function(a){},onZoomToFitPage:function(){},onZoomToFitPageWidth:function(){},onZoomToFitPageHeight:function(){},
onSetZoomPercent:function(a){},onClosePopup:function(){}});return m([p,q],{templateString:"\x3cdiv class\x3d'esriGEPlayerToolbarOuter'\x3e\x3c/div\x3e",popupButtonDiv:null,formatAreaTitleFunc:null,formatAreaTitleMultiFunc:null,showToolbarInPopup:!1,showAreaTitle:!1,stretchToolbarNode:null,isMobileDevice:!1,showCloseButton:!1,toolbarHolder:null,postCreate:function(){var a=this;this.inherited(arguments);this.toolbarHolder=(new B({showAreaTitle:this.showAreaTitle,stretchToolbarNode:this.stretchToolbarNode,
onShowPageAt:function(b){a.onShowPageAt(b)},onShowAnalysisAreaAt:function(b){a.onShowAnalysisAreaAt(b)},onZoomToFitPage:function(){a.onZoomToFitPage()},onZoomToFitPageWidth:function(){a.onZoomToFitPageWidth()},onZoomToFitPageHeight:function(){a.onZoomToFitPageHeight()},onSetZoomPercent:function(b){a.onSetZoomPercent(b)},onClosePopup:function(){a.closePopup()}})).placeAt(this.domNode);this.own(this.toolbarHolder)},updateAreaSelect:function(a,b,c,d){this.toolbarHolder.formatAreaTitleFunc=this.formatAreaTitleFunc;
this.toolbarHolder.formatAreaTitleMultiFunc=this.formatAreaTitleMultiFunc;this.toolbarHolder.updateAreaSelect(a,b,c,d)},setPageControlsVisible:function(a){this.toolbarHolder.setPageControlsVisible(a)},updatePageSelect:function(a,b){this.toolbarHolder.updatePageSelect(a,b)},setZoomSupportsInfo:function(a){this.toolbarHolder.setZoomSupportsInfo(a)},setZoomInfo:function(a){this.toolbarHolder.setZoomInfo(a)},createCommandButton:function(a,b){return this.toolbarHolder.createCommandButton(a,b)},setTheme:function(a){this.toolbarHolder.setTheme(a)},
setErrorShown:function(a){this.toolbarHolder.setErrorShown(a)},_popupHandle:null,_popupButton:null,update:function(){z.invoke(this,"_doUpdateToolbar")},_doUpdateToolbar:function(){g[this.isScrollShown()?"add":"remove"](this.popupButtonDiv,"playerToolbar_parentHasScroll");g[this.isMobileDevice?"add":"remove"](this.popupButtonDiv,"isMobileDevice");g[this.isMobileDevice?"add":"remove"](this.toolbarHolder.domNode,"isMobileDevice");this._resetToolbarNode();var a=k.isOpen(this.toolbarHolder);this._popupHandle&&
this._popupHandle.remove();this._popupHandle=null;this.showToolbarInPopup?(this._popupButton=d.create("div",{"class":"dijitInline playerToolbar_outerButton playerToolbar_settingsButton"},this.popupButtonDiv,"first"),this._popupHandle=k.makePopup(this.toolbarHolder,this,this._popupButton,{orient:["before","below"],openPopup:a})):d.place(this.toolbarHolder.domNode,this.domNode);this.toolbarHolder.arrangeControls();e[this.toolbarHolder.hasVisibleControls()?"show":"hide"](this.domNode)},_resetToolbarNode:function(){this.toolbarHolder.domNode.parentNode&&
this.toolbarHolder.domNode.parentNode.removeChild(this.toolbarHolder.domNode);d.empty(this.domNode);this._popupButton&&d.destroy(this._popupButton);this._popupButton=null},closePopup:function(){this.showToolbarInPopup&&k.close(this.toolbarHolder)},isScrollShown:function(){return!1},placeInfographicsSelect:function(a){a.placeAt(this.toolbarHolder.infographicsSelectDiv)},createCustomCommandButton:function(a){return this.toolbarHolder.createCustomCommandButton(a)},notifyCommandButtonsAdded:function(){if(this.showCloseButton)if(this.showToolbarInPopup){var a=
d.create("div",{"class":"dijitInline playerToolbar_outerButton playerToolbar_closeButtonOuter"},this.popupButtonDiv);l.setTooltipToNode(a,f.close);n(a,"click",function(){this.onClose()}.bind(this))}else this.createCustomCommandButton({buttonClass:"playerToolbar_closeButton",tooltip:f.close,callback:function(){this.closePopup();this.onClose()}.bind(this),visibleOnError:!0})},addInfographicsSelect:function(a){this.toolbarHolder.addInfographicsSelect(a)},isMouseOver:function(){return t.isMouseOver(this.domNode)||
this.toolbarHolder.isMouseOver()},setContentLoadPromise:function(a){this.toolbarHolder.setContentLoadPromise(a)},onShowPageAt:function(a){},onShowAnalysisAreaAt:function(a){},onZoomToFitPage:function(){},onZoomToFitPageWidth:function(){},onZoomToFitPageHeight:function(){},onSetZoomPercent:function(a){},onClose:function(){}})});