// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/tableJson/TableJsonUtil",["dojo/_base/lang","../templateJsonUtils/fieldInfo/FieldInfoBuilder","esri/dijit/geoenrichment/ReportPlayer/core/sections/SectionTypes"],function(k,r,l){var g={createTable:function(a){var b=a.numColumns,e=a.numRows,c=a.width,d=a.widths,g=a.style,t=a.attributes&&a.attributes.fixedColumns,l=a.attributes&&a.attributes.dynamicColumns;if(c)if(d)d=d.map(function(a){return c*Number(a.replace("%",""))/100});else for(var h=
c/b,d=[],f=0;f<b;f++)d.push(h);if(d)c||isNaN(Number(d[0]))||(c=0,d.forEach(function(a){c+=a}));else for(h=Number(100/b).toFixed(3)+"%",d=[],f=0;f<b;f++)d.push(h);h=[];for(f=0;f<b;f++)h.push({field:"field"+f,style:{width:d[f]}});for(var d=[],p=!0,u=a.height?a.height/e:a.rowHeight||15.07,m=0;m<e;m++){for(var n={style:{height:u,fields:{}},fieldInfos:{}},f=0;f<b;f++){var q="field"+f;!1!==a.useDefaultTheme&&(n.style.fields[q]=k.mixin({horizontalAlign:0===f?"left":"right",overrideStyle:0===m?1<e?!1!==a.useDefaultHeaderTheme?
"TableHeader":"Default":void 0:p?"AlternatingRow":"Default"},a.cellParams));l&&f>=t&&0===m&&(n.fieldInfos[q]=r.createFieldInfoFromSpecialFieldName("AREA_DESC"));a.processTableCell&&a.processTableCell(n,q,m,f,a)}d.push(n);p=!p}return{id:"table",attributes:k.mixin({},a.attributes),style:k.mixin({width:c||772.33},g),data:{columns:h,data:d}}},createSingleCellTable:function(a){a=a||{};var b=g.createTable({numColumns:1,numRows:1,attributes:a.attributes,useDefaultTheme:!1});g.modifyTableJson(b,0,0,a);return b},
modifyTableJson:function(a,b,e,c){b=a.data.data[b];e=a.data.columns[e];var d=e.field;c.text&&(b[d]=c.text);c.fieldInfo&&(b.fieldInfos[d]=c.fieldInfo);c.cellStyle&&(b.style.fields[d]=c.cellStyle);c.columnSpan&&(b.columnSpans=b.columnSpans||{},b.columnSpans[d]=c.columnSpan);c.rowSpan&&(b.rowSpans=b.rowSpans||{},b.rowSpans[d]=c.rowSpan);b.themeStyle=c.themeStyle;c.width&&(a.style.width=c.width,e.style.width=c.width);c.height&&(b.style.height=c.height);void 0!==c.left&&(a.style.left=c.left);void 0!==
c.spaceBefore&&(a.style.spaceBefore=c.spaceBefore)},getTableWidth:function(a){return a.style.width},getTableHeight:function(a){var b=0;a.data.data.forEach(function(a){b+=a.style?a.style.height:0});return b},createDetailsSection:function(a){return{type:l.DETAILS,stack:[g.createTable(a)]}},createDetailsSectionForFieldInfos:function(a,b){return{type:l.DETAILS,stack:[function(){var e=g.createTable(k.mixin({numColumns:2,numRows:a.length+1},b));e.data.data.forEach(function(b,d){0===d?b.field0=a[0].hasVariable?
a[0].fieldCategory:"":(d=a[d-1],b.field0=d.script?d.script.alias:d.alias,b.fieldInfos.field1=d)});g.provideSpaceAfter(e);return e}()]}},createDetailsSectionForFieldInfoGroups:function(a,b){return{type:l.DETAILS,stack:[function(){var e=g.createTable(k.mixin({numColumns:a.length+1,numRows:a[0].length+1},b));e.data.data.forEach(function(b,d){e.data.columns.forEach(function(c,e){0!==e&&(0===d?b[c.field]=a[e-1][0].fieldCategory||"":(e=a[e-1][d-1],b.field0=b.field0||(e.script?e.script.alias:e.alias),b.fieldInfos[c.field]=
e))})});g.provideSpaceAfter(e);return e}()]}},provideSpaceAfter:function(a,b){a.style.spaceAfter=Math.max(b||0,90-15.07*a.data.data.length)},applyDefaultStyling:function(a){var b=!0;a.data.data.forEach(function(e,c){a.data.columns.forEach(function(a){e.style.fields[a.field].overrideStyle=0===c?"TableHeader":b?"AlternatingRow":void 0});b=!b})},setTableHeaderStyle:function(a){if(a.style)for(var b in a.style.fields)(a.style.fields[b]=a.style.fields[b]||{}).overrideStyle="TableHeader"},DEFAULT_ROW_HEIGHT:15.07};
return g});