// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
var __extends=this&&this.__extends||function(){var l=function(e,d){l=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(d,f){d.__proto__=f}||function(d,f){for(var e in f)f.hasOwnProperty(e)&&(d[e]=f[e])};return l(e,d)};return function(e,d){function k(){this.constructor=e}l(e,d);e.prototype=null===d?Object.create(d):(k.prototype=d.prototype,new k)}}();
define("esri/arcade/featureset/support/BigDataFeatureSetIterator","require exports dojo/Deferred ../../../graphic ../support/shared ./FeatureSetIterator ../../../geometry/jsonUtils".split(" "),function(l,e,d,k,f,m,n){return function(e){function h(a,b){a=e.call(this,a,b)||this;a._currentPage=null;a._iteratorStarted=!1;a._indexInCurrentPage=0;a._noMorePages=!1;a._script=null;a._featuresetMoniker="";return a}__extends(h,e);h.prototype.reset=function(){this._currentPage=null;this._iteratorStarted=!1;
this._indexInCurrentPage=0;this._featuresetMoniker=""};h.prototype.next=function(){var a=this,b=new d;!1===this._iteratorStarted?this.requestFirstPage().then(f.callback(function(){a.handleFeatureFromPage(b)},b),function(a){b.reject(a)}):this.handleFeatureFromPage(b);return b.promise};h.prototype.handleFeatureFromPage=function(a){var b=this;null===this._currentPage&&a.resolve(null);if(this._indexInCurrentPage<this._currentPage.length){this._indexInCurrentPage++;var c=this._currentPage[this._indexInCurrentPage-
1];if(null!==c&&!(c instanceof k)){var g=null;null!==c.geometry&&(g=this._script.spatialReference,g.toJson?g=g.toJson():g.toJson&&(g=g.toJson()),c.geometry.spatialReference=g,g=n.fromJson(c.geometry));c=new k({geometry:g,attributes:c.attributes});this._currentPage[this._indexInCurrentPage-1]=c}a.resolve(c)}else 0===this._currentPage.length?(this._noMorePages=!0,this._currentPage=null,this._indexInCurrentPage=0,a.resolve(null)):this.requestNextPage().then(f.callback(function(){b.handleFeatureFromPage(a)},
a),function(b){a.reject(b)})};h.prototype.requestFirstPage=function(){var a=this,b=new d;this._indexInCurrentPage=0;this._currentPage=[];this._parent.top(1E3).expressAsArcadeScript().then(f.callback(function(c){c.script+="\n return "+c.featuresetIdentifier+";\n";a._script=c;c=a._parent.sourceGeoAnalyticsProvider();null===c?b.reject(Error("No Big Data Provider")):c.executeFeatureSetPageRequest(a._script.script,a._script.globals,a._script.spatialReference,"").then(function(c){a._featuresetMoniker=c.moniker;
a._currentPage=c.records;a._iteratorStarted=!0;b.resolve(!0)},function(a){b.reject(a)})},b),function(a){b.reject(a)});return b.promise};h.prototype.requestNextPage=function(){var a=this,b=new d;this._indexInCurrentPage=0;this._currentPage=[];var c=this._parent.sourceGeoAnalyticsProvider();null===c?b.reject(Error("No Big Data Provider")):c.executeFeatureSetPageRequest(this._script.script,this._script.globals,this._script.spatialReference,this._featuresetMoniker).then(function(c){a._currentPage=c.records;
b.resolve(!0)},function(a){b.reject(a)});return b.promise};h.prototype.count=function(){var a=this,b=new d;-1!==this._parent._totalCount?b.resolve(this._parent._totalCount):this._parent.count().then(f.callback(function(c){a._parent._totalCount=c;b.resolve(a._parent._totalCount)},b),f.errback(b));return b.promise};return h}(m)});