// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/infographics/utils/InfographicLayoutResizer",["dojo/_base/lang","../../supportClasses/tableJson/TableJsonUtil","esri/dijit/geoenrichment/utils/ObjectUtil"],function(r,t,u){function m(a){var b={l:1E6,t:1E6,w:0,h:0};a.forEach(function(a){b.l=Math.min(b.l,a.left);b.t=Math.min(b.t,a.top);b.w=Math.max(b.w,a.left+a.width);b.h=Math.max(b.h,a.top+a.height)});b.w-=b.l;b.h-=b.t;return b}function n(a){var b=[];p.forEach(function(c){a[c]&&b.push(a[c].style)});
return b}function v(a,b,c,e){e=e||{};p.forEach(function(f){var d=a[f]&&a[f].style;if(d)if(e.preserveElementsSize){var k=d.left+d.width/2,g=d.top+d.height/2,k=k*b,g=g*c;d.left=k-d.width/2;d.top=g-d.height/2}else k=function(){var b=a[f].themeStyle;return d.fontSize||b&&b.fontSize},g=k()?k()/d.height:1,d.left*=b,d.width*=b,d.top*=c,d.height*=c,e.updateFontSize&&("description"===f||"variable"===f)&&k()&&(d.fontSize=u.roundNumber(g*d.height,2))})}var g={getContentDim:function(a){var b=a.header?t.getTableHeight(a.header)+
(a.header.style.spaceBefore||0):5,b={w:a.style.width,h:a.style.height-b,t:b,l:0,prettyBoxConstraints:{minW:"number"===typeof a.style.minWidth?a.style.minWidth:50,maxW:"number"===typeof a.style.maxWidth?a.style.maxWidth:1E6,minH:"number"===typeof a.style.minHeight?a.style.minHeight:50,maxH:"number"===typeof a.style.maxHeight?a.style.maxHeight:1E6},hasHeader:!!a.header};if(a.variableTables){var c=[],e=[];a.variableTables.forEach(function(a){c.push(a.style);n(a).forEach(function(b){b=r.mixin({},b);b.left+=
a.style.left;b.top+=a.style.top;e.push(b)})});b.vtInnerBox=m(c);b.innerBox=m(e)}return b},resizeLayout:function(a,b,c,e){e=e||{};var f=g.getContentDim(a);a.style.width=b;a.style.height=c;a.header&&(a.header.data.columns[0].style.width="100%",e.preserveHeaderPosition?(b/=f.w,a.header.style.left*=b,a.header.style.width*=b):(a.header.style.left=0,a.header.style.spaceBefore=0,a.header.style.width=a.style.width));a.variableTables&&a.variableTables.length&&g._resizeVariableTables(a,f,e)},_resizeVariableTables:function(a,
b,c){function e(b,c){a.variableTables.forEach(function(a){a.style.left+=b;a.style.top+=c})}function f(b,c){a.variableTables.forEach(function(a){a.style.left*=b;a.style.top=(a.style.top-n)*c+n;g.resizeVariableTable(a,a.style.width*b,a.style.height*c,{preserveElementsSize:!d,updateFontSize:m})})}c=c||{};var d=c.allowResizeInnerElements,k=c.ignoreMinMaxConstraints,m=c.updateFontSize,h=g.getContentDim(a),n=h.t,l=1,q=1,l=h.w/b.w,q=h.h/b.h;if(k)f(l,q);else{var k=function(a,b,c,d,e,f){var h=1,g=0,k=!1;1<
b?c>=f?g=(d-c)/2:d<=e?g=(d-c)/2:c>e&&d<f?h=b:c<e&&d>e?(g=(e-c)/2,k=!0,h=d/e):c<f&&d>f&&(h=f/a,g=(d-f)/2):d>=f?g=(d-c)/2:c<=e?g=(d-c)/2:c<f&&d>e?h=b:d<e&&c>e?(h=e/a,g=(d-e)/2):c>f&&d<f&&(g=(f-c)/2,k=!0,h=d/f);return{scale:h,delta:g,shiftFirst:k}},p=h.vtInnerBox,l=k(p.w,l,b.w,h.w,h.prettyBoxConstraints.minW,h.prettyBoxConstraints.maxW);b=k(p.h,q,b.h,h.h,h.prettyBoxConstraints.minH,h.prettyBoxConstraints.maxH);l.shiftFirst?(e(l.delta,0),f(l.scale,1)):(f(l.scale,1),e(l.delta,0));b.shiftFirst?(e(0,b.delta),
f(1,b.scale)):(f(1,b.scale),e(0,b.delta))}c.headerChanged&&(c.headerPreChangeDim.hasHeader?e(0,-(c.headerPreChangeDim.t-h.t)):e(0,h.t-c.headerPreChangeDim.t),f(1,h.h/c.headerPreChangeDim.h))}},p=["shape","image","variable","description"];g.getVariableTableContentDim=function(a){return m(n(a))};g.resizeVariableTable=function(a,b,c,e){b=b||a.style.width;c=c||a.style.height;var f=b/a.style.width||1,d=c/a.style.height||1;a.style.width=b;a.style.height=c;v(a,f,d,e)};return g});