// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/infographics/paginatableTable/SectionJsonsBuilder","dojo/_base/lang ../../sections/SectionTypes ../../grid/coreUtils/GridDataUtil ../../supportClasses/tableJson/TableJsonResizeUtil ../../supportClasses/templateJsonUtils/fieldInfo/FieldInfoFormatUtil esri/dijit/geoenrichment/utils/FieldUtil".split(" "),function(e,w,q,r,x,t){var c={buildSectionJsonsAndStat:function(b){var a=c._collectGridDataObjectsAndStats(b);if(!a)return null;if(a.gridDataObjects.length)var d=
c._splitRowsByPages(a.gridDataObjects,b).map(function(a){return c._buildSectionJsonForPage(a,b)});return{sectionJsons:d,stats:a.stats,unitedSectionJson:c._buildSectionJsonForPage(a.gridDataObjects,b)}},_collectGridDataObjectsAndStats:function(b){var a=b.calculatorDataArray,d=b.searchTextRe;if(!a||!a.length)return null;var c=b.dataSectionJson.stack[0],k=c.data.data[0],h=c.data.data[1],f={numAttributesTotal:0,numAttributesShown:0,ranges:{}},l;b.filterRanges&&(l={},b.filterRanges.forEach(function(a){l[a.fieldName]=
a}));for(var y in k.fieldInfos){var m=k.fieldInfos[y];t.isNumericField(m)&&(f.ranges[m.name]={fieldName:m.name,alias:m.alias,min:Infinity,max:-Infinity,decimals:m.decimals,dataArray:[]})}var p=[];a.forEach(function(a,v){var n={style:null,fieldInfos:{}};f.numAttributesTotal++;var e=!1,u=!1,m=!1;c.data.columns.forEach(function(b){var c=k.fieldInfos[b.field],g=a[c.name];if(t.isNumericField(c)&&"number"===typeof g&&!isNaN(g)){var h=f.ranges[c.name];h.min=Math.min(h.min,g);h.max=Math.max(h.max,g);h.dataArray.push(g)}void 0===
g||"string"===typeof g?n[b.field]=g||"":(n[b.field]=x.formatNumber(g,c),q.setNumericDataValue(g,n,b.field));n.__attributeIndex=v;(b=l&&l[c.name])&&(g<b.min||g>b.max)&&(e=!0);d&&"string"===typeof g&&(u=!0,d.test(g)&&(m=!0))});var h=e||u&&!m;h||(p.push(n),f.numAttributesShown++);b.setAttributeVisibleAt&&b.setAttributeVisibleAt(v,!h)});b.sorting&&p.sort(function(a,c){var d=q.getNumericDataValue(a,b.sorting.field),d=void 0!==d?d:a[b.sorting.field];a=q.getNumericDataValue(c,b.sorting.field);a=void 0!==
a?a:c[b.sorting.field];c="number"===typeof d?d-a:d.localeCompare(a);return"desc"===b.sorting.order?-c:c});p.forEach(function(a,b){a.style=e.clone((0!==b%2?h||k:k).style);a.style.height=k.style.height});f.ranges=Object.keys(f.ranges).map(function(a){return f.ranges[a]});return{stats:f,gridDataObjects:p}},getAttributeIndexForGridData:function(b){return b.__attributeIndex},_splitRowsByPages:function(b,a){var d=c._getHeaderHeight(a),e=c._getDataRowHeight(a),k=c._getDataListHeight(b,a),h=[],f,l=0;b.forEach(function(a){f||
(f=[],h.push(f),l+=d);f.push(a);l+=e;l+e>k&&(f=null,l=0)});return h},_getHeaderHeight:function(b){return b.scaleToFitHeight?b.minRowHeight:b.headerSectionJson?b.headerSectionJson.stack[0].data.data[0].style.height:0},_getDataRowHeight:function(b){return b.scaleToFitHeight?b.minRowHeight:b.dataSectionJson.stack[0].data.data[0].style.height},_getDataListHeight:function(b,a){var d=c._getHeaderHeight(a),e=c._getDataRowHeight(a),k=a.height-(a.hasFooter?a.footerHeight:0)-(a.hasTitle?a.titleHeight:0);a=
a.height-a.footerHeight-(a.hasTitle?a.titleHeight:0);return d+e*b.length<=k?k:a},_buildSectionJsonForPage:function(b,a){var d;a.headerSectionJson?(d=a.headerSectionJson.stack[0],d={id:"table",attributes:{},style:{width:a.width},data:{columns:e.clone(d.data.columns),data:[e.clone(d.data.data[0])].concat(e.clone(b))}}):d={id:"table",attributes:{},style:{width:a.width},data:{columns:e.clone(a.dataSectionJson.stack[0].data.columns),data:e.clone(b)}};d.data.data.forEach(function(b,d){b.style.height=0===
d&&a.headerSectionJson?c._getHeaderHeight(a):c._getDataRowHeight(a)});a.scaleToFitHeight&&(b=c._getDataListHeight(b,a),r.resizeTableJsonToFitHeight(d,b));r.resizeTableJsonToFitWidth(d,a.width);return{type:w.DETAILS,stack:[d]}}};return c});