// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/layers/rasterLib/function/rasterIndex",["dojo/_base/lang"],function(n){return{calculate:function(f,e){if(f&&f.pixels&&f.pixels.length){var g=e&&e.bandIndexes;e=e&&e.method;var c=g.trim().split(" ").map(function(a){return parseInt(a,10)}).filter(function(a){return null!=a});f=this._clonePixelBlock(f);var d=f.pixels,b=f.mask;switch(e){case 1:d=this._calculateNDVI(b,d[c[0]-1],d[c[1]-1]);break;case 2:d=this._calculateSAVI(b,d[c[0]-1],d[c[1]-1],c[2]);break;case 3:d=this._calculateTSAVI(b,
d[c[0]-1],d[c[1]-1],c[2],c[3],c[4]);break;case 4:d=this._calculateMSAVI(b,d[c[0]-1],d[c[1]-1]);break;case 5:d=this._calculateGEMI(b,d[c[0]-1],d[c[1]-1]);break;case 6:d=this._calculatePVI(b,d[c[0]-1],d[c[1]-1],c[2],c[3]);break;case 7:d=this._calculateGVITM(b,d[c[0]-1],d[c[1]-1],d[c[2]-1],d[c[3]-1],d[c[4]-1],d[c[5]-1]);break;case 8:d=this._calculateSultan(b,d[c[0]-1],d[c[1]-1],d[c[2]-1],d[c[3]-1],d[c[4]-1],d[c[5]-1]);break;case 0:d=this._calculateUserDefined(b,d,g)}f.pixels=d;f.pixelType="F32";f.calculateStatistics();
return f}},_clonePixelBlock:function(f){return f.clone?f.clone():n.clone(f)},_parseUserDefined:function(f,e){f=f.replace(" ","");0===f.indexOf("-")&&(f="0"+f);0===f.indexOf("+")&&(f=f.slice(1,f.length));f=f.split("");var g=[],c=[],d="+-*/()".split(""),b,a="",h;for(b=0;b<f.length;b++)h=f[b],d.some(function(a){return a===h})?(""!==a&&c.push(parseFloat(a)),g.push(h),a=""):"b"===h.toLowerCase()?(b++,a=h.concat(f[b]),c.push(e[parseInt(a[1],10)-1]),a=""):(a=a.concat(h),b===f.length-1&&c.push(parseFloat(a)));
return{ops:g,nums:c}},_op:function(f,e,g,c){if(g.constructor===Number&&c.constructor===Number)return g+c;var d,b,a;if(g.constructor===Number)for(d=c.length,b=g,g=new Float32Array(d),a=0;a<d;a++)g[a]=b;else if(d=g.length,c.constructor===Number)for(b=c,c=new Float32Array(d),a=0;a<d;a++)c[a]=b;b=new Float32Array(d);if(null==f)if("+"===e)for(a=0;a<d;a++)b[a]=g[a]+c[a];else if("-"===e)for(a=0;a<d;a++)b[a]=g[a]-c[a];else if("*"===e)for(a=0;a<d;a++)b[a]=g[a]*c[a];else{if("/"===e)for(a=0;a<d;a++)b[a]=g[a]/
c[a]}else if("+"===e)for(a=0;a<d;a++)f[a]&&(b[a]=g[a]+c[a]);else if("-"===e)for(a=0;a<d;a++)f[a]&&(b[a]=g[a]-c[a]);else if("*"===e)for(a=0;a<d;a++)f[a]&&(b[a]=g[a]*c[a]);else if("/"===e)for(a=0;a<d;a++)f[a]&&(b[a]=g[a]/c[a]);return b},_shrinkOp:function(f,e){f.splice(e,1);var g=e=0,c=0;do{for(e=c=g=0;e<f.length;e++)if("("===f[e])g=e;else if(")"===f[e]){c=e;break}c===g+1&&f.splice(g,2)}while(c===g+1);return f},_getPriorityOpIndex:function(f,e){if(1===f.length)return{opIndex:0,numIndex:0};var g=e=0,
c=0,d=-1,b=0,a;for(e=0;e<f.length;e++)if("("===f[e])g=e;else if(")"===f[e]){c=e;break}a=0===c?f:f.slice(g+1,c);for(e=0;e<a.length;e++)if("*"===a[e]||"/"===a[e]){d=e;break}if(!(-1<d))for(e=0;e<a.length;e++)if("+"===a[e]||"-"===a[e]){d=e;break}0<c&&(d+=g+1);for(e=0;e<d;e++)"("===f[e]&&b++;return{opIndex:d,numIndex:d-b}},_calculateUserDefined:function(f,e,g){e=this._parseUserDefined(g,e);g=e.ops;for(var c=e.nums,d,b,a;0<g.length&&(e=this._getPriorityOpIndex(g,c),d=g[e.opIndex],b=c[e.numIndex],a=c[e.numIndex+
1],d=this._op(f,d,b,a),1!==g.length);)g=this._shrinkOp(g,e.opIndex),c.splice(e.numIndex,2,d);return[d]},_calculateNDVI:function(f,e,g){var c=g.length,d=new Float32Array(c),b,a,h;if(null==f)for(b=0;b<c;b++)a=g[b],h=e[b],d[b]=(h-a)/(h+a);else for(b=0;b<c;b++)f[b]&&(a=g[b],h=e[b],d[b]=(h-a)/(h+a));return[d]},_calculateSAVI:function(f,e,g,c){var d=g.length,b=new Float32Array(d),a,h,m;if(null==f)for(a=0;a<d;a++)h=g[a],m=e[a],b[a]=(m-h)/(m+h+c)*(1+c);else for(a=0;a<d;a++)f[a]&&(h=g[a],m=e[a],b[a]=(m-h)/
(m+h+c)*(1+c));return[b]},_calculateTSAVI:function(f,e,g,c,d,b){var a=g.length,h=new Float32Array(a),m,k,l=-d*c+b*(1+c*c);if(null==f)for(b=0;b<a;b++)m=g[b],k=e[b],h[b]=c*(k-c*m-d)/(d*k+m+l);else for(b=0;b<a;b++)f[b]&&(m=g[b],k=e[b],h[b]=c*(k-c*m-d)/(d*k+m+l));return[h]},_calculateMSAVI:function(f,e,g){var c=g.length,d=new Float32Array(c),b,a,h;if(null==f)for(b=0;b<c;b++)a=g[b],h=e[b],d[b]=.5*(2*(h+1)-Math.sqrt(Math.pow(2*h+1,2)-8*(h-a)));else for(b=0;b<c;b++)f[b]&&(d[b]=.5*(2*(h+1)-Math.sqrt(Math.pow(2*
h+1,2)-8*(h-a))));return[d]},_calculateGEMI:function(f,e,g){var c=g.length,d=new Float32Array(c),b,a,h;if(null==f)for(b=0;b<c;b++)a=g[b],h=e[b],h=(2*(h*h-a*a)+1.5*h+.5*a)/(h+a+.5),d[b]=h*(1-.25*h)-(a-.125)/(1-a);else for(b=0;b<c;b++)f[b]&&(a=g[b],h=e[b],h=(2*(h*h-a*a)+1.5*h+.5*a)/(h+a+.5),d[b]=h*(1-.25*h)-(a-.125)/(1-a));return[d]},_calculatePVI:function(f,e,g,c,d){var b=g.length,a=new Float32Array(b),h,m,k,l=Math.sqrt(1+c*c);if(null==f)for(h=0;h<b;h++)m=g[h],k=e[h],a[h]=(k-c*m-d)/l;else for(h=0;h<
b;h++)f[h]&&(m=g[h],k=e[h],a[h]=(k-c*m-d)/l);return[a]},_calculateGVITM:function(f,e,g,c,d,b,a){var h=e.length,m=new Float32Array(h),k;if(null==f)for(k=0;k<h;k++)m[k]=-.2848*e[k]-.2435*g[k]-.5436*c[k]+.7243*d[k]+.084*b[k]-1.18*a[k];else for(k=0;k<h;k++)f[k]&&(m[k]=-.2848*e[k]-.2435*g[k]-.5436*c[k]+.7243*d[k]+.084*b[k]-1.18*a[k]);return[m]},_calculateSultan:function(f,e,g,c,d,b,a){g=e.length;var h=new Float32Array(g),m=new Float32Array(g),k=new Float32Array(g),l;if(null==f)for(l=0;l<g;l++)h[l]=b[l]/
a[l]*100,m[l]=b[l]/e[l]*100,k[l]=c[l]/d[l]*(b[l]/d[l])*100;else for(l=0;l<g;l++)f[l]&&(h[l]=b[l]/a[l]*100,m[l]=b[l]/e[l]*100,k[l]=c[l]/d[l]*(b[l]/d[l])*100);return[h,m,k]}}});