// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/templateJsonUtils/query/_SectionJsonCollector",[],function(){var k={},m={provideParentInfo:function(a,b,c,d,e,f){g.collectStatistics(b);var h;a:{switch(e){case "floating":h=b.style.left+f.left;break a;case "page":h=g.calcX(b,c,d)+f.left;break a}h=void 0}a:{switch(e){case "floating":e=b.style.spaceBefore+f.top;break a;case "page":e=g.calcY(b,c,d)+f.top;break a}e=void 0}a._parentBox={x:h,y:e,w:g.calcFullWidth(b,c,d),h:g.calcFullHeight(b,
c,d)};b=d.field;c.style.fields=c.style.fields||{};c=(c.style.fields[b]=c.style.fields[b]||{}).backgroundColor;a._parentStyle={backgroundColor:c}},sanitize:function(a){g.sanitize(a)}},g={collectStatistics:function(a){if(!a._measureInfo){var b={},c={},d;a.data.columns.forEach(function(a){d&&(c[d.field]=a);d=a;b[a.field]=a});var e={},f={},h={},k={},m={},q={};a.data.data.forEach(function(b,c){a.data.columns.forEach(function(a,d){var n=m[d]||0,p=q[c]||0,l=g._getDataHeight(b,a.field);a=g._getFieldWidth(b,
a);n+=l;p+=a;m[d]=n;q[c]=p;l=d+"_"+c;f[l]=n;e[l]=p;h[l]=e[d-1+"_"+c]||0;k[l]=f[d+"_"+(c-1)]||0})});a._measureInfo={xPositions:h,yPositions:k,columnsHash:b,nextColumnHash:c}}},calcX:function(a,b,c){c=a.data.columns.indexOf(c);b=a.data.data.indexOf(b);return a._measureInfo.xPositions[c+"_"+b]||0},calcY:function(a,b,c){c=a.data.columns.indexOf(c);b=a.data.data.indexOf(b);return a._measureInfo.yPositions[c+"_"+b]||0},_getFieldWidth:function(a,b){a.style.fields=a.style.fields||{};return(a.style.fields[b.field]=
a.style.fields[b.field]||{}).width||b.style.width},calcFullWidth:function(a,b,c){c=c.field;var d=g._getFieldWidth(b,a._measureInfo.columnsHash[c]),e=b.columnSpans&&b.columnSpans[c]||1;if(1<e)for(var f,h=0;h<e-1;h++)f=a._measureInfo.nextColumnHash[f?f.field:c],d+=g._getFieldWidth(b,f);return d},_getDataHeight:function(a,b){a.style.fields=a.style.fields||{};return(a.style.fields[b]=a.style.fields[b]||{}).height||a.style.height},calcFullHeight:function(a,b,c){c=c.field;var d=a.data.data.indexOf(b),e=
g._getDataHeight(b,c);b=b.rowSpans&&b.rowSpans[c]||1;if(1<b)for(var f=d+1,h=0;h<b-1;h++)d=a.data.data[f++],e+=g._getDataHeight(d,c);return e},sanitize:function(a){delete a._measureInfo}};k.collectSectionJsons=function(a,b){b=b||{};var c=[];if(!a)return[];if(a.sections)return a.sections;if(!a.sectionsTables)return[];a.sectionsTables.forEach(function(d){k._processTableJson(d,c,"page",a.documentOptions,b);!1!==b.backgroundForeground&&(d.backgroundSectionJson&&c.push(d.backgroundSectionJson),d.foregroundSectionJson&&
c.push(d.foregroundSectionJson));!1!==b.floatingTables&&d.backgroundFloatingTablesSectionJson&&d.backgroundFloatingTablesSectionJson.stack.forEach(function(d){"table"===d.id&&k._processTableJson(d,c,"floating",a.documentOptions,b)});!1!==b.floatingTables&&d.foregroundFloatingTablesSectionJson&&d.foregroundFloatingTablesSectionJson.stack.forEach(function(d){"table"===d.id&&k._processTableJson(d,c,"floating",a.documentOptions,b)})});return c.filter(function(a){return!!a.stack})};k._processTableJson=
function(a,b,c,d,e){a.data.data.forEach(function(f){f.fieldInfos&&a.data.columns.forEach(function(h){var g=f.fieldInfos[h.field];g&&g.sectionJson&&(e.processFieldInfoFunc&&e.processFieldInfoFunc(g),!1!==e.saveParentInfo&&m.provideParentInfo(g.sectionJson,a,f,h,c,d),b.push(g.sectionJson))})});m.sanitize(a)};k.getParentBox=function(a){return a&&a._parentBox};k.getParentStyle=function(a){return a&&a._parentStyle};return k});