// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/templateJsonUtils/query/TemplateJsonQueryUtil",["./_SectionJsonCollector","../../../infographics/InfographicTypes"],function(h,g){var d={},e={process:function(a,c,b,d,f){var k=d;d=function(a,c,b){a&&k.apply(this,arguments)};f={processLevel:c,objJson:b,processFunc:d,ignoreComparisonCalculators:f&&f.ignoreComparisonCalculators};a===c?d(b):"document"===a?e._processTemplateJson(b,f):"section"===a?e._processSectionJson(b,f):"table"===a?
e._processTableJson(b,f):"tableRow"===a&&e._processTableDataObj(b,f)},_processTemplateJson:function(a,c){a.sectionsTables?a.sectionsTables.forEach(function(a){e._processTableJson(a,c)}):h.collectSectionJsons(a,{saveParentInfo:!1,processFieldInfoFunc:function(a){"field"===c.processLevel&&c.processFunc(a)}}).forEach(function(a){e._processSectionJson(a,c)})},_processSectionJson:function(a,c){"section"===c.processLevel?c.processFunc(a):a.stack&&a.stack.forEach(function(a){"sectionElement"===c.processLevel?
c.processFunc(a):"table"===a.id&&("table"===c.processLevel?c.processFunc(a):e._processTableJson(a,c))})},_processTableJson:function(a,c,b){a.data.data.forEach(function(a){"tableRow"===c.processLevel&&c.processFunc(a,b);e._processTableDataObj(a,c,b)});a.backgroundSectionJson&&e._processSectionJson(a.backgroundSectionJson,c);a.foregroundSectionJson&&e._processSectionJson(a.foregroundSectionJson,c);a.backgroundFloatingTablesSectionJson&&e._processSectionJson(a.backgroundFloatingTablesSectionJson,c);
a.foregroundFloatingTablesSectionJson&&e._processSectionJson(a.foregroundFloatingTablesSectionJson,c)},_processTableDataObj:function(a,c,b){if(a.fieldInfos)for(var d in a.fieldInfos)e._processFieldInfo(a.fieldInfos[d],c,b)},_processFieldInfo:function(a,c,b){function d(a,b){"field"===c.processLevel&&c.processFunc(a,b)}a&&(d(a,b),a&&a.triggerJson&&a.triggerJson.fieldInfo&&a.templateName!==a.triggerJson.fieldInfo.templateName&&d(a.triggerJson.fieldInfo,a),a.linkFieldInfo&&d(a.linkFieldInfo,a),a.isInfographic&&
e._processInfographicFieldInfo(a,c),a.isRichText&&(a.richTextJson.fieldInfos.forEach(function(b){e._processFieldInfo(b,c,a)}),a.richTextJson.specialFieldInfos.forEach(function(b){e._processFieldInfo(b,c,a)})),a.isChart&&(b=a.chartJson.visualProperties,b.chartIcons&&b.chartIcons.forEach(function(b){e._processFieldInfo(b,c,a)}),b.floatingIcons&&b.floatingIcons.forEach(function(b){e._processTableJson(b,c,a)}),b.floatingTexts&&b.floatingTexts.forEach(function(b){e._processTableJson(b,c,a)}),a.chartJson.seriesItems.forEach(function(b){b.points.forEach(function(b){c.ignoreComparisonCalculators&&
a.chartJson.comparisonInfo||e._processFieldInfo(b.fieldInfo,c,a);b.iconFieldInfo&&e._processFieldInfo(b.iconFieldInfo,c,a);b.captionFieldInfo&&e._processFieldInfo(b.captionFieldInfo,c,a)})})),a.isReportSection&&a.sectionJson&&e._processSectionJson(a.sectionJson,c))},_processInfographicFieldInfo:function(a,c){var b=a.infographicJson;switch(b.type){case g.STATIC:b.header&&e._processTableJson(b.header,c,a);b.variableTables&&b.variableTables.forEach(function(b){b.variable&&e._processFieldInfo(b.variable.fieldInfo,
c,a);b.description&&b.description.fieldInfo&&e._processFieldInfo(b.description.fieldInfo,c,a)});if(b.dataDrilling)for(var d in b.dataDrilling){var f=b.dataDrilling[d];f&&f.sectionJson&&e._processSectionJson(f.sectionJson,c)}break;case g.AREA_DETAILS:b.header&&e._processTableJson(b.header,c,a);break;case g.AGE_PYRAMID:case g.TAPESTRY:case g.RELATED_VARS:case g.ONE_VAR:!c.ignoreComparisonCalculators&&b.fieldInfos&&b.fieldInfos.forEach(function(b){e._processFieldInfo(b,c,a)});break;case g.LOCATOR_TABLE:b.titleSectionJson&&
e._processSectionJson(b.titleSectionJson,c);e._processSectionJson(b.headerSectionJson,c);e._processSectionJson(b.dataSectionJson,c);break;case g.COMPARISON_TABLE:b.titleSectionJson&&e._processSectionJson(b.titleSectionJson,c),c.ignoreComparisonCalculators||e._processSectionJson(b.dataSectionJson,c)}}};d.DOCUMENT="document";d.SECTION="section";d.TABLE="table";d.SECTION_ELEMENT="sectionElement";d.TABLE_ROW="tableRow";d.FIELD="field";d.process=e.process;d.processTemplateFieldInfos=function(a,c,b){e.process("document",
"field",a,c,b)};d.processSectionFieldInfos=function(a,c,b){e.process("section","field",a,c,b)};d.processSectionElements=function(a,c){e.process("document","sectionElement",a,c)};d.processTableFieldInfos=function(a,c,b){e.process("table","field",a,c,b)};d.hasMultiFeatureChart=function(a){var c=!1;d.processTemplateFieldInfos(a,function(a){a.isChart&&(c=c||a.chartJson&&!!a.chartJson.isMultiFeatureChart)});return c};d.hasComparisonInfographicTable=function(a){var c=!1;d.processTemplateFieldInfos(a,function(a){a.isInfographic&&
(c=c||a.infographicJson&&a.infographicJson.type===g.COMPARISON_TABLE)});return c};d.isGraphicReport=function(a){return!!a.sectionsTables};d.hasDynamicColumns=function(a){return d._checkTableAttributes(a,function(a){return 0<a.dynamicColumns})};d.hasDynamicRows=function(a){return d._checkTableAttributes(a,function(a){return 0<a.dynamicRows})};d._checkTableAttributes=function(a,c){var b;d.isGraphicReport(a)?d.processTemplateFieldInfos(a,function(a){a.isReportSection&&a.sectionJson&&a.sectionJson.stack&&
a.sectionJson.stack.some(function(a){if("table"===a.id&&a.attributes&&c(a.attributes))return b=!0})}):b=d.collectSectionJsons(a).some(function(a){return a.stack&&a.stack.some(function(a){return"table"===a.id&&a.attributes&&c(a.attributes)})});return b};d.hasMultiFeatureSections=function(a){return d.isGraphicReport(a)?d.hasMultiFeatureChart(a)||d.hasDynamicColumns(a)||d.hasComparisonInfographicTable(a):!1};d.collectSectionJsons=h.collectSectionJsons;d.getParentBox=h.getParentBox;d.getParentStyle=h.getParentStyle;
return d});