// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/geoenrichment/ReportPlayer/core/templates/ComparisonTableInfographic.html":'\x3cdiv class\x3d"esriGEComparisonTableInfographic"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"noDataPlaceHolder" class\x3d"esriGENoDataPlaceHolder"\x3e\r\n        \x3cdiv class\x3d"esriGENoDataPlaceHolderLabel"\x3e${nls.noComparisonData}\x3c/div\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"titleDiv" class\x3d"comparisonTableInfographic_titleDiv"\x3e\x3c/div\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"dataDiv" class\x3d"comparisonTableInfographic_dataDiv"\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"dataSectionDiv" class\x3d"esriGEAbsoluteStretched"\x3e\x3c/div\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"chartDiv" class\x3d"esriGEAbsoluteStretched"\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e\r\n\r\n\r\n'}});
define("esri/dijit/geoenrichment/ReportPlayer/core/infographics/comparison/ComparisonTableInfographic","dojo/_base/declare dojo/_base/lang dojo/on dojo/when dojo/dom-style dijit/_WidgetBase dijit/_TemplatedMixin ../../sections/supportClasses/SectionContentFitModes ../../supportClasses/ViewModes ../../../dataProvider/supportClasses/AreaDataUtil ../../supportClasses/tableJson/TableJsonUtil ../../supportClasses/tableJson/TablePrettyParameters ../utils/InfographicThemeUtil ./jsonBuilder/SectionJsonBuilder ./ComparisonSelectionBuilder ./ChartViewBuilder esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/InvokeUtil esri/dijit/geoenrichment/utils/WaitingUtil dojo/text!../../templates/ComparisonTableInfographic.html dojo/i18n!esri/nls/jsapi".split(" "),
function(h,m,k,t,n,u,v,q,l,w,x,r,y,f,z,A,e,B,C,D,p){p=p.geoenrichment.dijit.ReportPlayer.ComparisonTableInfographic;h=h([u,v],{templateString:D,nls:p,viewModel:null,theme:null,parentWidget:null,isEditMode:!1,simplifySelectionForSingleGeography:!0,minRowHeight:20,_titleSection:null,_dataSection:null,_currentInfographicJson:null,_updatePromise:null,_selectedLevelsCache:null,_additionalColumnsCache:null,_sorting:null,_columnWidths:null,_dataInfo:null,_analysisAreas:null,_isChartView:!1,_chartViewBuilder:null,
_stdPolygonsController:null,_thisAreasHighlightController:null,postCreate:function(){this.inherited(arguments);this._selectedLevelsCache={};this._additionalColumnsCache={};this._showEmptyView(!1)},updateInfographic:function(a){if(this.domNode)return this._currentInfographicJson=a,this._analysisAreas=this.viewModel.dynamicReportInfo&&this.viewModel.dynamicReportInfo.analysisAreas,a=this.viewModel.getStaticInfographicDefaultStyles(this.theme),y.applyThemeSettingsComparisonInfographicJson(this._currentInfographicJson,
a),this.viewModel.dynamicReportInfo&&(this._stdPolygonsController=this.viewModel.getStdPolygonsController(this._currentInfographicJson.calculatorName,this.currentFeatureIndex),this.own(this._stdPolygonsController),this._thisAreasHighlightController=this.viewModel.getThisAreasHighlightController(),this.own(this._thisAreasHighlightController)),this.onContentLoadingStart(),this._updatePromise=this._updateContent(),C.showProgressPromise(this.domNode,this._updatePromise),this._updatePromise.always(function(){this.onContentLoadingEnd()}.bind(this)),
this._updatePromise},_updateContent:function(){return B.invoke(this,"_doUpdateContent",50)},_doUpdateContent:function(){this._destroySections();this.domNode&&this.width&&(this._resizeContent(),this._createTitleSection(),this._createDataSection(),this.onContentUpdated(),this.setChartView(this._isChartView))},_resizeContent:function(){this._syncJsonDimensions();n.set(this.domNode,{width:this.width+"px",height:this.height+"px"});setTimeout(this._syncEmptyViewPlaceholder.bind(this))},_syncJsonDimensions:function(){this._currentInfographicJson&&
(this._currentInfographicJson.style.width=this.width,this._currentInfographicJson.style.height=this.height)},_createTitleSection:function(){if(this._currentInfographicJson.titleSectionJson){var a={};a.initialWidth=this.width;a.json=this._currentInfographicJson.titleSectionJson;a.viewModel=this.viewModel;a.theme=this.theme;a.hasFixedLayout=!1;a.parentWidget=this;a.noContentOffset=!0;a.tableParams={trimTextIfOverflows:!0};a.initialViewMode=this.isEditMode?l.EDIT:l.PREVIEW_VALUES;m.mixin(a,this._prepareTitleSectionCreationParams());
this._titleSection=this.viewModel.layoutBuilder.createElement("section",a,this.titleDiv);this._titleSection.setWidth(this.width);this._titleSection.fitContentNicely({fitMode:q.WIDTH})}},_prepareTitleSectionCreationParams:function(){return null},_createDataSection:function(){var a=this,b={};b.initialWidth=this.width;this._dataInfo=this._buildDataInfo();this._showEmptyView(!this._dataInfo);if(this._dataInfo){b.json=this._dataInfo.sectionJson;b.viewModel=this.viewModel;b.theme=this.theme;b.hasFixedLayout=
!1;b.parentWidget=this;b.noContentOffset=!0;b.tableParams={trimTextIfOverflows:!0,keepGridWidthWhenResized:!0,hasResizableColumns:!0,fitParentWhenResized:!0,enableAsyncRendering:!this.isEditMode,asyncBatchSize:this._dataInfo.sectionJson.stack[0].data.columns.length,layoutDefaults:{columnMinWidth:r.MIN_COLUMN_WIDTH},onColumnWidthChanged:function(){a._columnWidths=c&&c.columns.map(function(a){return a.style.width})}};b.initialViewMode=this.isEditMode?l.EDIT:l.PREVIEW_VALUES;m.mixin(b,this._prepareSectionCreationParams());
b=this.viewModel.layoutBuilder.createElement("section",b,this.dataSectionDiv);b.setResizedHeight(this._getDataHeight());b.setWidth(this.width);this._dataSection=b;var c=b.getTables()[0];c.onSortingChanged=function(b){a._sorting=b};this._sorting&&c.setSorting(this._sorting);this._resizeDataSection();new z({grid:b.getTables()[0],groups:this._dataInfo.groups,numThisAreas:this._dataInfo.numThisAreas,fields:this._dataInfo.fields,selectedLevelsCache:this._selectedLevelsCache,additionalColumnsCache:this._additionalColumnsCache,
variablesInColumns:this._currentInfographicJson.variablesInColumns,isEditMode:this.isEditMode,simplifySelectionForSingleGeography:this.simplifySelectionForSingleGeography,onFeatureSelected:function(b,c){a._selectedLevelsCache[b]=c;a._updateContent()},onAddFeature:function(b,c){b=a._additionalColumnsCache[b]=a._additionalColumnsCache[b]||[];-1===b.indexOf(c)&&b.push(c);a._updateContent()},onRemoveAdditionalFeature:function(b,c){b=a._additionalColumnsCache[b]=a._additionalColumnsCache[b]||[];c=b.indexOf(c);
-1!==c&&(b.splice(c,1),a._updateContent())}});this._stdPolygonsController&&this._registerTableForControllers()}else this._stdPolygonsController&&this._stdPolygonsController.setShownFeatureAttributes([])},_prepareSectionCreationParams:function(a){return null},_buildDataInfo:function(){return f.buildSectionJsonAndGroups({infographicJson:this._currentInfographicJson,calculators:this._getCalculatorDataArray(),selectedLevelsCache:this._selectedLevelsCache,additionalColumnsCache:this._additionalColumnsCache,
analysisAreas:this._analysisAreas,filterRanges:this._filterRanges,numLevels:this._currentInfographicJson.levels.length,width:this.width,height:this.height,columnWidths:this._columnWidths})},_getCalculatorDataArray:function(){var a=this;return this.viewModel.dynamicReportInfo.fieldData.areaData.map(function(b,c){return w.getAreaDataObjectCalculator(a.viewModel.dynamicReportInfo.fieldData.areaData[c],a._currentInfographicJson.calculatorName)})},_resizeDataSection:function(){this.dataDiv.style.top=this._getTitleHeight()+
"px";if(this.isEditMode){var a=this._dataSection.getTables()[0],b=a.store.data.length,b=Math.max(this._getDataHeight(),b*this.minRowHeight);a.resizeToFitHeight(b);this._dataSection.fitContentNicely({fitMode:q.WIDTH})}},_registerTableForControllers:function(){this._registerTableForStdController();this._dataInfo.numThisAreas&&this._registerTableForThisAreasController()},_registerTableForStdController:function(){var a=this;this._stdPolygonsController.setAttributeFields(this._dataInfo.fields);this._stdPolygonsController.setShownFeatureAttributes(this._dataInfo.geographiesInTable);
this._stdPolygonsController.setAllFeatureAttributes(this._dataInfo.allGeographies);var b=this._dataSection.getTables()[0],c;this._stdPolygonsController.registerInfographic({highlightInfographicForAttributes:function(d){if(b.domNode){var g=a._currentInfographicJson.variablesInColumns?"setCellRowHighlighted":"setCellColumnHighlighted";c&&(c.parentGrid&&c.parentGrid[g](c,!1),c=null);(d=d&&a._getCellForFeatureAttributes(d))&&d.parentGrid&&(d.parentGrid[g](d,!0),c=d)}}}).then(function(){if(b.domNode){var c;
a._currentInfographicJson.variablesInColumns?(b.set("highlightRowsOnHover",!0),b.canHighlightHeader=!1,b.canHighlightFirstColumn=!0):(b.set("highlightColumnsOnHover",!0),b.canHighlightHeader=!0,b.canHighlightFirstColumn=!1);k(b.domNode,"mouseover,mousemove",function(){var d=b.getOverFieldCell();d&&d!==c&&(c=d,a._stdPolygonsController.highlightGraphicForAttributes(c&&a._getCellAttrs(c)))});k(b.domNode,"mouseout",function(){a._stdPolygonsController.highlightGraphicForAttributes(null);c=null})}})},_registerTableForThisAreasController:function(){var a=
this,b=this._dataSection.getTables()[0],c;this._thisAreasHighlightController.registerTable({highlightTableForAreaIndex:function(d){if(b.domNode){var g=a._currentInfographicJson.variablesInColumns?"setCellRowHighlighted":"setCellColumnHighlighted";c&&(c.parentGrid&&c.parentGrid[g](c,!1),c=null);(d="number"===typeof d&&a._getCellForThisAreaAt(d))&&d.parentGrid&&(d.parentGrid[g](d,!0),c=d)}}}).then(function(){var c;a._currentInfographicJson.variablesInColumns?(b.set("highlightRowsOnHover",!0),b.canHighlightHeader=
!1,b.canHighlightFirstColumn=!0):(b.set("highlightColumnsOnHover",!0),b.canHighlightHeader=!0,b.canHighlightFirstColumn=!1);k(b.domNode,"mouseover,mousemove",function(){var d=b.getOverFieldCell();d&&d!==c&&(c=d,a._thisAreasHighlightController.highlightGraphicForAreaIndex(c&&f.getThisAreaIndex(a._getCellAttrs(c))))});k(b.domNode,"mouseout",function(){a._thisAreasHighlightController.highlightGraphicForAreaIndex(null);c=null})})},_getCellAttrs:function(a){return a?this._currentInfographicJson.variablesInColumns?
f.getAttributesForColumn(a.gridData):f.getAttributesForGridData(a.column):null},_getCellForFeatureAttributes:function(a){var b;a&&this._dataSection.getTables()[0].getFieldCells().some(function(c){var d=this._getCellAttrs(c);if(d&&d.StdGeographyLevel===a.StdGeographyLevel&&d.StdGeographyID==a.StdGeographyID)return b=c,!0},this);return b},_getCellForThisAreaAt:function(a){var b;this._dataSection.getTables()[0].getFieldCells().some(function(c){var d=this._getCellAttrs(c);if(d&&f.getThisAreaIndex(d)===
a)return b=c,!0},this);return b},_getTitleHeight:function(){return this._currentInfographicJson.titleSectionJson?x.getTableHeight(this._currentInfographicJson.titleSectionJson.stack[0])+r.TITLE_GAP:0},_getDataHeight:function(){return this.height-this._getTitleHeight()},notifyShown:function(){this._dataSection&&this._dataSection.notifyShown()},getVisualState:function(){return{filterRanges:this._filterRanges,selectedLevelsCache:this._selectedLevelsCache,additionalColumnsCache:this._additionalColumnsCache,
sorting:this._sorting,columnWidths:this._columnWidths,isChartView:this.isChartView()}},setVisualState:function(a){a&&(this._selectedLevelsCache=a.selectedLevelsCache||{},this._additionalColumnsCache=a.additionalColumnsCache||{},this._sorting=a.sorting,this._columnWidths=a.columnWidths,this._filterRanges=a.filterRanges,this._isChartView=a.isChartView,this._updateContent())},isChartView:function(){return!!this._chartViewBuilder},setChartView:function(a){this._chartViewBuilder&&this._chartViewBuilder.destroy();
this._chartViewBuilder=null;e.hide(this.chartDiv);e.show(this.dataSectionDiv);if(this._isChartView=a)e.show(this.chartDiv),e.hide(this.dataSectionDiv),this._chartViewBuilder=new A({viewModel:this.viewModel,theme:this.theme,parentWidget:this,chartNode:this.chartDiv,width:this.width,height:this._getDataHeight(),chartSeriesItems:this._dataInfo.chartSeriesItems}),this._chartViewBuilder.renderChart()},width:0,height:0,resize:function(a,b){void 0!==a&&(this.width=a,this.height=b);return this._updateContent()},
_showEmptyView:function(a){e[a?"hide":"show"]([this.titleDiv,this.dataDiv]);e[a?"show":"hide"](this.noDataPlaceHolder);a&&this._syncEmptyViewPlaceholder()},_syncEmptyViewPlaceholder:function(){this.noDataPlaceHolder&&n.set(this.noDataPlaceHolder,"paddingTop",(this.height-n.get(this.noDataPlaceHolder,"height"))/2+"px")},_filterRanges:null,getFilterRanges:function(){return t(this._updatePromise,function(){return this._dataInfo.ranges}.bind(this))},setFilterRanges:function(a){this._filterRanges=a;this._updateContent()},
getNumAreasTotal:function(){return this._dataInfo&&this._dataInfo.numAreasTotal||0},getNumAreasShown:function(){return this._dataInfo&&this._dataInfo.numAreasShown||0},toJson:function(){return m.clone(this._currentInfographicJson)},onContentLoadingStart:function(){},onContentLoadingEnd:function(){},onContentUpdated:function(){},_destroySections:function(){this._chartViewBuilder&&this._chartViewBuilder.destroy();this._chartViewBuilder=null;this._dataSection&&this._dataSection.destroy();this._dataSection=
null;this._titleSection&&this._titleSection.destroy();this._titleSection=null},destroy:function(){this._destroySections();this.inherited(arguments)}});h.MIN_ROW_HEIGHT=20;return h});