// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/FlowList","dojo/_base/declare dojo/_base/lang dojo/dom-construct dojo/dom-class dojo/on ./utils/DeviceUtil ./utils/DnDUtil ./utils/TooltipUtil ./FlowListDefaultItemRenderer dijit/_WidgetBase dijit/_TemplatedMixin".split(" "),function(d,k,l,e,f,g,m,n,h,p,q){d=d([p,q],{templateString:"\x3cdiv data-dojo-attach-point\x3d'listDiv' class\x3d'esriGEFlowList esriGENonSelectable'\x3e\x3c/div\x3e",idProperty:"value",labelProperty:"label",selectedIndex:-1,selectedItem:null,items:null,
store:null,defaultItemRendererClass:h,itemRenderer:null,itemClass:null,itemClassSelected:null,keepScrollPosition:!1,allowRepetitiveSelection:!0,selectOnMouseDown:!1,noDragTolerance:0,selectionValidator:null,allowManualSelection:!0,stopMouseEventPropagation:!0,hasSelectableItems:!0,autoDetectUrlsInLabels:!1,_addedWrappers:null,_clickHandles:null,_valueOnCreation:null,_isCreated:!1,postCreate:function(){this.inherited(arguments);this._clearHandlers();this._setUpItemRenderer();n.autoTooltip(this.domNode);
this._isCreated=!0;this._valueOnCreation?this._setValueAttr(this._valueOnCreation):this.refresh()},_setUpItemRenderer:function(){this.itemRenderer||(this.itemRenderer=new this.defaultItemRendererClass);this.itemClass&&(this.itemRenderer.itemClass=this.itemClass);this.itemClassSelected&&(this.itemRenderer.itemClassSelected=this.itemClassSelected)},_getValueAttr:function(){return this.selectedItem&&this.selectedItem[this.idProperty]},_setValueAttr:function(a){var c=this;if(this._isCreated){var b=this.items||
this.store&&this.store.data;b&&b.some(function(b){if(b[c.idProperty]==a)return c.setSelectedItem(b),!0})}else this._valueOnCreation=a},_scrollTopMemo:0,_memoScroll:function(){this._scrollTopMemo=this.listDiv.scrollTop},_applyScrollFromMemo:function(){this.listDiv.scrollTop=this._scrollTopMemo||0},_setItemsAttr:function(a){this.setItems(a)},setItems:function(a,c){this.keepScrollPosition&&this._memoScroll();this.clear();this.items=a;c||(this.items&&this._isCreated?(this._addItems(a),this._checkIfStillSelected(),
this.keepScrollPosition&&this._applyScrollFromMemo()):this._checkIfStillSelected())},_checkIfStillSelected:function(){if(-1!=this.selectedIndex||this.selectedItem){var a=this;this._addedWrappers&&this._addedWrappers.some(function(c,b){return a.__isSelectedFunction(c,b)})||(this.selectedIndex=-1,this.selectedItem=null)}},refresh:function(){this.store?this.setStore(this.store):this.setItems(this.items)},setSelectedItem:function(a,c){this.selectedItem=a;this.selectedIndex=-1;this.refresh();c&&this._dispatchChangeEvent()},
setSelectedIndex:function(a,c){this.selectedIndex=a;this.selectedItem=null;this.refresh();c&&this._dispatchChangeEvent()},getItemNode:function(a){var c;this._addedWrappers&&this._addedWrappers.some(function(b){if(b.itemRef===a)return c=b.__itemPresentation,!0});return c},getItemByNode:function(a){var c;this._addedWrappers&&this._addedWrappers.some(function(b){if(b.__itemPresentation===a)return c=b.itemRef,!0});return c},__selectedPresentation:null,_addItems:function(a){this._addedWrappers=this._addedWrappers||
[];var c=this;a.forEach(function(a){var b=k.mixin({},a);b.itemRef=a;c.__addWrapper(b)})},__addWrapper:function(a){var c=this._addedWrappers.length,b=this.itemRenderer.createPresentation(a.itemRef,this.__isSelectedFunction(a,c),this.listDiv,this,a);b&&(b.index=c,b.item=a.itemRef,a.__itemPresentation=b,this.__isSelectedFunction(a,c)&&(this.selectedItem=a.itemRef,this.selectedIndex=c,this.__selectedPresentation=b),this._addClickHandler(b),this._addedWrappers.push(a),a=this._addedWrappers.length-1,e.add(b,
"listItem_"+a),e.add(b,"listItem_"+(0==a%2?"even":"odd")))},__isSelectedFunction:function(a,c){return this.hasSelectableItems?c==this.selectedIndex||a.itemRef===this.selectedItem?!0:a.itemRef&&this.selectedItem?(a=a.itemRef[this.idProperty],c=this.selectedItem[this.idProperty],void 0!==a&&a===c):!1:!1},_selectionValidatorDefault:function(a){return!!a&&!a.isSeparator&&!1!==a.enabled},_addClickHandler:function(a){function c(){if(b.allowRepetitiveSelection||b.__selectedPresentation!=a)if(b.selectionValidator?
!1!==b.selectionValidator(a.item):b._selectionValidatorDefault(a.item))b.__selectedPresentation&&b.itemRenderer.selectPresentation&&b.itemRenderer.selectPresentation(b.__selectedPresentation,!1),b.itemRenderer.selectPresentation&&b.itemRenderer.selectPresentation(a,b.hasSelectableItems),b.__selectedPresentation=a,b.selectedIndex=a.index,b.selectedItem=a.item,b._dispatchChangeEvent()}var b=this;if(this.allowManualSelection){var d;d=this.selectOnMouseDown||!this.noDragTolerance?f(a,this.selectOnMouseDown?
g.press:g.click,function(a){b.stopMouseEventPropagation&&a.stopPropagation();c()}):m.addNoDragClickHandler(a,c,{tolerance:this.noDragTolerance});this._clickHandles.push(d)}},_dispatchChangeEvent:function(){this.onChange({type:"change",selectedIndex:this.selectedIndex,selectedItem:this.selectedItem,value:this.selectedItem&&this.selectedItem[this.idProperty]})},clear:function(){this.__selectedPresentation=null;this._addedWrappers=this._addedWrappers||[],this._addedWrappers.forEach(function(a){a.destroyPresentation&&
a.destroyPresentation()});this._addedWrappers.length=0;this.listDiv&&l.empty(this.listDiv);this._clearHandlers()},_clearHandlers:function(){this._clickHandles=this._clickHandles||[];this._clickHandles.forEach(function(a){a.remove()});this._clickHandles.length=0},scrollToItem:function(a){if(a=this.getItemNode(a))this.listDiv.scrollTop=a.offsetTop},store:null,onDemandModeLoadStep:1E3,onDemandPopulateLimit:1E3,onDemandPopulatePeriod:200,_setStoreAttr:function(a){this.setStore(a)},setStore:function(a){this.keepScrollPosition&&
this._memoScroll();this.clear();this.idProperty=(this.store=a)&&a.idProperty;if(this.store&&this._isCreated){this._loadNextPart();this._checkIfStillSelected();this.keepScrollPosition&&this._applyScrollFromMemo();var c=this;this.own(f(this.listDiv,"scroll",function(){var a=c._addedWrappers[c._addedWrappers.length-30];(a=a?a.__itemPresentation:null)&&a.offsetTop<c.listDiv.scrollTop&&c._loadNextPart()}))}else this._checkIfStillSelected()},_loadNextPart:function(){if(this.store&&this.store.query().length!=
this._addedWrappers.length){var a=this.store.query(null,{start:this._addedWrappers.length,count:this.onDemandModeLoadStep});delete a.total;this._addItems(a);a.length&&this._addedWrappers.length<this.onDemandPopulateLimit&&(a=this._loadNextPart.bind(this),setTimeout(a,this.onDemandPopulatePeriod))}},onChange:function(a){},destroy:function(){this.clear();this.inherited(arguments)}});d.itemRenderers={DefaultItemRenderer:h};return d});