// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/Geoenrichment","../../declare dojo/_base/lang dojo/on dojo/string dojo/promise/all ./bufferTitle ./DataProvider ../../tasks/geoenrichment/GeoenrichmentTask ../../tasks/geoenrichment/EnrichParameters ../../tasks/geoenrichment/RingBuffer ../../tasks/geoenrichment/DriveBuffer ../../tasks/geoenrichment/GeographyLevel ../../tasks/geoenrichment/GeometryStudyArea ../../tasks/geoenrichment/AddressStudyArea ../../tasks/geoenrichment/studyAreaFromJson ./config ./lang ./_Invoke dojo/when ../../tasks/locator ../../tasks/FeatureSet ../../graphic ../../geometry/jsonUtils".split(" "),
function(e,h,d,x,y,z,A,B,C,r,D,t,E,F,u,l,v,G,H,I,w,J,K){function L(a){a=a.toJson();delete a.returnGeometry;delete a.comparisonLevels;delete a.attributes;return a=JSON.stringify(a)}var k=e(null,{_keys:null,_values:null,_capacity:5,constructor:function(a){this._keys=[];this._values={};a&&(this._capacity=a)},getValue:function(a){return this._values[a]},setValue:function(a,c){this._keys.push(a);this._values[a]=c;this._removeOverflow()},hasValue:function(a){return this._values.hasOwnProperty(a)},_removeOverflow:function(){if(this._keys.length>
this._capacity)for(var a=this._keys.splice(0,this._keys.length-this._capacity),c=0;c<a.length;c++)delete this._values[a[c]]},setCapacity:function(a){this._capacity=a;this._removeOverflow()},toJson:function(){var a={},c;for(c in this._values){var b=this._values[c];void 0===b||null===b||"number"==typeof b&&isNaN(b)||("string"==typeof b||"boolean"==typeof b||"number"==typeof b?a[c]=b:"object"==typeof b&&b.toJson&&(a[c]=b.toJson()))}return{keys:this._keys.slice(),values:a,capacity:this._capacity}},fromJson:function(a,
c){if(a){this._keys=a.keys;this._capacity=a.capacity;this._values={};for(var b in a.values)this._values[b]=c?c(a.values[b]):a.values[b]}}}),p=e(null,{_values:null,constructor:function(a){this._values=new k(a)},getValue:function(a){var c=this.keyToString(a);if(this._values.hasValue(c))return this._values.getValue(c);var b=this;return this.keyToValue(a).then(function(a){b._values.setValue(c,a);return a})},keyToString:function(a){return JSON.stringify(a)},keyToValue:function(a){throw"Not implemented";
},setCapacity:function(a){this._values.setCapacity(a)},toJson:function(){return this._values.toJson()},fromJson:function(a,c){a&&this._values.fromJson(a,c)}}),M=e([p],{keyToString:function(a){return JSON.stringify(a.toJson())},keyToValue:function(a){return(new I(l.locatorUrl)).locationToAddress(a).then(function(a){return x.substitute(l.addressFormat,a.address,function(a){return a||""})},function(a){return""})}}),N=e([p],{_countryValues:null,_geometries:null,constructor:function(){this._countryValues=
new k;this._geometries=new k(3)},keyToValue:function(a){var c=this,b=u(a.studyArea),e=b.returnGeometry,q,m;e&&(m=L(b),q=this._geometries.hasValue(m));var h=e&&!q,g=new B(l.server);g.token=l.token;for(var d=null,f=b.comparisonGeographyLevels.length-1;0<=f;f--)"Admin1"==b.comparisonGeographyLevels[f].layerID&&(d=b.comparisonGeographyLevels.splice(f,1)[0]);var n,k;d&&(n=JSON.stringify({variables:a.variables,country:a.country}),(k=this._countryValues.hasValue(n))||b.comparisonGeographyLevels.push(d));
f=new C;f.forStorage=!1;f.countryID=a.country;f.variables=a.variables;if(b.returnGeometry=h)f.outSR=b.geometry?b.geometry.spatialReference:a.outSR;f.studyAreas.push(b);return g.enrich(f).then(function(a){var b=a.featureSets[0].features;d&&(k?b.push(c._countryValues.getValue(n)):c._countryValues.setValue(n,b[b.length-1]));e&&(q?b[0].geometry=c._geometries.getValue(m):c._geometries.setValue(m,b[0].geometry));return a.featureSets[0]})},setCapacity:function(a){this.inherited(arguments);this._countryValues.setCapacity(a)},
toJson:function(){var a=this.inherited(arguments);a.countryValues=this._countryValues.toJson();a.geometries=this._geometries.toJson();return a},fromJson:function(a){a&&(this._countryValues.fromJson(a.countryValues,function(a){return new J(a)}),this._geometries.fromJson(a.geometries,function(a){return K.fromJson(a)}),this.inherited(arguments,[a,function(a){return new w(a)}]))}}),O=e([p],{metadata:null,_enrichCache:null,_addressCache:null,constructor:function(a){this._enrichCache=new N(a);this._addressCache=
new M(3)},keyToValue:function(a){var c=this,b=[],e=a.returnAddress;delete a.returnAddress;b.push(this._enrichCache.getValue(a));var d=u(a.studyArea);e&&b.push(this._addressCache.getValue(d.geometry));return y(b).then(function(a){var b=a[0],g=b.features[0];g.attributes[c.metadata.name]||(g.attributes[c.metadata.name]=z(d.getGeomType(),d.options),e?g.attributes[c.metadata.address]=a[1]:d instanceof F&&(g.attributes[c.metadata.address]=d.address.text));return b})},setCapacity:function(a){this.inherited(arguments);
this._enrichCache.setCapacity(a)},toJson:function(){var a=this.inherited(arguments);a.metadata=h.clone(this.metadata);a.enrichCache=this._enrichCache.toJson();a.addressCache=this._addressCache.toJson();return a},fromJson:function(a){a&&(this.metadata=a.metadata,this._enrichCache.fromJson(a.enrichCache),this._addressCache.fromJson(a.addressCache),this.inherited(arguments,[a,function(a){return new w(a)}]))}});return e("esri.dijit.geoenrichment.Geoenrichment",[A,G],{country:null,returnGeometry:!1,returnAddress:!1,
returnData:!0,studyArea:null,outSR:null,buffer:null,variables:null,levels:null,highestLevel:null,data:null,restartOnDone:!1,requests:null,started:!1,cache:null,constructor:function(){this.buffer=new r;this.cache=new O;this.cache.metadata=this.metadata},handleResponse:function(a){try{this.data=a,this.data.features[0].attributes.isThisArea=!0,this.onDone(null)}catch(c){this.onDone(c)}},handleError:function(a){this.onDone(a)},onDone:function(a){this.requests=null;a?"CancelError"!==a.name&&(console.log(a),
d.emit(this,"error",a)):d.emit(this,"data");this.restartOnDone?(this.invalidate(),this.restartOnDone=!1):(d.emit(this,"end"),this.started=!1)},requestData:function(){if(this.studyArea&&this.variables&&this.buffer){this.requests=[];this.started||(d.emit(this,"start"),this.started=!0);var a,c=this.buffer;a=!1;if(this.studyArea instanceof E)switch(this.studyArea.geometry.type){case "point":a=this.returnAddress;break;case "polyline":this.buffer instanceof D&&(c=new r);break;case "polygon":c=null}var b=
h.clone(this.studyArea);!b.options&&c&&(b.options=c);if(this.levels)for(c=0;c<this.levels.length;c++)b.comparisonGeographyLevels.push(new t({layerID:this.levels[c]}));this.highestLevel&&b.comparisonGeographyLevels.push(new t({layerID:this.highestLevel}));b.returnGeometry=this.returnGeometry;a=H(this.cache.getValue({country:this.country,variables:this.variables,returnData:this.returnData,studyArea:b.toJson(),outSR:this.outSR,returnAddress:a}));this.requests.push(a);a.then(h.hitch(this,this.handleResponse),
h.hitch(this,this.handleError))}},invalidate:function(){this.pendingInvoke("requestData")||(this.requests?this.restartOnDone=!0:(this.geometry=null,this.invoke("requestData")))},setStudyArea:function(a){this.studyArea=a;this.invalidate()},setBuffer:function(a){this.buffer=a;this.invalidate()},getBuffer:function(){return this.buffer},invalidateData:function(){this.data=null;this.invalidate()},setVariables:function(a){v.arraysEqual(this.variables,a)||(this.variables=a,this.invalidateData())},setGeoLevels:function(a,
c){v.arraysEqual(this.levels,a)&&this.highestLevel==c||(this.levels=a,this.highestLevel=c,this.invalidateData())},setCacheLimit:function(a){this.cache.setCapacity(a)},getData:function(){return this.data},getGeometry:function(){return this.data.features[0].geometry},isBusy:function(){return this.pendingInvoke("requestData")||this.requests||this.restartOnDone},stop:function(){this.restartOnDone=!1;this.cancelInvoke("requestData");if(this.requests)for(var a=this.requests.slice(0),c=0;c<a.length;c++)a[c].cancel()},
setReturnAddress:function(a){this.returnAddress!=a&&(this.returnAddress=a)&&this.invalidateData()}})});