// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/SelectableLegend","dojo/_base/declare dojo/_base/lang dojo/dom-class dojo/dom-construct dojo/dom-style dojo/on dijit/_WidgetBase dijit/_TemplatedMixin ./TriStateItem ./FlowList".split(" "),function(h,m,g,e,k,n,p,q,r,t){var u=h(null,{createPresentation:function(a,c,b,f,h){var l=this,d=e.create("div",{"class":"selectableLegendRoot"},b);c=this.canSelect()&&new r(d,{"class":"dijitInline selectableLegendRootCheckbox"});b=e.create("div",{"class":"dijitInline selectableLegendRootColorRect"});
a.fill&&(b.style.backgroundColor=a.fill);a.stroke&&(b.style.border="1px solid "+a.stroke,g.add(b,"selectableLegendRootColorRectWithBorder"));f=e.create("div",{innerHTML:a.label,"class":"dijitInline selectableLegendRootLabel TrimWithEllipses"});this.isRtlPlacement()?(e.place(f,d),e.place(b,d)):(e.place(b,d),e.place(f,d));c&&(c.set("checked",!a.unchecked),g[a.unchecked?"add":"remove"](d,"selectableLegendRoot_unselected"),c.onClick=function(b){g[b.checked?"remove":"add"](d,"selectableLegendRoot_unselected");
l.onSelectionChanged(a.label,b.checked)});this.getItemMaxWidth()&&k.set(d,"width",this.getItemMaxWidth()+"px");this.setItemWidth(k.get(d,"width"));this.canEditLabels()&&(g.add(f,"isEditable"),n(f,"click",function(b){b.stopPropagation();l.onLabelClicked(a,d)}));return d},onSelectionChanged:function(a,c){},onLabelClicked:function(a,c){},canSelect:function(){},canEditLabels:function(){},isRtlPlacement:function(){},getItemMaxWidth:function(){},setItemWidth:function(a){}});return h([p,q],{templateString:"\x3cdiv class\x3d'esriGESelectableLegend'\x3e\x3cdiv data-dojo-attach-point\x3d'listDiv'\x3e\x3c/div\x3e\x3c/div\x3e",
series:null,allowSelect:!0,allowEditLabels:!1,showSeriesData:!1,isRtlPlacement:!1,keepItemsTheSameWidth:!1,_isCollectingWidthsFlag:!1,list:null,_uncheckedSeriesHash:null,_itemMaxWidth:0,postCreate:function(){var a=this;this._uncheckedSeriesHash={};var c=m.mixin(new u,{onSelectionChanged:function(b,c){c?delete a._uncheckedSeriesHash[b]:a._uncheckedSeriesHash[b]=!0;a.onSeriesExclusionChanged(a._uncheckedSeriesHash)},onLabelClicked:function(b,c){if(a.showSeriesData)a.onPointLabelClickedAt(void 0!==b.unsortedIndex?
b.unsortedIndex:a.list.items.indexOf(b),c);else a.onSeriesLabelClickedAt(a.list.items.indexOf(b),c)},canSelect:function(){return a.allowSelect},canEditLabels:function(){return a.allowEditLabels},isRtlPlacement:function(){return a.isRtlPlacement},getItemMaxWidth:function(){return a._isCollectingWidthsFlag?0:a._itemMaxWidth},setItemWidth:function(b){a._itemMaxWidth=Math.max(a._itemMaxWidth||0,b||0)}});this.list=new t({"class":"selectableLegendFlowList",itemRenderer:c},this.listDiv);this.own(this.list)},
onSeriesLabelClickedAt:function(a,c){},onPointLabelClickedAt:function(a,c){},onSeriesExclusionChanged:function(a){},resetExclusion:function(){this._uncheckedSeriesHash={}},refresh:function(){var a=[],c=this;this.showSeriesData?this.series&&this.series[0]&&this.series[0].data.forEach(function(b){a.push({label:b.name||"",fill:b.fill,stroke:b.stroke&&b.stroke.color,unsortedIndex:b.unsortedIndex})}):this.series&&this.series.forEach(function(b){a.push({label:b.name,fill:b.data[0].fill,stroke:b.data[0].stroke&&
b.data[0].stroke.color,unchecked:!0===c._uncheckedSeriesHash[b.name]})});this._itemMaxWidth=0;this._isCollectingWidthsFlag=!0;this.list.setItems(a);this._isCollectingWidthsFlag=!1;this.keepItemsTheSameWidth&&this.list.refresh()}})});