// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/grid/coreUtils/sorting/GridSortUtil","dojo/dom-class dojo/dom-construct ./GridRowStyler ../GridDataUtil ../GridQueryUtil esri/dijit/geoenrichment/utils/DnDUtil esri/dijit/geoenrichment/utils/ObjectUtil esri/dijit/geoenrichment/utils/TooltipUtil dojo/i18n!esri/nls/jsapi".split(" "),function(f,r,l,t,n,p,q,m,k){k=k.geoenrichment.dijit.ReportPlayer.Grid;var c={},u=/^(\d+|\d+[.,]\d+)%$/;c.isGridSortable=function(a){return!a.allowSorting||a.isEmptyTable()||
3>a.store.data.length||!a.viewModel.dynamicReportInfo?!1:!0};c.updateSorting=function(a,d){if(c.isGridSortable(a)){var b=c._collectHeaderRowInfo(a);b&&c._makeSortable(a,b);!d&&b&&c._applySortInfo(a,b)}};c._collectHeaderRowInfo=function(a){for(var d=a.store.data.length-2,b,e,c=0;c<d;c++){var g=n.queryCells(a,{rowIndex:c});if(g&&g.length===a.columns.length){b=g;e=c;break}}if(b)for(c=e+1;c<a.store.data.length;c++){if(g=n.queryCells(a,{rowIndex:c}),!g||g.length!==a.columns.length)return null}else return null;
return{cells:b,headerRowIndex:e}};c._makeSortable=function(a,d){d.cells.forEach(function(b){var e=r.create("div",{"class":"sortArrow sortArrowHoverIndicator"},b.domNode),h=b.getFullStyle();e.style[h&&"left"===h.horizontalAlign?"right":"left"]="5px";b._sortArrow=e;f.add(b.domNode,"esriGEClickable");p.addNoDragClickHandler(b.contentBlock,function(e){a&&a.canSortCellFunc&&!a.canSortCellFunc(b)||c._checkCanSortOnHeaderClick(e)&&c._toggleSortForCell(b,d)});p.addNoDragClickHandler(e,function(a){c._toggleSortForCell(b,
d)})});c._updateArrows(a,d)};c._toggleSortForCell=function(a,d){var b=a.parentGrid,e=b._sortInfo&&b._sortInfo.field===a.column.field?b._sortInfo.order:null;b._sortInfo={field:a.column.field,order:null,originalData:b._sortInfo?b._sortInfo.originalData:b.store.data.slice()};e?"desc"===e?b._sortInfo.order="asc":"asc"===e&&(b._sortInfo.order=null):b._sortInfo.order="desc";c._applySortInfo(b,d);b.onSortingChanged(c.getSorting(b))};c._checkCanSortOnHeaderClick=function(a){if(a&&a.path){if(a.path.some(function(a){return"A"===
a.nodeName}))return!1}else if(a&&a.srcElement&&a.srcElement.parentNode&&"A"===a.srcElement.parentNode.nodeName)return!1;return!0};c._applySortInfo=function(a,d,b){c._updateArrows(a,d);if(a._sortInfo){if(a._sortInfo.order){for(var e=[],h=a._sortInfo.originalData.slice(),g=0;g<d.headerRowIndex+1;g++)e.push(h.shift());d=l.getStyleInfo(h,a.columns);var f=a._sortInfo.field;h.sort(function(b,c){function e(a){var b=t.getNumericDataValue(a,f);if(void 0!==b)return b;a=a[f];return"string"===typeof a?(b=u.test(a)?
q.parseNumber(a.replace("%","")):q.parseNumber(a),isNaN(b)?a:b):a}b=e(b);var d=e(c);c="desc"===a._sortInfo.order;"number"===typeof b||"number"===typeof d?(b=Number(b),d=Number(d),b=b>d?1:b<d?-1:0):(b=String(b),d=String(d),b=b.localeCompare(d));return c?-b:b});d&&l.setAlternatingColors(h,a.columns,d);a.store.data=e.concat(h)}else a.store.data=a._sortInfo.originalData,l.resetStyling(a._sortInfo.originalData,a.columns);b||a.refresh({skipSorting:!0})}};c._updateArrows=function(a,c){c.cells.forEach(function(b){var c=
b._sortArrow;f.remove(c,"sortArrowHoverIndicator sortArrowUp sortArrowDown");m.setTooltipToNode(c,null);a._sortInfo&&a._sortInfo.field===b.column.field?"asc"===a._sortInfo.order?f.add(c,"sortArrowUp"):"desc"===a._sortInfo.order?f.add(c,"sortArrowDown"):(m.setTooltipToNode(c,k.sortTable),f.add(c,"sortArrowHoverIndicator")):(m.setTooltipToNode(c,k.sortTable),f.add(c,"sortArrowHoverIndicator"));setTimeout(function(){c.style.top=(b.getHeight()-c.clientHeight)/2+"px"},100)})};c.getSorting=function(a){return a._sortInfo&&
{field:a._sortInfo.field,order:a._sortInfo.order}};c.setSorting=function(a,d,b){if(c.isGridSortable(a)&&d){var e=c._collectHeaderRowInfo(a);e&&(a._sortInfo={field:d.field,order:d.order,originalData:a._sortInfo?a._sortInfo.originalData:a.store.data.slice()},c._applySortInfo(a,e,b&&b.doNotRefresh))}};c.getSortRowIndexMapping=function(a){if(!a._sortInfo||!a._sortInfo.order)return null;var c={};a.store.data.forEach(function(b,d){c[d]=a._sortInfo.originalData.indexOf(b)});return c};return c});