// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/reportContainerStack/_ZoomSupport","dojo/_base/declare dojo/Deferred dojo/when dojo/dom-construct ./utils/ReportQueryUtil ../reportContainerGrid/utils/ZoomUtil ../../supportClasses/ZoomUtil esri/dijit/geoenrichment/utils/animation/AnimationUtil".split(" "),function(g,h,k,d,l,c,e,m){var f={zoomLabel:null,_showTimeoutH:null,_dfd:null,_createLabel:function(){this.zoomLabel=d.create("div",null,document.body);var a=this.zoomLabel.style;a.position="absolute";
a.zIndex="10000";a.right="5px";a.bottom="5px";a.backgroundColor="gray";a.color="white";a.padding="5px"},showLabel:function(a,b){var c=this;this._reset();this._createLabel();this._showScale(a);this._dfd=new h;this._dfd.promise.then(function(b){"cancel"!==b&&(c._showScale(a),c._showTimeoutH=setTimeout(function(){m.animateFadeOut({domNode:c.zoomLabel})},1E3))});k(b,this._dfd.resolve)},_showScale:function(a){this.zoomLabel&&(this.zoomLabel.innerHTML=Math.round(e.getClosestZoomAndUpdateOptions(100*a.getZoomInfo().scale,
e.getOptions()))+"%")},_reset:function(){this._dfd&&this._dfd.resolve("cancel");this._dfd=null;clearTimeout(this._showTimeoutH);this.zoomLabel&&d.destroy(this.zoomLabel);this.zoomLabel=null}};return g(null,{getZoomInfo:function(){return c.getZoomInfo(this)},setZoomInfo:function(a,b){c.setZoomInfo(this,a,b)},zoomIn:function(a){var b=c.zoomIn(this,a);a&&a.showLabel&&f.showLabel(this,b)},zoomOut:function(a){var b=c.zoomOut(this,a);a&&a.showLabel&&f.showLabel(this,b)},zoomToFitPageWidth:function(a){c.zoomToFitPageWidth(this,
a)},zoomToFitPageHeight:function(a){c.zoomToFitPageHeight(this,a)},setZoomPercent:function(a,b){c.setZoomPercent(this,a,b)},setBestZoom:function(){c.setBestZoom(this)},resetZoom:function(){c.reset(this)},_syncFillerContainer:function(){if(this.domNode){var a=this.getZoomInfo().scale;this.fillerContainer.style.marginTop="";this.fillerContainer.style.marginRight="";this.fillerContainer.style.marginBottom="";this.fillerContainer.style.marginLeft="";this.fillerContainer.style.width=this.scalableContainer.clientWidth*
a+"px";this.fillerContainer.style.height=this.scalableContainer.clientHeight*a+"px";this.renderOptions&&this.renderOptions.center&&(this.fillerContainer.style.marginTop=Math.max(this.renderOptions.minTop,(this.domNode.clientHeight-this.fillerContainer.clientHeight)/2)+"px");this.renderOptions&&(this.fillerContainer.style.marginRight=this.renderOptions.minRight+"px",this.fillerContainer.style.marginBottom=this.renderOptions.minBottom+"px",this.fillerContainer.style.marginLeft=this.renderOptions.minLeft+
"px");this.onViewSyncronized()}},getPanelZoomScale:function(a){return l.getPanelInfoByNode(this,a).panelScale*this.getZoomInfo().scale},onViewSyncronized:function(){},emitZoomChangedEvent:function(){this.infographicPage.getSections().forEach(function(a){this._notifySectionAboutScale(a)},this);this.onZoomChanged()},_notifySectionAboutScale:function(a){var b=this.infographicPage.getSections().indexOf(a),b=this.infographicPage.getPanelScaleAt(b)*this.getZoomInfo().scale;a.notifyPanelScaleChanged(b)},
onZoomChanged:function(){}})});