// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/grid/coreUtils/gridLayoutCalcUtils/rows/RowsProcessor",["dojox/uuid/generateRandomUuid","./RowDataUtil","../GridLayoutCalculatorQueryUtil"],function(n,h,m){function p(b,f){var c=[],k,g=0;f&&Object.keys(f).forEach(function(a){m.fieldToColumn(b,a)?g++:delete f});g&&b.columns.some(function(a){if(k||f[a.field])c.push(a),k=!0;f[a.field]&&g--;if(!g)return!0});return c}function q(b,f){var c=[],k,g=0;f&&Object.keys(f).forEach(function(a){m.dataIdToData(b,
a)?g++:delete f});g&&b.store.data.some(function(a){if(k||f[a.id])c.push(a),k=!0;f[a.id]&&g--;if(!g)return!0});return c}return{recalcRows:function(b){var f={};b.columns.forEach(function(a,b){f[a.field]=b});var c;b.store.data.forEach(function(a,d){a.index=d;a.style=a.style||{};a.style.fields=a.style.fields||{};void 0===a.id&&(a.id=n());void 0===a.style.height&&(a.style.height=b.layoutDefaults.defaultRowHeight);delete a.excludedIndexHorizontal;delete a.movableFieldsHashHorizontal;if(a.columnSpans){a.excludedIndexHorizontal=
{};a.movableFieldsHashHorizontal={};a._columnSpans=a._columnSpans||{};for(c in a.columnSpans){d=a._columnSpans[c];var e={};d=d?p(b,d):m.getSpannedColumns(b,c,a.columnSpans[c]);1<d.length&&(d.forEach(function(b){e[b.field]=!0;b.field!==c&&(a.excludedIndexHorizontal[f[b.field]]=!0)}),a.movableFieldsHashHorizontal[c]=d[d.length-1].field);a.columnSpans[c]=d.length;a._columnSpans[c]=e}var l=0;Object.keys(a.columnSpans).forEach(function(b){2>a.columnSpans[b]?(delete a.columnSpans[b],delete a._columnSpans[b]):
l++});l||(delete a.columnSpans,delete a._columnSpans)}delete a.excludedIndexVertical;delete a.movableIndexHashVertical;a.fieldInfos=a.fieldInfos||{}});b.store.data.forEach(function(a,d){if(a.rowSpans)for(c in a._rowSpans=a._rowSpans||{},a.rowSpans){var e=a._rowSpans[c],l={};l[a.id]=!0;var g=f[c],k=a.rowSpans[c];if(e)e=q(b,e);else for(var e=[],h=d;h<d+k;h++)e.push(b.store.data[h]);1<e.length&&(e.forEach(function(b){if(b.id!==a.id){b.excludedIndexVertical=b.excludedIndexVertical||{};b.excludedIndexVertical[g]=
!0;var e=a.columnSpans&&a.columnSpans[c];if(e)for(var d=1;d<e;d++)b.excludedIndexVertical[g+d]=!0}l[b.id]=!0}),a.movableIndexHashVertical=a.movableIndexHashVertical||{},a.movableIndexHashVertical[c]=d+e.length-1);a.rowSpans[c]=e.length;a._rowSpans[c]=l}});b.store.data.forEach(function(a,d){if(a.rowSpans){for(c in a.rowSpans)a.rowSpans[c]=Math.min(a.rowSpans[c],b.store.data.length-d);var e=0;Object.keys(a.rowSpans).forEach(function(b){2>a.rowSpans[b]?(delete a.rowSpans[b],a._rowSpans&&delete a._rowSpans[b]):
e++});e||(delete a.rowSpans,delete a._rowSpans)}});b.store.data.forEach(function(a,b){a.fieldInfos&&Object.keys(a.fieldInfos).forEach(function(b){void 0===f[b]&&delete a.fieldInfos[b]});a.style&&a.style.fields&&Object.keys(a.style.fields).forEach(function(b){void 0===f[b]&&delete a.style.fields[b]})});if(b.looseResize){b.store.data.forEach(function(a){b.columns.some(function(d){h.getDataHeightOwn(b,a,d.field)||h.setDataHeight(b,a,d.field,a.style.height)})});var k=b.store.data[b.store.data.length-
1],g=h.recalcGridHeight(b);b.columns.some(function(a){var d=0;b.store.data.forEach(function(c){d+=h.getDataHeightOwn(b,c,a.field)});var c=g-d;0!==c&&h.setDataHeight(b,k,a.field,h.getDataHeightOwn(b,k,a.field)+c)})}h.recalcGridHeight(b)}}});