// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
require({cache:{"url:esri/dijit/geoenrichment/ReportPlayer/core/templates/Section.html":'\x3cdiv class\x3d"esriGEReportPlayer_section"\x3e\r\n    \x3cdiv data-dojo-attach-point\x3d"stackNode" class\x3d"section_stackNode"\x3e\x3c/div\x3e\r\n\x3c/div\x3e'}});
define("esri/dijit/geoenrichment/ReportPlayer/core/sections/Section","dojo/_base/declare dojo/_base/lang dojo/dom-construct dojo/dom-class dojo/dom-style dojo/store/Memory dijit/_WidgetBase dijit/_TemplatedMixin ./_SectionQueryElementsMixin ../supportClasses/tableJson/TableJsonUtil ../supportClasses/ViewModes ../supportClasses/templateJsonUtils/fieldInfo/FieldInfoBuilder ./supportClasses/SectionLayoutManager ./sectionUtils/SectionJsonUtil ./dynamicSettings/SectionDynamicSettingsBuilder esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/MouseUtil esri/dijit/geoenrichment/ReportPlayer/core/sections/SectionTypes dojo/text!../templates/Section.html dojo/i18n!esri/nls/jsapi".split(" "),function(p,
k,h,l,f,q,r,t,u,v,n,m,w,x,y,z,A,g,B,e){e=e.geoenrichment.dijit.ReportPlayer.Sections;return p([r,t,u],{templateString:B,nls:e,isSection:!0,json:null,viewModel:null,theme:null,currentFeatureIndex:null,initialWidth:null,hasFixedLayout:!0,disableContentCrop:!1,parentWidget:null,parentElementInPageInfo:null,viewPortContainer:null,parentGridCell:null,isPagePanelSection:!1,isInfographicHeaderSection:!1,isInfographicSection:!1,infographicViewController:null,calculationStatesGroup:null,noContentOffset:!1,
tableClass:null,tableParams:null,initialViewMode:null,initialSpecificViewMode:null,isDataDrillingView:!1,dynamicSettingsToolbarRoot:null,_stackElements:null,_layoutManager:null,_dynamicSettingsBuilder:null,_backgroundColor:void 0,_cropContent:!1,_canMoveElementsOutside:!1,_opacity:1,_topSpacer:null,_bottomSpacer:null,postCreate:function(){this.inherited(arguments);this._showError(!1);this._layoutManager=new w(this);this._stackElements=[];this.infographicViewController&&this.infographicViewController.addSection(this);
(this.initialViewMode||this.initialSpecificViewMode)&&this._tryApplyNewViewMode(this.initialViewMode,this.initialSpecificViewMode);this.initialWidth&&this.setWidth(this.initialWidth);this.fromJson(this.json);this.json=null},_createStack:function(a){this._destroyStack();if(a){this._topSpacer=h.create("div",{"class":"stackNodeSpacer"},this.stackNode);var b=this;a.stack.forEach(function(a,d){switch(a.id){case "table":b._createGrid(a);break;case "img":b._createImage(a);break;case "hr":b._createHorizontalLine(a,
d);break;case "pageBreak":b._createPageBreak(a)}});this._bottomSpacer=h.create("div",{"class":"stackNodeSpacer"},this.stackNode);this._updateSpacersForHorizontalLines()}},_addEmptyLine:function(){h.create("div",{"class":"stackNodeEmptyLine"},this.stackNode)},_getGridCreateParams:function(a,b){return null},_createGrid:function(a,b,c,d){var e=this;a.style=a.style||{};a.attributes=a.attributes||{};a.data.columns=a.data.columns||[];a.data.data=a.data.data||[];var f=b&&(b.domNode||b);c=f?c||"after":void 0;
var f=f||this.stackNode,g="function"===typeof this.tableClass?this.tableClass(a):this.tableClass;d=this.viewModel.layoutBuilder.createElement("grid",k.mixin({"class":g||"",fieldCellClass:g?g+"Cell":"",viewModel:this.viewModel,theme:this.theme,columns:a.data.columns,store:new q({data:a.data.data,idProperty:"id"}),parentWidget:this,viewPortContainer:this.viewPortContainer,fixedViewMode:a.attributes.viewMode,currentFeatureIndex:this.currentFeatureIndex,isDataDrillingView:this.isDataDrillingView,getPreviewValueFunction:this.infographicViewController&&
function(){return e.infographicViewController.getValueInfo(e)},enableNumberAnimation:this.isInfographicSection&&!!this.viewModel.dynamicReportInfo,allowSorting:!this.isInfographicSection&&!!this.viewModel.dynamicReportInfo&&!(this.tableParams&&!1===this.tableParams.allowSorting),onContentLoadingStart:function(){e.onContentLoadingStart()},onContentLoadingEnd:function(){e.onContentLoadingEnd()}},this._getGridCreateParams(a,d),this.tableParams),f);h.place(d.domNode,f,c);d.setMaxWidth(this.hasFixedLayout?
this.getWidth():1E5);d.setSettings(k.mixin({style:{width:a.style.width,left:a.style.left,spaceBefore:a.style.spaceBefore,spaceAfter:a.style.spaceAfter,alternatingStyle:a.style.alternatingStyle,opacity:a.style.opacity,fixedCellsOpacity:a.style.fixedCellsOpacity},attributes:k.mixin({fixedColumns:a.attributes.fixedColumns,dynamicColumns:a.attributes.dynamicColumns,fixedRows:a.attributes.fixedRows,dynamicRows:a.attributes.dynamicRows},this._getAdditionalTableAttributes(a)),scaleToFitWidth:a.scaleToFitWidth,
scaleToFitHeight:a.scaleToFitHeight,viewMode:this._viewMode,specificViewMode:this._specificViewMode},this._getAdditionalTableSettings(a)));d.stackId="table";b?this._stackElements.splice(this._stackElements.indexOf(b)+("after"===c?1:0),0,b):this._stackElements.push(d);return d},_getAdditionalTableAttributes:function(a){},_getAdditionalTableSettings:function(a){},_createImage:function(a){return a.isMapImage||!this.viewModel.isGraphicStyle?this._createFloatingImage(a):this._createElementInTable(a,"image")},
_createFloatingImage:function(a){var b=this,c;c=this._doCreateImageWithParams({viewModel:this.viewModel,theme:this.theme,parentWidget:this,currentFeatureIndex:this.currentFeatureIndex,onInitialized:function(){c&&c.resize()},onContentLoadingStart:function(){b.onContentLoadingStart()},onContentLoadingEnd:function(){b.onContentLoadingEnd()},onMapLoadError:function(){b._showError(!0)}},a);c.stackId="img";this._stackElements.push(c);this._syncElementViewMode(c);return c},_doCreateImageWithParams:function(a,
b){return this.viewModel.layoutBuilder.createElement("image",{node:this.stackNode,relativeParent:this.domNode,json:b,creationParams:a})},_createElementInTable:function(a,b,c){a.style=a.style||{};"chart"===b?c={x:0,y:0,w:a.visualProperties.width,h:a.visualProperties.height}:(a=k.mixin({},a),a.style=k.clone(a.style),c=c&&c.defaultSize||100,a.style.width=a.style.width||c,a.style.height=a.style.height||c,c={x:a.style.left||0,y:a.style.top||0,w:a.style.width,h:a.style.height},a.style.left=0,a.style.top=
0);var d;switch(b){case "image":d=m.createFieldInfoFromImage(a);break;case "shape":d=m.createFieldInfoFromShape(a);break;case "chart":d=m.createFieldInfoFromChart(a)}d=v.createSingleCellTable({left:c.x,spaceBefore:c.y,width:c.w,height:c.h,fieldInfo:d,cellStyle:{horizontalAlign:a.style.horizontalAlign||"center",verticalAlign:a.style.verticalAlign||"middle",backgroundColor:"transparent"}});0===a.style.opacity&&(d.style.opacity=0);a=this._createGrid(d);"image"===b&&(a.__isImageTable=!0);return a},isImageTable:function(a){return a&&
a.__isImageTable},_createHorizontalLine:function(a,b){a.style=a.style||{};var c=h.create("div",{"class":"templateHorizontalLine"},this.stackNode);0===b?(l.add(c,"templateHorizontalLineTop"),this._stackElements.unshift(c),c._isTopLine=!0):(l.add(c,"templateHorizontalLineBottom"),this._stackElements.push(c),c._isTopLine=!1);c.stackId="hr";a.style.backgroundColor&&f.set(c,"backgroundColor",a.style.backgroundColor);a.style.height&&f.set(c,"height",a.style.height+"px")},_updateSpacersForHorizontalLines:function(){var a=
this._queryElementsById("hr");f.set(this._topSpacer,"height","0px");f.set(this._bottomSpacer,"height","0px");var b=this;a.forEach(function(a){f.set(a._isTopLine?b._topSpacer:b._bottomSpacer,"height",f.get(a,"height")+"px")})},_createPageBreak:function(a){a=h.create("div",{"class":"esriGEReportPlayer_pageBreak"},this.stackNode);a.stackId="pageBreak";h.create("div",{"class":"pageBreakLine dijitInline"},a);h.create("div",{"class":"pageBreakLabel dijitInline",innerHTML:e.pageBreak},a);h.create("div",
{"class":"pageBreakLine dijitInline"},a);this._stackElements.push(a)},_destroyStack:function(){for(;this._stackElements.length;)this._removeElement(this._stackElements[0]);this.stackNode&&h.empty(this.stackNode);this._addEmptyLine()},removeElement:function(a){a&&this._removeElement(a)},_removeElement:function(a){a&&(a.destroy?a.destroy():h.destroy(a),this._stackElements.splice(this._stackElements.indexOf(a),1),"hr"===a.stackId&&this._updateSpacersForHorizontalLines())},getWidth:function(){return this._layoutManager.getWidth()},
setWidth:function(a,b){this._layoutManager.setWidth(a,b)},getHeight:function(a){return this._layoutManager.getHeight(a)},getResizedHeight:function(){return this._layoutManager.getResizedHeight()},setResizedHeight:function(a,b){this._layoutManager.setResizedHeight(a,b)},getPreferredHeight:function(){return this._layoutManager.getPreferredHeight()},collapseContent:function(){var a=this.getInfographicWithTable();a&&a.infographic.collapseContent()},calculateFloatingContentBox:function(){return this._layoutManager.getFloatingContentBox()},
scaleFloatingContentProportionally:function(a){this._layoutManager.scaleFloatingContentProportionally(a)},fitContentNicely:function(a,b){this._layoutManager.fitContentNicely(a,b)},setChartCalculationState:function(a){this.onCalculationStateChanged(a)},onCalculationStateChanged:function(a){},getStyle:function(){return{backgroundColor:this._backgroundColor,cropContent:this._cropContent,canMoveElementsOutside:this._canMoveElementsOutside,opacity:this._opacity}},setStyle:function(a){a=k.mixin(this.getStyle(),
a);this._backgroundColor=a.backgroundColor;this._cropContent=a.cropContent;this._canMoveElementsOutside=a.canMoveElementsOutside;this.domNode.style.backgroundColor=this._backgroundColor||"";this.domNode.style.overflow=this._cropContent&&!this.disableContentCrop?"hidden":"";"number"===typeof a.opacity&&(this._opacity=Math.max(0,Math.min(1,a.opacity)),this.domNode.style.opacity=1===this._opacity?"":this._opacity,l[0===this._opacity?"add":"remove"](this.domNode,"esriGENonInteractable"))},getSettings:function(){var a=
this._queryElementsById("hr"),b=a[0]&&a[0]._isTopLine?a[0]:null,a=a.filter(function(a){return!a._isTopLine})[0],c={type:this._sectionType,hasTopLine:!!b,hasBottomLine:!!a};b&&(c.topLineHeight=f.get(b,"height"),c.topLineColor=f.get(b,"backgroundColor"));a&&(c.bottomLineHeight=f.get(a,"height"),c.bottomLineColor=f.get(a,"backgroundColor"));return c},setSettings:function(a){var b=this;this._queryElementsById("hr").map(function(a){b._removeElement(a)});a.hasTopLine&&this._createHorizontalLine({style:{height:a.topLineHeight,
backgroundColor:a.topLineColor}},0);a.hasBottomLine&&this._createHorizontalLine({style:{height:a.bottomLineHeight,backgroundColor:a.bottomLineColor}})},_notifyContentChanged:function(){this._layoutManager.updateHeightAfterContentChange()},_viewMode:null,_specificViewMode:null,_viewModeKey:null,getViewMode:function(){return this._viewMode},setViewMode:function(a,b){this._tryApplyNewViewMode(a,b)&&this._stackElements.forEach(function(a){this._syncElementViewMode(a)},this)},_tryApplyNewViewMode:function(a,
b){a=a||this._viewMode;b=b||this._specificViewMode;var c=a+b;if(this._viewModeKey===c)return!1;this._viewModeKey=c;this._viewMode=a;this._specificViewMode=b;l[this._viewMode===n.EDIT?"add":"remove"](this.domNode,"esriGEReportPlayer_sectionEditMode");l[this._viewMode===n.EDIT?"remove":"add"](this.domNode,"esriGEReportPlayer_sectionPreviewMode");return!0},_syncElementViewMode:function(a){a.setViewMode&&a.setViewMode(this._viewMode,this._specificViewMode)},notifyShown:function(){this._stackElements.forEach(function(a){a.notifyShown&&
a.notifyShown()});this._panelScale&&this.notifyPanelScaleChanged(this._panelScale);this.viewModel.dynamicReportInfo&&(this._dynamicSettingsBuilder?this._dynamicSettingsBuilder.notifyShown():(this._dynamicSettingsBuilder=new y(this),this.own(this._dynamicSettingsBuilder),this._panelScale&&this._dynamicSettingsBuilder.setPanelScale(this._panelScale)))},_panelScale:null,getPanelScale:function(){return this._panelScale||1},notifyPanelScaleChanged:function(a){this._panelScale=a;this._dynamicSettingsBuilder&&
this._dynamicSettingsBuilder.setPanelScale(a);var b=this.getMapImages()[0];b&&b.notifyPanelScaleChanged(a);(b=this.getInfographic())&&b.notifyPanelScaleChanged&&b.notifyPanelScaleChanged(a)},_sectionType:null,getSectionType:function(){return this._sectionType},isEmpty:function(){return!1},isDataSection:function(){var a=this.getSectionType();return!this.hasPageBreak()&&this.hasNonEmptyTables()&&(a===g.DETAILS||a===g.DETAILS_HEADER||a===g.GROUP)},isPageHeader:function(){return this.getSectionType()===
g.PAGE_HEADER},isPageFooter:function(){return this.getSectionType()===g.PAGE_FOOTER},getSectionName:function(){if(this.hasPageBreak())return"";switch(this._sectionType){case g.PAGE_HEADER:return e.pageHeader;case g.DETAILS_HEADER:return this.hasLocatorHeaderTables()?e.locatorHeaderTable:e.detailsHeader;case g.DETAILS:return this.hasLocatorTables()?e.locatorTable:this.hasSummarizeTables()?e.summarizeTable:e.details;case g.GROUP:return e.group;case g.REPORT_FOOTER:return e.reportFooter;case g.PAGE_FOOTER:return e.pageFooter}return""},
getVisualState:function(){return{stackElements:this._stackElements.map(function(a){return a.getVisualState&&a.getVisualState()})}},setVisualState:function(a){a&&a.stackElements&&a.stackElements.length===this._stackElements.length&&(this._stackElements.forEach(function(b,c){b.setVisualState&&b.setVisualState(a.stackElements[c])}),this._dynamicSettingsBuilder&&this._dynamicSettingsBuilder.setVisualState(a))},refresh:function(){this.updateContentFromJson(this.toJson())},updateContentFromJson:function(a){this.fromJson(a);
this._notifyContentChanged()},fromJson:function(a){this._showError(!1);this._sectionType=a.type;"number"===typeof a.currentFeatureIndex&&(this.currentFeatureIndex=a.currentFeatureIndex);this.setStyle(a.style);this._createStack(a)},toJson:function(){var a=this,b={type:this._sectionType,style:this.getStyle(),stack:[]};this._stackElements.forEach(function(c){var d;switch(c.stackId){case "table":a.isImageTable(c)?(c=c.toJson(),(d=x.getTableJsonFirstFieldInfo(c).imageJson)?(d.style.left=c.style.left,d.style.top=
c.style.spaceBefore,d.style.opacity*=c.style.opacity):d=c):d=c.toJson();break;case "img":d=c.toJson();break;case "hr":d={id:"hr",style:{height:f.get(c,"height"),backgroundColor:f.get(c,"backgroundColor")}};break;case "pageBreak":d={id:"pageBreak"}}d&&b.stack.push(d)});return b},isMouseOver:function(){return A.isMouseOver(this.domNode)||this._dynamicSettingsBuilder&&this._dynamicSettingsBuilder.isMouseOver()||this._checkTableCellsMouseOver()},_checkTableCellsMouseOver:function(){return this.getTables().some(function(a){return a.getFieldCells().some(function(a){return a.content&&
a.content.isMouseOver&&a.content.isMouseOver()})})},_showError:function(a){this.errorDiv&&h.destroy(this.errorDiv);this.errorDiv=null;z[a?"hide":"show"](this.stackNode);a&&(this.errorDiv=h.create("div",{"class":"esriGEAbsoluteStretched section_errorDiv",innerHTML:e.mapLoadError},this.domNode))},onContentLoadingStart:function(){},onContentLoadingEnd:function(){},destroy:function(){this._destroyStack();this.inherited(arguments)}})});