// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/ChartJsonUtil","dojo/_base/lang ./ThemeCalculator ./ChartTypes ./ChartDataLabelsTypes ../legends/ChartLegendPlacements ../legends/ChartLegendTypes ./_ChartJsonCleaner ./_ChartJsonClassicReportSupports esri/dijit/geoenrichment/utils/ObjectUtil ./plots/supportClasses/GaugeLabelPlacement ../../../dataProvider/supportClasses/AreaDataUtil dojo/i18n!esri/nls/jsapi".split(" "),function(c,d,h,n,k,p,q,r,l,t,m,f){f=f.geoenrichment.dijit.ReportPlayer.ChartContainer;
var g={getDefaultChartSettings:function(b){b=b||{};var a=c.mixin({},b.font),e=c.mixin({},b.font);delete e.fontSize;return{isChart:!0,type:b.chartType||h.COLUMN,isMultiFeatureChart:!!b.isMultiFeatureChart,seriesItems:b.seriesItems||[],visualProperties:{width:b.width||400,height:b.height||300,barBorders:!1,view3D:!1,origin:0,backgroundColor:void 0,backgroundImageData:void 0,panelBackgroundColor:void 0,title:{text:"",align:"center",style:c.mixin({},a),verticalShift:0},xAxis:{show:!0,showTicks:!0,ticksInside:!1,
showLine:!0,title:"",titleStyle:c.mixin({},a),style:c.mixin({},a),labelsAngle:0,lineColor:void 0,gridLines:!1,gridLinesCentered:!1,gridLinesColor:void 0,gridLinesOpacity:1,gridLinesThickness:.5,gridLinesStyle:void 0,gridStripes:!1,gridStripesColor:void 0,gridStripesColorAlt:void 0,placement:void 0},yAxis:{show:!0,showTicks:!0,ticksInside:!1,showLine:!0,title:"",titleStyle:c.mixin({},a),style:c.mixin({},a),labelsAngle:0,lineColor:void 0,gridLines:!1,gridLinesCentered:!1,gridLinesColor:void 0,gridLinesOpacity:1,
gridLinesThickness:.5,gridLinesStyle:void 0,gridStripes:!1,gridStripesColor:void 0,gridStripesColorAlt:void 0,baseLine:!0,baseLineColor:void 0,baseLineOpacity:1,baseLineThickness:.5,baseLineStyle:void 0,baseLineValue:0,showPercentIndicator:!1,showValuesAsWeightsInSeries:!1,placement:void 0},legend:{type:p.SERIES,series:{placement:k.RIGHT,placementOffset:10,hasBorder:!0,labelParts:"Label",style:c.mixin({},a)},minMax:{placement:k.RIGHT,placementOffset:3,titleStyle:c.mixin({},e),minVariableLabelStyle:c.mixin({},
e),maxVariableLabelStyle:c.mixin({},e)}},isStacked:!1,columnThickness:d.DEFAULT_COLUMN_THICKNESS,showColumnBarBackground:!1,columnBarBackgroundColor:void 0,renderColumnBarsInOppositeDirections:!1,columnBarGap:void 0,lineThickness:d.DEFAULT_LINE_THICKNESS,fillLineArea:!1,lineAreaOpacity:1,donutHolePercent:d.DEFAULT_DONUT_HOLE_PERCENT,donutGap:d.DEFAULT_DONUT_GAP,donutArcPercent:d.DEFAULT_DONUT_ARC_PERCENT,gaugeHolePercent:d.DEFAULT_GAUGE_HOLE_PERCENT,gaugeRangeMin:void 0,gaugeRangeMax:void 0,gaugeGap:d.DEFAULT_GAUGE_GAP,
gaugeStartAngle:d.DEFAULT_GAUGE_ANGLE,gaugeArcPercent:d.DEFAULT_GAUGE_ARC_PERCENT,gaugeLabelPlacement:t.INSIDE,gaugeLabelStyle:c.mixin({},e),gaugeShowArrow:!1,gaugeArrowLineColor:void 0,gaugeArrowFillColor:void 0,gaugeConditionalStylingIgnoreOthers:!1,gaugeConditionalStylingLabel:!1,gaugeShowFromToLabels:!1,gaugeFromLabelStyle:c.mixin({},e),gaugeToLabelStyle:c.mixin({},e),ringBackgroundColor:void 0,showWholePictures:!1,dataLabels:n.NONE,dataLabelsStyle:c.mixin({},a),dataLabelsDecimals:0,dataLabelsInside:!1,
dataLabelsStackedInColumns:!1,dataLabelsHorizontalAlign:void 0,chartIcons:void 0,floatingIcons:void 0,showAxisIcons:!1,showChartIcons:!1,floatingTexts:void 0,sorting:void 0,conditionalStyling:void 0},comparisonInfo:void 0}},provideDefaultValueForMissing:function(b,a){a=g.getDefaultChartSettings(a);l.populateObject(b,a);return b},cleanUpJson:function(b,a){q.cleanUpJson(b,a)},filterChartJsonForClassicReport:function(b){return l.filterByPattern(b,r)},createChartPoint:function(b,a,c,d,u){return{color:c||
"",label:void 0!==a?a||"":b&&b.alias,fieldInfo:b,iconFieldInfo:d,captionFieldInfo:u}}},v=[{headers:{data:{AREA_DESC:f.oneMile}}},{headers:{data:{AREA_DESC:f.threeMiles}}},{headers:{data:{AREA_DESC:f.fiveMiles}}}];g.getSeriesItemsForMultiFeatureChart=function(b,a,e){if(!a)return a;e=e||v;var d=a[0];return h.isLineLike(b)?e.map(function(b){var a=c.clone(d);a.color=d.points[0].color;a.points.forEach(function(a){delete a.color});a.label=m.getAreaDataValue({areaDataObject:b,fieldName:"AREA_DESC"})||"";
return a}):d.points.map(function(a){return{label:a.label,thickness:d.thickness,points:e.map(function(b){return g.createChartPoint(a.fieldInfo,m.getAreaDataValue({areaDataObject:b,fieldName:"AREA_DESC"})||"",a.color||d.color)})}})};g.getOriginalPointByMultiFeatureIndexes=function(b,a,c){return b[0].points[a]};return g});