// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/grid/valueField/_ResizableField","dojo/_base/declare dojo/_base/lang dojo/aspect dojo/on dojo/string dojo/dom-class dojo/dom-construct dojo/dom-style ./utils/ResizeColumnRowTooltipVisualizer esri/dijit/geoenrichment/utils/PageUnitsConverter esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/KeyboardUtil esri/dijit/geoenrichment/utils/MouseUtil esri/dijit/geoenrichment/utils/TooltipUtil dojo/i18n!esri/nls/jsapi".split(" "),function(E,
F,G,y,z,e,B,v,u,C,p,H,x,D,q){q=q.geoenrichment.dijit.ReportPlayer.ValueField;var I={_grid:null,_timeoutHandle:null,setIsBeingResized:function(b,c){this._cleanUp();c&&b.parentGrid&&b.parentGrid.domNode&&(this._grid=b.parentGrid,e.add(this._grid.domNode,"isBeingResized"),this._timeoutHandle=setTimeout(this._cleanUp.bind(this),1E4))},_cleanUp:function(){clearTimeout(this._timeoutHandle);this._grid&&this._grid.domNode&&e.remove(this._grid.domNode,"isBeingResized");this._grid=null}};return E(null,{resizable:!0,
hasAllSidesSizers:!1,showSizeLabel:!1,showSizeLabelsInAllRelatedCells:!1,showColumnRowSizeTooltip:!1,showSizersOnFocus:!1,createSizersOnDemand:!0,resizeRestrictNode:null,allowHorizontalResizing:!0,allowVerticalResizing:!0,sizeLabel:null,_tooltipHandles:null,postCreate:function(){this._tooltipHandles=[];this.inherited(arguments);this.resizable&&this._addCreateSizersTrigger()},_isBeingResized:!1,_isBeingResizedDelayed:!1,_sizers:null,isBeingResized:function(){return this.resizable&&this._sizers?this._isBeingResized||
this._sizers.some(function(b){return x.isMouseOver(b)})||!this.hasAllSidesSizers&&this._sizers.some(function(b){return 0<v.get(b,"opacity")}):!1},wasResizedRecently:function(){return this.isBeingResized()||this._isBeingResizedDelayed},_addCreateSizersTrigger:function(){var b=this;this.createSizersOnDemand||this._updateSizers();y(this.domNode,"mouseover",function(){b._updateSizers()})},_createSizers:function(){var b=this;this.resizable&&!this._sizers&&(this._sizers=(this.hasAllSidesSizers?"e se s sw w nw n ne".split(" "):
[this.allowHorizontalResizing?"e":null,this.allowVerticalResizing?"s":null].filter(function(b){return!!b})).map(function(c){var a=B.create("div",null,b.domNode);b.hasAllSidesSizers?(e.add(a,(b.showSizersOnFocus?"valueField_allSidesSizer_showOnFocus":"valueField_allSidesSizer")+" "+c+"_fieldSizer"),b.fieldCellClass&&e.add(a,"fieldSizer_"+b.fieldCellClass)):"e"===c?(e.add(a,"valueField_widthSizer"),b._tooltipHandles.push(D.setTooltipToNode(a,q.dragToChangeWidth)),b.fieldCellClass&&e.add(a,"widthSizer_"+
b.fieldCellClass)):(e.add(a,"valueField_heightSizer"),b._tooltipHandles.push(D.setTooltipToNode(a,q.dragToChangeHeight)),b.fieldCellClass&&e.add(a,"heightSizer_"+b.fieldCellClass));a._sizerInfo={dir:c,canChangeW:-1!==c.indexOf("w")||-1!==c.indexOf("e"),canChangeH:-1!==c.indexOf("n")||-1!==c.indexOf("s"),canChangeX:-1!==c.indexOf("w"),canChangeY:-1!==c.indexOf("n"),dxDir:-1!==c.indexOf("w")?-1:1,dyDir:-1!==c.indexOf("n")?-1:1};return a}),this._addResizeHandlers())},unitTesting_getSizerByDirection:function(b){this._updateSizers();
return this._sizers.filter(function(c){return c._sizerInfo.dir===b})[0]},_addResizeHandlers:function(){var b=this;this._sizers.forEach(function(c){var a=c._sizerInfo;y(c,"mousedown",function(c){c.stopPropagation();var g;b._setIsBeingResized(!0);b.stopEdit&&b.stopEdit();var l=x.getCursorPosition().clientX,h=x.getCursorPosition().clientY,e=b.getWidth(),p=b.getHeight(),q=l,v=h,w=b._getResisableNodePos(),d={x:w.x,y:w.y,dxShiftSingle:0,dyShiftSingle:0,w:e,h:p,dwSingle:0,dhSingle:0},u=y(document.body,"mousemove",
function(c){var f=x.getCursorPosition().clientX,A=x.getCursorPosition().clientY,k=f-l,m=A-h,k=k*a.dxDir,m=m*a.dyDir;if(c.shiftKey){var n=d.h/d.w,t=(k+m)/2;switch(a.dir){case "se":k=t;m=t*n;break;case "sw":m=t*n;f+=k-t;k=t;break;case "nw":f+=k-t,A+=m-t*n,k=t,m=t*n}}var r;if(H.isCtrl(c))switch(a.dir){case "e":case "w":r=w.x-k;d.dxShiftSingle=r-d.x;d.x=r;k*=2;r=!0;break;case "se":case "sw":case "nw":r=w.x-k;n=w.y-m;d.dxShiftSingle=r-d.x;d.dyShiftSingle=n-d.y;d.x=r;d.y=n;k*=2;m*=2;r=!0;break;case "s":case "n":n=
w.y-m,d.dyShiftSingle=n-d.y,d.y=n,m*=2,r=!0}!g&&(a.canChangeW&&k||a.canChangeH&&m)&&(b._onManualSizePreChange(),g=!0);n=!1;d.dwSingle=0;d.dhSingle=0;a.canChangeW&&k&&(d.w=e+k,d.dwSingle=k,n=!0);a.canChangeH&&m&&(d.h=p+m,d.dhSingle=m,n=!0);!r&&(d.dxShiftSingle=0,d.dyShiftSingle=0,a.canChangeX||a.canChangeY)&&(r=a.canChangeX?f-q:0,t=a.canChangeY?A-v:0,d.dxShiftSingle=r,d.dyShiftSingle=t,d.x+=r,d.y+=t,q=f,v=A);b._applyResizedCellBox(d,a);n&&(b._onManualSizeChange(a),b.onManualSizeChange());if(a.canChangeW&&
k)b.onManualWidthChange(c);if(a.canChangeH&&m)b.onManualHeightChange(c);b._updateSizers()}),z=y.once(document.body,"mouseup, click",function(){z.remove();u.remove();b._setIsBeingResized(!1)})})});this.hasAllSidesSizers&&this.own(G.after(this,"onSizeChanged",function(){p.isNodeInLayout(b._sizers[0])&&b._updateSizers()}))},_setIsBeingResized:function(b){b?(this._isBeingResizedDelayed=this._isBeingResized=!0,e.add(this.domNode,"isBeingResized")):(this._isBeingResized&&this._onManualSizeChangeEnd(),this._isBeingResized=
!1,e.remove(this.domNode,"isBeingResized"),p.stealFocus(),setTimeout(function(){this._isBeingResizedDelayed=!1}.bind(this),100));this._tooltipHandles.forEach(function(c){b?c.suspend():c.resume()});I.setIsBeingResized(this,b)},_getResisableNodePos:function(){return p.position(this.domNode)},_applyResizedCellBox:function(b,c){var a=F.mixin({},b),g=this.resizeRestrictNode&&p.position(this.resizeRestrictNode),f=!1,l=!1;if(a.dxShiftSingle||a.dyShiftSingle){if(g){var h=this._getResisableNodePos();0>a.dxShiftSingle?
g.x>=h.x?(a.dxShiftSingle=0,f=!0):(a.dxShiftSingle=Math.max(a.dxShiftSingle,g.x-h.x),a.w-=a.dxShiftSingle-b.dxShiftSingle):a.x<=g.x?(a.dxShiftSingle=0,f=!0):(a.dxShiftSingle=Math.min(a.dxShiftSingle,a.x-g.x),a.w-=b.dxShiftSingle-a.dxShiftSingle);0>a.dyShiftSingle?g.y>=h.y?(a.dyShiftSingle=0,l=!0):(a.dyShiftSingle=Math.max(a.dyShiftSingle,g.y-h.y),a.h-=a.dyShiftSingle-b.dyShiftSingle):a.y<=g.y?(a.dyShiftSingle=0,l=!0):(a.dyShiftSingle=Math.min(a.dyShiftSingle,a.y-g.y),a.h-=b.dyShiftSingle-a.dyShiftSingle)}this.onNeedShiftPositionFromResizing(a.dxShiftSingle,
a.dyShiftSingle)}c.canChangeX&&0===a.dxShiftSingle&&(f=!0);c.canChangeY&&0===a.dyShiftSingle&&(l=!0);if(a.dwSingle||a.dhSingle)g&&(h=this._getResisableNodePos(),b=g.y+g.h-h.y,a.w=Math.max(3,Math.min(a.w,g.x+g.w-h.x)),a.h=Math.max(3,Math.min(a.h,b))),f||this.setWidth(a.w),l||this.setHeight(a.h)},updateSizers:function(){this._updateSizers()},_updateSizers:function(){function b(){c._sizers.forEach(function(a){var b,f,l=a._sizerInfo,h=c.getWidth(),e=c.getHeight(),q=v.get(a,"width"),u=v.get(a,"height");
switch(l.dir){case "e":b=h;f=(e-u)/2;break;case "se":b=h;f=e;break;case "s":b=(h-q)/2;f=e;break;case "sw":b=0;f=e;break;case "w":b=0;f=(e-u)/2;break;case "nw":f=b=0;break;case "n":b=(h-q)/2;f=0;break;case "ne":b=h,f=0}v.set(a,{left:b+"px",top:f+"px",cursor:l.dir+"-resize",marginLeft:l.canChangeW?-q/2+"px":"",marginTop:l.canChangeH?-u/2+"px":""});if("w"===l.dir||"e"===l.dir)p[30>e?"hide":"show"](a);if("s"===l.dir||"n"===l.dir)p[30>h?"hide":"show"](a)})}this._createSizers();if(this._sizers&&this.hasAllSidesSizers){var c=
this;5<v.get(this.domNode,"height")?b():setTimeout(b,100)}},_onManualSizePreChange:function(){this.setToolbarSuspended&&this.setToolbarSuspended(!0);this.onManualSizePreChange()},_onManualSizeChange:function(b){this.inherited(arguments);this.showSizeLabel&&this._showAndUpdateSizeLabel();this.showSizeLabelsInAllRelatedCells&&this._showAndUpdateRelatedCellsSizeLabels();this.showColumnRowSizeTooltip&&("e"===b.dir?u.showColumnTooltip(this):"s"===b.dir&&u.showRowTooltip(this))},_onManualSizeChangeEnd:function(){p.hide(this.sizeLabel);
this.setToolbarSuspended&&this.setToolbarSuspended(!1);this.showSizeLabelsInAllRelatedCells&&this._hideRelatedCellsSizeLabels();this.showColumnRowSizeTooltip&&u.removeTooltip();this.onManualSizeChangeEnd()},_showAndUpdateSizeLabel:function(){this.sizeLabel=this.sizeLabel||B.create("div",{"class":"elementSizeLabel"},this.domNode);p.show(this.sizeLabel);setTimeout(function(){if(this.domNode&&!p.isHidden(this.sizeLabel)){var b=this.domNode.clientWidth,c=this.domNode.clientHeight;if(this.viewModel&&this.viewModel.showUnitsInPt){var a=
C.pxToPt(b),e=C.pxToPt(c);this.sizeLabel.innerHTML=z.substitute(q.elementSizeFormatPt,{width:Math.round(a),height:Math.round(e)})}else this.sizeLabel.innerHTML=z.substitute(q.elementSizeFormat,{width:Math.round(b),height:Math.round(c)});a=this.sizeLabel.clientHeight;this.sizeLabel.style.left=(b-this.sizeLabel.clientWidth)/2+"px";this.sizeLabel.style.top=(20<c?(c-a)/2:-a-5)+"px"}}.bind(this))},_showAndUpdateRelatedCellsSizeLabels:function(){this._getRelatedCells().forEach(function(b){b._showAndUpdateSizeLabel()})},
_hideRelatedCellsSizeLabels:function(){this._getRelatedCells().forEach(function(b){p.hide(b.sizeLabel)})},_getRelatedCells:function(){return this.parentGrid?this.parentGrid.getFieldCells().filter(function(b){return b!==this},this):[]},onManualSizePreChange:function(){},onManualSizeChangeEnd:function(){},onManualSizeChange:function(){},onManualWidthChange:function(b){},onManualHeightChange:function(b){},onNeedShiftPositionFromResizing:function(b,c){}})});