// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/grid/valueField/ValueField","dojo/_base/Color dojo/_base/declare dojo/_base/lang dojo/on dojo/sniff dojo/dom-construct dojo/dom-class dojo/dom-geometry dijit/Destroyable ./utils/ValueFieldTextTrimmer ./utils/ValueFieldNumberAnimator esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/UrlUtil".split(" "),function(u,d,f,r,v,g,k,w,l,h,x,p,t){function y(a){a.domNode=g.toDom("\x3cdiv class\x3d'esriGEAdjustableGridValueField esriGENonSelectable'\x3e\x3cdiv class\x3d'valueField_contentBlock' data-dojo-attach-point\x3d'contentBlock'\x3e\x3cdiv data-dojo-attach-point\x3d'valueContainer' class\x3d'valueField_valueBlock'\x3e\x3cdiv data-dojo-attach-point\x3d'valueLabel' class\x3d'valueField_valueLabel'\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e");
a.contentBlock=a.domNode.children[0];a.valueContainer=a.contentBlock.children[0];a.valueLabel=a.valueContainer.children[0]}var z=d(l,{_buildLayoutFunc:null,_parentNode:null,constructor:function(a,b){f.mixin(this,a);this._parentNode=b;this.postCreate()},postCreate:function(){this._buildLayoutFunc(this);this["class"]&&k.add(this.domNode,this["class"]);this._parentNode&&this.placeAt(this._parentNode);this.value&&this.set("value",this.value)},get:function(a){return"value"===a?this._getValueAttr?this._getValueAttr():
this.value:this[a]},set:function(a,b){"value"===a?this._setValueAttr?this._setValueAttr(b):this.value=b:this[a]=b},placeAt:function(a){g.place(this.domNode,a);return this},on:function(a,b){this.own(r(this.domNode,a,b))},isLeftToRight:function(){return w.isBodyLtr(document)},destroy:function(){g.destroy(this.domNode);this._buildLayoutFunc=this.domNode=this._parentNode=null}});l={width:1,height:1,angle:1,opacity:1};var q={color:1,fontSize:1,lineHeight:1,fontFamily:1,fontWeight:1,fontStyle:1,textDecoration:1,
backgroundColor:1,verticalAlign:1,horizontalAlign:1,horizontalPadding:1,verticalPadding:1,overrideStyle:1},m={borderTopColor:1,borderTopWidth:1,borderTopOpacity:1,borderTopStyle:1,borderRightColor:1,borderRightWidth:1,borderRightOpacity:1,borderRightStyle:1,borderBottomColor:1,borderBottomWidth:1,borderBottomOpacity:1,borderBottomStyle:1,borderLeftColor:1,borderLeftWidth:1,borderLeftOpacity:1,borderLeftStyle:1},A=f.mixin({},l,q,m),n={verticalAlign:"top",horizontalAlign:"left",horizontalPadding:0,
verticalPadding:0,angle:0,opacity:1};d=d(z,{DEFAULT_STYLES:n,viewModel:null,fieldCellClass:null,trimTextIfOverflows:!1,autoDetectUrl:!1,valueLabel:null,fieldStyle:null,defaultBorderStyle:null,_borderStyle:null,content:null,postCreate:function(){this._buildLayoutFunc=this._buildLayoutFunc||y;this.inherited(arguments);this.setStyle(this.fieldStyle);this.setContent(this.content);this.fieldCellClass&&(k.add(this.domNode,this.fieldCellClass),k.add(this.contentBlock,"contentBlock_"+this.fieldCellClass))},
_destroyExistingContent:function(){this.content&&(this.content.destroy&&this.content.destroy(),this.contentContainer&&g.empty(this.contentContainer),this.content=null)},getContentContainerNode:function(a){a||this._destroyExistingContent();this.contentContainer||(this.contentContainer=g.create("div",{"class":"valueField_valueBlock"},this.contentBlock,"first"));p.show(this.contentContainer);return this.contentContainer},setContent:function(a){this._destroyExistingContent();if(this.content=a)this.getContentContainerNode(!0),
(a=this.content.domNode||this.content)&&a.parentNode!==this.contentContainer&&g.place(a,this.contentContainer);p[this.content?"show":"hide"](this.contentContainer);p[this.content?"hide":"show"](this.valueContainer);this.content||this.set("value",this._value)},_value:null,_getValueAttr:function(){return this._value},_setValueAttr:function(a){this._value!==a&&(this._setValueLabelText(a),this._value=a)},_setValueLabelText:function(a){this.valueLabel&&h.checkValueLabelOverflow(this,a);return a},hasOverflowText:function(){return!this.content&&
h.hasOverflowText(this)},currentNumberValue:null,numberFormatFunction:null,_canAnimate:!1,setNumberValue:function(a,b,c){this.currentNumberValue=a;this.numberFormatFunction=b;this._canAnimate=c&&this.viewModel.animationAllowed;this.currentNumberValue&&this.numberFormatFunction&&this._canAnimate&&this._animateNumber()},notifyShown:function(){this.currentNumberValue&&this.numberFormatFunction&&this._canAnimate&&this._animateNumber()},_animateNumber:function(){x.animateNumber(this,this.currentNumberValue,
this.numberFormatFunction)},getFullStyle:function(){return f.mixin({},n,this.fieldStyle)},setStyle:function(a){a=a||{};this.fieldStyle=f.mixin(this.fieldStyle||{},a);"number"===typeof this.fieldStyle.opacity&&(this.fieldStyle.opacity=Math.max(0,Math.min(1,this.fieldStyle.opacity)));a=void 0!==a.width||void 0!==a.height;this._applyAlignAndPaddingStyles();this._applyTransformStyles();this._applyTextStyleToDom(this.domNode);(a=this._setBorderStyle()||a)&&this._refreshLayout()},_applyAlignAndPaddingStyles:function(){this.domNode.style.textAlign=
this.fieldStyle.horizontalAlign||n.horizontalAlign;this.valueLabel.style.paddingLeft="";this.valueLabel.style.paddingRight="";this.valueLabel.style.paddingTop="";"number"===typeof this.fieldStyle.horizontalPadding&&(this.valueLabel.style.paddingLeft=this.fieldStyle.horizontalPadding+"px",this._allowRightPadding()&&(this.valueLabel.style.paddingRight=this.fieldStyle.horizontalPadding+"px"));var a=this.fieldStyle.verticalAlign||n.verticalAlign;"number"===typeof this.fieldStyle.verticalPadding&&"top"===
a&&(this.valueLabel.style.paddingTop=this.fieldStyle.verticalPadding+"px");this.valueContainer.style.verticalAlign=a;this.contentContainer&&(this.contentContainer.style.verticalAlign=a);this.domNode.style.opacity="number"===typeof this.fieldStyle.opacity?this.fieldStyle.opacity:""},_allowRightPadding:function(){return this.viewModel&&this.viewModel.isGraphicStyle},_applyTransformStyles:function(){var a=v("webkit")?"webkitTransform":"transform";this.valueContainer.style[a]=0!==(Number(this.fieldStyle.angle)||
0)?"rotate("+this.fieldStyle.angle+"deg)":""},_supportedTextStyles:"color fontSize lineHeight fontFamily fontWeight fontStyle textDecoration backgroundColor".split(" "),_applyTextStyleToDom:function(a){var b=this;this._supportedTextStyles.forEach(function(c){if(b.fieldStyle[c]){var e=b.fieldStyle[c]+("fontSize"===c||"lineHeight"===c?"px":"");"backgroundColor"===c?b._setNodeBackgroundColor(a,e):a.style[c]=e}else a.style[c]=""})},_setNodeBackgroundColor:function(a,b){(a===this.domNode&&this.fieldStyle.angle?
this.valueContainer:a).style.backgroundColor=b;a===this.domNode&&this.fieldStyle.angle&&(this.domNode.style.backgroundColor="transparent")},clearTextStyle:function(){for(var a in q)delete this.fieldStyle[a];this.setStyle()},clearLineHeight:function(){delete this.fieldStyle.lineHeight;this.setStyle()},_currentBorderKey:null,_SIDES:["Top","Right","Bottom","Left"],setDefaultBorderStyle:function(a){this.defaultBorderStyle=a;this._setBorderStyle()&&this._refreshLayout()},clearBorder:function(){for(var a in m)delete this.fieldStyle[a];
this.setStyle()},_setBorderStyle:function(){this._borderStyle=borderStyle=f.mixin({},this.defaultBorderStyle,this.fieldStyle);var a=this._getBorderKey(borderStyle);if(this._currentBorderKey===a)return!1;this._currentBorderKey=a;this.domNode.style.border="";this._SIDES.forEach(function(a){var b="none",e=borderStyle["border"+a+"Color"],d=borderStyle["border"+a+"Width"],g=borderStyle["border"+a+"Style"]||"solid",f=borderStyle["border"+a+"Opacity"];e&&0<d&&0!==f&&"none"!==g&&(1>f&&(e=new u(e),e.a=f,e=
e.toCss(!0)),b=d+"px "+g+" "+e);this.domNode.style["border"+a]=b},this);return!0},_getBorderKey:function(a){var b="",c;for(c in m)b+=a[c]+"_";return b},_getLeftBorder:function(){return this._borderStyle?this._borderStyle.borderLeftWidth||0:0},_getLeftPadding:function(){return this.fieldStyle.horizontalPadding||0},_getRightBorder:function(){return this._borderStyle?this._borderStyle.borderRightWidth||0:0},_getRightPadding:function(){return this._allowRightPadding()?this.fieldStyle.horizontalPadding||
0:0},_getTopBorder:function(){return this._borderStyle?this._borderStyle.borderTopWidth||0:0},_getTopPadding:function(){return this.fieldStyle.verticalPadding||0},_getBottomBorder:function(){return this._borderStyle?this._borderStyle.borderBottomWidth||0:0},_getBottomPadding:function(){return this.fieldStyle.verticalPadding||0},getWidth:function(){return this.fieldStyle.width||0},getContentWidth:function(){return this.getWidth()-this._getLeftBorder()-this._getRightBorder()-this._getLeftPadding()-
this._getRightPadding()},setWidth:function(a){this.contentBlock&&this.domNode&&(a=Math.max(0,a),this.fieldStyle.width=a,this.domNode.style.width=a+"px",a=this.getWidth()-this._getLeftBorder()-this._getRightBorder(),this.contentBlock.style.width=a+"px",this.valueContainer.style.width=a+"px",this.valueLabel.style.width=a-this._getLeftPadding()-this._getRightPadding()+"px",this.contentContainer&&(this.contentContainer.style.width=a+"px"),h.checkValueLabelOverflow(this),this.onWidthChanged(),this.onSizeChanged())},
getHeight:function(){return this.fieldStyle.height||0},getContentHeight:function(){return this.getHeight()-this._getTopBorder()-this._getBottomBorder()-this._getTopPadding()-this._getBottomPadding()},setHeight:function(a){this.contentBlock&&this.domNode&&(a=Math.max(0,a),void 0!==this._minHeight&&(a=Math.max(a,this._minHeight)),this.fieldStyle.height=a,this.domNode.style.height=a+"px",a=this.getHeight()-this._getTopBorder()-this._getBottomBorder(),this.contentBlock.style.height=a+"px",this.valueContainer.style.height=
a+"px",this.contentContainer&&(this.contentContainer.style.height=a+"px"),h.checkValueLabelOverflow(this),this.onHeightChanged(),this.onSizeChanged())},getMinHeight:function(){return this._minHeight||0},_minHeight:void 0,setMinHeight:function(a){this._minHeight=a;this.domNode.style.minHeight=a+"px";a=a-this._getTopPadding()-this._getBottomPadding();this.contentBlock.style.minHeight=a+"px";this.valueContainer.style.minHeight=a+"px";this.contentContainer&&(this.contentContainer.style.minHeight=a+"px");
h.checkValueLabelOverflow(this)},_refreshLayout:function(){this.setWidth(this.getWidth());this.setHeight(this.getHeight());void 0!==this._minHeight&&this.setMinHeight(this.getMinHeight())},_urlClickHandle:null,setUrl:function(a){this._urlClickHandle&&this._urlClickHandle.remove();this.valueLabel&&(k[a?"add":"remove"](this.valueLabel,"esriGEAdjustableGridValueFieldHyperLink"),a&&(this._urlClickHandle=r(this.valueLabel,"click",function(){t.openUrl(t.toHttpUrl(a))})))},onWidthChanged:function(){},onHeightChanged:function(){},
onSizeChanged:function(){},destroy:function(){this.viewModel=null;this._destroyExistingContent();this.inherited(arguments)}});d.SUPPORTED_LAYOUT_STYLES=l;d.SUPPORTED_TEXT_STYLES=q;d.SUPPORTED_BORDER_STYLES=m;d.SUPPORTED_STYLES=A;return d});