// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/annotations/image/_ImageContainerMixin","dojo/_base/declare dojo/_base/lang dojo/Deferred dojo/sniff dojo/dom-class dojo/dom-construct dojo/dom-style dojo/when esri/dijit/geoenrichment/utils/ImageInfoUtil ./_LiveMapSupport ../utils/AnnotationsUtil ../utils/CircularMaskUtil ../utils/ScaleToCoverUtil ../../supportClasses/images/ImageDataHolder esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/WaitingUtil dojo/i18n!esri/nls/jsapi ../../../_devConfig".split(" "),
function(q,g,r,t,d,h,c,l,u,v,m,w,x,n,e,p,f,y){f=f.geoenrichment.dijit.ReportPlayer.ReportPlayer;return q(v,{viewModel:null,theme:null,currentFeatureIndex:null,imageJson:null,relativeParent:null,imageTriggerJson:null,alignParams:null,showError:!0,parentWidget:null,_createMapFunc:null,_circularMask:!1,_scaleToCover:!1,_fitParent:!0,_angle:0,_opacity:1,_isLogoPlaceholder:!1,_logoPlaceholderType:null,_dynamicBehavior:null,_isMapImage:!1,_webMapId:null,_defaultBasemapId:null,_thumbnailUrl:null,_calculatorFieldName:null,
_additionalLayerInfos:null,_pinSymbolJson:null,showMapLegend:!1,_useDefaultImageSizeFlag:!1,_fileName:null,_imageData:null,postCreate:function(){this._configurePropertiesFromImageJson();this._isMapImage&&(this._createMapFunc=this.viewModel.dynamicReportInfo&&this.viewModel.dynamicReportInfo.createMapFunc);this.content=this._isMapImage&&this._createMapFunc?h.create("div",{"class":"templateLiveMap"}):h.create(this._isMapImage?"div":"img",{"class":"floatingElement templateImage"});this.inherited(arguments);
this._configureDomNodeStylesFromParameters();this._addAdditionalUI();this._isMapImage?this.resize():this._isLogoPlaceholder&&(this.content._wToHRatio=1,this.resize());this._applyOpacity();this._applyRotation();this.alignParams&&m.alignAnnotationContainer(this,this.alignParams);(this.imageJson.fileName||this.imageJson.isLogoPlaceholder||this._imageData)&&this._initWithImageData()},_configurePropertiesFromImageJson:function(){this.fieldStyle=this.fieldStyle||{};this.fieldStyle.width=this.imageJson.style.width||
150;this.fieldStyle.height=this.imageJson.style.height||0;this._fileName=this.imageJson.fileName;this._opacity=Math.max(0,Math.min(1,void 0!==this.imageJson.style.opacity?this.imageJson.style.opacity:1));this._angle=this.imageJson.style.angle||0;this._dynamicBehavior=this.imageJson.dynamicBehavior;this._fitParent=!1!==this.imageJson.fitParent;this._circularMask=!!this.imageJson.circularMask;this._scaleToCover=!!this.imageJson.scaleToCover;this.imageJson.style.width||(this._useDefaultImageSizeFlag=
!0);this.alignParams||!this.imageJson.style.horizontalAlign&&!this.imageJson.style.verticalAlign||(this.alignParams={horizontalAlign:this.imageJson.style.horizontalAlign,verticalAlign:this.imageJson.style.verticalAlign});this._isMapImage=!!this.imageJson.isMapImage;this._calculatorFieldName=this.imageJson.calculatorFieldName;this._webMapId=this.imageJson.webMapId;this._defaultBasemapId=this.imageJson.defaultBasemapId;this._thumbnailUrl=this.imageJson.thumbnailUrl;this._additionalLayerInfos=this.imageJson.additionalLayerInfos;
this._pinSymbolJson=this.imageJson.pinSymbolJson;this.showMapLegend=this.imageJson.showMapLegend;this._isLogoPlaceholder=!!this.imageJson.isLogoPlaceholder;this._logoPlaceholderType=this.imageJson.logoPlaceholderType},_configureDomNodeStylesFromParameters:function(){this._isLogoPlaceholder&&d.add(this.domNode,"templateImage_logoPlaceholder");"short"===this._logoPlaceholderType&&d.add(this.domNode,"templateImage_logoPlaceholderShort");d.add(this.domNode,"floatingElementContainer");c.set(this.domNode,
"position","absolute");c.set(this.domNode,"top",(this.imageJson.style.top||0)+"px");c.set(this.domNode,"left",(this.imageJson.style.left||0)+"px")},_addAdditionalUI:function(){},_applyOpacity:function(){if(!this.domNode)return null;0<=this._opacity&&1>this._opacity?(this._clickMaskDiv&&(this._clickMaskDiv.style.opacity=this._opacity),this._scaleToCoverDiv&&(this._scaleToCoverDiv.style.opacity=this._opacity),this.content.style.opacity=this._opacity):(this.content.style.opacity="",this._clickMaskDiv&&
(this._clickMaskDiv.style.opacity=""),this._scaleToCoverDiv&&(this._scaleToCoverDiv.style.opacity=""))},_applyRotation:function(){if(!this.domNode)return null;this._angle=0<this._angle||0>this._angle?this._angle:0;var a=t("webkit")?"webkitTransform":"transform";this.content.style[a]="rotate("+this._angle+"deg)";this._updateCircularMaskAndScaleToCover()},_initPromise:null,_initWithImageData:function(){var a=this;return this._initPromise=l(this._reloadImageData(),function(){a.onInitialized();a._updateCircularMaskAndScaleToCover()})},
isInitialized:function(){return this._initPromise},_reloadImageData:function(){function a(a,c){return b._setImageData({data:a,fileName:c,recalcImageContainerDimentions:b._useDefaultImageSizeFlag,preserveHeight:!1,dispatchEvents:!1})}var b=this;if(!this._isMapImage)if(this._isLogoPlaceholder){if(this.viewModel.getDynamicImageFunc)return p.showProgress(this.domNode),this.onContentLoadingStart(),l(this.viewModel.getDynamicImageFunc(this._dynamicBehavior,this.theme),function(b){return b&&a(b)}).always(function(){p.removeProgress(b.domNode);
b.onContentLoadingEnd()})}else return a(n.getImageData(b._fileName)||b.imageJson.data,b._fileName)},_setImageData:function(a){if(this.domNode&&a.data){var b=this,e=a.data,d=a.fileName,f=a.recalcImageContainerDimentions,h=a.preserveHeight,g=a.dispatchEvents,k=new r;this._showErrorMessage(!1);c.set(this.domNode,"opacity","0.01");u.getImageInfo(e,d).then(function(a){if(b.domNode){g&&b.onImageDataPreChanged();var e=a.width/a.height;b.content._wToHRatio=e;var d;d=b._fitParent?b._useDefaultImageSizeFlag?
150:Math.min(b.getWidth(),b.getHeight()*e):b.imageJson.style.width||150;c.set(b.content,"width",d+"px");c.set(b.content,"height",d/e+"px");b.content.onload=function(){f&&b._recalcImageContainerDimentions(h);g&&b.onImageDataChanged();k.resolve()};b.content.onerror=function(a){k.reject(a)};b._fileName=a.filename;b._imageData=a.dataUrl;b._applyBackgroundUrl(a.dataUrl);n.putImageData(a.filename,a.dataUrl);b._syncLogoStateAfterLoadingImage()}else k.resolve()},k.reject);return k.promise.then(function(){b.domNode&&
c.set(b.domNode,"opacity","")},function(a){console.log(a);b._showErrorMessage(!0)})}},_syncLogoStateAfterLoadingImage:function(){this.domNode&&d[this._fileName||this._imageData?"remove":"add"](this.domNode,"templateImage_logoPlaceholder");this._isLogoPlaceholder=!this._fileName},_showErrorMessage:function(a){this.showError&&this.domNode&&(y.emulateErrors.contentErrors&&(a=!0),a&&!this.errorMessageDiv&&(this.errorMessageDiv=h.create("div",{"class":"esriGEReportPlayerErrorMessage",innerHTML:this._isMapImage?
f.mapLoadError:f.imageLoadError},this.domNode),c.set(this.errorMessageDiv,"paddingTop",c.get(this.domNode,"height")/2-20+"px")),e[a?"show":"hide"](this.errorMessageDiv),e[a?"hide":"show"](this.contentBlock))},_recalcImageContainerDimentions:function(a){if(this.domNode){var b=e.position(this.content),c=a&&this.getHeight();this.setWidth(b.w);this.setHeight(b.h);a&&this.setHeight(c)}},_applyBackgroundUrl:function(a){this.domNode&&(this._isMapImage?this.content.style.backgroundImage=a?"url("+a+")":"":
this.content.src=a||"",this._updateThumbnailClass(),this._updateCircularMaskAndScaleToCover())},_updateThumbnailClass:function(){this.content&&d[this._thumbnailUrl?"add":"remove"](this.content,"templateImageWithThumbnail")},_getBackgroundUrl:function(){return this.domNode?this._isMapImage?c.get(this.content,"backgroundImage").replace("url","").replace("(","").replace(")","").replace(/\"/g,""):this.content.src:null},isMapImage:function(){return this._isMapImage},_lastAlignParams:null,resize:function(a,
b){if(!this.domNode)return null;a&&(this.setWidth(a.w),this.setHeight(a.h),this._useDefaultImageSizeFlag=!1);if(this._isMapImage){a=c.get(this.content,"width");b=this.getWidth();var e=c.get(this.content,"height"),d=this.getHeight();if(a!==b||e!==d)c.set(this.content,"width",b+"px"),c.set(this.content,"height",d+"px"),this._createMapFunc&&this._placeMap()}else this._lastAlignParams=b,this._resizeContentImage();this._updateCircularMaskAndScaleToCover()},_getContentImageWToHRatio:function(){return this.content._wToHRatio||
(this.imageJson.style.innerImageW||this.imageJson.style.width)/(this.imageJson.style.innerImageH||this.imageJson.style.height)},_resizeContentImage:function(){var a=this._getContentImageWToHRatio(),b;b=this._fitParent?Math.min(this.getWidth(),this.getHeight()*a):Math.min(this.imageJson.style.width,this.imageJson.style.height*a,this.getWidth(),this.getHeight()*a);c.set(this.content,"width",b+"px");c.set(this.content,"height",b/a+"px");m.alignAnnotationContainer(this,this._lastAlignParams);this._updateCircularMaskAndScaleToCover()},
scaleProportionallyWithinParent:function(a){if(!this.domNode)return null;var b=this.getImageBox(!1);this.resize({w:b.w*a.xScale,h:b.h*a.yScale});c.set(this.domNode,{left:b.l*a.xScale+"px",top:b.t*a.yScale+"px"})},_clickMaskDiv:null,_scaleToCoverDiv:null,_updateCircularMaskAndScaleToCover:function(){!this._createMapFunc&&this.domNode&&(this._clickMaskDiv=w.setCircularMask(this._circularMask&&this._imageData,this.content,this._getBackgroundUrl(),this._angle),this._scaleToCoverDiv=x.setScaleToCover(this._scaleToCover&&
this._imageData,this.content,this._getBackgroundUrl(),this._angle),e[this._clickMaskDiv||this._scaleToCoverDiv?"hide":"show"](this.content),this._applyOpacity())},getFitParent:function(){return this._fitParent},setFitParent:function(a){this._fitParent=a;this._resizeContentImage()},getImageBox:function(a){a=!1!==a&&e.position(this.content);return{w:a?a.w:this.getWidth(),h:a?a.h:this.getHeight(),l:this.domNode?c.get(this.domNode,"left"):0,t:this.domNode?c.get(this.domNode,"top"):0}},setImageWidth:function(a){this._fitParent||
(this.imageJson.style.width=a,this.imageJson.style.height=a/this._getContentImageWToHRatio(),this._resizeContentImage())},setImageHeight:function(a){this._fitParent||(this.imageJson.style.height=a,this.imageJson.style.width=a*this._getContentImageWToHRatio(),this._resizeContentImage())},onInitialized:function(){},onImageDataPreChanged:function(){},onImageDataChanged:function(){},onContentLoadingStart:function(){},onContentLoadingEnd:function(){},onMapLoadError:function(){},toJson:function(){var a=
e.position(this.content),b={id:"img",fileName:this._isLogoPlaceholder?null:this._fileName,isMapImage:this._isLogoPlaceholder?!1:this._isMapImage,defaultBasemapId:this._defaultBasemapId,webMapId:this._webMapId,additionalLayerInfos:this._additionalLayerInfos&&g.clone(this._additionalLayerInfos),pinSymbolJson:this._pinSymbolJson&&g.clone(this._pinSymbolJson),showMapLegend:this.showMapLegend,calculatorFieldName:this._calculatorFieldName,thumbnailUrl:this._thumbnailUrl,circularMask:this._circularMask,
scaleToCover:this._scaleToCover,isLogoPlaceholder:this._isLogoPlaceholder,logoPlaceholderType:this._isLogoPlaceholder?this._logoPlaceholderType:null,dynamicBehavior:this._isLogoPlaceholder?this._dynamicBehavior:null,fitParent:this._fitParent,style:{top:this.domNode?c.get(this.domNode,"top"):0,left:this.domNode?c.get(this.domNode,"left"):0,angle:this._angle,opacity:this._opacity,horizontalAlign:this._lastAlignParams&&this._lastAlignParams.horizontalAlign,verticalAlign:this._lastAlignParams&&this._lastAlignParams.verticalAlign,
innerImageW:a&&a.w,innerImageH:a&&a.h}};this._fitParent?(b.style.width=this.getWidth(),b.style.height=this.getHeight()):(b.style.width=a.w,b.style.height=a.h);return b}})});