// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.27/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/annotations/image/_LiveMapSupport","dojo/_base/declare dojo/when dojo/dom-construct dojo/query ../../supportClasses/map/legend/LegendController esri/dijit/geoenrichment/utils/InvokeUtil esri/dijit/geoenrichment/utils/WaitingUtil".split(" "),function(g,h,k,l,m,n,f){return g(null,{_isPlacingMapFlag:!1,_placeMapPromise:null,_currentMap:null,_locatorPointsControllers:null,_stdPolygonsControllers:null,getCurrentMap:function(){return this._currentMap},
_placeMap:function(){return this._placeMapPromise=n.invoke(this,"_doPlaceMap")},_doPlaceMap:function(){function b(){a._currentMap&&a._currentMap.destroy();a._currentMap=null}function d(){f.removeProgress(a.content);a._finalizePlaceMap();a._showErrorMessage(!0);a.onMapLoadError()}var a=this;this._showErrorMessage(!1);this._isPlacingMapFlag&&this._finalizePlaceMap();k.empty(this.content);b();f.showProgress(this.content);this.onContentLoadingStart();this._isPlacingMapFlag=!0;this._legendController=new m;
this._additionalLayerInfos&&this.viewModel.dynamicReportInfo&&!this._locatorPointsControllers&&(this._locatorPointsControllers=[],this._additionalLayerInfos.forEach(function(a,b){a.index=b;if(a.isLocatorLayer){var c=this.viewModel.getLocatorPointsController(a.calculatorInfo,this.currentFeatureIndex);a.layerName&&c.setLayerName(this._calculatorFieldName,a.layerName);c.setRendererJson(this._calculatorFieldName,a.rendererJson);c.setLayerIndex(this._calculatorFieldName,b);this.own(c);this._locatorPointsControllers.push(c)}},
this),this._stdPolygonsControllers=[],this._additionalLayerInfos.forEach(function(c,b){c.index=b;if(c.isComparisonLayer){var d=function(d){d=a.viewModel.getStdPolygonsController(c.calculatorName,d);d.setRendererJson(a._calculatorFieldName,c.rendererJson);c.labelRendererJson&&d.setLabelRendererJson(a._calculatorFieldName,c.labelRendererJson);d.setLayerIndex(a._calculatorFieldName,b);a.own(d);a._stdPolygonsControllers.push(d)};this.viewModel.dynamicReportInfo.isMultiFeature?this.viewModel.dynamicReportInfo.analysisAreas.forEach(function(a,
c){d(c)}):d(this.currentFeatureIndex)}},this));return h(this._createMapFunc(this.content,{defaultBasemapId:this._defaultBasemapId,webMapId:this._webMapId,additionalLayerInfos:this._additionalLayerInfos&&this._additionalLayerInfos.filter(function(a){return!!a.url}),locatorPointsControllers:this._locatorPointsControllers,stdPolygonsControllers:this._stdPolygonsControllers,thisAreasHighlightController:this.viewModel.getThisAreasHighlightController(),legendController:this._legendController,waitForLoad:!0,
extent:this._mapExtentPending,calculatorFieldName:this._calculatorFieldName}),function(c){a.showMapLegend&&a._legendController.setLegendVisible(!0);a._locatorPointsControllers&&a._locatorPointsControllers.forEach(function(b){b.setMapInfo(a._calculatorFieldName,c)});a._stdPolygonsControllers&&a._stdPolygonsControllers.forEach(function(b){b.setMapInfo(a._calculatorFieldName,c)});var e=c&&c.map;b();!a.domNode&&e?e.destroy():(a._currentMap=e,a._syncWithPanelScale(),e?(a.own(e),f.removeProgress(a.content),
a._finalizePlaceMap()):d())},d)},_finalizePlaceMap:function(){this._isPlacingMapFlag&&(this._isPlacingMapFlag=!1,this.onContentLoadingEnd())},getLoadMapPromise:function(){return this._placeMapPromise},isLegendVisible:function(){return this.showMapLegend},setLegendVisible:function(b){this.showMapLegend=b;this._legendController.setLegendVisible(b)},_mapExtentPending:null,getVisualState:function(){return{mapExtent:this._currentMap&&this._currentMap.extent,showLegend:this.isLegendVisible()}},setVisualState:function(b){this._mapExtentPending=
null;b&&(b.mapExtent&&(this._currentMap&&this._currentMap.setExtent?this._currentMap.setExtent(b.mapExtent):this._mapExtentPending=b.mapExtent),void 0!==b.showLegend&&this.setLegendVisible(b.showLegend))},_panelScale:null,notifyPanelScaleChanged:function(b){this._panelScale=b;this._syncWithPanelScale()},_syncWithPanelScale:function(){if(this._panelScale&&this._currentMap){var b=1/this._panelScale,d=32*b+8;[".esriSimpleSliderTR",".HomeButton",".mapNavigationLockButton"].forEach(function(a){var c=l(a,
this.domNode)[0];c&&(".mapNavigationLockButton"===a&&50<this._currentMap.root.clientHeight-(d+c.clientHeight*b)&&(d+=20),c.style.top=d+"px",c.style.transformOrigin="100% 0%",c.style.transform="scale("+b+")",c.style["webkit-transform"]="scale("+b+")",d+=(c.clientHeight+(".esriSimpleSliderTR"===a?2:0))*b+5)},this)}},destroy:function(){this._finalizePlaceMap();this.inherited(arguments)}})});